- README.md
> README: Add travis build status badge

- CONTRIBUTING.md
- src/main.rs
Was reading through the repo the other day and felt I could contribute a bit. Let me know if you want any info or explanations.
> Refactored some param parsing in main

- README.md
- src/main.rs
- vmm/src/vm.rs
Add support for specifying multiple files with --disk
Fixes: #2
> Add support for multiple disks

- Cargo.lock
> build: Update Cargo.lock for linux-loader crate update

- pci/src/configuration.rs
- pci/src/device.rs
- pci/src/msix.rs
- pci/src/root.rs
- vm-virtio/src/transport/pci_device.rs
Based on more reading from the PCI Local Bus Specification, this pull request aims to fix some inconsistencies and lack of support regarding the current MSI-X implementation.
> msix: Enhance MSI-X implementation

- Cargo.lock
- vmm/src/vm.rs
Signed-off-by: Jing Liu <jing2.liu@linux.intel.com>
> vm-memory usage: vm-memory latest codes rename MmapError to Error

- README.md
- vmm/src/config.rs
We need to give it a suffix.
Fixes: #96
> config: Fix default memory size parameter

- README.md
> README: Really fix the memory parameters examples

- src/main.rs
- vmm/src/config.rs
- vmm/src/vm.rs
Add a "--serial" command line that takes as input either "off", "tty"
(default and current behaviour) and "file=/path/to/file".
When "--serial off" is used the serial device is not added to the VM
configuration at all.
> vmm: Make serial port controllable via command line

- Cargo.lock
- Cargo.toml
- Jenkinsfile
- scripts/run_integration_tests.sh
- src/main.rs
With this set of changes the time to run the integration tests drops significantly.
> Run integration tests in parallel

- qcow/src/qcow.rs
The QCOW2 format is documented here:
https://git.qemu.org/?p=qemu.git;a=blob;f=docs/interop/qcow2.txt;hb=HEAD
The only difference between v2 and v3 is the addition of some extra
fields into the header in v3 for which there are default values in v2.
This introduces a new unit test for the behaviour but it has been
manually verified by the converting the image from v3 to v2
with a command like:
qemu-img convert -O qcow2 -o compat=0.10 clear-29620-cloud.img clear-29620-cloud.img.v2
Fixes: #24 
> qcow: Add support for QCOW v2 header

- Cargo.lock
- src/main.rs
- vm-virtio/src/console.rs
- vm-virtio/src/lib.rs
- vmm/src/config.rs
- vmm/src/vm.rs
Here, I have implemented single port virtio console device. It compiles fine but the implementation is not tested yet. This is my first PR in this repo, and many things may not have been written properly. So, please take your time to review my code.
> Console device implementation

- vmm/src/vm.rs
Our DeviceManager::new() routine is reaching north of 250 lines.
For simplicity and readbility sake, extract all virtio devices creation
code into their own routines.
> vm: Factorize all virtio devices creation routines

- .travis.yml
> build: Upload release binary on tag

- docs/vfio.md
> docs: Add VFIO usage example

- arch/src/lib.rs
- arch/src/x86_64/mod.rs
- pci/src/configuration.rs
- vfio/src/vfio_device.rs
- vfio/src/vfio_pci.rs
- vm-allocator/src/address.rs
- vm-allocator/src/system.rs
- vmm/src/vm.rs
This PR gathers several patches related to VFIO, with the purpose of improving its support for the cloud-hypervisor VMM.
> vfio: Fixes and improvements

- release-notes.md
> release-notes: Add v0.1.0 notes

- scripts/run_integration_tests.sh
- src/main.rs
Add support for testing Bionic to the integration tests.
> Bionic integration testing

- vmm/src/vm.rs
Since virtio-pmem uses a KVM user memory region, it needs to increment the slot index in use to prevent from any conflict with further VFIO allocations (used for mapping mappable memory BARs).
> vmm: Increase memory slot from virtio-pmem

- qcow/src/qcow.rs
- qcow/src/qcow_raw_file.rs
Grab fixes from crosvm's QCOW code and update our code with them. In particular there are some issues that their fuzzing has detected.
> Import QCOW fixes from crosvm

- Cargo.lock
- vm-virtio/src/console.rs
- vm-virtio/src/lib.rs
- vmm/Cargo.toml
- vmm/src/vm.rs
Console size feature implementation for the virtio console device.
> Virtio console config

- src/main.rs
panic()ing after a panic() has already been recovered by the credibility
test system (i.e. after an aver! has failed) results in an abort which
triggers SIGILL.
Adjust the SSH based commands to generate a Result<...,Error> which we
then either propagate through the test block. Or if the function is
directly being evaluated in an aver! macro call .unwrap_with_default()
(or .unwrap_or() in the case where the default would be wrong.)
See #182
> tests: Remove potential sources of nested panics

- .travis.yml
- Jenkinsfile
- scripts/run_integration_tests.sh
- scripts/run_unit_tests.sh
Just some little issues that have been bugging me.
> Minor CI/tests tweaks

- net_util/src/tap.rs
- vm-virtio/src/transport/pci_common_config.rs
This PR fixes one error and one warning about cloud-hypervisor unit tests.
> Fix clippy errors regarding unit tests

- vm-virtio/src/net.rs
When there are no available descriptors in the queue (observed when the
network interface hasn't been brought up by the kernel) stop waiting for
notifications that the TAP fd should be read from.
This avoids a situation where the TAP device has data avaiable and wakes
up the virtio-net thread only for the virtio-net thread not read that
data as it has nowhere to put it.
When there are descriptors available in the queue then we resume waiting
for the epoll event on the TAP fd.
This bug demonstrated itself as 100% CPU usage for cloud-hypervisor
binary prior to the guest network interface being brought up. The
solution was inspired by the Firecracker virtio-net code.
Fixes: #208
> virtio: net: Remove TAP fd from epoll when no available descriptors

- vm-virtio/src/lib.rs
- vm-virtio/src/vhost_user/fs.rs
- vm-virtio/src/vhost_user/handler.rs
- vm-virtio/src/vhost_user/mod.rs
- vm-virtio/src/vhost_user/net.rs
- vm-virtio/src/vhost_user/vu_common_ctrl.rs
- vmm/src/vm.rs
The global purpose of this pull request is to factorize the existing code from virtio-fs with the generic vhost-user code introduced with vhost-user-net.
It also extends the vhost-user handler to push the factorization one step further, and finally it fixes a bunch of small issues in the code sequences.
> Factorize and fix vhost-user related code

- vm-virtio/src/vhost_user/handler.rs
- vm-virtio/src/vhost_user/net.rs
While review code for issue #224, two issues introduced by new code, add fixes to address them.
> Refactor vhost-user-net feature set and fix event count set

- release-notes.md
> release-notes: Add v0.2.0 notes

- vmm/src/vm.rs
Rather than sending a signal to the signal handler used for handling
SIGWINCH calls instead use the crate provided termination method. This
also unregisters the signal handler which also means that there won't be
a leaked signal handler remaining.
This leaked signal handler is what was causing a failure to cleanup up
the thread on subsequent requests breaking two reboots in a row.
Fixes: #252
> vmm: "close" the SIGWINCH signal handler

- src/main.rs
The goal here is to decouple the Guest instance from the ssh connection
to send some commands to the guest. The reason being to allow ssh
commands to be issued from a different thread, which can be useful to
wait for the end of a command with a thread.join().
> ci: Allow threads to send ssh commands

- Jenkinsfile
- scripts/run_integration_tests.sh
- src/main.rs
- test_data/cloud-init/clear/openstack/latest/user_data
This pull request ensures `virtio-vsock` is functional, relying on a new Clear Linux cloud image including the `socat` utility.
> Add virtio-vsock integration tests

- vmm/src/device_manager.rs
Create the virtio devices independently of adding them to the PCI bus.
Instead accrue the devices in a vector and add them to the bus en-masse.
This will allow the virtio device creation to be used independently of
PCI based transport.
> vmm: Make virtio device creation independent of PCI

- Cargo.lock
- Cargo.toml
- src/main.rs
> build, tests: Update to ssh2 0.4.0

- src/main.rs
Now that we have expanded our address space we should add automated
testing to try VMs that use a large amount of RAM.
As the hypervisor does an anonymous mmap() for the backing of memory and
during a typical test boot the guest will not touch it all it should be
possible to test large RAM VMs even if that exceeds the RAM of the host
machine.
> tests: Add a "huge" memory test

- vm-virtio/src/transport/pci_device.rs
The 32 or 64 bits type for the memory BAR was not set correctly. This
patch ensure the right type is applied to the BAR.
> vm-virtio: Fix virtio-pci BAR type

- arch/src/x86_64/mod.rs
- net_util/src/mac.rs
- vhost_rs/src/vhost_user/master.rs
- vm-virtio/src/console.rs
- vm-virtio/src/pmem.rs
- vm-virtio/src/rng.rs
- vm-virtio/src/vsock/device.rs
With the 1.38.0 toolchain rustfmt is even stricter about formatting now
> vm-virtio: Fix formatting

- arch/src/x86_64/acpi.rs
- arch/src/x86_64/layout.rs
- arch/src/x86_64/mptable.rs
- arch/src/x86_64/regs.rs
- devices/src/ioapic.rs
- vmm/src/config.rs
- vmm/src/device_manager.rs
- vmm/src/vm.rs
Further consolidation of memory layout constants.
> Memory layout improvements

- .travis.yml
- Cargo.lock
- Cargo.toml
- net_util/src/tap.rs
- scripts/run_integration_tests.sh
- src/bin/vhost_user_net.rs
- src/main.rs
- vhost_user_backend/Cargo.toml
- vhost_user_backend/src/lib.rs
- vm-virtio/src/vhost_user/net.rs
To consolidate with vhost-user-backend crate, put changes here for discussion. For change details, please refer to the commit message in "vhost-user-backend: Changes made to apply for vhost-user-net backend".
All issues are addressed, the code works as expected now, events in RX/TX queues and Tap direction could be handled normally, simple test to ping tap ip on host from guest, it works well.
> Vhost-user-net backend

- scripts/run_integration_tests.sh
- src/main.rs
Refactor the Ubuntu testing infrastructure to support testing different
versions.
> tests: Add support for integration testing Ubuntu "eoan"

- src/bin/vhost_user_net.rs
Not perfect but will no longer spam on stdout. There is so much common code with the virtio-net backend I feel like this could possibly be unified.
> Cleanup vhost-user-net code

- docs/custom-image.md
Based on recent update of the cloudguest image used by Cloud Hypervisor,
we identified some missing or incorrect details in the instructions.
This patch is here to fix those.
> docs: Update instructions to create custom ClearLinux image

- release-notes.md
> release-notes: v0.3.0 release

- Cargo.lock
- Cargo.toml
- devices/Cargo.toml
- net_gen/Cargo.toml
- net_util/Cargo.toml
- pci/Cargo.toml
- qcow/Cargo.toml
- vfio/Cargo.toml
- vhost_rs/Cargo.toml
- vhost_user_backend/Cargo.toml
- vm-virtio/Cargo.toml
- vmm/Cargo.toml
> Bump vmm-sys-utils to 0.2.0

- scripts/run_integration_tests.sh
- src/main.rs
> tests: Use release build for integration tests

- vmm/src/vm.rs
Isolate the CPU control from the main VMM code in order to work towards the ACPI CPU hotplug. There should be no functional changes with this code just restructuring.
> Split CPU control from VMM

- acpi_tables/src/rsdp.rs
- vm-virtio/src/vsock/csm/txbuf.rs
- vmm/src/config.rs
The toolchain on Travis got updated and found some little issues that have caused the build to start failing.
> Fix build from moving to new toolchain

- docs/device_model.md
> docs: device_model: Fix formatting error

- vfio/src/vfio_pci.rs
Unmapping all regions mapped to host.
This patch eliminate the error message "Could not unset
container".
Signed-off-by: Wu Zongyong <wuzongyong@linux.alibaba.com>
> vfio-pci: unmap regions when dropping VfioGroup

- docs/fs.md
- scripts/run_integration_tests.sh
> misc: Update locations to point to new kernel fork

- vhost_user_backend/src/lib.rs
The way in which offsets are currently use in memory regions is
derived from QEMU's contrib/libvhost-user, but while this one works
mainly by translating vmm va's to local va's, vm-memory expects us to
use proper guest addresses and thus, define memory regions that
actually match the guest's memory disposition.
With this change, we create the memory regions with the proper length
and offsets, extend AddrMapping to store the guest physical address,
and use the latter instead of offset in vmm_va_to_gpa().
Signed-off-by: Sergio Lopez <slp@redhat.com>
> vhost_user_backend: fix memory region offsetting

- pci/src/msi.rs
- vfio/src/vfio_pci.rs
- vmm/src/device_manager.rs
Along with some small VFIO/MSI fixes, this PR allows the proper support for multiple devices to be passed through the VM.
> vfio: pci: Allow multiple devices to be passed through

- vmm/src/vm.rs
Some physical address bits may become reserved in page table when SME is enabled on AMD platform. Guest will trigger a reserved bit violation page fault in this case due to write these reserved bits to 1 in page table. We need reduce the reserved bits to get the right physical address range.
> vmm: Detect and handle AMD SME (Secure Memory Encryption)

- vmm/src/vm.rs
The tty mode remains raw mode when cloud-hypervisor is terminted by SIGTERM or SIGINT. The terminal is unusable due to echoing is disabled which is really annoying.
> vmm: Restore tty to canonical mode when SIGTERM or SIGINT received

- src/main.rs
- vmm/src/acpi.rs
- vmm/src/api/http_endpoint.rs
- vmm/src/api/mod.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
Preserve vCPUs after a reboot by updating the configuration.
> Ensure hotplug vCPUs persist after reboot

- vmm/src/device_manager.rs
- vmm/src/vm.rs
Remove lots of code that wasn't being widely used.
Fixes: #511
Fixes: #282
> Always use userspace IOAPIC and MSI for virtio devices 

- vmm/src/api/openapi/cloud-hypervisor.yaml
Fix openapi schema to be a valid yaml.
> openapi: Fix schema

- README.md
Highlight that we support Ubuntu Bionic and Eoan as well as Clear Linux
and update the Clear Linux versions referenced.
Also update the firmware URL to point to the latest version.
> README: Update for newer distribution support

- README.md
- docs/hotplug.md
Add details of how to add vCPUs to the running VM.
> docs: Add CPU hot plug documentation

- Cargo.toml
- release-notes.md
Expand release notes and bump Cargo.toml.
> release: v0.4.0

- Cargo.lock
> cargo: Update Cargo.lock for the 0.4.0 release

- scripts/run_cargo_tests.sh
- scripts/run_integration_tests.sh
Add some use of "time" to measure the wallclock time for various items
within our CI scripts.
> ci: Add some time measurements to CI scripts

- src/main.rs
On our CI the /tmp filesystem is mounted as tmpfs and this is the
location where the test disk images are located. When the CI worker
nodes have less memory and fewer CPUs the tmpfs fills up as the tests
run in parallel.
Introduce a mechanism to reduce the parallelism of the tests based on
starvation of the tmpfs disk availability.
Fixes: #455
> tests: Throttle tests based on disk space

- src/main.rs
- vmm/src/cpu.rs
The VM can now be resized downwards
Fixes: #550
> Implement CPU unplug

- src/bin/vhost_user_blk.rs
- src/main.rs
The current code only support RW for backend block file, we need to add read only for it. Please @sboeuf help review, thanks.
> vhost-user-blk backend support readonly

- vm-virtio/src/console.rs
This pull request contains a set of changes meant to fix some functional issues found with virtio-console.
> vm-virtio: Improve functional stability of virtio-console

- pci/src/configuration.rs
- vfio/src/vfio_device.rs
This pull request addresses a few issues that have been observed while running cloud-hypervisor with VFIO.
> pci: Fix a few errors related to VFIO and PCI BAR reprogramming

- vmm/src/cpu.rs
- vmm/src/lib.rs
- vmm/src/memory_manager.rs
- vmm/src/vm.rs
Some minor tweaks as a follow-on to the hotplug work.
> Minor follow-on tweaks for hotplug

- devices/src/acpi.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/memory_manager.rs
Reverts cloud-hypervisor/cloud-hypervisor#654
See #660
> Revert "Move CpuManager, MemoryManager and GED to MMIO space"

- arch/src/lib.rs
- arch/src/x86_64/mod.rs
- arch/src/x86_64/mptable.rs
- arch/src/x86_64/regs.rs
- net_util/src/mac.rs
- qcow/src/qcow.rs
- src/bin/vhost_user_fs.rs
- src/main.rs
- vfio/src/vfio_device.rs
- vhost_user_net/src/lib.rs
- vm-virtio/src/vsock/unix/mod.rs
- vm-virtio/src/vsock/unix/muxer.rs
- vmm/src/config.rs
- vmm/src/cpu.rs
- vmm/src/memory_manager.rs
- vmm/src/vm.rs
This pull request improves the error propagation across the entire code base.
Fixes #274
> Fix map_err() calls losing the inner error

- vmm/src/device_manager.rs
Devices like virtio-pmem and virtio-fs require some dedicated memory
region to be mapped. The memory mapping from the DeviceManager is being
replaced by the usage of MmapRegion from the vm-memory crate.
The unmap will happen automatically when the MmapRegion will be dropped,
which should happen when the DeviceManager gets dropped.
Fixes #240
> vmm: Handle mapping from devices regions through vm-memory

- src/main.rs
- vm-virtio/src/block.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/device_manager.rs
This pull request adds the multiqueue/multithread support to virtio-blk.
Fixes #636
> vm-virtio: Implement MQ for virtio-blk

- vm-virtio/src/net.rs
- vm-virtio/src/net_util.rs
- vm-virtio/src/vhost_user/blk.rs
- vm-virtio/src/vhost_user/fs.rs
- vm-virtio/src/vhost_user/net.rs
Some virtio and vhost-user devices were using the `Vec<u8>` format to represent the configuration of a device. This was making the code hard to read regarding devices' configuration.
This pull request replaces for all these devices the `Vec<u8>` with the specific configuration related to the device. This makes the code easier to understand as we can now clearly identify what is being written and updated in the configuration.
> vm-virtio: Simplify device configurations

- src/bin/vhost_user_blk.rs
- src/main.rs
- vhost_user_block/src/lib.rs
- vm-virtio/src/vhost_user/blk.rs
- vm-virtio/src/vhost_user/mod.rs
@sboeuf @sameo 
This patch set is for MQ support in the vhost-user-blk device and backend, please help review, thanks.
> vhost-user-blk device and backend MQ support

- src/main.rs
We measure the memory overhead that the VMM process adds to the guest VM
and compare it with a maximum acceptable limit. The test is run against
a simple VM, running 1 vCPU and 512MB of RAM. Although this is not by
any mean a comprehensive VMM overhead measurement, it will allow us to
detect when and if any PR makes our code cross an arbitrary memory
overhead threshold.
Fixes: #64
> tests: integration: Add memory overhead test

- src/main.rs
@rbradford ,
Thanks for your reminder!
I added this patch for block-backend help info, please review and merge it, thanks!
> Add help info for block-backend

- vm-virtio/src/vsock/unix/muxer.rs
The existing code taking care of the epoll loop was too restrictive as
it was considering all errors the same. But in case the error is EINTR,
this means the syscall has been interrupted while waiting, and it should
be resumed to wait again.
This patch enforces the parsing of the returned error and prevent the
code from assuming EINTR should be handled as all other errors.
> vm-virtio: vsock: Don't return error when epoll_wait is interrupted

- vmm/src/vm.rs
If the ioctl syscall KVM_CREATE_VM gets interrupted while creating the
VM, it is expected that we should retry since EINTR should not be
considered a standard error.
> vmm: Make sure to retry creating the VM on EINTR

- vm-virtio/src/block.rs
- vm-virtio/src/console.rs
- vm-virtio/src/device.rs
- vm-virtio/src/iommu.rs
- vm-virtio/src/net.rs
- vm-virtio/src/pmem.rs
- vm-virtio/src/rng.rs
- vm-virtio/src/transport/mmio.rs
- vm-virtio/src/transport/pci_common_config.rs
- vm-virtio/src/vhost_user/blk.rs
- vm-virtio/src/vhost_user/fs.rs
- vm-virtio/src/vhost_user/net.rs
- vm-virtio/src/vsock/device.rs
Re-factor code to address issue #368
> Refactor virtio code

- docs/api.md
We document both the internal and external APIs, and how they relate to
each others.
Fixes: #318
> docs: Cloud Hypervisor API documentation

- Cargo.lock
- Cargo.toml
- release-notes.md
Expand the release notes and bump Cargo.toml.
> release: v0.5.0

- Jenkinsfile
- scripts/dev_cli.sh
> build: Do cargo tests, unit tests and OpenAPI check on master

- Cargo.lock
- src/bin/vhost_user_fs.rs
- vhost_user_backend/Cargo.toml
- vhost_user_backend/src/lib.rs
- vhost_user_block/src/lib.rs
- vhost_user_net/src/lib.rs
In particular making sure that the worker threads can be cleanly shutdown.
> Various vhost-user and backend fixes

- src/bin/vhost_user_fs.rs
- vhost_user_backend/src/lib.rs
- vhost_user_block/src/lib.rs
- vhost_user_net/src/lib.rs
Remove duplicated code across the different backends.
> Refactor worker thread killing

- scripts/dev_cli.sh
> scripts: dev_cli: Fix post build permissions for the whole tree

- src/main.rs
- vm-virtio/src/vhost_user/blk.rs
- vmm/src/config.rs
- vmm/src/device_manager.rs
If "vhost_user=true" is set but no socket is provided respawn the cloud-hypervisor binary as a network backend and use that.
See #630
> Add "self spawning" support to --disk

- Cargo.lock
- Cargo.toml
- arch/Cargo.toml
- devices/Cargo.toml
- net_gen/Cargo.toml
- net_util/Cargo.toml
- pci/Cargo.toml
- qcow/Cargo.toml
- scripts/dev_cli.sh
- scripts/run_integration_tests.sh
- src/main.rs
- test_data/cloud-init/clear/openstack/latest/user_data
- vfio/Cargo.toml
- vhost_rs/Cargo.toml
- vhost_rs/src/vhost_user/connection.rs
- vhost_user_backend/Cargo.toml
- vhost_user_block/Cargo.toml
- vhost_user_fs/Cargo.toml
- vhost_user_net/Cargo.toml
- vm-allocator/Cargo.toml
- vm-device/Cargo.toml
- vm-virtio/Cargo.toml
- vmm/Cargo.toml
- vmm/src/api/http_endpoint.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/device_manager.rs
- vmm/src/lib.rs
Here are proposed fixes to be incorporated in the v0.5.1 stable release.
> Proposed fixes for v0.5.1

- src/main.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/device_manager.rs
Remove deprecated command line options and API along with the internal use of those things.
See #678
> Remove deprecated functionality

- Cargo.lock
- devices/Cargo.toml
- devices/src/acpi.rs
- devices/src/lib.rs
- vmm/src/device_manager.rs
Fixes: #657
Signed-off-by: Qiu Wenbo <qiuwenbo@phytium.com.cn>
> devices: implement Aml trait for GED device

- src/bin/vhost_user_fs.rs
Fix event processing on HIPRIO queue and remove an unwrap in handle_event
> Fix event processing on HIPRIO queue and remove an unwrap in handle_event

- tests/integration.rs
This PR removes some duplicated code through a simple abstraction and removes unhelpful sleeps and shutdown commands (as the child was being killed anyway.)
> Some integration test improvements

- scripts/run_integration_tests.sh
- tests/integration.rs
The virtio-fs tests were accidentally disabled in #849 fix that plus some other minor integration test changes.
> Re-enable virtio-fs tests (+ other integration test changes.)

- vfio/src/vfio_device.rs
For cases where IOMMU is not supported, iommu_group will be no present.
This could happened because IOMMU is off at kernel level, bios level or
is not supported at all.
Instead of fail with a generic error handle it as different use case:
Before:
ReadLink(Os { code: 2, kind: NotFound, message: "No such file or directory"})
After:
VfioNoIommuGroup("/sys/bus/pci/devices/0000:03:00.0/iommu_group")
> vfio: handle case for missing iommu_group

- docs/api.md
Adding the missing entry for "add-device" in the API documentation.
Fixes #863 
> docs: Update api.md for VFIO hotplug

- Cargo.toml
- src/bin/ch-remote.rs
- tests/integration.rs
Add resize subcommand to ch-remote.
> Add "resize" command to ch-remote

- Cargo.lock
- vmm/Cargo.toml
It's been extracted from the Firecracker code base.
> vmm: Switch to the micro-http package

- .github/workflows/build.yaml
> github: Trigger the build job on PRs

- scripts/run_integration_tests.sh
- src/bin/ch-remote.rs
- src/main.rs
- tests/integration.rs
Use this in the test_vfio integration test.
> Add add/remove-device to ch-remote

- src/main.rs
- vmm/src/config.rs
- vmm/src/device_manager.rs
In particular reject specifying the socket for vhost-user and a disk path.
> Improve validation of "--disk" parameter

- vmm/src/device_manager.rs
Minor changes that I want to check / land ahead of first virtio-pci device hotplug.
> Preparatory work for virtio PCI device hotplug

- Cargo.lock
- Cargo.toml
- src/main.rs
- vmm/Cargo.toml
- vmm/src/api/http.rs
- vmm/src/api/mod.rs
- vmm/src/lib.rs
- vmm/src/seccomp_filters.rs
First step towards filtering the syscalls that are used by our VMM, this pull request introduces the seccomp filtering as the default to the Cloud-Hypervisor VMM.
> vmm: Introduce seccomp filters

- docs/api.md
- src/bin/ch-remote.rs
- src/main.rs
- tests/integration.rs
- vmm/src/api/http.rs
- vmm/src/api/http_endpoint.rs
- vmm/src/api/mod.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
Adds support for disk hotplug and lays the groundwork for net and pmem later. No unplug support yet.
> Disk hotplug support

- vm-virtio/src/vhost_user/fs.rs
We made sure gpa is in cache range, but not the end addr of request,
which is (gpa + len). If the end addr of request is beyond dax cache
window, vmm would corrupt guest memory or crash.
Fix it by making sure end addr of request is within cache range as well.
And while we're at it, return EFAULT if the request is out of range, as
write(2)/read(2) returns EFAULT when buffer is outside accessible
address space.
Fixes: #961
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
> virtio-fs: validate request len in fs_slave_io()

- docs/api.md
- src/bin/ch-remote.rs
- src/main.rs
- tests/integration.rs
- vmm/src/api/http.rs
- vmm/src/api/http_endpoint.rs
- vmm/src/api/mod.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
Like with disks add support for pmem device hotplug.
> Support hotplugging pmem devices

- test_data/cloud-init/clear/openstack/latest/user_data
- tests/integration.rs
- vfio/src/vfio_device.rs
- vfio/src/vfio_pci.rs
- vmm/src/device_manager.rs
- vmm/src/memory_manager.rs
- vmm/src/vm.rs
This pull request implement the lack of support for memory hotplug along with VFIO PCI devices.
Fixes #942
> Add support for memory hotplug for VFIO PCI devices

- src/bin/ch-remote.rs
- src/main.rs
Fixing two things that I forgot to include in the previous "High level API" pull request.
> Fix CLI and ch-remote for snapshot/restore

- arch/src/lib.rs
- arch/src/x86_64/regs.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/memory_manager.rs
- vmm/src/vm.rs
This pull request contains multiple factorization changes in order to facilitate the support for snapshot/restore with follow up pull requests.
> Preparatory work for snapshot/restore

- Cargo.lock
- Cargo.toml
- arch/Cargo.toml
- vfio/Cargo.toml
- vmm/Cargo.toml
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/memory_manager.rs
- vmm/src/seccomp_filters.rs
- vmm/src/vm.rs
This pull request finishes the series by enabling snapshot/restore functionality through the VM. It has limited scope for now as it does not support virtio and VFIO devices, but that's the first step in supporting snapshotting and restoring a VM.
> Enable snapshot/restore functionalities

- src/main.rs
- vmm/src/config.rs
- vmm/src/vm.rs
Improve the validation of the VM configuration particularly when that VM is created via the REST API.
> Improve validation of VM configuration

- pci/src/bus.rs
- vm-virtio/src/transport/pci_device.rs
When doing virtio-pci device unplug some issues were identified with BAR reprogramming of virtio-pci devices.
> virtio-pci device BAR reprogramming

- pci/src/configuration.rs
When reporting the BAR size it is necessary to return a value that is
encoded such that all the bits are set that represent the mask of the
natural alignment of the field.
> pci: configuration: Use correct algorithm for BAR size reporting

- vm-virtio/src/net.rs
- vm-virtio/src/net_util.rs
- vm-virtio/src/queue.rs
- vm-virtio/src/transport/mmio.rs
This pull request enables snapshot/restore support for `virtio-net`.
> Add snapshot/restore support to virtio-net

- vm-virtio/src/console.rs
This patch implements the Snapshottable trait for virtio-console, which
enables migration support for it. A VM with a virtio-console device
attached can be snapshot and then restored without issues.
Signed-off-by: Yi Sun <yi.y.sun@linux.intel.com>
> vm-virtio: Implement Snapshottable trait for Console

- docs/vhost-user-blk-testing.md
As #721 describe, we need to document vhost-user-block test like vhost-user-net did before, please help review and comments, thanks.
> docs: Add the vhost-user block test doc

- tests/integration.rs
Now that we have multiple virtio devices supporting snapshot and restore
operations, we can add a new integration test to validate the migration
feature works as expected.
The important part is virtio-net as it is used to ssh into the VM to
verify the VM has been restored in the proper state.
This test only works for virtio-mmio for now. Further support for
testing virtio-pci will be added once the virtio-pci transport layer
will support migration.
> ci: Add integration test for VM migration

- README.md
- scripts/run_integration_tests.sh
- scripts/sha1sums
- tests/integration.rs
This is the latest LTS release.
Fixes: #989
> tests: Migrate from Ubuntu Eoan to Focal

- vm-virtio/src/vhost_user/fs.rs
FS_IO is part of the actions a vhost-user-fs daemon can ask the VMM to
perform on its behalf. It is meant to read/write the content from a file
descriptor directly into a guest memory region. This region can either
be a RAM region or the dedicated cache region for virtio-fs.
The way FS_IO was implemented, it was only expecting the guest physical
address provided through the "cache_offset" field to refer to the cache
region. Unfortunately, this was only implementing FS_IO partially.
This patch extends the existing FS_IO implementation by checking the GPA
against the cache region as a first step, but if it is not part of the
cache region address range, then we fallback onto searching for a RAM
region that could match. If there is a matching RAM region, we retrieve
the corresponding host …
> vm-virtio: Fix FS_IO callback for virtio-fs

- docs/api.md
- src/bin/ch-remote.rs
- src/main.rs
- tests/integration.rs
- vmm/src/api/http.rs
- vmm/src/api/http_endpoint.rs
- vmm/src/api/mod.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
Support adding at most one virtio-vsock device.
> Make virtio-vsock hotpluggable/unpluggable

- vm-virtio/src/lib.rs
- vmm/src/config.rs
- vmm/src/device_manager.rs
This embraces and extends some commits from #1072
> Minor hotplug/unplug cleanup

- Cargo.lock
- Cargo.toml
- release-notes.md
Expand release notes and bump Cargo.toml.
> release: Release v0.7.0

- vmm/src/config.rs
Generate an error during validation if an attempt it made to place a
device behind an IOMMU or using a VFIO device when not using PCI.
Fixes: #751
> vmm: config: Reject attempts to use VFIO or IOMMU without PCI

- tests/integration.rs
To aid the debugging of why the test_memory_overhead sometimes fails
print a details of all the named regions that it uses in its
calculation.
> tests: Print out details for smaps in test_memory_overhead

- Cargo.lock
- src/bin/vhost_user_blk.rs
- src/bin/vhost_user_net.rs
- src/main.rs
- tests/integration.rs
- vhost_user_block/Cargo.toml
- vhost_user_block/src/lib.rs
- vhost_user_net/Cargo.toml
- vhost_user_net/src/lib.rs
- vmm/src/config.rs
- vmm/src/device_manager.rs
This removes the handcrafted parsing code.
Fixes: #1092
> Use OptionParser for --block-backend and --net-backend

- tests/integration.rs
- vmm/src/config.rs
Try unplugging and replugging.
Fixes: #1050
> Test virtio-fs unplug

- vmm/src/api/http.rs
- vmm/src/api/http_endpoint.rs
- vmm/src/api/mod.rs
- vmm/src/config.rs
Reduce copy and pasted code in the HTTP and API handling code.
Fixes: #982
> Reduce duplication in HTTP and API code

- Cargo.lock
- src/bin/vhost_user_fs.rs
- vhost_user_fs/Cargo.toml
- vhost_user_fs/src/lib.rs
- vhost_user_fs/src/seccomp.rs
Add seccomp filtering for vhost_user_fs.
This is built on top of Sergio's https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1071
> Seccomp for vhost_user_fs

- vm-virtio/src/block.rs
Permit the guest to suppress interrupts from the host as an
optimisation.
Fixes: #786
> vm-virtio: block: Add support for VIRTIO_RING_F_EVENT_IDX

- tests/integration.rs
- vm-virtio/src/iommu.rs
- vm-virtio/src/transport/mmio.rs
- vm-virtio/src/transport/pci_device.rs
Adding support for snapshot/restore for VM with virtio devices attached to a virtual IOMMU.
> vm-virtio: Snapshot restore virtio-iommu

- tests/integration.rs
- vm-virtio/src/vsock/device.rs
This pull request allows to snapshot and restore a VM with `virtio-vsock` devices attached.
As mentioned in the `vsock(7)` documentation:
```
Sockets are affected by live migration of virtual machines.  Con‐
nected SOCK_STREAM sockets become disconnected when the virtual
machine migrates to a new host.  Applications must reconnect when
this happens.
```
So we cannot expect a connection to survive over a snapshot/restore operation.
> vm-virtio: Add snapshot/restore support to Vsock

- docs/vhost-user-blk-testing.md
- src/main.rs
- tests/integration.rs
- vhost_user_backend/src/lib.rs
- vhost_user_block/src/lib.rs
- vm-virtio/src/block.rs
- vm-virtio/src/vhost_user/blk.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/device_manager.rs
Make sure to operate in writethrough mode unless we have something setup to turn on writeback mode.
Fixes: #1216
Fixes: #680
> Fix virtio-block/vhost-user-block cache mode behaviour and write stability

- vhost_user_backend/src/lib.rs
- vhost_user_net/src/lib.rs
- vm-virtio/src/lib.rs
- vm-virtio/src/net.rs
In preparation for enabling `VIRTIO_F_RING_EVENT_IDX` share common code between virtio-net  and vhost-user-net.
Fixes: #368
> Share code between vhost-user-net and virtio-net

- vhost_user_net/src/lib.rs
- vm-virtio/src/net.rs
- vm-virtio/src/net_util.rs
- vm-virtio/src/queue.rs
> Add VIRTIO_RING_F_EVENT_IDX to virtio-net/vhost-user-net

- tests/integration.rs
> tests: Extend test_*_reboot with checks on fd leaking

- src/bin/ch-remote.rs
If the server returns an error then print out the response body if there
is one present.
Fixes: #1262
> ch-remote: Show response body from error

- arch/src/aarch64/fdt.rs
- arch/src/aarch64/mod.rs
- arch/src/lib.rs
structure InitrdConfig duplicated with InitramfsConfig
Signed-off-by: LiYa'nan <oliverliyn@gmail.com>
> remove duplicated structure InitrdConfig

- Jenkinsfile
- scripts/dev_cli.sh
- scripts/run_integration_tests.sh
Run these builds against every PR rather than just master.
> build: Run musl builds in parallel to glibc builds

- Cargo.lock
- Cargo.toml
- release-notes.md
Update the build version and the release notes for the 0.8.0 release.
> build, release-notes: Document 0.8.0 release

- tests/integration.rs
- vmm/src/api/http.rs
- vmm/src/api/http_endpoint.rs
- vmm/src/api/mod.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
This PR implements a JSON response for any VFIO, disk, fs, pmem, net or vsock device hotplug, providing the user with the device name and its associated b/d/f.
Fixes #1267
> vmm: api: Return a response from PCI hotplug HTTP requests

- vmm/src/vm.rs
I was told that the CI has VT-x enabled and should be able to handle it.
> Enable test_vm test case

- .github/workflows/build.yaml
Reverts cloud-hypervisor/cloud-hypervisor#1321
> Revert "build: Temporarily disable nightly builds"

- vmm/src/device_manager.rs
When the hypervisor crate was introduced, a few places that handled
errors were commented out in favor of unwrap, but that's bad practice.
Restore proper error handling in those places in this patch.
We cannot use from_raw_os_error anymore because it is wrapped deep under
hypervisor crate. Create new custom errors instead.
Fixes: e4dee57e81369 ("arch, pci, vmm: Initial switch to the hypervisor crate")
> vmm: device_manager: restore error handling

- arch/src/x86_64/interrupts.rs
- arch/src/x86_64/regs.rs
- hypervisor/src/kvm/mod.rs
- src/main.rs
- vmm/src/device_manager.rs
- vmm/src/memory_manager.rs
- vmm/src/vm.rs
Patches I come up with when going over Cloud Hypervisor code today. They are mostly cosmetic changes so I'm too fussed about getting them accepted.
> Some cleanup patches for VMM crate

- docs/api.md
- vmm/src/api/openapi/cloud-hypervisor.yaml
Update for hotplug APIs returning data as well as the counters API
> Update API documentation and OpenAPI specification

- hypervisor/Cargo.toml
- hypervisor/src/arch/mod.rs
- hypervisor/src/arch/x86/mod.rs
- hypervisor/src/cpu.rs
- hypervisor/src/hypervisor.rs
- hypervisor/src/kvm/aarch64/mod.rs
- hypervisor/src/kvm/mod.rs
- hypervisor/src/kvm/x86_64/mod.rs
- hypervisor/src/lib.rs
- hypervisor/src/vm.rs
Fixes some white space issues and drop a duplicate comment. No functional change.
> Hypervisor crate misc cleanup

- docs/arm64.md
- vmm/src/seccomp_filters.rs
Signed-off-by: Michael Zhao <michael.zhao@arm.com>
> vmm: Fix Seccomp filter for AArch64

- tests/integration.rs
With QCOW disk images the space needed is greater than the size of the
iamge as any "zero" blocks in the image are allocated when they are
touched making the image bigger.
Here we add a threshold of 6GiB with added debugging messages to ensure
that there is sufficient disk space to run the tests.
> tests: Enhance rate_limited_copy() to also consider free disk space

- scripts/run_integration_tests.sh
- tests/integration.rs
In order to differentiate tests that can be run in parallel versus
tests that must be run on their own, we move all tests into dedicated
modules.
The point is to avoid glitches in results that can be caused by the fact
that other tests (hence VMs) are running at the same time.
> ci: Separate parallel vs sequential tests

- src/bin/ch-remote.rs
- src/main.rs
- tests/integration.rs
- virtio-devices/src/balloon.rs
- virtio-devices/src/lib.rs
- vmm/src/api/mod.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/memory_manager.rs
- vmm/src/vm.rs
This PR adds new option balloon to memory config.
Set it to on will open the balloon function.
> Add virtio-balloon support

- .github/workflows/cross-build.yaml
- Cargo.toml
- hypervisor/Cargo.toml
- scripts/dev_cli.sh
- scripts/run_cargo_tests.sh
- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_x86_64.sh
- scripts/run_unit_tests.sh
- vmm/Cargo.toml
I wrote some code to demonstrate the idea put forward in https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1421.
> Add a KVM feature and use it by default

- pci/src/configuration.rs
This simplies some of the handling for PCI BARs particularly with
respect to snapshot and restore. No attempt has been made to handle the
64-bit bar handling in a different manner to that which was used before.
Fixes: #1153
> pci: Introduce and use PciBar struct

- scripts/run_integration_tests_aarch64.sh
As the current AArch64 integration test builds kernel every time, which would take unnecessary time in CI and therefore not ideal.
This commit refactors the AArch64 kernel building strategy to:
1. Keep the Linux kernel source code directory instead of deleting it everytime after the kernel is built.
2. In integration test script, check if the Linux kernel source code directory exists. If so use `git fetch && git checkout -f` to keep the source code always updated, else run `git clone` to get the source code.
3. Copy config file in and then compile the kernel.
Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1444
> ci: AArch64: Refactor custom linux kernel building strategy

- pci/src/vfio.rs
vfio: Make vfio to use MemoryRegion instead of kvm_userspace_memory_region
> vfio: Make vfio to use MemoryRegion instead of kvm_userspace_memory_region

- README.md
We now have a defined governance model.
> README: Refer to the community repository

- fuzz/Cargo.toml
- fuzz/fuzz_targets/block.rs
- fuzz/fuzz_targets/qcow.rs
This is based on the block fuzzer from crosvm and ported to Cloud
Hypervisor.
> fuzz: Add a fuzzer for virtio-devices::Block

- vmm/src/device_manager.rs
We store the device passthrough handler, so we should use it through our
internal API and only carry the passed through device configuration.
> device_manager: Simplify the passthrough internal API

- devices/src/legacy/cmos.rs
This bit should be set for the last 224us of each second. To be able to
fill this bit we need to use clock_gettime() to get the nanoseconds.
Also set the frequency bit to indicate we update at 32kHz.
> devices: cmos: Populate Update in Progress bit (UIP)

- docs/snapshot_restore.md
Add some documentation regarding the snapshot/restore feature which was
introduced earlier, explaining how the feature works and how to use it
properly.
Fixes #1490
> docs: Add snapshot/restore documentation

- vmm/src/device_manager.rs
Cloud Hypervisor allows either the serial or virtio console to output to
TTY, but TTY input is pushed to both.
This is not correct. When Linux guest is configured to spawn TTYs on
both ttyS0 and hvc0, the user effectively issues the same commands twice
in different TTYs.
Fix this by only direct input to the one choice that is using host side
TTY.
> Console input should be consumed by only one device

- vmm/src/config.rs
Signed-off-by: Praveen Paladugu <prapal@microsoft.com>
> vmm: add validation for network parameters

- Cargo.lock
Point to the non-merge commit.
> build: Update Cargo.lock for kvm-bindings

- virtio-devices/src/pmem.rs
> virtio-devices: pmem: Port to EpollHelper

- scripts/sha1sums-aarch64
- tests/integration.rs
Enabled 3 more test cases.
Fixed an error in scripts/sha1sums-aarch64.
> Enable some AArch64 integration test cases

- Jenkinsfile
> build: Alert on Slack when master build regresses or is fixed

- Jenkinsfile
The builder is not currently responding to pings.
> build: Temporarily disable ARM64 builds

- Cargo.lock
> build: Bump vm-memory dependency

- Cargo.lock
- Cargo.toml
- release-notes.md
Update release notes and version number for the new release.
> build, release-notes.md: Document 0.9.0 release

- virtio-devices/src/mem.rs
> virtio-devices: mem: Port to EpollHelper

- docs/vhost-user-blk-testing.md
- docs/vhost-user-net-testing.md
> docs: use shared memory with vhost-user

- virtio-devices/src/balloon.rs
> virtio-devices: balloon: Port to EpollHelper

- tests/integration.rs
Including vhost-user-net, vhost-user-block and virtio-fs tests.
> Port more tests to new methodology

- tests/integration.rs
test_virtio_pmem, test_virtio_vsock, test_memory_mergeable and test_initramfs
> Port more integration tests to new methodology

- .github/workflows/audit.yaml
- .github/workflows/build.yaml
- .github/workflows/quality.yaml
- Jenkinsfile
- qcow/src/raw_file.rs
- virtio-devices/src/vsock/unix/muxer.rs
> build: Use GitHub actions for clippy/build/rustfmt tests

- Jenkinsfile
Remove this work from the Jenkins master.
> Jenkinsfile: Move OpenAPI validation to worker

- tests/integration.rs
Signed-off-by: Michael Zhao <michael.zhao@arm.com>
> tests: Enable test case test_counters on AArch64

- hypervisor/src/kvm/mod.rs
- hypervisor/src/lib.rs
- hypervisor/src/vm.rs
- vmm/src/vm.rs
Support hypervisor specific VM state to restore and snapshot path.
> Support hypervisor specific VM state to restore and snapshot path.

- tests/integration.rs
Enabled 2 more test cases on AArch64:
1. test_multi_cpu
2. test_pci_msi
> Enable 2 more test cases on AArch64

- hypervisor/src/hypervisor.rs
> hypervisor: Fix copy and pasted error enum entries

- tests/integration.rs
This patch ported many tests to the new methodology, where the guest log
will be printed only when the test is failing.
Things to finish in follow-up PRs:
1. Special tests not ported yet include: test_reboot,
test_bzimage_reboot, test_serial_null(), test_serial_tty(),
test_serial_file(), test_virtio_console(), test_console_file(),
and test_simple_launch().
2. Few direct calls to 'Command::new(clh_command("cloud-hypervisor"))',
which is still printing the guest console
> tests: Port various integration tests to new methodology

- devices/src/bus.rs
- vmm/src/cpu.rs
> vmm: cpu: Warn if the guest is trying to access unregistered IO ranges

- virtio-devices/src/balloon.rs
- virtio-devices/src/block.rs
- virtio-devices/src/block_io_uring.rs
- virtio-devices/src/console.rs
- virtio-devices/src/device.rs
- virtio-devices/src/iommu.rs
- virtio-devices/src/mem.rs
- virtio-devices/src/net.rs
- virtio-devices/src/pmem.rs
- virtio-devices/src/rng.rs
- virtio-devices/src/vhost_user/blk.rs
- virtio-devices/src/vhost_user/fs.rs
- virtio-devices/src/vhost_user/net.rs
- virtio-devices/src/vsock/device.rs
Initially only block is covered but I will add more to this PR if the CI goes green.
> Share common code between different virtio devices

- vmm/src/device_manager.rs
Extract common code for adding devices to the PCI bus into its own
function from the VFIO and VIRTIO code paths.
> vmm: device_manager: Extract common PCI code

- Cargo.lock
- vhost_user_backend/Cargo.toml
- vhost_user_block/Cargo.toml
- vhost_user_fs/Cargo.toml
- vhost_user_net/Cargo.toml
- virtio-devices/Cargo.toml
There is no need to point at our forked version any longer.
> build: Move to rust-vmm vhost crate

- arch/src/x86_64/mod.rs
- hypervisor/src/cpu.rs
- hypervisor/src/kvm/mod.rs
- src/main.rs
- vmm/src/config.rs
- vmm/src/cpu.rs
This when combined with #1701 enables Windows to boot.
> Add support for enabling KVM HyperV emulation

- block_util/src/lib.rs
Some operations complete directly after they have been submitted, which
means they are not submitted asynchronously and therefore they don't
generate any ioevent. This is the reason why we are not processing some
of the completed operations, which leads to some unpredictable
behaviors.
Forcing all io_uring operations submitted to the SQE to be asynchronous
helps simplifying the code as it ensures the completion of every
operation will generate an ioevent, therefore no operation is missed.
Fixes #1715 
> block_util: Ensure all io_uring operations are asynchronous

- vmm/src/seccomp_filters.rs
> vmm: Add missing syscall to vCPU thread

- Cargo.lock
- Cargo.toml
- release-notes.md
Update release notes and version number for the new release.
> build, release-notes.md: Document 0.10.0 release

- Cargo.lock
- devices/src/ioapic.rs
- vmm/src/acpi.rs
This pull request fixes both the IOAPIC and the MCFG table implementations to improve the guest kernel boot time.
> Improve Linux kernel boot time

- vmm/src/interrupt.rs
There is no point in manually dropping the lock for gsi_msi_routes then
instantly grabbing it again in set_gsi_routes.
Make set_gsi_routes take a reference to the routing hashmap instead.
No functional change intended.
> vmm: interrupts: adjust set_gsi_routes

- vmm/src/interrupt.rs
MsiInterruptGroup doesn't need to know the internal field names of
InterruptRoute. Introduce two helper functions to eliminate references
to irq_fd. This is done similarly to the enable and disable helper
functions.
Also drop the pub keyword from InterruptRoute fields. It is not needed
anymore.
> vmm: interrupts: clearly separate MsiInterruptGroup and InterruptRoute

- arch/src/x86_64/mod.rs
This is stored in leaves 0x80000002 to 0x80000004 inclusive.
> arch: x86_64: Copy CPU identification string into guest cpuid

- .github/workflows/docker-image.yaml
- resources/Dockerfile
By fixing the Dockerfile, we have now finalized the automated generation
of the Docker images for both architectures (amd64 and arm64).
Fixes #953
> resources: Finalize automated generation of the Docker image

- vmm/src/vm.rs
Write to the exit_evt EventFD which will trigger all the devices and
vCPUs to exit. This is slightly cleaner than just exiting the process as
any temporary files will be removed.
Fixes: #1242
> vmm: "Cleanly" shutdown on SIGTERM

- vmm/src/device_manager.rs
Because of the PCI refactoring that happened in the previous commit
d793cc4da365ef960a239ff32589efc2635072bd, the ability to fully remove a
PCI device was altered.
The refactoring was correct, but the usage of a generic function to pass
the same reference for both BusDevice, PciDevice and Any + Send + Sync
causes the Arc::ptr_eq() function to behave differently than expected,
as it does not match the references later in the code. That means we
were not able to remove the device reference from the MMIO and/or PIO
buses, which was leading to some bus range overlapping error once we
were trying to add a device again to the previous range that should have
been removed.
Fixes #1802
> vmm: device_manager: Fix PCI device unplug issues

- devices/src/ioapic.rs
Windows will write zero to the IOAPIC version register as part of
probing if the device is there.
Fixes: #1791
> devices: ioapic: Tolerate Windows writing zero to version register

- .github/workflows/cross-build.yaml
- hypervisor/src/kvm/mod.rs
- pci/src/vfio.rs
- src/bin/ch-remote.rs
- vmm/src/config.rs
Fix issues introduced by clippy in Rust 1.47
> Update for clippy checks in Rust 1.47

- README.md
> README: Add steps to install prerequisites

- Jenkinsfile
- scripts/dev_cli.sh
- scripts/run_integration_tests_windows.sh
- tests/integration.rs
> Windows CI integration testing

- scripts/dev_cli.sh
This makes it easier to grep. No functional change obviously.
> scripts: dev_cli: clarify which integration test is running

- vmm/src/device_manager.rs
When shutting down a VM using VFIO, the following error has been
detected:
vfio-ioctls/src/vfio_device.rs:312 -- Could not delete VFIO group:
KvmSetDeviceAttr(Error(9))
After some investigation, it appears the KVM device file descriptor used
for removing a VFIO group was already closed. This is coming from the
Rust sequence of Drop, from the DeviceManager all the way down to
VfioDevice.
Because the DeviceManager owns passthrough_device, which is effectively
a KVM device file descriptor, when the DeviceManager is dropped, the
passthrough_device follows, with the effect of closing the KVM device
file descriptor. Problem is, VfioDevice has not been dropped yet and it
still needs a valid KVM device file descriptor.
That's why the simple way to fix this issue coming from Rust dropping
all …
> vmm: Prevent KVM device fd from being unusable from VfioContainer

- README.md
Add link to issue and fix two typos.
Signed-off-by: pierwill <19642016+pierwill@users.noreply.github.com>
> docs: Edit README.md

- docs/windows.md
This covers topics on advanced Windows guest configuration for debugging and development workflows.
Thanks.
> doc: Add Windows debug instructions

- vhost_user_fs/src/sandbox.rs
- vhost_user_fs/src/seccomp.rs
- virtio-devices/src/transport/pci_common_config.rs
- virtio-devices/src/vsock/unix/muxer.rs
Fix some issues identified by clippy.
> Fix clippy issues

- hypervisor/Cargo.toml
> hypervisor: Update Author and license info in the toml file

- resources/linux-config-x86_64
- src/main.rs
- tests/integration.rs
- virtio-devices/src/lib.rs
- virtio-devices/src/seccomp_filters.rs
- virtio-devices/src/watchdog.rs
- vm-virtio/src/lib.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/device_manager.rs
- vmm/src/seccomp_filters.rs
Add a simple virtio-watchdog implementation. Need to merge change into our kernel fork before merging this PR.
Fixes: #1750
> Add support for virtio-watchdog

- scripts/run_integration_tests_windows.sh
- tests/integration.rs
> tests: add Windows guest snapshot test

- vmm/src/memory_manager.rs
When restoring if a region of RAM is backed by anonymous memory i.e from
memfd_create() then copy the contents of the ram from the file that has
been saved to disk.
Previously the code would map the memory from that file into the guest
using a MAP_PRIVATE mapping. This has the effect of
minimising the restore time but provides an issue where the restored VM
does not have the same structure as the snapshotted VM, in particular
memory is backed by files in the restored VM that were anonymously
backed in the original.
This creates two problems:
* The snapshot data is mapped from files for the pages of the guest
which prevents the storage from being reclaimed.
* When snapshotting again the guest memory will not be correctly saved
as it will have looked like it was backed by a file so it will …
> vmm: memory_manager: Always copy anonymous RAM regions from disk

- vmm/src/memory_manager.rs
Use GuestRegionMmap::read_exact_from() to ensure that all of the file is
read into the guest. This addresses an issue where
GuestRegionMmap::read_from() was only copying the first 2GiB of the
memory and so lead to snapshot-restore was failing when the guest RAM
was 2GiB or greater.
This change also propagates any error from the copying upwards.
> vmm: memory_manager: Completely fill guest ram from snapshot

- vmm/src/memory_manager.rs
In order to improve the `MemoryManager` code readability, this pull request replaces a few variables and fields names.
> vmm: memory_manager: Replace confusing variable names

- scripts/dev_cli.sh
This options allows caller to export any volumes into docker container. This is helpful if you need to work with some private git crate that cargo can't clone it. In some of the internal/personal pipelines there could be cloned the private git repo and use the local repo in the toml file. At least we are developing along this line in Microsoft internal pipeline.
This patch does not change any existing functionalities and this option is purely optional.
Sample command we are using:
_**scripts/dev_cli.sh tests --integration --volumes /mshv:/mshv**_
> scripts: dev_cli: Add an option to dev_cli to export volumes

- Cargo.lock
- Cargo.toml
- src/main.rs
- vmm/Cargo.toml
- vmm/src/lib.rs
This improves the error handling and cleans up the file created by the API socket.
> Minor cleanup to main()/start_vmm() function

- Cargo.lock
- Cargo.toml
- release-notes.md
Update release notes and version number for the new release.
> build, release-notes.md: Document 0.11.0 release

- rpm/cloud-hypervisor.spec
> rpm: Fix vhost_user_block binary name and use latest tag

- scripts/run_integration_tests_aarch64.sh
An error in updating guest kerne code was identified while trouble-shooting the test failure in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1934. The integration script failed to obtain the new guest kernel commit when the code folder had been existing on CI machine.
This problem was only on AArch64, as we re-use the existing guest kernel code to save time.
> scripts: Fix the failure to fetch latest guest kernel code on AArch64

- src/main.rs
- tests/integration.rs
- vmm/src/config.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
> Remove vhost-user-{net,block} self spawning

- scripts/dev_cli.sh
> scripts: dev_cli: Export volumes for windows test as well

- hypervisor/src/arch/x86/emulator/mod.rs
List all GPRs documented in Intel's SDM.
> hypervisor: x86: handle more registers in emulator

- hypervisor/src/arch/x86/emulator/instructions/mov.rs
Only calculate the address when the operand is memory.
> hypervisor: x86: only calculate address when necessary in MOV emulation

- docs/profiling.md
> docs: Add instructions for using perf

- pci/src/vfio.rs
- vmm/src/device_manager.rs
> pci, vmm: Include VFIO devices in device tree

- vmm/src/api/mod.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
> vmm: Include device tree in vm.info API

- scripts/dev_cli.sh
- scripts/run_cargo_tests.sh
- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_sgx.sh
- scripts/run_integration_tests_windows.sh
- scripts/run_integration_tests_x86_64.sh
- scripts/run_unit_tests.sh
- scripts/test-util.sh
> scripts: Add an option to accept hypervisor argument

- docs/windows.md
Missed this piece of info so adding a paragraph. Thanks Wei for pointing out.
> docs/windows.md: Add explicit note on how to start WinDbg

- hypervisor/Cargo.toml
> build: Only pull in iced-x86 for x86_64 builds

- tests/integration.rs
On the CI we are seeing that sometimes the epoll is receing these errors
which do not indicate a failure but that we should retry.
> tests: integration: Retry epoll if we receive -EINTR or -EAGAIN

- Cargo.lock
- Cargo.toml
- release-notes.md
Update release notes and version number for the new release.
> build, release-notes.md: Document 0.12.0 release

- rpm/cloud-hypervisor.spec
Update the spec file for the rpm to the latest version.
> rpm: Update spec file for version bump

- hypervisor/src/mshv/mod.rs
- hypervisor/src/mshv/x86_64/mod.rs
> hypervisor: Fix clippy errors in the mshv module

- arch/src/lib.rs
- arch/src/x86_64/mod.rs
- arch/src/x86_64/smbios.rs
- block_util/src/lib.rs
- devices/src/ioapic.rs
- devices/src/legacy/rtc_pl031.rs
- devices/src/legacy/serial.rs
- hypervisor/src/arch/x86/emulator/instructions/mov.rs
- hypervisor/src/kvm/mod.rs
- hypervisor/src/mshv/mod.rs
- net_util/src/mac.rs
- net_util/src/tap.rs
- pci/src/configuration.rs
- pci/src/vfio.rs
- qcow/src/qcow.rs
- vhost_user_block/src/lib.rs
- virtio-devices/src/balloon.rs
- virtio-devices/src/block.rs
- virtio-devices/src/block_io_uring.rs
- virtio-devices/src/mem.rs
- virtio-devices/src/vhost_user/fs.rs
- vm-virtio/src/queue.rs
- vmm/src/memory_manager.rs
The new toolchain introduced some new clippy checks as well as general build checks.
> Address Rust 1.49 issues

- Jenkinsfile
- test_data/cloud-init/ubuntu/user-data
If the guest fails to communicate with the test harness then retry.
> tests: Make boot notifications retry

- scripts/run_integration_tests_aarch64.sh
> scripts: error exit if aarch64 test is run on MSHV

- hypervisor/src/arch/x86/emulator/instructions/cmp.rs
- hypervisor/src/arch/x86/emulator/instructions/mov.rs
- hypervisor/src/arch/x86/emulator/mod.rs
- hypervisor/src/vm.rs
- vmm/src/vm.rs
The Windows on MSHV work is taking a bit longer than expected. I'm currently trying to enlist help from people who are more familiar with Windows than I am.
This PR contains patches from https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2166 that can be merged right away.
> Miscellaneous improvements to emulator code

- fuzz/Cargo.toml
The dependency on vm-memory was not updated by dependabot.
> build: fix cargo fuzz build

- tests/integration.rs
This integration test mimics the instructions from
`docs/macvtap-bridge.md`.
Fixes: #2215
> tests: Add integration test `test_macvtap`

- Cargo.lock
- arch/src/x86_64/mod.rs
- hypervisor/src/arch/x86/emulator/instructions/cmp.rs
- hypervisor/src/arch/x86/emulator/instructions/mov.rs
- hypervisor/src/arch/x86/emulator/mod.rs
- hypervisor/src/mshv/mod.rs
- tests/integration.rs
- virtio-devices/src/block.rs
- virtio-devices/src/console.rs
- virtio-devices/src/iommu.rs
- virtio-devices/src/net.rs
- virtio-devices/src/pmem.rs
- virtio-devices/src/rng.rs
- virtio-devices/src/seccomp_filters.rs
- virtio-devices/src/vsock/device.rs
- virtio-devices/src/watchdog.rs
- vm-migration/Cargo.toml
- vm-migration/src/lib.rs
- vm-migration/src/protocol.rs
- vmm/src/config.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
New Rust stable release introduces new checks.
> Fix 1.50.0 clippy issues

- Cargo.lock
- Cargo.toml
- release-notes.md
- rpm/cloud-hypervisor.spec
Update version numbers and release notes for new release.
> build, release-notes.md, rpm: Release 0.13.0

- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_x86_64.sh
- tests/integration.rs
> scripts, tests: Rustify the network setup commands for tests

- hypervisor/src/mshv/mod.rs
OVMF would use string IO on those ports. String IO has not been
implemented, so that leads to panics.
Since Cloud Hypervisor doesn't return anything useful from those IO
ports anyway, skip them explicitly in MSHV.
Leave a long-ish comment in code to explain the situation. We should
properly implement string IO once it becomes necessary.
> hypervisor: mshv: explicitly skip a few IO ports

- Cargo.lock
- arch/Cargo.toml
- arch/src/lib.rs
- hypervisor/src/kvm/mod.rs
- vmm/src/lib.rs
- vmm/src/memory_manager.rs
Some miscellaneous cleanups and preparatory changes ahead of TDX support.
> Preparatory work for TDX enabling

- hypervisor/src/arch/x86/emulator/instructions/mod.rs
- hypervisor/src/arch/x86/emulator/instructions/movs.rs
- hypervisor/src/arch/x86/emulator/mod.rs
- hypervisor/src/arch/x86/regs.rs
- hypervisor/src/mshv/mod.rs
This series implements MOVS emulation in the emulator.
> Emulate MOVS instruction

- hypervisor/src/mshv/mod.rs
These are prerequisite patches for adding Windows support on MSHV.
The patches to add TranslateGVA hypercall support will come after https://github.com/cloud-hypervisor/mshv/pull/15 is merged.
> Simplify code in MSHV

- Jenkinsfile
- scripts/run_integration_tests_windows.sh
- tests/integration.rs
> tests: Move Windows integration test to updated OVMF

- Cargo.lock
- hypervisor/src/arch/emulator/mod.rs
- hypervisor/src/cpu.rs
- hypervisor/src/mshv/mod.rs
I've reordered my patch queue a bit to come up with the bare minimum for Windows support. It turns out only one patch is needed.
> Bare minimum support for Windows on MSHV

- src/main.rs
Replace "--monitor-fd" with "--event-monitor" which can either take
"fd=<int>" or "path=<path>" which can point to e.g. a named pipe and
allow more flexibility.
> main: Refine event monitor control

- Jenkinsfile
This reverts commit 526cf32a78b0ef63dcbfe301cfab6ca78664deac.
> Revert "Jenkinsfile: Temporarily disable SGX CI"

- src/main.rs
Signed-off-by: Vineeth Pillai <viremana@linux.microsoft.com>
> Minor fix in the help message for event monitor

- .github/workflows/quality.yaml
- Cargo.toml
- arch/Cargo.toml
- arch/src/x86_64/mod.rs
- arch/src/x86_64/tdx/mod.rs
- hypervisor/Cargo.toml
- hypervisor/src/cpu.rs
- hypervisor/src/hypervisor.rs
- hypervisor/src/kvm/mod.rs
- hypervisor/src/vm.rs
- src/main.rs
- vmm/Cargo.toml
- vmm/src/config.rs
- vmm/src/cpu.rs
- vmm/src/memory_manager.rs
- vmm/src/vm.rs
With a stock TDVF this boots sufficiently far to show that the limitation is in the TDVF code (expecting a Q35 platform) rather than the VMM. (With TDX once the vCPUs are running there is no more interaction from the VMM.
See: #2226
> Initial TDX implementation

- docs/virtiofs-root.md
Add a quick HowTo for using a virtiofs root filesystem in a
cloud-hypervisor guest.
Signed-off-by: Iggy Jackson <iggy@theiggy.com>
> docs: Add virtiofs root howto

- src/main.rs
- vmm/src/api/http.rs
- vmm/src/lib.rs
> Improve API socket handling

- tests/integration.rs
- tests/test_infra/mod.rs
Extract non CH specific functionality into a new module so that it can be used from similar projects that want their own integration testing.
> Split integration test code

- vmm/src/device_manager.rs
There's no need to have the code creating the passthrough_device being
duplicated since we can factorize it in a function used in both cases
(both cold plugged and hot plugged devices VFIO devices).
> vmm: device_manager: Factorize passthrough_device creation

- docs/hotplug.md
Update the hotplug documentation to cover PCI devices and `virtio-mem`.
Fixes #1563
> docs: Update hotplug.md

- block_util/src/lib.rs
There are multiple reports of DescriptorChainTooShort errors and so add
some extra debugging to aid the debugging of this issue.
> block_util: Enhance error reporting for virtio-block usage

- Cargo.toml
- release-notes.md
> build: Update for 0.14.0 release

- vmm/src/cpu.rs
There are two parts:
- Unconditionally zero the output area. The length of the incoming
vector has been seen from 1 to 4 bytes, even though just the first
byte might need to be handled. But also, this ensures any possibly
unhandled offset will return zeroed result to the caller. The former
implementation used an I/O port which seems to behave differently from
MMIO and wouldn't require explicit output zeroing.
- An access with zero offset still takes place and needs to be handled.
Fixes #2437.
> CpuManager: Fix MMIO read handling

- .github/workflows/quality-aarch64.yaml
- .github/workflows/quality.yaml
- arch/src/aarch64/gic/gicv3_its.rs
- arch/src/aarch64/gic/mod.rs
- tests/integration.rs
- vhost_user_backend/src/lib.rs
- vhost_user_block/src/lib.rs
- vhost_user_net/src/lib.rs
- vmm/src/device_manager.rs
This will give us advanced notice of upcoming changes.
> build: Add quality (clippy & rustfmt) using beta toolchain

- Cargo.lock
- Cargo.toml
- release-notes.md
- vm-virtio/src/queue.rs
- vmm/src/cpu.rs
- vmm/src/seccomp_filters.rs
Bug fix release for newly fixed major bugs.
> v0.14.1 release

- src/main.rs
Clean up the error handling during VMM startup.
Fixes: #2342
> Remove early panic()s

- README.md
> docs: Update README to include details of new GitHub advisory process

- tests/integration.rs
We now reply on the value from '/sys/kernel/mm/ksm/shared_pages' to
validate our "--memory mergeable=on|off" option. For `mergeable=on`,
we are expecting to see more 'shared_pages' reported by the kernel when
we start more VMs with this option. For `mergeable=off`, we are
expecting the 'shared_pages' value to be always 0, as we are assuming
the rest of the system (in our CI) is not using mergeable memory.
Fixes: #2138
> tests: Simplify 'test_memory_mergeable'

- vm-device/src/bus.rs
- vmm/src/interrupt.rs
Found two trivial minor issues while going through the code.
> Miscellaneous clean-up patches

- vmm/src/cpu.rs
By disabling this KVM feature, we prevent the guest from using APF
(Asynchronous Page Fault) mechanism. The kernel has recently switched to
using interrupts to notify about a page being ready, but for some
reasons, this is causing unexpected behavior with Cloud Hypervisor, as
it will make the vcpu thread spin at 100%.
While investigating the issue, it's better to disable the KVM feature to
prevent 100% CPU usage in some cases.
> vmm: cpu: Disable KVM_FEATURE_ASYNC_PF_INT in CPUID

- block_util/src/lib.rs
- virtio-devices/src/console.rs
- virtio-devices/src/net_util.rs
With current serde_derive it is possible to #[derive(Serialize)] on
packed structures if they implement Copy. This allows the removal of the
manual equivalent code.
> virtio-devices, block_util: Automatically serialized packed structs

- vmm/src/memory_manager.rs
Instead of tracking on a block level of 64 pages, we are now collecting
dirty pages one by one. It improves the efficiency of dirty memory
tracking while live migration.
> vmm: Refine the granularity of dirty memory tracking

- virtio-devices/src/transport/pci_device.rs
- vm-migration/src/lib.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/memory_manager.rs
In preparation for versioning continue with simplification of the code around snapshot & restore.
> More (de)serialisation simplification

- net_util/src/queue_pair.rs
If the tap file descriptor is not writable then try again later.
Fixes: #2517
> net_util: queue_pair: Handle tap write returning EAGAIN/EWOULDBLOCK

- tests/integration.rs
The current approach as in other tests is used. With more tests coming there seems to be some refactoring potential which can be addressed at some later point.
> tests: Implement test for net dev hotplug for Windows guest

- docs/windows.md
Add a missing note on the supported functionality.
> doc: Add note on net dev hotplug to windows.md

- devices/src/ioapic.rs
- devices/src/legacy/serial.rs
- devices/src/legacy/uart_pl011.rs
- virtio-devices/src/block.rs
- virtio-devices/src/console.rs
- virtio-devices/src/iommu.rs
- vmm/src/memory_manager.rs
Move state structures over to use primitives supported by versionize.
> Start preparing for versioned state

- .github/ISSUE_TEMPLATE/bug_report.md
> .github: Add issue template for bug report

- docs/fs.md
Update obsolete information from the virtio-fs documentation.
Fixes #2538
> docs: Cleanup virtio-fs documentation

- tests/integration.rs
Add reboot to the VFIO baremetal testing.
> ci: Extend baremetal VFIO integration tests

- virtio-devices/src/net.rs
- virtio-devices/src/net_util.rs
- virtio-devices/src/seccomp_filters.rs
- virtio-devices/src/vhost_user/net.rs
Support reprogramming the offload status for the tap device through the control queue.
> virtio-devices: net: Support reprogramming offload

- README.md
Update supported OS & hypervisor details along with details of the new
stability guarantees.
> README.md: Update documentation

- arch/src/lib.rs
- arch/src/x86_64/mod.rs
- arch/src/x86_64/regs.rs
- scripts/run_integration_tests_x86_64.sh
- src/main.rs
- tests/integration.rs
- vmm/src/cpu.rs
- vmm/src/vm.rs
> Remove LinuxBoot support (support PVH only)

- vmm/src/vm.rs
After hotplugging a device validate that the config is valid.
Fixes: #2564
> Validate config on hotplug

- src/main.rs
- vmm/src/config.rs
> vmm: config: Validate that vCPUs is sufficient for MQ queue count

- hypervisor/src/kvm/aarch64/mod.rs
>  hypervisor: aarch64: Safer calculation of offset_of

- virtio-devices/src/console.rs
- virtio-devices/src/device.rs
- virtio-devices/src/vhost_user/net.rs
- virtio-devices/src/vsock/csm/connection.rs
- virtio-devices/src/watchdog.rs
Fix some trivial spelling problem.
Signed-off-by: Yi Wang <wang.yi59@zte.com.cn>
> virtio-device: fix some misspelled words in comment

- vmm/src/config.rs
> vmm: tdx: Reject attempt to use --kernel with --tdx

- Cargo.lock
- Cargo.toml
- fuzz/Cargo.lock
- fuzz/Cargo.toml
- virtio-devices/Cargo.toml
- vmm/Cargo.toml
> build: Bulk upgrade dependencies including fuzz

- vmm/src/vm.rs
Separate the population of the memory and the HOB from the TDX
initialisation of the memory so that the latter can happen after the CPU
is initialised.
> vmm: tdx: Reorder TDX ioctls

- vmm/src/api/mod.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
These messages are predominantly during the boot process but will also
occur during events such as hotplug.
These cover all the significant steps of the boot and can be helpful for
diagnosing performance and functionality issues during the boot.
> vmm: Enhance boot with info!() level messages

- vhost_user_block/src/lib.rs
- vhost_user_net/src/lib.rs
- virtio-devices/src/vhost_user/blk.rs
- virtio-devices/src/vhost_user/fs.rs
- virtio-devices/src/vhost_user/mod.rs
- virtio-devices/src/vhost_user/net.rs
- virtio-devices/src/vhost_user/vu_common_ctrl.rs
- vmm/src/device_manager.rs
Factorize the virtio features and vhost-user protocol features negotiation through a common function that blk, fs and net implementations can directly rely on.
> virtio-devices: vhost_user: Factorize features negotiation

- Cargo.lock
- vmm/Cargo.toml
- vmm/src/memory_manager.rs
> vmm: Version MemoryManager state

- Cargo.lock
- Cargo.toml
- fuzz/Cargo.lock
- fuzz/Cargo.toml
- virtio-devices/Cargo.toml
- vmm/Cargo.toml
Seccomp needs to be bumped in the main tree and fuzz at the same time.
> build: Manual seccomp bump

- Cargo.lock
- arch/Cargo.toml
- arch/src/aarch64/gic/gicv3.rs
- arch/src/lib.rs
> arch: aarch64: Versionize Gicv3State

- rpm/cloud-hypervisor.spec
> rpm: Update version to 15.0

- Cargo.lock
- virtio-devices/src/transport/pci_common_config.rs
- virtio-devices/src/transport/pci_device.rs
- virtio-devices/src/vsock/device.rs
- vm-virtio/Cargo.toml
- vm-virtio/src/lib.rs
- vm-virtio/src/queue.rs
Complete the versioning of the VirtioDevices crate.
> Complete versioning in virtio-devices crate

- virtio-devices/src/epoll_helper.rs
- virtio-devices/src/vhost_user/mod.rs
- virtio-devices/src/vhost_user/net.rs
- virtio-devices/src/vhost_user/vu_common_ctrl.rs
This PR handles a potential connection shutdown between the VMM and the backend.
Fixes #2593
> vhost-user-net: Handle reconnection

- Cargo.lock
- arch/src/aarch64/fdt.rs
> build: bump vm-fdt from 956b5a5 to 2e4ebde

- vmm/src/vm.rs
> vmm: tdx: Don't access same locked structure twice

- test_infra/src/lib.rs
- tests/integration.rs
> test_infra: Return an error if SSH executed command exits with non-zero

- tests/integration.rs
Some basic test cases are available on AArch64 now.
> Enable more test cases on AArch64

- docs/live_migration.md
This documentation is based on notes shared by @rbradford in https://github.com/cloud-hypervisor/cloud-hypervisor/issues/2458. These instructions have been tested on both my dev machine and Azure VM.
> docs: Add documentation for live migration

- tests/integration.rs
A new method has been introduced for WindowsGuest, that would poll on
the SSH connection and try to execute a test command. When successfull,
the polling stops and the guest is considered finished boot. The
downside of this method is that the network setup is needed always even
if the test doesn't use network, however it complies with the behavior
of other tests. I also observe a bit more stability on the local test
run, however it still appears to be a resource issue so some sporadic
fails are possible on a slower machine.
The hardcoded timeouts for guest boot and DHCP setup have been removed.
The dnsmasq invocation uses `--bind-dynamic` so then the daemon can be
started while the target interface could be down yet.
This closes #2520 if Jenkins is successful, as two open bullet points …
> tests: Simplify Windows guest boot and DHCP setup

- tests/integration.rs
Signed-off-by: Fei Li <lifei.shirley@bytedance.com>
> tests: Clean up unused workload_path

- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_x86_64.sh
> scripts: Use CDN to download images

- docs/memory.md
- tests/integration.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/memory_manager.rs
- vmm/src/vm.rs
A few fixes regarding the NUMA implementation of Cloud Hypervisor.
> vmm: NUMA fixes for vCPU, memory and PCI bus

- Cargo.lock
> build: Add missing Cargo.lock change

- .github/workflows/build.yaml
- .github/workflows/quality.yaml
> github: Check files are not modified during build

- docs/arm64.md
Adjusted the document structure and added ACPI related content.
Signed-off-by: Michael Zhao <michael.zhao@arm.com>
> docs: Update arm64 document

- hypervisor/src/cpu.rs
- hypervisor/src/mshv/mod.rs
- hypervisor/src/mshv/x86_64/mod.rs
Both commits are for debugging Snapshot/Restore functionality.
No functional changes.
> Implement get_suspend_regs for MSHV and implement Display for MSHV VCPU State

- tests/integration.rs
This should be the last point from the bullet list on planned tests for Windows guest and thus closes #1916.
> tests: Add case for multiple net devices for Windows guest

- net_util/src/queue_pair.rs
The TX rate limiter didn't correctly handle the `-EAGAIN` situation
where it should replenish the rate-limiter tokens. This patch simplifies
the TX rate-limiter code path by following the similar trade-off made in
the TX rate limiter, where we always let the `last` descriptor
go-through (even if it was over the rate limit. We simply stop
processing the oncoming `descriptors` if any.
Fixes: #2817
> net_util: queue_pair: Simplify and fix the TX rate limiter

- vmm/src/seccomp_filters.rs
At the beginning of the work we chose to disable seccomp to allow greater flexibility. As things mature we can start enabling seccomp to increase security.
This patch series is just a starting point. With this I can run a Linux guest. If we need to run Windows guest we will also need to add the translate GVA ioctl number.
CC @russell-islam @weltling
> Enable seccomp for MSHV

- test_data/cloud-init/ubuntu/user-data
- tests/integration.rs
> tests: Extend 'test_vfio' with block device passthrough

- vmm/src/api/http.rs
- vmm/src/api/http_endpoint.rs
In order to let a separate process open a TAP device and pass the file
descriptor through the control message mechanism, this patch adds the
support for sending a file descriptor over to the Cloud Hypervisor
process along with the add-net HTTP API command.
The implementation uses the NetConfig structure mutably to update the
list of fds with the one passed through control message. The list should
always be empty prior to this, as it makes no sense to provide a list of
fds once the Cloud Hypervisor process has already been started.
It is important to note that reboot is supported since the file
descriptor is duplicated upon receival, letting the VM only use the
duplicated one. The original file descriptor is kept open in order to
support a potential reboot.
Fixes #2525
Signed-off-by: …
> vmm: http: Allow file descriptor to be sent with add-net

- scripts/dev_cli.sh
It is useful to mount custom volumes sometimes.
> scripts: honour --volumes in cmd_shell

- Cargo.lock
- Cargo.toml
- release-notes.md
- vm-migration/src/lib.rs
> build: Release 17.0

- README.md
> Update README for new RHF version

- docs/memory.md
Documentation supplement for #2902
> docs: Add more information of hugepages.

- virtio-devices/src/vhost_user/vu_common_ctrl.rs
#2911 
after this patch the queue_map become normally. 
```
vgwadm dpdk queue-map
+----------------------------------------------------------------------+-----+----------------------+
|                                ifname                                | tid |      queue_map       |
+----------------------------------------------------------------------+-----+----------------------+
| /vm_data/xxxxxxxxx/test_user_20210712202411/sock/test_user_sn1.sock |  7  |   0 1 4 5 8 9 12 13  |
| /vm_data/xxxxxxxxx/test_user_20210712202411/sock/test_user_sn1.sock |  8  |  2 3 6 7 10 11 14 15 |
+----------------------------------------------------------------------+-----+----------------------+
```
can you review this out, thanks!
> virtio-devices: vhost-user: Enable vrings after all queues ready

- vmm/src/lib.rs
This patch adds a fallback path for sending live migration, where it
ensures the following behavior of source VM post live-migration:
1. The source VM will be paused only when the migration is completed
successfully, or otherwise it will keep running;
2. The source VM will always stop dirty pages logging.
Fixes: #2895
> vmm: Add fallback handling for sending live migration

- Cargo.lock
- pci/Cargo.toml
- pci/src/configuration.rs
- pci/src/vfio.rs
Refactor VFIO code to extract common code that can be reused by the vfio-user implementation. This PR contains a test commit to force the PR to be tried against on the VFIO test machine.
> Refactor VFIO to support userspace VFIO

- test_infra/src/lib.rs
These are are already references so there is no need to take another
reference.
> test_infra: Fix needless borrow warnings

- Cargo.lock
- Cargo.toml
- acpi_tables/Cargo.toml
- arch/Cargo.toml
- block_util/Cargo.toml
- devices/Cargo.toml
- fuzz/Cargo.toml
- hypervisor/Cargo.toml
- net_util/Cargo.toml
- pci/Cargo.toml
- vhost_user_backend/Cargo.toml
- vhost_user_block/Cargo.toml
- vhost_user_net/Cargo.toml
- virtio-devices/Cargo.toml
- vm-allocator/Cargo.toml
- vm-device/Cargo.toml
- vm-migration/Cargo.toml
- vm-virtio/Cargo.toml
- vmm/Cargo.toml
> build: Move from patched vm-memory version to released version

- Cargo.lock
- vhost_user_backend/Cargo.toml
- vhost_user_block/Cargo.toml
- vhost_user_net/Cargo.toml
- virtio-devices/Cargo.toml
> build: Switch to vhost 0.1.0 release

- virtio-devices/src/vhost_user/blk.rs
- virtio-devices/src/vhost_user/fs.rs
- virtio-devices/src/vhost_user/net.rs
- virtio-devices/src/vhost_user/vu_common_ctrl.rs
- vm-migration/src/lib.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
This pull request fixes the missing bits to make vhost-user live migration functional.
Fixes #2813
> vhost-user: Make live migration functional

- arch/src/aarch64/fdt.rs
- arch/src/aarch64/mod.rs
- arch/src/lib.rs
- docs/memory.md
- tests/integration.rs
- vmm/src/acpi.rs
- vmm/src/config.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/vm.rs
This PR will make `--numa` and related config from Cloud Hypervisor command line work on AArch64 platform with FDT.
> AArch64: Enable NUMA for FDT

- docs/uefi.md
I found a few issues when following the instructions.
> docs: amend CSM build instructions

- Cargo.lock
- Cargo.toml
- fuzz/Cargo.toml
- fuzz/fuzz_targets/block.rs
- src/main.rs
- virtio-devices/Cargo.toml
- virtio-devices/src/balloon.rs
- virtio-devices/src/block.rs
- virtio-devices/src/console.rs
- virtio-devices/src/iommu.rs
- virtio-devices/src/lib.rs
- virtio-devices/src/mem.rs
- virtio-devices/src/net.rs
- virtio-devices/src/pmem.rs
- virtio-devices/src/rng.rs
- virtio-devices/src/seccomp_filters.rs
- virtio-devices/src/vhost_user/fs.rs
- virtio-devices/src/vhost_user/net.rs
- virtio-devices/src/vsock/device.rs
- virtio-devices/src/vsock/mod.rs
- virtio-devices/src/watchdog.rs
- vmm/Cargo.toml
- vmm/src/api/http.rs
- vmm/src/api/mod.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/seccomp_filters.rs
- vmm/src/vm.rs
> Move to the rust-vmm/seccompiler crate

- Cargo.lock
- Cargo.toml
- block_util/Cargo.toml
- block_util/src/lib.rs
- block_util/src/vhdx_sync.rs
- fuzz/Cargo.lock
- fuzz/Cargo.toml
- fuzz/fuzz_targets/vhdx.rs
- tests/integration.rs
- vhdx/Cargo.toml
- vhdx/src/lib.rs
- vhdx/src/vhdx.rs
- vhdx/src/vhdx_bat.rs
- vhdx/src/vhdx_header.rs
- vhdx/src/vhdx_io.rs
- vhdx/src/vhdx_metadata.rs
- virtio-devices/src/seccomp_filters.rs
- vmm/Cargo.toml
- vmm/src/device_manager.rs
This PR introduces the support for both fixed and dynamic VHDx file format, along with proper integration testing and fuzzing.
Fixes #2282
> Vhdx: Vhdx implementation, integration, and test

- vmm/src/lib.rs
- vmm/src/vm.rs
Use two separate events for the console and serial PTY and then drive
the handling of the inputs on the PTY separately. This results in the
correct behaviour when both console and serial are attached to the PTY
as they are triggered separately on the epoll so events are not lost.
Fixes: #3012
> vmm: Handle epoll events for PTYs separately

- vmm/src/lib.rs
Remove the indirection of a dispatch table and simply use the enum as
the event data for the events.
> vmm: Simplify epoll handling for VMM main loop

- Cargo.lock
- vfio_user/Cargo.toml
> build: Update vfio_user's vm-memory dependency

- scripts/run_integration_tests_aarch64.sh
> scripts: Enable the live-migration test on AArch64

- tests/integration.rs
This patch refactors and reuses the existing 'test_live_migration' for
adding 'test_live_migraiton_numa'.
> Add integration test for live-migration with NUMA/memory-zones

- Jenkinsfile
This reverts commit d475b953b85289a45c699da77f595ff17724f352.
> Revert "build: Temporarily disable baremetal testing"

- devices/src/acpi.rs
- devices/src/legacy/i8042.rs
- pci/src/configuration.rs
- virtio-devices/src/device.rs
- virtio-devices/src/epoll_helper.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
As per our  documentation https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/logging.md these should be at `info!()` level.
> Move some debug statements to info!() level

- .github/workflows/build.yaml
> github: also build mshv enabled binaries

- fuzz/fuzz_targets/block.rs
- virtio-devices/src/balloon.rs
- virtio-devices/src/block.rs
- virtio-devices/src/console.rs
- virtio-devices/src/iommu.rs
- virtio-devices/src/lib.rs
- virtio-devices/src/mem.rs
- virtio-devices/src/net.rs
- virtio-devices/src/pmem.rs
- virtio-devices/src/rng.rs
- virtio-devices/src/seccomp_filters.rs
- virtio-devices/src/thread_helper.rs
- virtio-devices/src/vhost_user/blk.rs
- virtio-devices/src/vhost_user/fs.rs
- virtio-devices/src/vhost_user/net.rs
- virtio-devices/src/vsock/device.rs
- virtio-devices/src/vsock/mod.rs
- virtio-devices/src/watchdog.rs
- vmm/src/device_manager.rs
Ensure that the VMM is shutdown if a virtio thread panics.
See: #3031
> Shutdown VMM on virtio thread panic

- vmm/src/config.rs
- vmm/src/device_manager.rs
- vmm/src/vm.rs
Miscellaneous improvements around console and signal handling including deduplication of code and bug fixing.
> Improvements to console and signal handling

- Cargo.lock
- Cargo.toml
- release-notes.md
- rpm/cloud-hypervisor.spec
- vm-migration/src/lib.rs
> build: Release v18.0

- vmm/src/cpu.rs
> vmm: cpu: Increase robustness of CpuManager control device

- vmm/src/memory_manager.rs
> vmm: memory_manager: Increase robustness of MemoryManager control device

- vmm/src/api/http.rs
- vmm/src/lib.rs
> vmm: Shutdown VMM if API thread panics

- devices/src/acpi.rs
- devices/src/ioapic.rs
- devices/src/legacy/cmos.rs
> Increase robustness of more legacy devices

- virtio-devices/src/mem.rs
- vmm/src/device_manager.rs
For most use cases, there is no need to create multiple VFIO containers
as it causes unwanted behaviors. Especially when passing multiple
devices from the same IOMMU group, we need to use the same container so
that it can properly list the groups that have been already opened. The
correct logic was already there in vfio-ioctls, but it was incorrectly
used from our VMM implementation.
For the special case where we put a VFIO device behind a vIOMMU, we must
create one container per device, as we need to control the DMA mappings
per device, which is performed at the container level. Because we must
keep one container per device, the vIOMMU use case prevents multiple
devices attached to the same IOMMU group to be passed through the VM.
But this is a limitation that we are fine with, …
> vmm: Create a single VFIO container

- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_x86_64.sh
- tests/integration.rs
Note this PR is relying on #3134 which will be pushing a new docker image once it is merged to the main branch.
> ci: Use the pre-installed virtiofsd

- tests/integration.rs
- virtio-devices/src/balloon.rs
Adding the snapshot/restore support along with migration as well,
allowing a VM with a virtio-balloon device attached to be properly
migrated.
Fixes #1598 
> virtio-devices: balloon: Add snapshot/restore support

- Cargo.lock
- pci/src/lib.rs
- pci/src/vfio_user.rs
- virtio-devices/src/mem.rs
- virtio-devices/src/seccomp_filters.rs
- vmm/Cargo.toml
- vmm/src/device_manager.rs
Implement the mapping logic required for virtio-mem to handle memory changes when using virtio-mem.
> Implement virtio-mem support for vfio-user

- scripts/run_integration_tests_aarch64.sh
The PR optimizes the external software dependency building:
- Pin EDK2 and related software versions to avoid frequent updating and re-building
- Optimize EDK2 building by applying multi-threaded compiling
- Refactor the code for updating external source repos
> Optimize external software building on AArch64

- devices/src/legacy/serial.rs
- devices/src/legacy/uart_pl011.rs
- vmm/src/device_manager.rs
- vmm/src/serial_buffer.rs
- vmm/src/serial_manager.rs
> Serial pty flush

- vmm/src/device_manager.rs
Use a simpler method for extracting the affected slot on the eject
command. Also update the terminology to reflect that this a slot rather
than a bdf (which is what device id refers to elsewhere.)
> vmm: Simplify slot eject code in PCI ACPI device code

- scripts/run_integration_tests_aarch64.sh
- scripts/sha1sums-aarch64
- tests/integration.rs
> tests, scripts: Update custom aarch64 image to include "stress"

- arch/src/x86_64/tdx/mod.rs
- vmm/src/vm.rs
This PR adds the support for the TD_VMM_DATA mechanism allowing the VMM to share specific memory regions with the guest. This is particularly needed for passing the ACPI tables from the VMM to the TDVF running in the guest, so that this firmware can then expose the ACPI tables to the guest OS.
> tdx: Add support for TD_VMM_DATA mechanism and pass ACPI tables

- rpm/cloud-hypervisor.spec
As v19.0 has been release almost a month ago, let's also update the
project's spec file accordingly.
As a side note, it'd be interesting to have this one updated automagically as part of the release process, but that's for a different issue.
> rpm: Update to the latest (v19.0) release

- docs/vhost-user-blk-testing.md
The purpose is to add more info while running
spdk vhost tgt.
> docs: Update vhost-user-blk-testing.md

- option_parser/src/lib.rs
- src/main.rs
- tests/integration.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/cpu.rs
- vmm/src/seccomp_filters.rs
This PR brings to Cloud Hypervisor the ability to pin each and every virtual CPU to a set of host CPUs.
Fixes #3298
> Add CPU pinning support

- block_util/src/lib.rs
- vmm/src/device_manager.rs
These changes improved the time to first guest instruction (release build with huge pages) from about ~25ms to ~15ms.
> Optimise io_uring detection

- docs/vfio.md
Fixing a few inconsistencies and extending the document to tackle
multiple devices use case, as well as having multiple devices under the
same IOMMU group.
> docs: Update VFIO documentation

- .github/workflows/build.yaml
> build: Add GitHub action to build test TDX feature

- virtio-devices/src/epoll_helper.rs
Make some comments more clear.
> virtio-devices: Update some comments in epoll_helper.rs

- vmm/src/config.rs
Update some comments and error message info related with TDX.
> vmm: Update some comments and error message info in config.rs

- qcow/src/raw_file.rs
Function alloc_zeroed can fail. Check its return in read and write
functions. Its return value in is_valid_alignment is not checked because
handling error in that case does not give us much benefit. Instead, an
assertion is added.
Add safety comments to all `unsafe`s.
> qcow: check return value of alloc_zeroed and add safety comments

- vmm/src/config.rs
Make the comments style be consistent
> vmm: Update comments related with enum Error struct in config.rs

- vfio_user/src/lib.rs
In my opinion, it is enough to use debug!
> vfio_user: Replace info! with debug!

- vhost_user_net/src/lib.rs
Fix the comments style to make them consistent.
> vhost_user_net: fix some comments style in lib.rs

- arch/src/x86_64/mod.rs
- vmm/src/vm.rs
If the provided binary isn't an ELF binary assume that it is a firmware
to be loaded in directly. In this case we shouldn't program any of the
registers as KVM starts in that state.
> vmm: Add support for booting raw binary (e.g. firmware) on x86-64

- Cargo.lock
- Cargo.toml
- release-notes.md
- rpm/cloud-hypervisor.spec
- vm-migration/src/lib.rs
Cloud Hypervisor release `v20.0`.
> build: Release v20.0

- vmm/src/memory_manager.rs
Purpose: Do not directly use 0x1000 but use predefined constant value.
> vmm: Add a constant SGX_PAGE_SIZE variable in memory_manager.rs

- Jenkinsfile
> build: Use Ubuntu impish (21.10) for workers

- block_util/src/lib.rs
- block_util/src/qcow_sync.rs
- block_util/src/vhdx_sync.rs
Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3408
> Rework block_util code to be idiomatic

- Jenkinsfile
- scripts/run_integration_tests_windows.sh
- scripts/run_integration_tests_x86_64.sh
- tests/integration.rs
> build: Use OVMF binary released from edk2 repo

- vmm/src/api/openapi/cloud-hypervisor.yaml
> vmm: openapi: Add receive/send-migration endpoints

- Jenkinsfile
As an experiment switch back to hirsute to see if the CI failure /
timeout rate decreases.
> build: Switch base to hirsute as an experiment

- pci/src/vfio_user.rs
The sendmsg() syscall is limited in the number of fds it can handle.
This number matches that used by the vfio-user library and is
conservative (since we've seen it work with 64 fds.)
Fixes: #3401
> pci: vfio_user: Batch IRQ enabling into batches of 16

- block_util/src/async_io.rs
- block_util/src/raw_async.rs
- block_util/src/raw_sync.rs
- tests/integration.rs
- virtio-devices/src/block.rs
- vmm/src/seccomp_filters.rs
> Propagate block topology into guest

- Cargo.lock
- Cargo.toml
- release-notes.md
- rpm/cloud-hypervisor.spec
- virtio-devices/src/vsock/unix/muxer.rs
- vmm/src/device_manager.rs
- vmm/src/seccomp_filters.rs
Pull in new bug fixes for v20.2.
> v20.2 bug fix release

- acpi_tables/src/aml.rs
- arch/src/x86_64/mod.rs
- pci/src/configuration.rs
- src/main.rs
- virtio-queue/src/chain.rs
- vmm/src/acpi.rs
- vmm/src/config.rs
Since these new checks will be hitting beta soon we can get ahead of them.
> Fix new clippy issues (from nightly)

- README.md
> README: Ensure kernel build includes the ELF PVH note

- hypervisor/src/kvm/mod.rs
If the guest hasn't initialised a PV clock then the KVM_KVMCLOCK_CTRL
ioctl will return -EINVAL. Therefore if running in the firmware or an OS
that doesn't use the PV clock then we should ignore that error
Tested by migrating a VM that has not yet booted into the Linux kernel
(just in firmware) by specifying no disk image:
e.g. target/debug/cloud-hypervisor --kernel ~/workloads/hypervisor-fw --api-socket /tmp/api --serial tty --console off
Fixes: #3586
> hypervisor: kvm: Ignore -EINVAL from KVM_KVMCLOCK_CTRL ioctl()

- block_util/src/lib.rs
- tests/integration.rs
- virtio-devices/src/block.rs
Whenever the backing file of our virtio-block device is opened with
O_DIRECT, there's a requirement about the buffer address and size to be
aligned to the sector size.
We know virtio-block requests are sector aligned in terms of size, but
we must still check if the buffer address is. In case it's not, we
create an intermediate buffer that will be passed through the system
call. In case of a write operation, the content of the non-aligned
buffer must be copied beforehand, and in case of a read operation, the
content of the aligned buffer must be copied to the non-aligned one
after the operation has been completed.
Fixes #3587
> block_util: Align buffers for O_DIRECT

- Cargo.lock
- Cargo.toml
- release-notes.md
- rpm/cloud-hypervisor.spec
- vm-migration/src/lib.rs
> build: Release v21.0

- Cargo.lock
- arch/src/aarch64/fdt.rs
- arch/src/aarch64/mod.rs
- hypervisor/src/cpu.rs
- hypervisor/src/kvm/mod.rs
- tests/integration.rs
- vmm/src/cpu.rs
- vmm/src/seccomp_filters.rs
- vmm/src/vm.rs
PMU is needed for guest performance or debug profiling. Add it for arm64.
> arm64/vcpu: add PMU for vcpu

- README.md
- docs/uefi.md
- docs/windows.md
A general PR updating the documentation regarding OVMF and the usage with QEMU, as well as updating the README formatting.
> docs: Update documentation and formatting

- docs/snapshot_restore.md
Remove the bits about this feature being experimental, as well as
limitations around virtio-mem and vhost-user devices.
> docs: Update snapshot/restore documentation

- vmm/src/config.rs
> vmm: config: Validate balloon size is less than RAM size

- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_x86_64.sh
> tests: Bump version of virtiofsd-rs in use to latest tagged

- tests/integration.rs
In this way, we can cover local-migration with dpdk in our regular CI,
to prevent similar regressions reported and fixed by #3657.
Fixes: #3659
> tests: Add "test_live_migration_ovs_dpdk_local()" test

- docs/fs.md
- docs/virtiofs-root.md
- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_x86_64.sh
- tests/integration.rs
Remove tests and update documentation.
Fixes: #3729
> Move exclusively to Rust virtiofsd

- virtio-devices/src/vhost_user/blk.rs
- virtio-devices/src/vhost_user/fs.rs
- virtio-devices/src/vhost_user/net.rs
For vhost-user devices, we don't want to loose the vhost-user protocol
feature through the negotiation between guest and device. Since we know
VIRTIO has no knowledge of the vhost-user protocol feature, there is no
way it would ever be acknowledged by the guest. For that reason, we
create each vhost-user device with the set of acked features containing
the vhost-user protocol feature is this one was part of the available
list.
Having the set of acked features containing this bit allows for solving
a bug that was happening through the migration process since the
vhost-user protocol feature wasn't explicitely enabled.
> virtio-devices: Consider vhost-user protocol feature as acked

- vmm/src/api/mod.rs
> vmm: api: Make VmSendMigrationData.local optional

- pci/src/configuration.rs
The same way we mask the writes coming from the guest to the message
control register related to MSI-X capability, let's do the same for MSI.
The point is to prevent the guest from writing to read-only bits.
The correct writable bits for MSI are only bits 0, 4, 5 and 6 of 2nd
16-bit word.
Those are:
* MSI Enable: 0
* Multiple Message Enable: 6-4
See "Table 7-39 Message Control Register for MSI" from
"NCB-PCI_Express_Base_5.0r1.0-2019-05-22.pdf".
> pci: Allow only writable bits for MSI message control register

- Cargo.lock
- Cargo.toml
- release-notes.md
- rpm/cloud-hypervisor.spec
- vm-migration/src/lib.rs
> build: Release v22.0

- Cargo.lock
- test_infra/Cargo.toml
> build: Use consistent version of dirs crate

- performance-metrics/src/main.rs
* Boot time in ms
* Network throughput in Gbps
* Block throughput in MiBps
> performance-metrics: Use friendlier metric units

- src/main.rs
Replace the thread for handling SIGSYS with a simple signal handler.
This resolves inconsistent delivery of signals to the SIGSYS thread due
to other threads manipulating the signals.
Tested by removing key syscalls from vCPU and virtio device filters and
observing correct notice.
Fixes: #3811
> main: Use non-threaded signal handler for SIGSYS

- tests/integration.rs
- virtio-devices/src/net.rs
(Including Integration test.)
I have further fixes to this code but will push into a separate PR as I think we will want to cherry pick this bug fix to v22 and possibly v21.
> Fix virtio-net control queue issue

- Cargo.lock
- Cargo.toml
- hypervisor/src/cpu.rs
- hypervisor/src/kvm/mod.rs
- hypervisor/src/kvm/x86_64/mod.rs
- pci/src/configuration.rs
- release-notes.md
- rpm/cloud-hypervisor.spec
- virtio-devices/src/net.rs
- virtio-devices/src/seccomp_filters.rs
- vmm/src/cpu.rs
- vmm/src/interrupt.rs
> Release v21.1

- Cargo.lock
- Cargo.toml
- release-notes.md
- rpm/cloud-hypervisor.spec
- virtio-devices/src/net.rs
- vmm/src/interrupt.rs
> Release v22.1

- docs/performance_metrics.md
> docs: Add a documentation for performance metrics

- performance-metrics/src/main.rs
Main change is using UNIX exit code to indicate that something has failed.
> More peformance-metrics improvements

- Jenkinsfile
hirsute is EOLed and focal is receiving kernel updates on Azure.
> build: Move Jenkins workers to focal

- docs/api.md
vm.snapshot/restore is missed, add this part.
Signed-off-by: Yi Wang <wang.yi59@zte.com.cn>
> docs: api: Add documentation for vm.snapshot/restore

- Cargo.lock
- Jenkinsfile
- docs/api.md
- scripts/prepare_vdpa.sh
- scripts/run_integration_tests_x86_64.sh
- src/bin/ch-remote.rs
- src/main.rs
- tests/integration.rs
- virtio-devices/Cargo.toml
- virtio-devices/src/lib.rs
- virtio-devices/src/vdpa.rs
- vmm/src/api/http.rs
- vmm/src/api/http_endpoint.rs
- vmm/src/api/mod.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/seccomp_filters.rs
- vmm/src/vm.rs
Adding the vDPA support through this PR.
vIOMMU and migration support will come later.
> Add vDPA support

- vmm/src/lib.rs
Separate the destruction and cleanup of original VM and the creation of
the new one. In particular have a clear hand off point for resources
(e.g. reset EventFd) used by the new VM from the original. In the
situation where vm.shutdown() generates an error this also avoids the
Vmm reference to the Vm (self.vm) from being maintained.
>  vmm: Streamline reboot code path

- scripts/run_integration_tests_aarch64.sh
As Linux kernel, edk2, virtiofd, SPDK are all build from source, we
need to find a way to reduce the number of source code build.
To address this issue, this commit adds a stage that touching a
".built" file to each repo of the source code after a successfully
build. By checking if the ".built" file exists, we can determine
if there is already an old build. Since the source code repo will
be removed and cloned again when we bump the repo hash, the CI will
rebuild the repo.
> scripts: aarch64: Reduce source code build in CI

- vmm/src/memory_manager.rs
This is similar to the dynamic concept used in CpuManager.
> vmm: Reject memory resizing on TDX

- vmm/src/cpu.rs
This is now consistent with not supplying the _CRS for the device when
CpuManager is not dynamic.
> vmm: cpu: Don't place CpuManager on MMIO bus when non-dynamic

- vmm/src/config.rs
> vmm: Improve 'test_config_validation' with precise Err assertions

- docs/vdpa.md
Explain the reason why using vDPA might be interesting and how to use it
with Cloud Hypervisor.
> docs: Add documentation for vDPA

- scripts/run_metrics.sh
As discussed in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3838#discussion_r833056519
This commit makes sure that the custom linux kernel is always
rebuilt when running the performance metrics tests, and therefore
changes to the kernel config file is always caught.
> scripts: run_metrics: Always build the custom linux kernel

- tests/integration.rs
It seems the vdpa_sim_block isn't behaving properly after the vhost
device is closed, as it sometimes returns EBUSY when we try to open it
again. The easiest way to deal with this issue is by simplifying the
integration test, avoid to plug the same device after it's been
unplugged.
> tests: Simplify test_vdpa_block() to increase stability

- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_x86_64.sh
- scripts/sha1sums-aarch64
- scripts/sha1sums-x86_64
- tests/integration.rs
- vmm/src/seccomp_filters.rs
> tests: Move to use Jammy guest image for `test_vfio_user`

- README.md
Remove EOLed distributions and clarify the stability guarantees and what
the experimental features are.
> README: Update OS list and clarify release stability

- vhost_user_block/Cargo.toml
- vhost_user_net/Cargo.toml
Similar issues fixed from #3963 when building the binary from the target directory (instead of the project root directory).
> vhost_user_block/net: Fix build from the target folder

- .github/workflows/build.yaml
- .github/workflows/quality-aarch64.yaml
- tests/integration.rs
Ensure that we build the tests as part of our build testing using GH Actions.
- .github: Run clippy checks over tests on aarch64
- .github: Test building of tests on each commit
> Build tests in GH workflow

- Cargo.lock
- Cargo.toml
- release-notes.md
- rpm/cloud-hypervisor.spec
- vm-migration/src/lib.rs
> build: Release v23.0

- README.md
> README: Update recommended version of Rust Hypervisor Firmware

- virtio-devices/src/mem.rs
If the guest has not activated the virtio-mem device then reject an
attempt to resize using it.
Fixes: #4001
> virtio-devices: mem: Reject resize if device not activated by guest

- pci/src/msi.rs
- pci/src/vfio.rs
- pci/src/vfio_user.rs
- vmm/src/device_manager.rs
This PR introduces some preliminary changes that will be needed to implement Snapshot for VFIO and vfio-user devices.
> pci: Preparatory work for supporting snapshot/restore for Vfio and VfioUser

- arch/src/aarch64/mod.rs
- arch/src/lib.rs
- arch/src/x86_64/mod.rs
- vmm/src/api/http.rs
- vmm/src/config.rs
- vmm/src/cpu.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
- vmm: api: Don't use clashing struct name for Error
- arch: Improve arch::Error
- vmm: cpu: Improve Error reporting
- vmm: config: Derive thiserror::Error
- vmm: Improve error handling for vmm::vm::Error
> Some error improvements

- vmm/src/config.rs
This means that the automatic enabling of the virtio-iommu will also be
applied to VMs creates via the API as well as the CLI.
Fixes: #4016
> vmm: Enable virtio-iommu in VmConfig::validate()

- README.md
- docs/releases.md
Here's a write up based on the discussions in #3926. Some places could sure use a correction and more input is welcome especially from the folks on the maintainers list. If this form of a documentation and commitment is something we could bear, the feedback can be integrated directly or by filing a PR against this branch. Some parts depend on what will yet come out from the LTS proposal.
Thanks
> Release doc

- vmm/src/device_manager.rs
Whenever a device (virtio, vfio, vfio-user or vdpa) is hotplugged, we
must verify the provided identifier is unique, otherwise we must return
an error.
Particularly, this will prevent issues with identifiers for serial,
console, IOAPIC, balloon, rng, watchdog, iommu and gpio since all of
these are hardcoded by the VMM.
> vmm: Ensure hotplugged device identifier is unique

- qcow/src/qcow.rs
> qcow: Reject files with compressed blocks early

- vmm/src/config.rs
- vmm/src/device_manager.rs
For devices that cannot be named by the user use the "__" prefix to
identify them as internal devices. Check that any identifiers provided
in the config do not clash with those internal names. This prevents the
user from creating a disk such as "__serial" which would then cause a
failure in unpredictable manner.
> vmm: Prevent "internal" identifiers being used by user

- pci/src/vfio.rs
- pci/src/vfio_user.rs
- vfio_user/src/lib.rs
- vmm/src/device_manager.rs
> Support Sparse Regions for VFIO User

- pci/src/vfio.rs
Reorganizing the code to leverage the same mechanics implemented for
vfio-user and aimed at supporting sparse memory mappings for a single
region.
Relying on the capabilities returned by the vfio-ioctls crate, we create
a list of sparse areas depending if we get SPARSE_MMAP or MSIX_MAPPABLE
capability, or a single sparse area in case we couldn't find any
capability.
The list of sparse areas is then used to create both the memory mappings
in the Cloud Hypervisor address space and the hypervisor user memory
regions.
This allowed for the simplification of the MmioRegion structure.
> pci: vfio: Implement support for sparse mmap

- Jenkinsfile
These require machines that are currently offline.
> build: Temporarily disable VFIO, SGX and metrics build steps

- src/main.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
> vmm: config: Remove mergeable option from PmemConfig

- Cargo.lock
> deps: Bump version of kvm-ioctls

- vmm/src/cpu.rs
Based on recent KVM host patches (merged in Linux 5.16), it's forbidden
to call into KVM_SET_CPUID2 after the first successful KVM_RUN returned.
That means saving CPU states during the pause sequence, and restoring
these states during the resume sequence will not work with the current
design starting with kernel version 5.16.
In order to solve this problem, let's simply move the save/restore logic
to the snapshot/restore sequences rather than the pause/resume ones.
> vmm: cpu: Save and restore CPU states during snapshot/restore

- .github/workflows/quality.yaml
- vmm/src/coredump.rs
- vmm/src/cpu.rs
- vmm/src/vm.rs
- vmm: Fix clippy issues under "guest_debug" feature
- .github: Add missing clippy check with "guest_debug" feature
> Fix "guest_debug" clippy

- Jenkinsfile
This reverts commit d96614fe42e6c2f19538a4ef85b1a333593c0f16.
> Revert "build: Temporarily disable VFIO, SGX and metrics build steps"

- docs/profiling.md
> docs: Add LBR profiling instructions to profiling.md

- src/bin/ch-remote.rs
- test_infra/src/lib.rs
- tests/integration.rs
- ch-remote: Add missing boot and delete commands
- tests: Add tests for vm.delete and vm.shutdown
> Add missing API integration tests

- block_util/src/async_io.rs
- hypervisor/src/arch/emulator/mod.rs
- vhost_user_block/src/lib.rs
- virtio-devices/src/device.rs
- vmm/src/api/http.rs
Some of the traits don't need both. Some don't need them at all.
> Relax some Sync and Send bounds

- hypervisor/src/arch/x86/emulator/instructions/mod.rs
No functional change. Just make the code a bit nicer to read.
> hypervisor: emulator: use matches!

- src/bin/ch-remote.rs
Tested by:
1. Path: ch-remote --api-socket .. create test-config.json
2. stdin with "-" path: ch-remote --api-socket .. create - < test-config.json
2. stding with implicit "-": ch-remote --api-socket .. create < test-config.json
Fixes: #4250
> ch-remote: Add "create" command to ch-remote

- hypervisor/src/cpu.rs
- hypervisor/src/kvm/aarch64/gic/redist_regs.rs
- hypervisor/src/kvm/mod.rs
- hypervisor/src/lib.rs
- hypervisor/src/mshv/mod.rs
- hypervisor/src/mshv/x86_64/mod.rs
- hypervisor/src/vm.rs
- vmm/src/vm.rs
One step closer to a unified binary.
This series showcases how opaque structures will be handled.
The first patch is from another PR that's pending. You can safely ignore it.
CC @russell-islam @jinankjain
> Provide a few generic structures

- hypervisor/src/cpu.rs
- hypervisor/src/mshv/mod.rs
> hypervisor: mshv: drop get_suspend_regs

- tests/integration.rs
> tests: Skip test_vfio for now

- hypervisor/src/arch/x86/mod.rs
- hypervisor/src/cpu.rs
- hypervisor/src/kvm/mod.rs
- hypervisor/src/kvm/x86_64/mod.rs
- hypervisor/src/mshv/mod.rs
- hypervisor/src/mshv/x86_64/mod.rs
- vmm/src/cpu.rs
This PR focus on MSR list and entry.
Please review carefully the code in get_state and set_state, since it is difficult to test the loop there.
> Unified binary -- part 5

- Cargo.lock
- fuzz/Cargo.lock
- hypervisor/Cargo.toml
- hypervisor/src/arch/aarch64/gic.rs
- hypervisor/src/cpu.rs
- hypervisor/src/device.rs
- hypervisor/src/kvm/aarch64/gic/dist_regs.rs
- hypervisor/src/kvm/aarch64/gic/icc_regs.rs
- hypervisor/src/kvm/aarch64/gic/mod.rs
- hypervisor/src/kvm/aarch64/gic/redist_regs.rs
- hypervisor/src/kvm/mod.rs
- hypervisor/src/lib.rs
- hypervisor/src/mshv/mod.rs
- hypervisor/src/vm.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
This PR rework the code to make use of the new vfio-ioctls APIs.
The vfio-ioctls PR is still pending. https://github.com/rust-vmm/vfio/pull/9
This however showcases what the code looks like with the new APIs.
Cc @michael2012z @MrXinWang @jinankjain @russell-islam
> Unified binary -- part 6

- .github/workflows/build.yaml
- .github/workflows/quality.yaml
- hypervisor/src/cpu.rs
- hypervisor/src/hypervisor.rs
- hypervisor/src/kvm/mod.rs
- hypervisor/src/lib.rs
- hypervisor/src/mshv/mod.rs
- hypervisor/src/vm.rs
- src/main.rs
- vmm/src/api/http.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/seccomp_filters.rs
- vmm/src/vm.rs
This is the last batch for supporting a unified binary.
This PR deals with all the issues when I enable kvm and mshv at the same time. At the end it also contains ~a new command line option and~ changes to GitHub actions.
CC @michael2012z @MrXinWang @jinankjain @russell-islam
> Unified binary -- part 7

- Cargo.lock
- arch/Cargo.toml
- devices/Cargo.toml
- hypervisor/Cargo.toml
- vfio_user/Cargo.toml
- vhdx/Cargo.toml
- vm-allocator/Cargo.toml
- vm-device/Cargo.toml
- vm-virtio/Cargo.toml
I found these issues when analysing the dependencies tree for the Windows porting experiment.
> Clean up dependencies

- hypervisor/src/mshv/mod.rs
> hypervisor: mshv: Remove more #[allow(dead_code)] and unused code

- Jenkinsfile
- scripts/prepare_vdpa.sh
> build: Move Jenkins workers over to jammy

- Jenkinsfile
- fuzz/Cargo.lock
- fuzz/Cargo.toml
- fuzz/fuzz_targets/cmos.rs
- fuzz/fuzz_targets/serial.rs
> fuzz: Add fuzzers for serial & cmos devices

- Cargo.lock
- hypervisor/Cargo.toml
- hypervisor/src/arch/x86/mod.rs
Drop the hand-rolled serializer and deserializer.
~RFC due to introducing a new crate.~
> hypervisor: use serde_with with LapicState

- README.md
> README: Update version of Rust Hypervisor Firmware release

- tests/integration.rs
Both of these tests have been sporadically failing through multiple CI
runs. The reason is related to cloud-init which fails to run the
"init-local" script during the second boot of the VM. This causes the
network interface to not be available, and therefore the test can't SSH
into the VM as expected. The root cause is the filesystem and cache
corruption that happens on the cloud-init disk.
The way to prevent from this issue is to sync the guest filesystem
before we shut it down, and as a security harness, we also wait for a
few seconds for the shutdown command to complete inside the guest before
we trigger the API shutdown or delete.
> tests: Make test_api_shutdown and test_api_delete more reliable

- tests/integration.rs
Improve error catching on the steps creating the block device so that we
can understand if qemu-img or losetup is the faulty command leading to
an empty device path.
> tests: Re-enable virtio_block_topology on aarch64

- docs/fs.md
> docs: mention thread pool option for virtiofsd

- Cargo.lock
- arch/Cargo.toml
- arch/src/x86_64/mod.rs
- arch/src/x86_64/smbios.rs
- src/main.rs
- tests/integration.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/vm.rs
UUID indicates the unique ID of a VM, cloud-hypervisor takes the uuid passed by libvirt and also uses it to initialize cloud-init.
> Expose platform uuid via SMBIOS

- arch/Cargo.toml
- fuzz/Cargo.lock
- net_util/Cargo.toml
- pci/Cargo.toml
- test_infra/Cargo.toml
- vfio_user/Cargo.toml
- vhdx/Cargo.toml
- virtio-devices/Cargo.toml
Some dependencies are not tracking the latest version in the .toml file
so update all dependencies to the latest version.
> deps: Bulk upgrade dependencies

- arch/src/x86_64/smbios.rs
Fix memory corruption and use proper end of table structure.
> Fix SMBIOS code

- arch/src/x86_64/mod.rs
- arch/src/x86_64/smbios.rs
- src/main.rs
- tests/integration.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/vm.rs
> Add SMBIOS OEM strings support

- virtio-devices/src/block.rs
Remove the use of 'unwrap()' that assumes the guest address for request
status is always valid, which avoid virtio-block thread panic on
malformed descriptors from the guest.
> virtio-devices: block: Avoid panic with invalid guest address

- devices/src/legacy/uart_pl011.rs
- hypervisor/src/arch/x86/gdt.rs
- qcow/src/qcow.rs
- vfio_user/src/lib.rs
> Fix a bunch of clippy warnings

- tests/integration.rs
The test test_virtio_block_topology has been recently failing due to an
error happening in losetup while trying to set the block size. Since
there's no option in losetup for retrying, we took the approach of
programming the expected behavior of creating a loop device relying
directly on the system ioctl LOOP_CONFIGURE. We apply a retry loop based
on the result returned by this ioctl, so that we don't fail on the first
try. We also added a sleep before retrying, hoping this would help the
next iteration to succeed.
Fixes #3494
> tests: Improve test_virtio_block_topology reliability

- docs/api.md
- test_infra/src/lib.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- docs: Update API documentation for payload API
- docs: api.md: Fix table markdown syntax
- tests: Update integration test to use new payload API
- vmm: openapi: Fix OpenAPI YAML file formatting
- vmm: openapi: Switch to describing new payload API
> Update use of API for payload changes

- vmm/src/device_manager.rs
Adding new I/O ports for both the ACPI shutdown and the ACPI PM timer
devices so they can be triggered from both addresses. The reason for
this change is that TDX expects only certain I/O ports to be enabled
based on what QEMU exposes. We follow this to avoid new ports from being
opened exclusively for Cloud Hypervisor.
We have to keep the former I/O ports available given all firmwares
haven't been updated yet. Once we reach a point where we know both Rust
Hypervisor Firmware, OVMF, TDVF and TDSHIM have been updated with the
new port values, we'll be able to remove the former ports.
> vmm: Add new I/O ports for ACPI shutdown and PM timer devices

- Cargo.lock
- Cargo.toml
- release-notes.md
- rpm/cloud-hypervisor.spec
- vm-migration/src/lib.rs
> build: Release v26.0

- Jenkinsfile
These machines will be temporarily unavailable.
> Jenkinsfile: Temporarily remove x86-64 bare metal testing

- virtio-devices/src/block.rs
- virtio-devices/src/net.rs
Following the previous refactoring of virtio-devices #4479, this PR refactors the event handling of block/net with cleaner error reporting, which is mostly about handling 'rate-limiter' events. 
I also manually tested the PR with rate-limiter on both `block` (single-queue, throughput and IOPS) and `net` (single-queue, rx/tx throughput), and the results are consistent with the ones reported from #2333 and #2401.
> virtio-devices: Refactor event handling (mostly on rate-limiter) of block and net for readability 

- scripts/run_integration_tests_aarch64.sh
- tests/integration.rs
Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4510
> tests: Enable live upgrade tests on AArch64

- vmm/src/serial_buffer.rs
We must limit how much the buffer can grow, otherwise this could lead
the process to consume all the memory on the machine. This could happen
if the output from the guest was very important and nothing would
connect to the PTY for a long time.
> vmm: Limit the size of the SerialBuffer

- .github/workflows/quality-aarch64.yaml
- .github/workflows/quality.yaml
> .github: workflows: Fix per commit buildability check

- fuzz/fuzz_targets/block.rs
- virtio-devices/src/device.rs
- virtio-devices/src/epoll_helper.rs
It provides fuzzer a reliable way to wait for a sequence of synchronous
events to complete for virtio-devices while not using a fixed timeout to
maintain the full speed of fuzzing.
Take virtio-block (with synchronous backends) as an example, the 'queue
event' with a valid available queue setup can trigger a 'completion
event'. This is a meaningful virtio-block code path of processing guest
inputs which is our target for fuzzing virtio devices.
> fuzz, virtio-devices: Custom `EpollHelper::run` and `VirtioCommon:reset` for fuzz via `#[cfg(fuzzing)]`

- fuzz/fuzz_targets/block.rs
Instead of always fuzzing virt-queues with default values (mostly 0s),
the fuzzer now initializes the virt-queue based on the fuzzed input
bytes, such as the tail position of the available ring, queue size
selected by driver, descriptor table address, available ring address,
used ring address, etc. In this way, the fuzzer can explore the
virtio-block code path with various virt-queue setup.
> fuzz: block: Setup the virt queue based on the fuzzed input bytes

- devices/src/acpi.rs
Rather than overloading the GED device with the detection of what the
underlying event means move that to a new generic event controller.  The
advantage of this is that that the generic event controller can have a
_CRS that covers the memory for the OperationRegion (the ged driver
rejects _CRS entries that contain anything beyond the single interrupt)
> devices: acpi: Add generic event controller

- README.md
> README: Add host kernel version details

- tests/integration.rs
This patch moves the actual test logic and assertions from various functions to the actual tests, which makes these tests more readable and easier to debug.
> tests: Refactor 'test_watchdog' for better readability

- docs/vsock.md
The page contains basic terms and usage instructions on the vsock usage in Cloud Hypervisor.
Co-authored-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
> doc: Add VSOCK doc page

- virtio-devices/src/rng.rs
- virtio-devices/src/watchdog.rs
> Avoid panic and propagate errors properly for virtio-rng and virtio-watchdog

- fuzz/Cargo.toml
- fuzz/fuzz_targets/balloon.rs
- fuzz/fuzz_targets/rng.rs
- fuzz/fuzz_targets/watchdog.rs
> Add fuzzers for virtio balloon, rng and watchdog

- arch/src/x86_64/mod.rs
- build.rs
- hypervisor/src/arch/x86/emulator/instructions/cmp.rs
- hypervisor/src/kvm/aarch64/gic/redist_regs.rs
- hypervisor/src/kvm/mod.rs
- performance-metrics/build.rs
- performance-metrics/src/main.rs
- performance-metrics/src/performance_tests.rs
- qcow/src/qcow.rs
- src/main.rs
- test_infra/src/lib.rs
- tests/integration.rs
- virtio-devices/src/transport/pci_common_config.rs
- vmm/src/lib.rs
- vmm/src/pci_segment.rs
- vmm/src/vm.rs
- misc: Automatic beta clippy fixes
- misc: Manual beta clippy fixes (boolean to int conversion using if)
> Fixes for beta clippy

- Jenkinsfile
Bare metal x86-64 systems are offline
> build: Disable VFIO, metrics and rate limit testing

- virtio-devices/src/mem.rs
- vmm/src/device_manager.rs
- vmm/src/memory_manager.rs
There's no need to delegate the resize operation to the virtio-mem thread. This can come directly from the vmm thread which will use the Mem object to update the VIRTIO configuration and trigger the interrupt for the guest to be notified.
In order to achieve what's described above, the VirtioMemZone structure now has a handle onto the Mem object directly. This avoids the need for intermediate Resize and ResizeSender structures.
> virtio-devices, vmm: Simplify virtio-mem resize operation

- README.md
> README: Add roadmap section pointing to our new GitHub project

- virtio-devices/src/rng.rs
With the virtio-rng device the descriptors that are provided by the
guest must be writable and of non-zero length. Also propagate an error
if writing to the guest memory fails.
> virtio-devices: rng: Error out of queue execution on invalid requests

- api_client/src/lib.rs
api-client: Refactor to removed hard-coded prefix
The existing API client only allows access to "VM" operations, so added
a new `simple_api_full_command_with_fds()` that allows access to "VMM"
operations too.
Also added a `simple_api_full_command()` to avoid having to specify the
file descriptors, in a similar manner to `simple_api_command()`.
Fixes: #4701.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
> api-client: Refactor to removed hard-coded prefix

- api_client/src/lib.rs
Previously, the API response was always written to stdout, but that may not be appropriate for all clients.
The client can now control this behaviour as the client API returns the response in the `Result`.
Fixes: #4703.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
> api-client: Allow response to be captured

- README.md
> README.md: Add mailing list details

- Cargo.lock
- Cargo.toml
- block_util/Cargo.toml
- fuzz/Cargo.toml
- net_util/Cargo.toml
- release-notes.md
- vhost_user_block/Cargo.toml
- virtio-devices/Cargo.toml
- vm-migration/src/lib.rs
- vm-virtio/Cargo.toml
- vmm/Cargo.toml
This also incorporates the bump to virtio-queue 0.6.1
> build: Release v27.0

- vmm/src/vm.rs
This functionality was deprecated and is for removal in the upcoming
release.
Fixes: #4511
> vmm: Remove legacy firmware loading

- virtio-devices/src/watchdog.rs
Don't silently ignore the descriptors provided by the guest. This is
consistent with other devices.
> virtio-devices: watchdog: Generate error on invalid queue descriptor

- virtio-devices/src/mem.rs
Propagating errors of the virtio-mem worker thread correctly ensures timely error handling from the VMM. This makes fuzzing more efficient as "error" paths will be reported and terminated faster.
> Refactor virtio-mem for better error handling and simplicity

- pci/src/msix.rs
With an updated Linux kernel the kernel reprograms the same table entry
in the MSI-X table multiple times. Fortunately it does so with entry
masked (the default.)
The costly part of MSI-X table reprogramming is going out to the host
kernel to update the GSI routing entries. This change makes three
optimisations.
1. If the table entry is unchanged: skip handking updates
2. Only update the GSI routing table if the table entry is unmasked
(this skips extra calls to the ioctl() for reprogramming the
entries.)
3. Only generate a message on entry unmasking if the global MSI-X enable
bit is set.
Fixes: #4273
> pci: Optimise MSI-X table programming

- vmm/src/seccomp_filters.rs
> seccomp: mshv: Allow create partition ioctl

- hypervisor/src/cpu.rs
> hypervisor: Fix a typo in error message

- virtio-devices/src/console.rs
- virtio-devices/src/iommu.rs
- virtio-devices/src/net.rs
For virtio console/iommu/net, the number of queues and associated events
is known and fixed. We can define and use each of them explicitly and 
avoid using vector (and hence direct indexing), which is cleaner and
slightly more efficient. For the case of virtio-iommu, the refactoring
also make it clearer that the "event queue" events are not being handled.
> virtio-devices: Avoid using vector and direct indexing

- virtio-devices/src/iommu.rs
> virtio-devices: iommu: Remove trivial handling of 'EVENT_Q_EVENT'

- fuzz/Cargo.toml
- fuzz/fuzz_targets/iommu.rs
- virtio-devices/src/iommu.rs
- virtio-devices: iommu: Provide 'wait_for_epoll_threads()'
- fuzz: Add fuzzer for virtio-iommu
> Add fuzzer for virtio-iommu

- virtio-devices/src/console.rs
- virtio-devices: console: Report error instead of panic
- virtio-devices: console: Propagate GuestMemory errors properly
> Improve error handling for virtio-console

- virtio-devices/src/console.rs
Since the processing of the console inputs was moved from the VMM thread
to the virtio-console thread (#3061), we have been using the 'FILE_EVENT'
to handle input from stdin/pty/file, which made 'INPUT_EVENT' obsoleted.
> virtio-devices: console: Remove obsoleted 'INPUT_EVENT'

- Jenkinsfile
- scripts/run_integration_tests_x86_64.sh
- build: Run linter over Jenkinsfile
- build: Consolidate integration testing to reused built assets
> Experiment with streamlined Jenkins builds

- docs/windows.md
> docs: Fix broken link in windows.md

- fuzz/Cargo.toml
- fuzz/fuzz_targets/console.rs
- virtio-devices/src/console.rs
- virtio-devices/src/epoll_helper.rs
- virtio-devices: console: Provide 'wait_for_epoll_threads'
- virtio-devices: Custom 'EpollHelper::run_with_timeout' for fuzz
- fuzz: Add fuzzer for virtio-console
> Add fuzzer for virtio-console

- arch/src/aarch64/fdt.rs
Currently, CPU mask involved into PMU irqflag caculation which is used for Gicv2. It limits the CPU number up to 31. For Gicv3+, CPU mask is no longer needed. More info see [1].
[1] https://lore.kernel.org/all/165668798833.3744902.12084627427900181326.b4-ty@kernel.org/t/
> AArch64/fdt: fix PMU irqflag calculation

- docs/seccomp.md
> docs: seccomp: Enhance strace command to print thread name

- virtio-devices/src/block.rs
TEST=Boot `--disk readonly=on` along with a guest that tries to write
(unmodified hypervisor-fw) and observe that the virtio device thread no
longer panics.
Fixes: #4888
> virtio-devices: block: Return error to driver on writes if read-only

- tests/integration.rs
There is no need for this test any longer as we have plenty of other
tests that reboot the VM.
Further this test used unmodified bionic image, which not only will be
EOLed soon but also took a long time to shutdown as it still had snapd
installed.
Fixes: #4849
> tests: Remove test_reboot

- README.md
> README: Update version of Rust Hypervisor Firmware

- tracer/src/tracer.rs
Allocation is only required when creating a new entry in the hashmap.
> tracer: avoid unnecessary allocations

- Jenkinsfile
> Jenkinsfile: Re-enable metrics CI

- Cargo.lock
- Cargo.toml
- release-notes.md
- vm-migration/src/lib.rs
> build: Release v28.0

- Jenkinsfile
- docs/custom-image.md
- scripts/run_integration_tests_sgx.sh
- scripts/run_integration_tests_x86_64.sh
- scripts/sha1sums-x86_64
- tests/integration.rs
- tests: Modernise SGX testing
- docs: Add cpuid to custom disk image instructions
- tests: Update version of jammy image in use
- Jenkinsfile: Re-enable SGX CI testing
> Modernise & re-enable SGX testing

- net_util/src/tap.rs
- net_util: tap: Refactor TAP ioctl calls
- net_util: tap: Include ioctl code in failure errors
> Improve ioctl tap error reporting

- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_live_migration.sh
- scripts/run_integration_tests_rate_limiter.sh
- scripts/run_integration_tests_sgx.sh
- scripts/run_integration_tests_vfio.sh
- scripts/run_integration_tests_windows_aarch64.sh
- scripts/run_integration_tests_windows_x86_64.sh
- scripts/run_integration_tests_x86_64.sh
- scripts/run_metrics.sh
- scripts: Make --hypervisor=mshv only affect features used by tests
- build: Add mshv as default feature
> Integration test mshv+kvm binary

- Cargo.lock
- Cargo.toml
- fuzz/Cargo.toml
- vhost_user_block/Cargo.toml
- vhost_user_net/Cargo.toml
- virtio-devices/Cargo.toml
> build: Move to released versions of vhost and vhost-user-backend crates

- vmm/src/vm.rs
TDX was broken by the recent refactoring moving the vCPU creation earlier than before. The simple and correct way to fix this problem is by moving the TDX initialization right before the vCPUs creation. The rest of the TDX setup can remain where it is.
> vmm: Move TDX initialization before vCPUs creation

- README.md
> README: Use consistent path to cloud-hypervisor binary

- arch/src/x86_64/tdx/mod.rs
The preferred way of retrieving the offset where to find the TDVF descriptor structure is by going through a table of GUIDs that can be found at a specific offset in the firmware file. If the expected GUIDs can't be found, we can fallback onto the former way, which is to read directly the value at a specific offset in the file.
This patch implements the new mechanism without breaking compatibility for older firmwares as it keeps supporting the previous mechanism.
As a reference, here is the documentation from the EDK2 code, and particularly from the OvmfPkg/ResetVector/Ia16/ResetVectorVtf0.asm file:
```
GUIDed structure.  To traverse this you should first verify the
presence of the table footer guid
(96b582de-1fb2-45f7-baea-a366c55a082d) at 0xffffffd0.  If that
is found, the two bytes at …
```
> tdx: Add support for new method of TDVF descriptor discovery

- fuzz/Cargo.lock
- fuzz/Cargo.toml
- fuzz/fuzz_targets/linux_loader.rs
- fuzz/fuzz_targets/linux_loader_cmdline.rs
- vmm/src/vm.rs
> Add fuzzers for linux loader

- Cargo.lock
- Cargo.toml
- release-notes.md
- vm-migration/src/lib.rs
> build: Release v28.1 (bug fix release)

- Jenkinsfile
These machines are unreachable.
> build: Temporarily disable bare metal x86-64 workers

- .gitignore
> .build: Add .vscode to .gitignore

- vmm/src/memory_manager.rs
Including the guest RAM (or other mapped memory) in a coredump is not
useful.
See: #5014
> vmm: memory_manager: Mark guest memory mappings as non-dumpable

- Jenkinsfile
> build: Skip running Jenkins on .github/ only changes

- virtio-devices/src/block.rs
There is duplicated code when handlin queue events in handle_event()
refactor and introduce a new helper function.
Signed-off-by: Hao Xu <howeyxu@tencent.com>
> virtio-devices: block: Remove duplicated code in handle_event()

- Jenkinsfile
> build: Re-enable Jenkins bare metal workers

- Cargo.toml
- build.rs
- performance-metrics/Cargo.toml
- performance-metrics/build.rs
- performance-metrics/src/main.rs
- src/bin/ch-remote.rs
- src/main.rs
- vhost_user_block/Cargo.toml
- vhost_user_block/src/main.rs
- vhost_user_net/Cargo.toml
- vhost_user_net/src/main.rs
I found a few minor issues when going through Clap's usage in Cloud Hypervisor.
> Misc patches related to Clap

- virtio-devices/src/block.rs
During analysis of the asynchrous block I/O handling it was observed
that the majority of the time the completion events occur in the same
order as submissions. Further the maximum number of inflight requests
during the boot time is much lower than the size of the queue.
Through the use of a double ended queue (VecDequeue) with a reasonable
pre-allocation capacity we can have O(1) allocation free addition of
items to the list of inflight requests and mostly O(1) matching of
completed requests to submissions.
> virtio-devices: block: Replace use of HashMap for inflight requests

- arch/src/x86_64/mod.rs
e.g. on QEMU on KVM:
cloud-hypervisor: 17.079406ms: <vmm> INFO:arch/src/x86_64/mod.rs:565 -- Running under nested virtualisation. Hypervisor string: KVMKVMKVM
Or under Azure:
cloud-hypervisor: 3.881263ms: <vmm> INFO:arch/src/x86_64/mod.rs:565 -- Running under nested virtualisation. Hypervisor string: Microsoft Hv
Fixes: #5067
> arch: Print details of host hypervisor status & address space size

- hypervisor/src/lib.rs
- vmm/src/cpu.rs
Cleanups to the previous pr https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5077
> vmm: move kvm feature gate right before the if condition

- Cargo.lock
- Cargo.toml
- release-notes.md
- vm-migration/src/lib.rs
> build: Release v29.0

- Cargo.lock
- Cargo.toml
- docs/heap-profiling.md
- docs/profiling.md
- src/main.rs
- build: Add new profiling target
- docs: Update instructions to point to new profiling target
- build: Add optional dhat heap profiling
- docs: Add instructions for heap profiling
> Add heap profiling support

- docs/custom-image.md
- scripts/run_integration_tests_sgx.sh
- scripts/run_integration_tests_x86_64.sh
- scripts/sha1sums-x86_64
- tests/integration.rs
> tests: Add tpm2-tools to custom jammy image

- Cargo.lock
- Cargo.toml
- release-notes.md
- vm-migration/src/lib.rs
> build: Release v28.2 (bug fix release)

- devices/src/tpm.rs
At first glance there isn't much value in allowing the guest to continue using TPM after that.
> Failing to finish TPM requests should be considered fatal

- tpm/src/emulator.rs
- tpm/src/lib.rs
- tpm/src/socket.rs
I wrote a few more patches while learning the TPM code.
> TPM patches

- MAINTAINERS.md
I propose to add myself to the MAINTAINERS.md, and would like to get a consent from the community. 
> docs: Add @likebreath to MAINTAINERS.md

- Jenkinsfile
This reverts commit 496f932276b1de9591f30fe78f1a4354d741efb9.
The systems are back online and reachable.
> Revert "build: Temporarily disable bare metal x86-64 workers"

- docs/hotplug.md
> docs: hotplug: Fix link to booting with uefi on aarch64

- Cargo.lock
- Cargo.toml
- release-notes.md
- vm-migration/src/lib.rs
> build: Release v30.0

- README.md
> README: Add slack channel for community activity

- tests/integration.rs
> Replace use of "curl" with direct HTTP API calls

- docs/api.md
> docs: document that `vmcoredump` is conditionally compiled

- Cargo.lock
- Cargo.toml
- hypervisor/src/kvm/mod.rs
- src/main.rs
- tests/integration.rs
- virtio-devices/src/seccomp_filters.rs
- vmm/src/api/http_endpoint.rs
- vmm/src/config.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/vm.rs
- vmm/src/vm_config.rs
- #5350
- #5361
- #5360
- #5343
- #5373
> Stable backport fixes for v31.x

- Cargo.lock
- Cargo.toml
- hypervisor/src/kvm/mod.rs
- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_live_migration.sh
- src/bin/ch-remote.rs
- src/main.rs
- tests/integration.rs
- virtio-devices/src/seccomp_filters.rs
- virtio-devices/src/vhost_user/fs.rs
- vmm/src/api/http_endpoint.rs
- vmm/src/config.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/pci_segment.rs
- vmm/src/vm.rs
- vmm/src/vm_config.rs
- #5235
- #5322
- #5350
- #5361
- #5360
- #5343
- #5373
> Stable backport fixes for v30.x

- .github/workflows/build.yaml
- Cargo.lock
- Cargo.toml
- arch/src/x86_64/mod.rs
- arch/src/x86_64/tdx/mod.rs
- fuzz/Cargo.lock
- hypervisor/Cargo.toml
- hypervisor/src/cpu.rs
- hypervisor/src/kvm/mod.rs
- hypervisor/src/kvm/x86_64/mod.rs
- performance-metrics/src/performance_tests.rs
- src/main.rs
- tests/integration.rs
- vfio_user/src/lib.rs
- virtio-devices/src/seccomp_filters.rs
- virtio-devices/src/vhost_user/fs.rs
- vmm/src/api/http_endpoint.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/config.rs
- vmm/src/cpu.rs
- vmm/src/device_manager.rs
- vmm/src/lib.rs
- vmm/src/pci_segment.rs
- vmm/src/seccomp_filters.rs
- vmm/src/vm_config.rs
- #5179
- #5186
- #5211
- #5235
- #5350
- #5361
- #5360
- #5373
> Stable backport fixes for v28.x

- Cargo.lock
- Cargo.toml
- release-notes.md
- vm-migration/src/lib.rs
> build: Release v28.3 (bug fix release)

- net_gen/src/lib.rs
- qcow/src/qcow_raw_file.rs
- virtio-devices/src/lib.rs
> Fix beta clippy issues

- tests/integration.rs
- vmm/src/config.rs
- vmm/src/device_manager.rs
- vmm/src/pci_segment.rs
Bump the number of PCI segments supported.
See https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5403.
> Bump PCI segments limit

- scripts/run_integration_tests_vfio.sh
Details: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5190#issuecomment-1599357074
> tests: disable test_vfio test

- .github/workflows/hadolint.yaml
- resources/Dockerfile
- scripts/dev_cli.sh
> Add Hadolint Dockerfile Linter to CI

- vmm/src/cpu.rs
The pause of vcpu is async now, which makes the vm pause is not synchronised. As virtio device calls paused_sync wait() to make sure device_manager pause synchronously, if we make vcpu pause synchronously, the vm pause can be synchronously then. After vm.pause() returns the vm is really paused now.
This patch adds a AtomicBool variable to mark vcpu paused state, to make sure the pause of CpuManager is synchronised.
> vmm: Ensure vcpu pause is synchronised

- Jenkinsfile
The jenkins controller cannot reach them
See: #5670
> build: Temporarily disable bare metal Intel workers

- scripts/run_integration_tests_vfio.sh
- test_data/cloud-init/ubuntu/ci/user-data
> Fix test_vfio test by fixing cloud-hypervisor invocation in test_data

- Jenkinsfile
This reverts commit 96df501b7f1b5d9d2bc2b21c19ee63a97c1c36e7.
> Revert "build: Temporarily disable bare metal Intel workers"

- docs/intel_tdx.md
> docs: intel_tdx: add jobs argument to make

- Jenkinsfile
- tests/integration.rs
In this way, this test can be run against all PRs.
Fixes: #4324
> tests: Enable "test_vfio" on Azure VM instances

- Jenkinsfile
The bare metal machines are now not reachable from our Jenkins controller, and causing CI pipeline timeout for the past few days.
> build: Temporarily disable bare metal workers

- hypervisor/src/mshv/mod.rs
It's a requirement that a SEV-SNP enabled guest on MSHV must have isolation policy set before launching the guest.
> hypervisor: Set isolation policy for SNP guest

- Cargo.lock
- Cargo.toml
- README.md
- docs/api.md
- docs/debug-port.md
- docs/gdb.md
- docs/hotplug.md
- docs/iommu.md
- docs/live_migration.md
- docs/logging.md
- docs/memory.md
- docs/profiling.md
- docs/snapshot_restore.md
- docs/vhost-user-blk-testing.md
- fuzz/Cargo.lock
- performance-metrics/Cargo.toml
- performance-metrics/src/main.rs
- performance-metrics/src/performance_tests.rs
- src/bin/ch-remote.rs
- src/main.rs
- test_data/cloud-init/ubuntu/ci/user-data
- test_infra/src/lib.rs
- tests/integration.rs
- vhost_user_block/Cargo.toml
- vhost_user_block/src/lib.rs
- vhost_user_block/src/main.rs
- vhost_user_net/Cargo.toml
- vhost_user_net/src/main.rs
- vmm/Cargo.toml
- vmm/src/config.rs
Switching back to clap crate for command line parsing.
https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5550 provides background information about this work.
> Switch back to the clap crate

- src/main.rs
> main: Add the '--serial socket=' option help information

- tests/integration.rs
- vmm/src/config.rs
Performance of legacy serial is poor, so we want to use virtio console for better performance, but once we configure VM console as virito console, the boot stage kernel logs will be lost, including some critical exception message in boot stage.
Linux support assign console for early stage via "earlyprintk", with this feature we could assign legacy serial to early stage, and virito console to normal console (after early boot stage), then we could catch most VM console logs via virito console, also catch boot stage important logs via legacy serial.
This patch remove the double TTY restriction, so that we could use both serial and console with TTY mode.
> vmm: Allow simultaneously set serial and console as TTY mode

- test_infra/src/lib.rs
- tests/integration.rs
- tests: Print details when checks on event monitor failed
- test_infra: Print error and output if host commands failed
- test_infra, tests: Unify error message formatting 
- tests: Improve debuggability for "test_vfio"
> Improve debuggability for integration tests with more error message

- Jenkinsfile
- scripts/dev_cli.sh
- scripts/run_integration_tests_sgx.sh
- scripts/run_integration_tests_vfio.sh
- scripts/run_integration_tests_x86_64.sh
- scripts/test-util.sh
- scripts: Extract downloading hypervisor-fw to a function
- scripts: Authenticate to GitHub if token present
- build: Populate AUTH_DOWNLOAD_TOKEN environment variable
- scripts: Propagate AUTH_DOWNLOAD_TOKEN into container
Fixes: #5759
> Authenticated github download

- docs/amd_sev_snp.md
- docs/mshv.md
This patch adds brief overview and relation of mshv, igvm, and sev-snp features.
> docs: Add documentations for MSHV and related features

- .github/workflows/gitlint.yaml
- .gitlint
- scripts/gitlint/rules.py
Implement commit message check workflow using gitlint
Fixes: #5840
> build: add gitlint commit message linter

- tests/integration.rs
> tests: test_watchdog: use event monitor

- scripts/run_integration_tests_aarch64.sh
Random failures of downloading `cloud-hypervisor-static-aarch64` with `wget` were seen. 
The PR applies a workaround to retry the download for a few times.
Related to https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6006, but this is not a fix.
> Workaround random wget failures on AArch64

- hypervisor/src/mshv/mod.rs
- hypervisor/src/vm.rs
- vmm/src/igvm/igvm_loader.rs
After parsing is done on the IGVM file VMM needs to tell the Microsoft Hypervisor that import and complete so that
hypervisor can issue SNP_LAUNCH_FINISH command.
> Import the isolated pages and complete the isolation for SEV-SNP guest

- virtio-devices/src/vsock/unix/muxer.rs
The socket is nonblocking, so it's not guaranteed that it will be possible to read the whole connect command in a single iteration of the event loop.  To reproduce:
```sh
(echo -n 'CONNECT '; sleep 1; echo 1234; cat) | socat STDIO UNIX-CONNECT:vsock.sock
```
This would produce the error:
cloud-hypervisor: 5.509209s: <_vsock4> INFO:virtio-devices/src/vsock/unix/muxer.rs:446 -- vsock: error adding local-init connection: UnixRead(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" })
To fix this, if we only get a partial command, we need to save it for future iterations of the event loop, and only proceed once we've read a complete command.
> virtio-devices: fix reading vsock connect command

- arch/src/x86_64/mod.rs
- block/src/raw_async_aio.rs
- devices/src/pvpanic.rs
- resources/Dockerfile
- scripts/dev_cli.sh
- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_live_migration.sh
- scripts/run_integration_tests_x86_64.sh
- test_infra/src/lib.rs
- tests/integration.rs
- virtio-devices/src/vhost_user/vu_common_ctrl.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/lib.rs
- vmm/src/vm.rs
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5930
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5956
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5967
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6025
> Stable backport fixes for v36.x 

- arch/src/aarch64/fdt.rs
- devices/src/pvpanic.rs
- resources/Dockerfile
- scripts/common-aarch64.sh
- scripts/dev_cli.sh
- scripts/run_integration_tests_aarch64.sh
- scripts/run_integration_tests_live_migration.sh
- scripts/run_integration_tests_rate_limiter.sh
- scripts/run_integration_tests_sgx.sh
- scripts/run_integration_tests_vfio.sh
- scripts/run_integration_tests_windows_aarch64.sh
- scripts/run_integration_tests_windows_x86_64.sh
- scripts/run_integration_tests_x86_64.sh
- scripts/run_metrics.sh
- scripts/run_unit_tests.sh
- test_infra/src/lib.rs
- tests/integration.rs
- virtio-devices/src/vhost_user/vu_common_ctrl.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/lib.rs
- vmm/src/vm.rs
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5845
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5893
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5956
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5967
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6025
> Stable backport fixes for v35.x

- arch/src/x86_64/mod.rs
When configuring amd cpu topology, the svm feature flag on cpuid leaf 0x8000_0001.ecx is overwritten. Instead, update the amd cpu topology logic to use the flag values that originated in KVM_GET_SUPPORTED_CPUID ioctl.
This fixes a bug in which nested virtualization does not work on amd guests when cpu topology is specified.
> arch: x86_64: enable nested virtualization on amd if supported

- vmm/src/config.rs
> vmm: remove redundant tests

- arch/src/x86_64/mod.rs
When the HTT flag CPUID.1.EDX[HTT] is 0, it indicates that there is only a single logical processor in the package. When HTT is 1, it indicates that CPUID.1.EBX[23:16] contains the number of logical processors in the package.
When this information is not included in CPUID leaf 0x1, some cpu topology enumeration software such as hwloc are known to crash.
Note: 
I have experienced crashes on the version of lstopo available on Ubuntu 22.04 on some (but interestingly not all) machines I've tested on. Newer version of lstopo [work around this bug](https://github.com/open-mpi/hwloc/commit/33b555b5a1c8339daeb4215bad57430b57a6b33f), but its still good to be correct for maximum compatability.
TIL that the HTT flag has [absolutely nothing](https://www.os2museum.com/wp/htt-means-hyper-threading-right …
> arch: x86_64: enable HTT flag

- vmm/src/igvm/loader.rs
When we import a page, we have a page with
some data or empty, empty does not mean there is no data, it rather means it's full of zeros. We can skip writing the data as guest memory of the page is already zeroed.
A page could be partially filled and the rest of the content is zero. Our IGVM generation tool only fills data here if there is some data without zeros. Rest of them are padded. We only write data without padding and compare whether we complete  writing the buffer content. Still it's a full page and update the variable with length of full page
> vmm: check correct buffer size during import

- vmm/src/memory_manager.rs
On guests with large amounts of memory, using the `prefault` option can lead to a very long boot time. This PR implements the strategy taken by QEMU to prefault memory in parallel using multiple threads which was first introduced by this [RFC](https://patchwork.ozlabs.org/project/qemu-devel/patch/1483601042-6435-1-git-send-email-jitendra.kolhe@hpe.com/), decreasing time the allocate memory for large guest by an order of magnitude or more.
The implementation generally follows that of [`qemu_prealloc_mem`](https://github.com/qemu/qemu/blob/bd2e12310b18b51aefbf834e6d54989fd175976f/util/oslib-posix.c#L500), simplifying where possible. The essence is that, rather than prefaulting memory by calling `mmap` with the `MAP_POPULATE` flag, this implementation prefaults memory by calling `madvise` …
> vmm: prefault memory in parallel to optimize boot time

- pci/src/vfio.rs
For all VFIO devices, map all non-emulated MMIO regions to the vfio container to allow PCIe P2P between all VFIO devices on the virtual machine. This is required for a wide variety of multi-GPU workloads involving GPUDirect P2P (DMA between two GPUs), GPUDirect RDMA (DMA between a GPU and an IB device).
> vfio: VFIO_IOMMU_MAP_DMA mmio regions

- hypervisor/src/lib.rs
- hypervisor/src/mshv/mod.rs
GPA_MAP_ADJUSTABLE suggests hypervisor to adjust GPA permissions as required.
> hypervisor: mshv: Add new memory region flag

- vmm/src/vm.rs
Since the ACPI tables are provided via IGVM file in case of SEV-SNP guest. So, we should not generate it as part of CloudHypervisor process.
> vmm: Don't generate ACPI tables in case of SEV-SNP guest

- .github/workflows/integration-x86-64.yaml
> build: Add GitHub action for unit/integration testing

- .github/workflows/integration-sgx.yaml
Currently it applies on pull request, once testing is done, I will add main branch requirements.
> Add GitHub action for SGX integration tests

- .github/workflows/integration-rate-limiter.yaml
Currently it applies on pull request, once testing is done, I will update it to only main branch.
> Add GitHub action for Rate Limiter integration tests

- .github/workflows/integration-rate-limiter.yaml
- .github/workflows/integration-sgx.yaml
- .github/workflows/integration-vfio.yaml
- build: Use authentication token to avoid GitHub rate limit
> Use authenticated download for bare metal workers

- docs/api.md
- fuzz/fuzz_targets/http_api.rs
- hypervisor/src/cpu.rs
- hypervisor/src/kvm/mod.rs
- src/bin/ch-remote.rs
- tests/integration.rs
- vmm/src/api/http/http_endpoint.rs
- vmm/src/api/http/mod.rs
- vmm/src/api/mod.rs
- vmm/src/api/openapi/cloud-hypervisor.yaml
- vmm/src/cpu.rs
- vmm/src/lib.rs
- vmm/src/seccomp_filters.rs
- vmm/src/vm.rs
It's useful to inject NMI to guest for analysis sometimes, let's support that.
#5909
> Add support for inject NMI to guest

- hypervisor/src/mshv/mod.rs
Microsoft Hypervisor raises this request to change the guest page visibility in case of SEV-SNP guest.
> hypervisor: mshv: Add support to handle GPA Attribute Intercept

- .github/workflows/build.yaml
- .github/workflows/fuzz-build.yaml
actions-rs/toolchain is unmaintained, replace it with dtolnay/rust-toolchain
See: #5929
> build: replace actions-rs/toolchain with dtolnay/rust-toolchain

- hypervisor/src/mshv/mod.rs
Model Specific Registers (MSRs) are usually available on x86 architecture. So, let's reduce the visibility of MSRs to just x86 architecture.
> hypervisor: mshv: Reduce msrs visibility to x86_64

- .github/workflows/integration-metrics.yaml
- .github/workflows/integration-rate-limiter.yaml
This reverts commit https://github.com/cloud-hypervisor/cloud-hypervisor/commit/00684e6d1905b24eb33d35b5bc323bd46b3701e2.
> build: Enable metrics and rate-limiter worker

- vmm/src/interrupt.rs
It may casue kernel out-of-bounds panic when set_gsi_routing before irq routing update using enable(). Though kernel has been fixed this in commit a80ced6e(KVM: SVM: fix panic on out-of-bounds guest IRQ) which has not been include in 5.15, it's better to avoid this in cloud-hypervisor.
It is worth noting that when unmask a gsi disable() should be called before set_gsi_routing(), as entry.masked is set to be true so we should call disable() before set_gsi_routing() update the kvm->irq_routing.
fix: #6353
> vmm: interrupt: fix kernel panic on out-of-bounds guest IRQ

- Cargo.lock
- hypervisor/src/lib.rs
- hypervisor/src/mshv/mod.rs
- hypervisor/src/mshv/x86_64/mod.rs
- vmm/src/vm.rs
Implement get/set_clock for MSHV and make the clock info independent of hypervisors.
> Save and restore clock info for MSHV

- hypervisor/src/kvm/aarch64/mod.rs
- hypervisor/src/kvm/x86_64/mod.rs
I was enumerating the required capabilities but found the lists incomplete.
No functional change intended with this PR.
> Update KVM's required capability lists

- tests/integration.rs
Currently, the watchdog configuration in systemd is reloaded by reboot. We can cancel this reboot operation by restarting the systemd daemon process.
> tests: restart systemd daemon to reload systemd configuration

- src/main.rs
Whenever the file descriptor table is full, Linux expands it by doubling it's size.
The filesystem code that does this uses RCU synchronization to ensure all pre-existing RCU read-side critical sections have completed. The latency induced by this synchronization is a big part of the total time required to restore a snapshot.
The kernel has an optimization in the expand table code path where it doesn't call synchronize_rcu() if there is only one thread in the process.
To address this issue we attempt to expand the descriptor table at the application start, when it has only one thread. The latency is between 20 and 50 ms from the tests I've done. You can easily observe the issue by using `strace -TT`. The time spent in syscalls that return file handles with numbers 64, 128, 256, etc. will …
> Fix high latency generated by file handle creation

- devices/src/ioapic.rs
- vmm/src/serial_manager.rs
Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6485.
> Fix a bug in serial manager that closes a file descriptor more than once

- block/src/qcow/mod.rs
Impose a limit on the maximum nesting of file formats that can open more files. For example, a qcow2 file can have a backing file, which could be another qcow2 file with a backing file (or even the same file as the original), potentially causing unbounded recursion.
This commit is based on crosvm implementation:
https://chromium.googlesource.com/crosvm/crosvm/+/eb1640e301d66c06e0e0a07886946830f3f2f4fe
Fixes: #6472
> block: qcow: limit max nesting depth for backing file

- Cargo.lock
Bump some dependencies.
Update libz-sys from 1.1.16 -> 1.1.18
Update openssl-src from 3.2.1 -> 3.3.1
> Bump libz and openssl dependencies

- .github/workflows/integration-sgx.yaml
- .github/workflows/integration-vfio.yaml
This reverts commit 7d84654a79a4a4ed86e911b35a9ed78ec1468ea0.
> build: Enable vfio and sgx worker

- docs/performance_metrics.md
Add a performance metrics list and the definition of output format.
> docs: improve performance metrics documentation

- hypervisor/src/mshv/mod.rs
There were some scenarios where we are not clearing SW_EXIT_INFO1 to indicate that there were no error while handling the GHCB exit. Recently, new Linux guests got stricter with checking the value of SW_EXIT_INFO1 after coming back from VMGEXIT and started crashing. Fix this behavior by clearing out SW_EXIT_INFO1 in case of no error.
> hypervisor: mshv: Clear SW_EXIT_INFO1 in case of no error

- virtio-devices/src/vsock/unix/muxer.rs
Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6621
> Handle short read in vsock muxer

- .github/workflows/build.yaml
- .github/workflows/quality.yaml
> Add build and clippy tests for pvmemcontrol

- hypervisor/src/kvm/aarch64/gic/dist_regs.rs
- hypervisor/src/kvm/aarch64/gic/icc_regs.rs
- hypervisor/src/kvm/aarch64/gic/mod.rs
- hypervisor/src/kvm/aarch64/gic/redist_regs.rs
`DeviceFd::get_device_attr` should be marked as unsafe, because it allows writing to an arbitrary address.  I have opened a [kvm-ioctls PR][1] to fix this.  The hypervisor crate was using the function unsafely by passing it addresses of immutable variables.  I noticed this because an [optimisation change][2] in Rust 1.80.0 caused the `kvm::aarch64::gic::tests::test_get_set_icc_regs` test to start failing when built in release mode.
To fix this, I've broken up the _access functions into _set and _get variants, with the _get variant using a pointer to a mutable variable. This has the side effect of making these functions a bit nicer to use, because the caller now has no need to use references at all, for either getting or setting.
[1]: https://github.com/rust-vmm/kvm-ioctls/pull/273
[2]: …
> hypervisor: kvm: aarch64: fix get_device_attr() UB

- net_util/src/queue_pair.rs
Currently when converting desc chain to iovecs, it uses `Vec::new()`. To save allocation, this PR proposed to using a long lifetime buffer to save the result.
A simulated benchmark about whether use persistent buffer or smallvec: https://gist.github.com/ihciah/dcfaf13393bfada1ff8f372b4fa16e3f
> virtio-devices: net: reduce vec allocations for iovec conversion

- virtio-devices/src/block.rs
Currently, when finishing processing disk IO completion event, virtio-blk calls `process_queue_submit_and_signal` if rate limit not reached. That's because to support notification suppression, the backend needs to work in a loop and process all available event in the queue until nothing remained.
However, for case that `rate_limit_reached == true`, the backend stop handling without sending frontend a signal. Though when rate limit refills, the backend will be able to send the signal when handling `RATE_LIMITER_EVENT`, the signal is actually delayed for some time.
This fix will make the backend able to send the signal immediately no matter rate limit is hit or not.
> virtio-devices: virtio-blk always tries signal used queue when receiving completion event

- virtio-devices/src/seccomp_filters.rs
With cd0cdac ("virtio-devices: Fix seccomp rules for SevSnp guest"), the
sys_ioctl rule that was applied in virtio_thread_common, would override
previously specified sys_ioctl rules for individual thread type. This
causes the SevSnp guest to crash with seccomp violation.
Fixes: cd0cdac ("virtio-devices: Fix seccomp rules for SevSnp guest")
Signed-off-by: Purna Pavan Chandra <paekkaladevi@microsoft.com>
> virtio-devices: Fix seccomp rules for SevSnp

- .github/workflows/quality.yaml
Refactored quality check GitHub action.
A pavement to enable RISC-V gnu target CI quality check crates-wise at the time being.
> github: Refactor quality check GitHub action

- .github/workflows/integration-arm64.yaml
- hypervisor/src/kvm/mod.rs
- scripts/test-util.sh
- vmm/src/cpu.rs
Using new worker donated by @ubicloud.
- **vmm: cpu: Fix aarch64 unit test**
- **scripts: Only download kernel binaries if changed**
- **build: Enable ARM64 worker**
> Enable ARM64 CI

- vmm/src/device_manager.rs
AddressManager::move_bar() acquires the device_tree mutex. The function is called from PciConfigIo::config_space_write()/PciConfigMmio::config_space_write() while the pci_bus mutex is acquired.
The functions DeviceManager::pci_resources()/eject_device() acquire these mutexes in reverse order, which leads to a deadlock.
Fixes: #6775
> vmm: drop device_tree mutex before acquiring pci_bus mutex

- resources/Dockerfile
- scripts/dev_cli.sh
Jammy packages swtpm, install it and drop the steps for building it.
> Dockerfile: install swtpm from Jammy

- .github/workflows/docker-image.yaml
Fixes: 34dc97f74fc2a39e502f593c13e0e2bbf7e0724d
> build: Bump version in docker image upload

- docs/coverage.md
- scripts/run_coverage.sh
docs: improve code coverage document
Fixes: #6507 
This patch improves the code coverage use case for integration
tests and unit tests.
> docs: improve code coverage document

- docs/custom-image.md
Hey yall,
super tiny PR just fixing one link in the documentation.
Cheers,
Jonas
> docs: Fix scripts link

- block/src/raw_async.rs
Two small patches I wrote when I investigated block performance.
> Adjust io_uring code

- block/src/lib.rs
- virtio-devices/src/block.rs
- vmm/src/config.rs
Significant improvements in block device performance across the board.
With this new feature:
```
Test 'block_read_MiBps' running .. (control: test_timeout = 10s, test_iterations = 5, num_queues = 1, queue_size = 128, fio_ops = read, bandwidth = true, overrides: )
Test 'block_read_MiBps' .. ok: mean = 1041.1836760485135, std_dev = 55.7625072234085
Test 'block_write_MiBps' running .. (control: test_timeout = 10s, test_iterations = 5, num_queues = 1, queue_size = 128, fio_ops = write, bandwidth = true, overrides: )
Test 'block_write_MiBps' .. ok: mean = 630.6574363756009, std_dev = 58.07112046007685
Test 'block_random_read_MiBps' running .. (control: test_timeout = 10s, test_iterations = 5, num_queues = 1, queue_size = 128, fio_ops = randread, bandwidth = true, overrides: )
Test …
```
> Introduce VIRTIO_BLK_F_SEG_MAX

- devices/src/pvmemcontrol.rs
- devices/src/pvpanic.rs
- pci/src/bus.rs
- pci/src/device.rs
- pci/src/vfio.rs
- pci/src/vfio_user.rs
- virtio-devices/src/transport/mod.rs
- virtio-devices/src/transport/pci_device.rs
- vmm/src/device_manager.rs
A set of patches when I looked at refining SEV-SNP code long ago.
> Miscellaneous patches

- hypervisor/src/cpu.rs
- hypervisor/src/kvm/aarch64/gic/redist_regs.rs
- hypervisor/src/kvm/aarch64/mod.rs
- hypervisor/src/kvm/mod.rs
- hypervisor/src/kvm/riscv64/mod.rs
- hypervisor/src/lib.rs
- hypervisor/src/mshv/mod.rs
- hypervisor/src/vm.rs
- vmm/src/cpu.rs
This is a continuation of the previous work #6629
> Implement hypervisor agnostic variants for various ARM64 data structures

- .github/workflows/docker-image.yaml
- resources/Dockerfile
- scripts/dev_cli.sh
Attempt to fix `SPDK` caused VFIO issue when image is built from GHA runner then pulled to our ARM host.
> build: Fix spdk in linux/arm64 image

- hypervisor/src/mshv/x86_64/emulator.rs
Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6961.
> hypervisor: mshv: handle cross-page access in emulator

- Cargo.toml
- event_monitor/Cargo.toml
- hypervisor/Cargo.toml
- net_util/Cargo.toml
- performance-metrics/Cargo.toml
- test_infra/Cargo.toml
- tracer/Cargo.toml
- virtio-devices/Cargo.toml
- vm-migration/Cargo.toml
- vmm/Cargo.toml
`serde_json` crate is referenced by multiple components, centralize it to workspace to better manage this crate.
> build: Centralize serde_json crate to workspace

- hypervisor/src/mshv/mod.rs
Enable getting and setting registers for ARM64 guests on MSHV
> hypervisor: Add support for get/set regs for ARM guest on MSHV

- docs/riscv.md
Since there are not a wide availability of RISC-V boards 
available at the moment, it is easiest to develop 
with a QEMU virtual machine. I had a hard time setting 
one up, but with the assistance of Ruoqing, I was able to 
get one running. These are the steps I took to do so.
Signed-off-by: abm-77 <andrewmiller77@protonmail.com>
> docs: Update riscv docs for developing in QEMU VM

- Cargo.lock
- Cargo.toml
- api_client/Cargo.toml
- arch/Cargo.toml
- block/Cargo.toml
- devices/Cargo.toml
- hypervisor/Cargo.toml
- net_util/Cargo.toml
- option_parser/Cargo.toml
- pci/Cargo.toml
- performance-metrics/Cargo.toml
- rate_limiter/Cargo.toml
- test_infra/Cargo.toml
- tpm/Cargo.toml
- vhost_user_block/Cargo.toml
- vhost_user_net/Cargo.toml
- virtio-devices/Cargo.toml
- vm-device/Cargo.toml
- vm-migration/Cargo.toml
- vmm/Cargo.toml
`thiserror` is used almost everywhere, so lets make it a workspace dependency.
> misc: streamline thiserror cargo dep

- vmm/src/cpu.rs
This is a prerequisite for #7066. It is a little cumbersome to properly test for the underlying error, but it is manageable.
> tests: fix vCPU test relying on specific Display formatting

- vmm/src/config.rs
Follow-up to #7089 and related changes. Some manual `Display` implementations were missed previously - this completes the transition and ensures consistency across all `Error` types.
> vmm: streamline Display impl of Error types

- arch/src/x86_64/mpspec.rs
- arch/src/x86_64/mptable.rs
- block/src/lib.rs
- docs/intel_sgx.md
See individual commit messages for details.  No functional change intended.
> Simple fixes

- net_util/src/open_tap.rs
- net_util/src/tap.rs
Small cleanup to improve code readability.
For example, refactoring a huge loop body into
a function call.
> net_util: cleanup

- Cargo.lock
- arch/Cargo.toml
- performance-metrics/Cargo.toml
- test_infra/Cargo.toml
- tpm/Cargo.toml
- vhost_user_block/Cargo.toml
- virtio-devices/Cargo.toml
- vm-device/Cargo.toml
- vm-virtio/Cargo.toml
- vmm/Cargo.toml
build: clean up unused dependencies
> build: clean up unused dependencies

- tests/integration.rs
Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/7209
The analysis is there.
> Fix VHDX dynamic expansion test

- docs/windows.md
The current "Windows Support" documentation only mentions Windows server support. Since only minimal adjustments are needed for Windows 11 support, these were added where applicable.
> docs: Add Windows 11 support information

- vmm/src/vm.rs
In case of CVM guest rsdp is set to none. Unwrapping it make the vmm crashed. Don't call configure system if the rsdb address is none.
> vmm: don't configure system if rsdp is not available

- .lychee.toml
- src/main.rs
ci: Improve link checker conditions
Link checker excludes checks on local links and links with variables.
> ci: Improve link checker conditions

- option_parser/src/lib.rs
The option parser did not allow quoting any special characters, which means that some strings could not be passed via command-line options. Fix this by allowing double quotes to quote all the special characters, such as '@', ',', '[', and ']'.  '"' can be escaped by doubling it.  The implementation uses some tricks to stay modular.
> misc: option_parser: allow quoting special characters

- vmm/src/vm.rs
Harmonize bootpath, remove code duplications.
Follow-up of https://github.com/cloud-hypervisor/cloud-hypervisor/pull/7166#issuecomment-3178495354.
On aarch64 and RISC-V, calling load_firmware() through load_kernel()
provides no benefit and only duplicates checks already performed in
load_payload(). load_payload() now directly invokes load_firmware() or
load_kernel(), removing unnecessary indirection and redundancy.
> vmm: harmonize bootpath

- net_util/src/tap.rs
- vmm/src/clone3.rs
This is my attempt to address the concerns of @likebreath in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/7256#discussion_r2298831641 to hopefully unblock #7256.
- add missing Safety doc sections
- ~~remove unused bindings~~
- Please review this commit by commit and read the commit message
> style: fix up safety doc sections

- hypervisor/src/mshv/mod.rs
Handle MSHV reset intercepts on arm64 such that guests can gracefully shutdown/reboot instead of panicking due to unhandled intercept.
> hypervisor: mshv: handle reset intercepts for arm64

- src/main.rs
- test_infra/src/lib.rs
- vm-migration/src/protocol.rs
Fixed with 'cargo clippy --fix' mostly.
> misc: Fix beta clippy issues

- vmm/src/cpu.rs
Rust's aliasing rules do not permit mutating a `usize` through a shared reference. Unsafe blocks and FFI are no exception.
This PR fixes such a violation detected in the AMX support checks by passing a raw mutable pointer instead of a shared reference in the syscall.
The way the current code is written is effectively equivalent to transmuting a shared reference `&` to an exclusive reference `&mut`. The [Rustonomicon](https://doc.rust-lang.org/nomicon/transmutes.html) has the following to say about that:
> Transmuting an & to &mut is Undefined Behavior. While certain usages may appear safe, note that the Rust optimizer is free to assume that a shared reference won't change through its lifetime and thus such transmutation will run afoul of those assumptions. So:
- Transmuting an & to &mut …
> vmm: Fix UB in AMX support checks
