Cargo.lock, arch/Cargo.toml, pci/Cargo.toml, vmm/Cargo.toml
=> cloud-hypervisor: Switch to crates.io kvm-ioctls

src/main.rs
Recent refactoring of the flags parsing broke the --net behavior where
the network tap interface should be created by the VMM if the user does
not provide any argument to this option.
=> main: Fix --net behavior

src/main.rs
Reverts intel/cloud-hypervisor#20
I am positive that this change introduces no change in logic but makes the code less readable. The second branch of the else is an unreachable piece of code.
See my minimal example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4e88d273ee891a55f209f8e0f33818d5
Signed-off-by: Logan Saso <logansaso@gmail.com>
=> Revert "main: Fix --net behavior"

Cargo.lock, vmm/Cargo.toml, vmm/src/lib.rs, vmm/src/vm.rs
Use a catchall case for all reasons that we do not handle, and
move the vCPU run switch into its own function.
=> vmm: Simplify the vcpu run switch

vm-allocator/src/address.rs, vm-allocator/src/lib.rs, vm-allocator/src/system.rs
We can only free address ranges for now, and only when they match exactly one that was allocated.
In other words, we can't partially free and address range.
=> Add a resource freeing API for vm-allocator

src/main.rs, vmm/src/config.rs, vmm/src/lib.rs, vmm/src/vm.rs
The command line parsing of the user input was not properly
abstracted from the vmm specific code. In the case of --net,
the parsing was done when the device manager was adding devices.
In order to fix this confusion, this patch introduces a new
module "config" dedicated to the translation of a VmParams
structure into a VmCfg structure. The former is built based
on the input provided by the user, while the latter is the
result of the parsing of every options.
VmCfg is meant to be consumed by the vmm specific code, and
it is also a fully public structure so that it can directly
be built from a testing environment.
Fixes #31
=> config: Reorganize command line parsing

vm-allocator/src/system.rs
The IO memory alignment should be set as 4 instead of 0x400 which is copied
from crosvm. Take 0xcf8, 0xcfc for pci bus as examples.
Signed-off-by: Jing Liu <jing2.liu@linux.intel.com>
=> vmm: Repair the port IO memory alignment

Cargo.lock, Cargo.toml, Jenkinsfile, scripts/run_integration_tests.sh, src/main.rs, test_data/cloud-init/openstack/latest/meta_data.json, test_data/cloud-init/openstack/latest/user_data, vmm/src/vm.rs
All the fiddly cloud-init stuff has been worked out now and it is possible to get a very basic integration test.
Short term before merging:
=> Add basic integration testing

Cargo.lock, vm-virtio/src/transport/pci_device.rs, vmm/src/vm.rs
When the KVM capability KVM_CAP_SIGNAL_MSI is not present, the VMM
falls back from MSI-X onto pin based interrupts. Unfortunately, this
was not working as expected because the VirtioPciDevice object was
always creating an MSI-X capability structure in the PCI configuration
space. This was causing the guest drivers to expect MSI-X interrupts
instead of the pin based generated ones.
This patch takes care of avoiding the creation of a dedicated MSI-X
capability structure when MSI is not supported by KVM.
=> irq: Fix pin based interrupt for virtio-pci

Cargo.lock, vmm/src/vm.rs
As mentioned in the KVM documentation, TSC_DEADLINE_TIMER feature
needs some special checks to validate that it is supported as the
cpuid will always report it as disabled.
We need to use the KVM_CHECK_EXTENSION ioctl to request the value
of KVM_CAP_TSC_DEADLINE_TIMER. In case it is supported through
the local APIC emulation provided by the CREATE_IRQCHIP in KVM,
we have to set manually this feature by patching the cpuid.
Here quoted from the KVM documentation:
```
The TSC deadline timer feature (CPUID leaf 1, ecx[24]) is always
returned as false, since the feature depends on KVM_CREATE_IRQCHIP
for local APIC support. Instead it is reported via
ioctl(KVM_CHECK_EXTENSION, KVM_CAP_TSC_DEADLINE_TIMER)
if that returns true and you use KVM_CREATE_IRQCHIP, or if you
emulate the feature in …
```
=> vmm: Enabling TSC_DEADLINE_TIMER allows for PIT emulation removal

src/main.rs, vmm/src/vm.rs
KVM exposes CPUID 0BH when host supports that, but the APIC ID that KVM
provides is the host APIC ID so we need replace that with ours.
Without this Linux guest reports something like:
[Firmware Bug]: CPU1: APIC id mismatch. Firmware: 1 APIC: 21
Fixes #42
Signed-off-by: Chao Peng <chao.p.peng@linux.intel.com>
=> vmm: Set the APIC ID in the extended topology

README.md
The previous one was mistakenly set to expire after 30 days.
Fixes: #59
=> README: Use a permanent Slack invite link

Jenkinsfile
We need to export the variable DEBIAN_FRONTEND=noninteractive from the
Jenkinsfile if we want to make sure the VM update won't get stuck into
an interactive window.
=> CI: Fix the Ubuntu VM update stuck on an interactive window

Cargo.lock, devices/Cargo.toml, devices/src/ioapic.rs, devices/src/legacy/serial.rs, devices/src/lib.rs, src/main.rs, vmm/src/vm.rs
This pull request implements a userspace IOAPIC and plumbs
it into the cloud-hypervisor VMM to allow getting rid of the in
kernel emulation provided by `KVM_CREATE_IRQCHIP`.
It allows for what is called a "split" irqchip, which means that
only the local APIC is emulated in kernel.
Fixes #13
=> Add support for userspace IOAPIC

devices/src/bus.rs, pci/src/device.rs, pci/src/root.rs, vm-virtio/src/transport/pci_device.rs, vmm/src/vm.rs
BusDevice includes two methods which are only for PCI devices, which should
be as members of PciDevice trait for a better clean high level APIs.
Signed-off-by: Jing Liu <jing2.liu@linux.intel.com>
=> device: Improvement for BusDevice trait and PciDevice trait

Jenkinsfile, scripts/run_integration_tests.sh, src/main.rs, vm-virtio/src/lib.rs, vm-virtio/src/pmem.rs, vmm/src/config.rs, vmm/src/vm.rs
This pull request introduces the support for virtio-pmem, which allows the VMM to expose some persistent memory to the guest, that can be backed by any type of file.
Fixes #68
=> Add virtio-pmem support

vmm/src/vm.rs
Remove println! left over from virtio-fs development.
=> vmm: Remove println! from debugging

pci/src/configuration.rs, pci/src/lib.rs, vm-virtio/src/lib.rs, vm-virtio/src/transport/pci_device.rs
Use the virtio device type to generate the righ class and subclass.
Fixes: #83
=> Fix the network and storage PCI class and sub-class

devices/src/bus.rs, devices/src/ioapic.rs, devices/src/legacy/i8042.rs, devices/src/legacy/serial.rs, pci/src/device.rs, pci/src/root.rs, vm-virtio/src/transport/pci_device.rs
We extend the `Bus` and `PciDevice` traits so that their IO callbacks carry the base IO region address that the callback need to handle.
Fixes: #87
=> Add support for multiple IO regions devices

pci/src/bus.rs, pci/src/device.rs, pci/src/lib.rs, vmm/src/vm.rs
@sameo @chao-p @rbradford @sboeuf 
This refines PCI emulated hierarchy to make VMExit resolving and handling clean and easy.
=> Refine pci topology

src/main.rs, vmm/src/config.rs, vmm/src/vm.rs
For every parameter dealing with a size as option, such as memory or
virtio-pmem, the CLI can now parse sizes with the suffixes K, M or G.
Fixes #70
=> cli: Accept K,M,G suffixes for size parameters

src/main.rs, test_data/cloud-init/openstack/latest/user_data, vmm/src/config.rs, vmm/src/vm.rs
Until now, the VMM was only accepting a single instance of virtio-net
device. This commit extends the virtio-net support by allowing several
devices to be created for a single VM.
Fixes #71
=> vmm: Add support for multiple virtio-net devices

src/main.rs, vmm/src/config.rs, vmm/src/vm.rs
Now that cloud-hypervisor VMM supports virtio-pmem, it can directly
boot a VM from an image exposed as a persistent memory block device.
That's why there is no need to force the --disk option as being
mandatory.
Fixes #90
=> vmm: Flag --disk should be optional

pci/src/bus.rs, src/main.rs
The Bridge header type is really meant to be for PCI-to-PCI bridges.
Fixes: #85
=> pci: Use device PCI header type for our root bridge

scripts/run_unit_tests.sh
In some situations it is possible for the setting of the capabilities to
fail due to the variable naming of the build artifacts resulting in the
first parameter to setcap being rejected and thus the whole command
failing.
Use xargs -n 1 to ensure that every potential target independently has
its caps set.
Further it was observed that in some situations the binary produced by
cargo test --all --no-run would not be used and instead a new binary
would be produced when the test was run using the second method. This
again would result in test failures as that binary did not have the
desired capabilities set. Therefore build the test binaries with the
same methodology used to run them.
=> build: Ensure caps needed for unit test are set

pci/src/bus.rs, pci/src/configuration.rs, pci/src/device.rs, pci/src/lib.rs, pci/src/msi.rs, pci/src/msix.rs, vm-virtio/src/transport/pci_device.rs, vmm/src/vm.rs
In order to build our initial VFIO support (see #60), we had to fix and improve the PCI crate:
- Improve the MSI-X support to use it directly from the VFIO code.
- Add MSI support to the PCI crate
- Support IO (PIO based) BARs
- Fix the PCI configuration write emulation
=> PCI fixes and improvements

arch/src/aarch64/mod.rs, arch/src/lib.rs, arch/src/x86_64/mod.rs, vm-allocator/src/address.rs, vm-allocator/src/gsi.rs, vm-allocator/src/lib.rs, vm-allocator/src/system.rs, vm-virtio/src/transport/pci_device.rs, vmm/src/vm.rs
In the context of the VFIO initial support PR (#60), we need to fix and improve the `vm-allocator` crate in several ways:
- Allow for allocation time alignment requirements: Not all address range allocation will have the same alignment requirements, so the vm-allocator API need to take that into account.
- Support the 32-bit hole: We want to vm-allocator crate to handle the 32-bit hole as a distinct sub MMIO range, as some allocations (e.g. IOAPIC range, 32-bit PCI BARs) must take place there.
- Extend the IRQ allocation API to support GSI and take IOAPIC IRQ ranges into account.
- A few fixes that surfaced when adding the 32-bit hole as a MMIO sub-region
=> vm-allocator fixes and improvements

README.md
We use the virtio console device now.
Fixes: #116
=> README: Fix kernel command line console argument

scripts/run_integration_tests.sh, src/main.rs
This should reduce the integration testing time considerably. When a
custom kernel is no longer required we can pull kernel from tarball
again.
Fixes: #100
=> tests: Use custom kernel for all tests

vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/device.rs, vm-virtio/src/fs.rs, vm-virtio/src/net.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/transport/pci_common_config.rs, vm-virtio/src/transport/pci_device.rs
As per the VIRTIO specification, every virtio device configuration can
be updated while the guest is running. The guest needs to be notified
when this happens, and it can be done in two different ways, depending
on the type of interrupt being used for those devices.
In case the device uses INTx, the allocated IRQ pin is shared between
queues and configuration updates. The way for the guest to differentiate
between an interrupt meant for a virtqueue or meant for a configuration
update is tied to the value of the ISR status field. This field is a
simple 32 bits bitmask where only bit 0 and 1 can be changed, the rest
is reserved.
In case the device uses MSI/MSI-X, the driver should allocate a
dedicated vector for configuration updates. This case is much simpler as
it only requires the device …
=> vm-virtio: Add support for notifying about virtio config update

pci/src/bus.rs, pci/src/configuration.rs, vfio/src/vfio_pci.rs
This PR includes two fixes for the VFIO implementation. First, it masks the multi-function bit from the device PCI configuration space to prevent conflicts, and then it adds support for the expansion ROM BAR.
=> vfio: Mask multi-functions devices and add support for expansion ROM BAR

arch/src/x86_64/regs.rs
In the context of VFIO, we use Vt-d, which means we rely on an IOMMU. Depending on the IOMMU capability, and in particular if it is not able to perform SC (Snooping Control), the memory will not be tagged as WB by KVM, but instead the vCPU will rely on its MTRR/PAT MSRs to find the appropriate way of interact with specific memory regions.
Because when Vt-d is not involved KVM sets the memory as WB (write-back) the VMM should set the memory default as WB. That's why this patch sets the MSR MTRRdefType with the default memory type being WB.
One thing that it is worth noting is that we might have to specifically create some UC (uncacheable) regions if we see some issues with the ranges corresponding to the MMIO ranges that should trap.
=> arch: x86_64: Set MTRR default memory type as WB

vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/fs.rs, vm-virtio/src/net.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vmm/src/vm.rs
The existing code taking care of the epoll loop was too restrictive as                                                                                                                                                                                                
it was propagating the error returned from the epoll_wait() syscall, no                                                                                                                                                                                               
matter what was the error. This causes the epoll loop to be broken,                                                                                                                                                                                                   
leading to …
=> Don't break from epoll loop on EINTR

pci/src/msix.rs, vfio/src/vfio_pci.rs
This pull request fixes errors in the VFIO and associated MSI-X code that were not discovered until now. The reason is that all devices tested so far had their MSI-X table placed on a BAR at the offset 0x0. As soon as we started testing with devices where the MSI-X table was placed at an offset different from 0x0, we could identify those implementation flaws.
=> vfio: Fix MSI-X erroneous implementation

Cargo.lock, Cargo.toml, arch/Cargo.toml, devices/Cargo.toml, net_util/Cargo.toml, pci/Cargo.toml, qcow/Cargo.toml, vfio/Cargo.toml, vhost_rs/Cargo.toml, vm-allocator/Cargo.toml, vm-virtio/Cargo.toml, vmm/Cargo.toml
Update all dependencies with "cargo update" with the exception of
vmm-sys-utils which needs some extra porting work.
=> build: Bulk update dependencies

Cargo.lock, devices/src/legacy/i8042.rs, devices/src/legacy/serial.rs, pci/src/device.rs, qcow/src/qcow.rs, qcow/src/qcow_raw_file.rs, vfio/src/vfio_device.rs, vfio/src/vfio_pci.rs, vhost_rs/src/backend.rs, vhost_rs/src/vhost_kern/mod.rs, vhost_rs/src/vhost_user/master.rs, vhost_rs/src/vhost_user/mod.rs, vhost_rs/src/vhost_user/sock_ctrl_msg.rs, vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/device.rs, vm-virtio/src/fs.rs, vm-virtio/src/net.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/transport/pci_common_config.rs, vm-virtio/src/transport/pci_device.rs, vmm/src/vm.rs
The structure of the vmm-sys-util crate has changed with lots of code
moving to submodules.
This change adjusts the use of the imported structs to reference the
submodules.
Fixes: #145
=> build, misc: Bump vmm-sys-util dependency

pci/src/configuration.rs
The structure provided to the add_capability() function should only
contain what comes after the capability ID and the next capability
pointer, which are located on the first WORD.
Because the structure TestCap included _vndr and _next fields, they
were directly set after the first WORD, while the assertion was
expecting to find the values of len and foo fields.
Fixes #105
=> pci: Fix add_capability unit test

scripts/run_integration_tests.sh
With the addition of commands after running the integration tests the
exit code of the tests were lost.
=> tests: Ensure that the test pipeline fails

Cargo.lock, Cargo.toml, src/main.rs
This makes the log macros (error!, warn!, info!, etc) in the code work.
It currently defaults to showing only error! messages, but by passing an
increasing number of "-v"s on the command line the verbosity can be
increased.
By default log output goes onto stderr but it can also be sent to a
file.
Fixes: #121
=> main: Add logging support controlled by command line

pci/src/msix.rs
The vector control offset is at the 4th byte of each MSI-X table entry.
For that reason, it is located at 0xc, and not 0x10 as implemented.
This commit fixes the current MSI-X code, allowing proper reading and
writing of each vector control register in the MSI-X table.
Fixes #156
=> pci: Fix vector control read/write from/to MSI-X table

pci/src/msix.rs, vm-virtio/src/transport/pci_device.rs
In case the MSI-X enabling bit (bit 15) has not been set from the guest, no interrupt should be triggered from the device.
Fixes #156
=> Don't trigger MSI-X interrupt if not enabled

devices/src/legacy/serial.rs, src/main.rs, vmm/src/config.rs, vmm/src/vm.rs
Default the serial port to "null" output mode that disregards any output. This ensures that the booted kernel does not suffer from negative performance caused by trying to interact with a disabled serial port.
Fixes: #163
=> Add support for "null" serial output

vm-virtio/src/net.rs
The numbr of bytes read was being incorrectly increased by the potential
length of the end of the sliced data rather than the number of bytes
that was in the range. This caused a panic when the the network was
under load by using iperf.
It's important to note that in the Firecracker code base the function
that read_slice() returns the number of bytes read which is used to
increment this counter. The VM memory version however only returns the
empty unit "()".
Fixes: #166
=> vm-virtio: net: Fix out-of-range slice panic when under load

pci/src/device.rs
We do not use the on_device_sandboxed and register_device_capabilities
methods.
=> pci: Simplify PciDevice trait

Cargo.lock, arch/src/x86_64/mod.rs
The linux-loader crate has been updated with a regnerated bootparams.rs
which has changed the API slightly. Update to the latest linux-loader
and adapt the code to reflect the changes:
* e820_map is renamed to e820_table (and all similar variables updated)
* e820entry is renamed to boot_e820_entry
* The E820 type constants are not no longer included
=> arch: x86_64: Update linux-loader crate

docs/debug-port.md, vmm/src/vm.rs
The 0x80 IO port is typically used for BIOS debugging and testing on
bare metal x86 platforms.
We use that port and its dedicated 16 debug codes to time and track the
guest boot process.
Fixes #63
=> Debug I/O port

arch/src/lib.rs, arch_gen/src/x86/mod.rs, devices/src/bus.rs, devices/src/ioapic.rs, devices/src/legacy/serial.rs, pci/src/bus.rs, pci/src/device.rs, qcow/src/qcow.rs, src/main.rs, vfio/src/vfio_pci.rs, vm-virtio/src/console.rs, vm-virtio/src/device.rs, vm-virtio/src/transport/pci_device.rs, vmm/src/vm.rs
Latest clippy version complains about our existing code for the
following reasons:
- trait objects without an explicit `dyn` are deprecated
- `...` range patterns are deprecated
- lint `clippy::const_static_lifetime` has been renamed to
`clippy::redundant_static_lifetimes`
- unnecessary `unsafe` block
- unneeded return statement
All these issues have been fixed through this patch, and rustfmt has
been run to cleanup potential formatting errors due to those changes.
=> linters: Fix clippy issues

docs/networking.md
documentation: Change summary
Adding a network connectivity howto summarizing how cloud-hypervisor can be provisioned to use the hypervisor host for external connectivity.
Signed-off-by: <johan.kuijpers@ericsson.com>
=> Add networking howto to docs

scripts/run_integration_tests.sh
Avoid network delays by grabbing the bionic image from the local storage
bucket.
=> tests: Retrieve the bionic image from the Azure storage bucket

src/main.rs
When virtio-fs is being tested through the integration tests, there is
one specific test where DAX and cache region are disabled. In this case
the virtiofsd daemon should be used with the correct option cache=none
instead of cache=always.
=> tests: Fix virtio-fs with dax=off integration test

scripts/run_integration_tests.sh, scripts/run_unit_tests.sh
This will help pinpoint issues when debugging test failures.
=> tests: Make panics generate a backtrace

arch/src/x86_64/mod.rs
This was set to the MP table address rather than the start of the EBDA.
=> arch: x86_64: Fix EBDA adddress

scripts/run_integration_tests.sh, src/main.rs
The virtiofsd daemon takes a bit of time creating and listening on the
socket. By adding 10s timeout, we make sure the vhost-user socket has
been properly created before the VMM tries to connect to it.
Also, the daemon needs cap_dac_override capabilities to access debugfs
filesystem.
Last thing, both virtio-fs and virtio-pmem tests were slightly different
from the others since they were not explicitly killing cloud-hypervisor
and virtiofsd processes once the test was done.
Fixes #182
=> ci: Fix virtio-fs tests

vfio/src/vfio_device.rs, vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/device.rs, vm-virtio/src/fs.rs, vm-virtio/src/net.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/transport/pci_common_config.rs, vm-virtio/src/transport/pci_device.rs, vmm/src/vm.rs
This PR solves the problem of duplicating the VM guest memory by sharing it appropriately with every thread instead of copying it everywhere it needs to be owned.
=> vmm: Correctly share guest memory regions across the whole codebase

vhost_rs/src/vhost_user/sock_ctrl_msg.rs
The recvmsg syscall can split a request in multiple packets unless we
use the flag MSG_WAITALL to make sure the request will wait for the
whole data to be transferred before returning.
This flag is needed to prevent the vhost crate from returning the error
PartialMessage, which occured sporadically when using virtio-fs, and
which was detected as part of our continuous integration testing.
Fixes #182
=> vhost_rs: Wait for full request to be satisfied

scripts/run_integration_tests.sh, src/main.rs, vm-virtio/src/lib.rs, vm-virtio/src/vhost_user/handler.rs, vm-virtio/src/vhost_user/mod.rs, vm-virtio/src/vhost_user/net.rs, vm-virtio/src/vhost_user/vu_common_ctrl.rs, vmm/src/config.rs, vmm/src/vm.rs
vhost-user-net could provide good performance during the communication with userspace proces, due to it's mechanism of sharing memory. Enable this support by this PR.
The main purpose to add this support, is aim to support DPDK. There is a design picture for how Rust-based VMM with vhost-user-net will work will DPDK + ovs shown in the following issue link.
The following basic functionalities are added in this support:
- Hugetlbfs handling
- VMM as Client to connect dpdkvhostuser port provided by OVS + DPDK
- VMM as Server to connect dpdkvhostuserclient port provided by OVS + DPDK
- Multiple queue pairs support for vhost-user-net device
Fixes https://github.com/intel/cloud-hypervisor/issues/8
=> Add vhost-user-net support

Cargo.lock, vfio/src/lib.rs
cloud-hypervisor: Bumb vmm-sys-util crate version
PR #225 failed because we were still using the vmm-sys-util logging
macros and the crate's syslog module got removed. 
This PR relies on the previous commit switching to using the log crate macros instead.
=> Bump vmm-sys-util crate version

vhost_rs/src/vhost_user/connection.rs, vhost_rs/src/vhost_user/master.rs, vhost_rs/src/vhost_user/message.rs
As @sboeuf said in #173, i split out vhost user changes to this PR, the older PR will be as pure vhost-user-blok changes.
There are some bugs in current vhost_rs code, and read_config()/write_config() are not compatible with vhost user config info spec. I changed those according to vhost user spec, please help review those patches, thanks. 
@sameo @sboeuf @rbradford @chao-p
=> vhost_rs: some changes according to vhost user spec 

vmm/src/vm.rs
Do this by using the same mechanism as the vCPU threads by sending a
signal to the thread. As this is the same mechanism reuse the same code
and rename the "vcpus" member to "threads" to indicate this represents
both the vCPU threads and also the signal handler thread.
=> vmm: Cleanup signal_handler thread used for console SIGWINCH handling

src/main.rs, vmm/src/lib.rs, vmm/src/vm.rs
Now that the thread management in under control thanks to #234 and the fix for #229 the only thing that remains to be cleaned up in the manually mmap()ed regions. I hope that we will have a cleaner solution in the future with rust-vmm/vm-memory#43 this will works for now.
=> Enable rebooting

scripts/run_integration_tests.sh
Running the integration test script showed the following error:
+ '[' '!' -f /home/rob/workloads/virtiofsd
scripts/run_integration_tests.sh: line 84: [: missing `]'
+ -f /home/rob/workloads/vubridge ']'
scripts/run_integration_tests.sh: line 84: -f: command not found
This was preventing the test from reusing build QEMU artifacts.
=> scripts: Fix integration tests script:

Cargo.toml, arch/Cargo.toml, arch/src/lib.rs, arch/src/x86_64/mod.rs, devices/Cargo.toml, vmm/Cargo.toml
The command "cargo build --no-default-features" does not recursively
disable the default features across the workspace. Instead add an acpi
feature at the top-level, making it default, and then make that feature
conditional on all the crate acpi features.
=> build: Really make the acpi feature disableable

src/main.rs, vm-virtio/src/lib.rs, vm-virtio/src/queue.rs, vm-virtio/src/vsock.rs, vm-virtio/src/vsock/csm/connection.rs, vm-virtio/src/vsock/csm/mod.rs, vm-virtio/src/vsock/csm/txbuf.rs, vm-virtio/src/vsock/device.rs, vm-virtio/src/vsock/mod.rs, vm-virtio/src/vsock/packet.rs, vm-virtio/src/vsock/unix/mod.rs, vm-virtio/src/vsock/unix/muxer.rs, vm-virtio/src/vsock/unix/muxer_killq.rs, vm-virtio/src/vsock/unix/muxer_rxq.rs, vmm/src/config.rs, vmm/src/device_manager.rs
This pull request implement `virtio-vsock`. It is entirely based off of Firecracker's hybrid implementation of `virtio-vsock`. It ports both the code and the unit tests over to Cloud-Hypervisor.
The interesting approach with this specific implementation is the absence of backend running in the host kernel. The goal being to prevent any malicious guest from exploiting the host over the virtqueues from the vsock device.
In details, the backend that was `vhost` so far, has been replaced with some code proxying an `AF_UNIX` socket on the host into `AF_VSOCK` socket in the guest. The guest remains unchanged compared to a standard `vhost-vsock` implementation, but the host application now needs to connect to an `AF_UNIX` socket and send a special frame at first to initiate the connection.
The …
=> vm-virtio: Add vsock support

vmm/src/lib.rs
With ACPI disabled there is no way to support both reset and shutdown so
make the VMM exit if the VM is rebootet (via i8042 or triple-fault
reset.)
=> vmm: If acpi feature is disabled make "reboot" shutdown

src/main.rs
As part of the reboot test check that the binary cleanly terminated
after the subsequent shutdown.
=> tests: Check that the test binary cleanly terminated

README.md
We should use the 0.2.0 firmware.
Fixes: #258
=> README: Update rust-hypervisor-firmware link

scripts/run_integration_tests.sh
In order to make the tests more verbose and help identify more quickly
where a test might be failing, this patch adds the ability for the unit
tests to print useful information with println.
=> ci: Allow tests to print some useful information with println

vmm/src/device_manager.rs, vmm/src/vm.rs
Rather than calling it at the very start of the VM execution (i.e. when
the VCPUs are created) do it as part of the DeviceManager creation.
=> vmm: Call DeviceManager's register_devices() on creation

scripts/run_integration_tests.sh
By relying on a decompressed image, this patch assumes that downloading
the image will always be faster than decompressing it from the worker
VM.
=> ci: Reduce integration testing time

docs/custom-image.md
This is a quick guide on how to create a custom Clear Linux image based
on the official tooling provided by Clear Linux. If for any reason, the
image we are using is missing some interesting bundles that are packaged
by Clear Linux, this documentation will be the guide on how to proceed.
=> docs: Explain how to create a custom Clear Linux cloud image

Cargo.toml, devices/src/lib.rs, scripts/run_integration_tests.sh, src/main.rs, vm-virtio/Cargo.toml, vm-virtio/src/lib.rs, vm-virtio/src/transport/mmio.rs, vm-virtio/src/transport/mod.rs, vm-virtio/src/transport/pci_device.rs, vmm/Cargo.toml, vmm/src/device_manager.rs, vmm/src/vm.rs
This PR still needs some polish as there are various clippy warnings due to conditional compilation. And it also lacks some new integration tests that will require us to build an alternative version of the binary.
=> Add support for virtio-mmio based transport

.travis.yml, vm-virtio/src/transport/mmio.rs, vmm/src/device_manager.rs
With the addition of some conditionally built features some build warnings have crept in. Add build testing (with warnings treated as errors) for all supported feature configurations and fix the issues shown up.
=> Clean-up all feature based build warnings

arch/src/x86_64/acpi.rs
The starting length of the MCFG table was too long resulting in the
kernel trying to get extra MCFG entries from the table that weren't
there resulting in the following error message from the kernel:
PCI: no memory for MCFG entries
The MCFG table also has an 8 bytes of padding at the start before the
table begins.
=> arch: acpi: Correct starting length of MCFG table

scripts/run_integration_tests.sh, src/main.rs, vhost_rs/src/vhost_user/connection.rs, vhost_rs/src/vhost_user/master.rs, vhost_rs/src/vhost_user/message.rs, vm-virtio/src/lib.rs, vm-virtio/src/vhost_user/blk.rs, vm-virtio/src/vhost_user/mod.rs, vm-virtio/src/vhost_user/vu_common_ctrl.rs, vmm/src/config.rs, vmm/src/device_manager.rs
@sameo @rbradford @sboeuf @chao-p @bjzhjing 
for #130 
Please help review this PR, which is only work in **SINGLE** queue, and multi-queue is still on working. 
Below is command for vhost-user-blk 
./target/debug/cloud-hypervisor \
--cpus 2 \
--memory size=1024M,file=/dev/hugepages \
--kernel /home/chen/project/linux-stable/arch/x86/boot/compressed/vmlinux.bin \
--cmdline "console=ttyS0 reboot=k panic=1 nomodules i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda3" \
--disk /home/chen/project/clear-18080-kvm.img  \
--console off \
--serial tty \
--vhost-user-blk "sock=/var/tmp/vhost.1,num_queues=1,queue_size=128,wce=true"  \
--rng
for issue #232 , i also did one patch to fix it , please @sboeuf review and try it, thanks. …
=> vhost-user-blk device implementation

src/main.rs, vm-virtio/src/vhost_user/vu_common_ctrl.rs
The vhost-user implementation was always passing the maximum size
supported by the virtqueues to the backend, but this is obviously wrong
as it must pass the size being set by the driver running in the guest.
=> vm-virtio: vhost-user: Set the right vring size

vm-virtio/src/vhost_user/blk.rs, vm-virtio/src/vhost_user/net.rs, vm-virtio/src/vhost_user/vu_common_ctrl.rs, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/vm.rs
This is needed for the API server implementation #244 since the `VmConfig` structure is going to be moved between threads.
Fixes #298
=> Convert all VmConfig fields to owned data types

src/main.rs, vmm/src/lib.rs, vmm/src/vm.rs
And get rid of the VMM structure.
We're currently in a weird place where we have a VMM dedicated structure, but it's only a placeholder. We can simply get rid of it and remove one abstraction layer.
=> Simplify the VM starting flow

README.md
The current one is no longer valid.
The new one does not expire.
=> README: Update Slack invitation link

Cargo.lock, Cargo.toml, src/main.rs, vmm/src/api/mod.rs, vmm/src/lib.rs, vmm/src/vm.rs
And decouple the main VMM control logic from the VM itself. This is needed for properly supporting the HTTP external API.
Fixes #303
=> Add a VMM control loop

arch/src/lib.rs, arch/src/x86_64/acpi.rs, arch/src/x86_64/layout.rs, arch/src/x86_64/mod.rs, vmm/src/vm.rs
Using the existing layout module start documenting the major regions of
RAM and those areas that are reserved. Some of the constants have also
been renamed to be more consistent and some functions that returned
constant variables have been replaced.
Future commits will move more constants into this file to make it the
canonical source of information about the memory layout.
=> arch, vmm: Start documenting major regions of RAM and reserved memory

vhost_user_backend/Cargo.toml, vhost_user_backend/src/lib.rs, vm-virtio/src/queue.rs
The purpose of this new crate is to provide a common library to all
vhost-user backend implementations. The more is handled by this library,
the less duplication will need to happen in each vhost-user daemon.
This crate relies a lot on vhost_rs, vm-memory and vm-virtio crates.
=> vhost_user_backend: Add new crate

arch/src/x86_64/acpi.rs, arch/src/x86_64/layout.rs, arch/src/x86_64/mod.rs, pci/src/bus.rs, pci/src/lib.rs, vmm/src/device_manager.rs
Add support for PCI MMCONFIG so that the extended configuration space can be used. The ACPI and E820 tables need to be updated to reference the region of memory. The region also has strict placement requirements (< 4GiB and not in device space).
The PCI data structures also required refactoring to support both port IO and MMIO access.
Fixes: #221
=> Enable PCI MMCONFIG

scripts/run_integration_tests.sh
We no longer build vubridge, so we end up cloning qemu and building
virtiofs and the block backend all the time.
Fixes: #312
=> ci: Do not look for vubridge to decide if qemu must be built

Cargo.toml, devices/Cargo.toml, devices/src/legacy/cmos.rs, devices/src/legacy/mod.rs, vmm/Cargo.toml, vmm/src/device_manager.rs
Based off of crosvm revision b5237bbcf074eb30cf368a138c0835081e747d71
add a CMOS device. This environments that can't use KVM clock to get the
current time (e.g. Windows and EFI.)
=> devices, vmm: Add legacy CMOS device

Cargo.lock, micro_http/Cargo.toml, micro_http/src/common/headers.rs, micro_http/src/common/mod.rs, micro_http/src/connection.rs, micro_http/src/lib.rs, micro_http/src/request.rs, micro_http/src/response.rs, src/main.rs, vmm/Cargo.toml, vmm/src/api/http.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/vm.rs
Cloud Hypervisor API is a RPC-style HTTP based API, using JSON for its payload.
The API is described at `vmm/src/api/swagger/`
The HTTP requests are handled by a `micro_http` HTTP server thread. Each request is routed to its specific handler, which will translate the HTTP request into an IPC one. Each handler is given an `mpsc` Sender for sending the IPC commands and listening for the reply back.
The HTTP handlers are responsible for handling HTTP requests and unconditionally returning an HTTP response back.
The HTTP server is responsible for collecting incoming requests, routing them to the appropriate endpoint handler and sending the handler response back to the caller.
Fixes: #244 
TODO
=> Cloud  Hypervisor HTTP API

vmm/src/lib.rs
This way, we are forced to re-create the VM object when moving from
shutdown to boot.
Fixes: #321
=> vmm: Unreference the VM when shutting down

vmm/src/api/http.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/lib.rs, vmm/src/vm.rs
We can simplify the VMM thread and its control loop by handling the Exit and Reset events directly from the control loop itself, and avoid passing an exit behaviour up to the VMM thread.
By handling everything from the control loop, we can also easily add a `vmm.shutdown` endpoint to kill the VMM itself from the HTTP API interface.
=> VMM thread simplification

src/main.rs, test_data/cloud-init/clear/openstack/latest/user_data
Because the L2 VM running in the VFIO integration test is actually
running as L3 (since the CI runs in a VM), it can take quite some
time for this VM to boot.
The way to solve this issue is to extend the sleep time before to try
communicating with the L2 VM, but also to speed up the boot time by
using virtio-console instead of serial. We suspect the use of serial,
implying PIO VM exits for each character on the serial port is quite
expensive compared to the paravirtualized console.
=> ci: Allow enough time for L2 VM to boot

src/main.rs, vmm/src/api/http.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/lib.rs, vmm/src/vm.rs
We implement a simple VM pause and resume support by parking vCPU threads when receiving a pause request from the HTTP API, and unparking them when receiving a resume request.
The PR also includes an integration test for the pause/resume cycle.
=> VM pause and resume support

vmm/src/vm.rs
We should return an explicit error when the transition from on VM state
to another is invalid.
The valid_transition() routine for the VmState enum essentially
describes the VM state machine.
=> vmm: vm: Verify that state transitions are valid

Cargo.lock, Cargo.toml, docs/vfio.md, src/main.rs, test_data/cloud-init/clear/openstack/latest/user_data, vfio/Cargo.toml, vfio/src/lib.rs, vfio/src/vfio_device.rs, vm-device/Cargo.toml, vm-device/src/lib.rs, vm-virtio/Cargo.toml, vm-virtio/src/iommu.rs, vmm/Cargo.toml, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs
This PR intends to bring a new feature to cloud-hypervisor. By relying on the recently added virtual IOMMU device, a physical device being passed through a first layer of virtualization can now be passed to a second layer.
The idea is to place the physical device behind the virtual IOMMU as it gets attached to an IOMMU group from the L1 guest. And from this L1 guest, we can simply use VFIO to pass the device through a second layer of virtualization, which end up being managed by an L2 guest.
=> Support VFIO nested with virtio-iommu

src/main.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/vm.rs
cpu: cpu is an number under the implementation not struct, unless we
need to add more values to the cpu it make sense keep it as integer.
vsocks: vsocks is implemented as an array
=> api: http: make consistent api and implementation

docs/iommu.md, vm-virtio/src/iommu.rs
In order to speed up boot time, the virtual IOMMU must support 2MiB page size along with 4KiB ones.
This pull request also extend the documentation, explaining how to leverage huge pages with a virtual IOMMU.
=> iommu: Allow 2MiB page mappings

scripts/run_integration_tests.sh, src/main.rs, test_data/cloud-init/clear/openstack/latest/user_data
A new ClearLinux image has been uploaded to the Azure storage account.
It is based off of the ClearLinux cloudguest image 31310 version, with
two extra bundles added to it.
First bundle is sysadmin-basic to include utility like netcat, and the
second bundle is iperf, adding the iperf binary to the image.
The image is 2G in size.
=> ci: Update ClearLinux image

.travis.yml
cargo audit audits Cargo.lock for crates with security vulnerabvilities
reported by the RustSec Advisory Database.
=> ci: Add cargo audit to the travis pipeline

acpi_tables/src/aml.rs, acpi_tables/src/lib.rs, acpi_tables/src/sdt.rs, arch/src/x86_64/acpi.rs
Rather than using precompiled DSDT chunks that are then patched to customise them for the running environment instead generate AML directly.
Fixes: #352
=> Create the DSDT programatically

Cargo.toml
=> cargo: Move to 0.3.0

.travis.yml
After some of the build changes there was no longer a release artifact
left to be used for the release builds.
=> build: Ensure there is a release build artifact for travis to upload

Cargo.lock, pci/Cargo.toml, pci/src/lib.rs
The PCI crate should not depend on the KVM crates.
=> pci: Remove KVM dependency

vmm/src/device_manager.rs
Ensure that we tell the allocator about all the I/O ports that we are
using for I/O bus attached devices (serial, i8042, ACPI device.)
=> vmm: device_manager: Ensure I/O ports are allocated

vmm/src/lib.rs
In vm_reboot, while build the new vm, the old one pointed by self.vm is not released, that is, the tap opened by self.vm is not closed either. As a result, the associated dev name slot in host kernel is still in use state, which prevents the new build from picking it up as the new opened tap's name, it needs to use the name in next slot instead. Assign self.vm as None once shutdown, to ensure the old vm is destructed before the new vm build.
To address #389
=> Fix the issue that the opened tap is renamed after vm reboot

acpi_tables/src/aml.rs, arch/src/x86_64/acpi.rs
The first step in the CPU hotplug implementation is to be able to expose the basic processor state in the DSDT. This PR adds the ability to define methods which are needed to allow the OSPM to query state or have the platform act on it.
Working towards: #407
=> Expose processors in the DSDT

arch/Cargo.toml, arch/src/aarch64/mod.rs, arch/src/x86_64/mod.rs, vmm/Cargo.toml, vmm/src/acpi.rs, vmm/src/lib.rs, vmm/src/vm.rs
Remove ACPI table creation from arch crate to the vmm crate simplifying
arch::configure_system()
GuestAddress(0) is used to mean no RSDP table rather than adding
complexity with a conditional argument or an Option type as it will
evaluate to a zero value which would be the default anyway.
=> arch: vmm: Move ACPI tables creation to vmm crate

Cargo.lock, Cargo.toml, devices/Cargo.toml, vhost_user_backend/Cargo.toml, vm-virtio/Cargo.toml, vmm/Cargo.toml, vmm/src/api/http.rs
The HTTP API responses are encoded in JSON, change the default content type. 
Suggested-by:  Samuel Ortiz <sameo@linux.intel.com>
Tested-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
=> API: HTTP: change response content type to JSON

Cargo.lock, vmm/Cargo.toml, vmm/src/api/http.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/openapi/cloud-hypervisor.yaml
The new micro_http package provides a built-in HttpServer wrapper for
running a more robust HTTP server based on the package HTTP API.
Switching to this implementation allows us to, among other things,
handle HTTP requests that are larger than 1024 bytes.
Fixes: #423
=> Convert to micro_http HttpServer

vmm/src/cpu.rs, vmm/src/lib.rs, vmm/src/vm.rs
Move CpuManager, Vcpu and related functionality to its own module (and
file) inside the VMM crate
=> vmm: Move CPU management code to its own module

vmm/src/api/openapi/cloud-hypervisor.yaml
We are returning a state and a config.
Fixes: #431
=> vmm: api: Fix the vm.info response payload

docs/networking.md
An extra double quote was introduced by mistake in one of the hyperlink.
Signed-off-by: Emin Ghuliev <drmint80@gmail.com>
=> docs: networking: Fix typo in hyperlink

docs/fs.md
The cloud-hypervisor supports the DAX shared region for better virtio-fs
performances, but it was not updated in the documentation. This commit
takes care of this and also update the mount command since it changed
with virtio-fs v0.3.
Fixes #433
=> docs: fs: Update virtio-fs documentation

vmm/src/device_manager.rs
By moving each device creation logic into its specific routines, we make the `new()` routine smaller and easier to read.
Fixes: #441
=> Extract DeviceManager new() code out into smaller routines

README.md, docs/device_model.md
This commit introduces a dedicated document describing the device model
supported by cloud-hypervisor VMM.
It needs to be updated anytime a new device will be added in the future.
Fixes #437
=> docs: Add device model

CONTRIBUTING.md, README.md, docs/device_model.md, docs/fs.md, release-notes.md, scripts/run_integration_tests.sh
Update all references to the new repository locations. Many of these will
redirect however the one used for the hypervisor-fw binary does not so
this is required to allow the builds to pass.
=> misc: Update to new repository locations

vfio/src/vfio_device.rs, vfio/src/vfio_pci.rs
These patches fix the error message "Could not disable the MSI-X" when shutdown a vm.  
Patch 1: use correct flags to disable interrupts
Patch 2: cleanup msi/msix according to whether the capability is enabled instead disable interrupts twice
=> vfio: eliminate the error message "Could not disable the MSI-X" when shutdown a vm

acpi_tables/src/aml.rs, vmm/src/acpi.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/vm.rs
Have the guest OS query the status of the CPU (via the _STA method) in the ACPI DSDT table and ultimately query the CPU manager via the I/O port.
This is a step towards implementing CPU hotplug, with CPU hotplug the CPU manager will be enhanced to support reporting which of the CPUs are enabled (requring the need to separate boot and max CPUs) and an ACPI GED device will be added to signal to the guest that it should rescan the list of CPUs and receive device notifications if they've changed.
=> Dynamically query CPU status from cpu manager via ACPI

src/main.rs, vmm/src/api/http.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/lib.rs
vmm.ping will help to check if http API server is up and
running.
=> http: api: implement vmm.ping

Jenkinsfile
In order to prevent bad builds on the CI consuming excessive resources
set a build timeout of 1 hour. In order to be able to do this it was
necessary to switch to the declarative pipeline syntax.
=> Jenkinsfile: Switch to declarative pipeline format to add a timeout

scripts/run_integration_tests.sh, src/main.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/vm.rs
In order to let users decide whether or not they want to use KSM on the host, this pull request makes the marking of the memory pages as "mergeable" optional. By default, the pages are not marked as "mergeable", which means the default behavior of the VMM is not modified.
If the user is looking for better memory footprint when running multiple VMs side by side on the same host, KSM can help. By adding the option `mergeable=on` to `--memory` or `--pmem`, one can decide to mark the memory pages as mergeable, hence making them detectable by KSM.
Fixes #436
=> Allow VMM to mark memory pages as mergeable

Cargo.lock, Cargo.toml, scripts/run_integration_tests.sh, src/bin/vhost_user_fs.rs, src/main.rs, vhost_user_fs/Cargo.toml, vhost_user_fs/src/descriptor_utils.rs, vhost_user_fs/src/file_traits.rs, vhost_user_fs/src/filesystem.rs, vhost_user_fs/src/fuse.rs, vhost_user_fs/src/lib.rs, vhost_user_fs/src/multikey.rs, vhost_user_fs/src/passthrough.rs, vhost_user_fs/src/server.rs, vm-virtio/src/queue.rs
The purpose of this pull request is to introduce the first vhost-user-fs daemon (also known as `virtiofsd`) in Rust, relying on the crates such as `vm-virtio` and `vhost_user_backend` meant to live under the `rust-vmm` organization at some point.
One important thing to notice is that most of this code has been ported from the original implementation that can be found in Crosvm, or from pieces that are still pending.
So far, the current pull request ported the existing code from Crosvm into a dedicated crate `vhost_user_fs` to act as a specific library. This library is being used from the newly introduced binary `vhost-user-fs` which is generated from `/src/bin/vhost_user_fs.rs`.
Important to note that most of the code ported from Crosvm has been added to the `vhost_user_fs` crate in order …
=> Add a vhost-user-fs daemon in Rust

scripts/run_integration_tests.sh
The setcap tool is unusual in its behaviour in that it will process each
parameter separately and abort if one of the parameters is invalid (e.g.
after a symlink.) But any previous parameters will be correctly
processed. This means that depending on the generated test binary name
an invalid entry might occur before it and thus abort the setcap.
Fix to only setcap on the test binary by excluding the other files.
Because the binary name is based on a hash the PR that introduced this
version worked but once merged the hash changed and broke the build.
=> tests: Only setcap on test binary

vfio/src/vfio_device.rs
This reverts commit 66fde245b39b71dfc2e46803bcaf640f8175bcb5.
The commit broke the VFIO support for MSI. Issue needs to be
investigated but in the meantime, it is safer to fix the codebase.
=> Revert "vfio: use correct flags to disable interrupts"

vmm/src/api/openapi/cloud-hypervisor.yaml
context ID on vsock man defines a 32-bits value, openapi default integer
is a signed 32-bits value.
This could lead to miss one bit during castings for typed client
implmentations. Lets increase the range of valid values by requesting an
int64.
=> openapi: make context ID vsock int64

Cargo.toml
cloud-hypervisor is the main create, useful to do `cargo run`.
=> cargo: set cloud-hypervisor as default crate

.travis.yml
Reorder the build commands so that more build assets in the target/
build directory can be reused. This will reduce the build time.
=> build: Reorder travis build commands to reuse build assets

Cargo.lock, Cargo.toml, arch/Cargo.toml, arch/src/x86_64/interrupts.rs, arch/src/x86_64/regs.rs, devices/Cargo.toml, devices/src/ioapic.rs, net_gen/Cargo.toml, net_util/Cargo.toml, pci/Cargo.toml, qcow/Cargo.toml, vfio/Cargo.toml, vfio/src/vfio_device.rs, vfio/src/vfio_pci.rs, vhost_rs/Cargo.toml, vhost_user_backend/Cargo.toml, vm-virtio/Cargo.toml, vmm/Cargo.toml, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/vm.rs
Since the kvm crates now depend on vmm-sys-util, the bump must be
atomic.
The kvm-bindings and ioctls 0.2.0 and 0.4.0 crates come with a few API
changes, one of them being the use of a kvm_ioctls specific error type.
Porting our code to that type makes for a fairly large diff stat.
=> cargo: Bump the kvm and vmm-sys-util crates

devices/src/acpi.rs, devices/src/lib.rs, src/main.rs, vmm/src/acpi.rs, vmm/src/api/http.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/vm.rs
Add a "vm.resize()" http method that will ultimately result in more vCPU devices being added to the system.
Integration test included. For manual testing:
`target/debug/cloud-hypervisor  --kernel ~/src/linux/arch/x86/boot/bzImage --cmdline "root=/dev/vda3 console=ttyS0" --serial tty --console off --disk path=~/workloads/clear-31520-kvm.img --memory size=1024M --cpus boot=2,max=4 --api-socket=/tmp/ch-socket`
and 
` curl -H "Accept: application/json" -H "Content-Type: application/json" -i -XPUT --unix-socket /tmp/ch-socket -d "{ \"desired_vcpus\":4}" http://localhost/api/v1/vm.resize`
to resize
Fixes: #407
=> Add support for CPU hotplug

vmm/src/api/openapi/cloud-hypervisor.yaml
Some renames from "cpu_count" were missing.
=> api: Fix OpenAPI specification entries

vmm/src/cpu.rs
The function that programs the vCPUs is expected to be run from within
each vCPU thread.
=> vmm: cpu: Call vcpu configure() on the vCPU thread

docs/fs.md
The documentation was out of date since the URL to download virtiofsd
binary was not valid anymore. Instead, the updated documentation now
describe how to build virtiofsd from source.
Fixes #491
=> docs: Update instructions regarding virtiofsd

vfio/src/vfio_device.rs, vfio/src/vfio_pci.rs
This PR contains the previous patch from @Cordius that we had to revert since we identified a problem with NIC devices supporting only MSI interrupts.
The PR contains a second commit that includes the fix for this issue.
Fixes #460
=> vfio: Correctly implement MSI/MSI-X disable

scripts/run_integration_tests.sh, src/main.rs, test_data/cloud-init/clear/openstack/latest/user_data
In order to validate that multiple devices can be passed through and
they are still fully functional, this patch extends the existing VFIO
test to pass a second virtio-net device, and verifies that both
interfaces are functional by ssh'ing into each network interface.
Fixes #503
=> ci: Extend VFIO integration test

vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs
When consumer of the HTTP API try to interact with cloud-hypervisor,
they have to provide the equivalent of the config structure related to
each component they need. Problem is, the Rust enum type "Option" cannot
be obtained from the OpenAPI YAML definition.
This patch intends to fix this inconsistency between what is possible
through the CLI and what's possible through the HTTP API by using simple
types bool and int64 instead of Option<u64>.
=> vmm: api: Modify FsConfig to be OpenAPI friendly

vmm/src/acpi.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/vm.rs
Move the ACPI table creation (in particular the DSDT creation) to make it easier to handle functionality like adding device hotplug,
=> Delegate ACPI functionality to DeviceManager/CpuManager

vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs
This reverts commit defc5dcd9cf883178d958ec3260fb886e700d5e1.
For some reasons, the OpenAPI and serde don't behave as expected and the previous PR should be reverted.
=> Revert "vmm: api: Modify FsConfig to be OpenAPI friendly"

devices/src/acpi.rs, vmm/src/device_manager.rs, vmm/src/vm.rs
Now that creation of the ACPI tables is delegated to the device manager the hardcoded GED IRQ can be removed.
=> Remove hardcoded GED IRQ

vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs
In order to let the CLI and the HTTP API behave the same regarding the
NetConfig structure, this patch defines some default values for tap, ip,
mask, mac and iommu.
tap is None, ip is 192.168.249.1, mask is 255.255.255.0, mac is a
randomly generated value, and iommu is false.
=> vmm: api: Make NetConfig defaults match between CLI and HTTP API

vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs
In order to let the CLI and the HTTP API behave the same regarding the
FsConfig structure, this patch defines some default values for
num_queues, queue_size and the cache_size.
num_queues is set to 1, queue_size is set to 1024, and cache_size is set
to Some(8G) which means that DAX is enabled by default with a shared
region of 8GiB.
Fixes #508
=> vmm: api: Make FsConfig defaults match between CLI and HTTP API

.travis.yml, Jenkinsfile, scripts/run_cargo_tests.sh, scripts/run_openapi_tests.sh
In order to run our CI more efficiently, we decided to offload some tests running on Travis to the Azure worker node. Additionally, we introduced some testing for the OpenAPI scheme definition.
Fixes #527
=> ci: Offload more tests to the Azure worker node

Cargo.lock, Cargo.toml, devices/Cargo.toml, net_gen/Cargo.toml, net_util/Cargo.toml, pci/Cargo.toml, qcow/Cargo.toml, vfio/Cargo.toml, vhost_rs/Cargo.toml, vhost_user_backend/Cargo.toml, vm-virtio/Cargo.toml, vmm/Cargo.toml, vmm/src/cpu.rs
The signal handling for vCPU signals has changed in the latest release
so switch to the new API.
=> vmm: Port to latest vmm-sys-util

Jenkinsfile
When a new build is triggered cancel any older builds to conserve
resources.
=> ci: Cancel older builders on Jenkins

src/main.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs
The point of this pull request is to improve a bit the code and the OpenAPI definition to ensure CLI and HTTP behave the same regarding the provided parameters, and especially regarding the default values being picked.
=> Make CLI and HTTP API behave identically

Jenkinsfile
To alleviate load on the CI only test PRs that are not marked as RFC or
WIP.
=> Skip testing of PRs based on title

Cargo.lock, scripts/run_cargo_tests.sh, vm-device/Cargo.toml, vm-device/src/lib.rs, vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/device.rs, vm-virtio/src/iommu.rs, vm-virtio/src/lib.rs, vm-virtio/src/net.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/transport/mmio.rs, vm-virtio/src/transport/pci_common_config.rs, vm-virtio/src/transport/pci_device.rs, vm-virtio/src/vhost_user/blk.rs, vm-virtio/src/vhost_user/fs.rs, vm-virtio/src/vhost_user/handler.rs, vm-virtio/src/vhost_user/net.rs, vm-virtio/src/vsock/device.rs, vm-virtio/src/vsock/mod.rs, vmm/Cargo.toml, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/vm.rs
Define the `Pausable` trait for components that can pause and resume.
Through this trait we can do 2 things:
1. Iteratively go through all devices and pause or resume them when respectively pausing or resuming a VM. This fixes #341  
2. Define the `Migratable` trait as a conjonction of the `Pausable` and `Snapshotable` traits. PR #444 is now based on this PR and on the `Pausable` trait.
To emphasize the relationship between this PR and #444: #444 defines the `Snapshotable` trait on top of the `Pausable` one and this current PR allows to make the initial migration/snapshoting implementation shorter by pushing the `Pausable` part first. 
Fixes #341
=> Add Pausable trait

Jenkinsfile, scripts/run_integration_tests.sh
Virtio-fs maintainers recently updated the virtiofsd daemon through
their official branch on Gitlab. It includes fixes that were needed for
cloud-hypervisor to work correctly with it.
Jenkinsfile needs to be updated since the virtiofsd build requires both
libseccomp and libcap-ng to be present on the system.
One thing to notice, because the latest branch introduced a change
regarding libfuse behavior, the counterpart patch has been added to the
custom kernel branch "virtio-fs-virtio-iommu".
Fixes #536
=> ci: Rely on latest virtiofsd version

README.md
We recommend to specify the boot cpus, even though the old syntax is still
supported.
=> README: Update the --cpus command line examples

Cargo.lock, vfio/src/vfio_device.rs, vm-device/Cargo.toml, vm-device/src/lib.rs, vm-virtio/src/queue.rs, vm-virtio/src/vhost_user/vu_common_ctrl.rs, vm-virtio/src/vsock/packet.rs
The vsock packets that we're building are resolving guest addresses to
host ones and use the latter as raw pointers.
If the corresponding guest mapped buffer spans across several regions in
the guest, they will do so in the host as well. Since we have no
guarantees that host regions are contiguous, it may lead the VMM into
trying to access memory outside of its memory space.
For now we fix that by ensuring that the guest buffers do not span
across several regions. If they do, we error out.
Ideally, we should enhance the rust-vmm memory model to support safe
acces across host regions.
Fixes CVE-2019-18960
=> vsock: Fix potential host memory overflow

Cargo.lock, Cargo.toml, src/main.rs, vmm/Cargo.toml, vmm/src/config.rs
The goal here is to ensure that CLI and OpenAPI both behave as closely
as possible, and also that they behave as expected.
Leveraging the reorganization of the code, we can now compare two
VmConfig structures generated from one CLI entry on one side, and from
an OpenAPI entry (JSON payload) on the other side.
Fixes #535 
=> ci: Add unit tests to compare CLI and OpenAPI

vmm/src/cpu.rs, vmm/src/device_manager.rs
Rather than notifying for all ACPI CPU objects when we received a notification of hotplug instead only notify on the changed devices.
This fixes: #555 and works towards CPU unplug.
=> Only notify on newly inserted CPUs

vm-virtio/src/vsock/csm/connection.rs, vm-virtio/src/vsock/csm/mod.rs, vm-virtio/src/vsock/unix/muxer.rs
This patch has been cherry-picked from the Firecracker tree. The
reference commit is 1db04ccc69862f30b7814f30024d112d1b86b80e.
Changed the host-initiated vsock connection protocol to include a
trivial handshake.
The new protocol looks like this:
- [host] CONNECT <port><LF>
- [guest/success] OK <assigned_host_port><LF>
On connection failure, the host host connection is reset without any
accompanying message, as before.
This allows host software to more easily detect connection failures, for
instance when attempting to connect to a guest server that may have not
yet started listening for client connections.
Signed-off-by: Dan Horobeanu <dhr@amazon.com>
=> vm-virtio: Add connection handshake to vsock

scripts/run_integration_tests.sh, src/main.rs
Because we don't always reach the expected footprint improvements with
KSM, let's review the numbers. By reducing the expectations and
increasing the amount of pages to scan, this should stabilize the CI.
=> ci: Fix flaky test_memory_mergeable_on test

vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
The memory manager is responsible for setting up the guest memory and in
the long term will also handle addition of guest memory.
In this commit move code for creating the backing memory and populating
the allocator into the new implementation trying to make as minimal
changes to other code as possible.
Follow on commits will further reduce some of the duplicated code.
=> vmm: Introduce MemoryManager

Cargo.lock, Cargo.toml, vfio/Cargo.toml, vfio/src/lib.rs, vfio/src/vfio_device.rs, vm-virtio/Cargo.toml, vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/device.rs, vm-virtio/src/iommu.rs, vm-virtio/src/lib.rs, vm-virtio/src/net.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/transport/mmio.rs, vm-virtio/src/transport/pci_common_config.rs, vm-virtio/src/transport/pci_device.rs, vm-virtio/src/vhost_user/blk.rs, vm-virtio/src/vhost_user/fs.rs, vm-virtio/src/vhost_user/net.rs, vm-virtio/src/vsock/device.rs, vm-virtio/src/vsock/mod.rs, vmm/Cargo.toml, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
This allows us to change the memory map that is being used by the
devices via an atomic swap (by replacing the map with another one). The
ArcSwap provides the mechanism for atomically swapping from to another
whilst still giving good read performace. It is inside an Arc so that we
can use a single ArcSwap for all users.
Not covered by this change is replacing the GuestMemoryMmap itself.
This change also removes some vertical whitespace from use blocks in the
files that this commit also changed. Vertical whitespace was being used
inconsistently and broke rustfmt's behaviour of ordering the imports as
it would only do it within the block.
=> vm-virtio, vmm, vfio: Store GuestMemoryMmap in an Arc<ArcSwap<T>>

Cargo.toml, scripts/run_unit_tests.sh, vhost_rs/src/vhost_user/connection.rs, vhost_rs/src/vhost_user/master.rs, vhost_rs/src/vhost_user/message.rs, vhost_rs/src/vhost_user/mod.rs, vm-virtio/src/transport/pci_common_config.rs
Use cargo workspaces to simplify our unit test running. This shows up some broken tests which this PR also fixes.
=> Fix unit tests

vm-virtio/src/lib.rs
The From and Display traits were not handling some of the enum
definitions. We no longer have a default case for Display so any future
misses will fail at build time.
=> vm-virtio: Fix VirtioDeviceType traits

docs/fs.md, scripts/run_integration_tests.sh, src/main.rs
With the latest version of virtiofsd, some changes have been made
to the socket path parameter. This needs to be updated in the cloud
hypervisor codebase, so that our CI keeps running correctly.
Fixes #611
=> virtio-fs: Update virtiofs daemon parameters

Cargo.lock, arch/Cargo.toml, net_util/Cargo.toml
When we get a large backlog of dependabot PRs it's much easier to collate all the "simple" ones together and create a new PR from that.
=> Coalesce dependabot PRs

vmm/src/device_manager.rs
If neither PCI or MMIO are built in, we should not bother creating any
virtio devices at all.
When building a minimal VMM made of a kernel with an initramfs and a
serial console, the RNG virtio device is still created even though there
is no way it can ever get probed.
=> vmm: Do not create virtio devices when missing a transport

Cargo.lock, qcow/Cargo.toml, qcow/src/qcow.rs, qcow/src/qcow_raw_file.rs, src/bin/vhost_user_blk.rs, src/main.rs, vm-virtio/src/block.rs, vmm/src/device_manager.rs
Add support for opening the disk images with O_DIRECT. This allows
bypassing the host's file system cache, which is useful to avoid
polluting its cache and for better data integrity.
On the downside, O_DIRECT imposes certain alignment restrictions for
the I/O operations done on the disk image. Ideally, a layer between
the disk format and the underlying file should be implemented to cope
with such restrictions. But, for the moment, we just reject opening
qcow2 images in direct mode.
=> vhost_user_blk: implement support for direct (O_DIRECT) mode 

Cargo.lock, devices/Cargo.toml, devices/src/acpi.rs, devices/src/legacy/serial.rs, devices/src/lib.rs, pci/src/device.rs, pci/src/lib.rs, vm-virtio/src/transport/mmio.rs, vm-virtio/src/transport/pci_device.rs, vmm/src/device_manager.rs, vmm/src/interrupt.rs
In order to follow up the pull request introducing the `InterruptManager` for PCI devices (`virtio-pci` and `vfio-pci`), this new pull request replaces the old way of dealing with legacy interrupts with the `InterruptManager` and more particularly with `InterruptSourceGroup` implementation for legacy interrupts.
Additionally, this pull request fixes and cleans up some code that can be simplified after the Interrupt Manager is being used everywhere in the codebase.
=> Introduce InterruptManager for legacy interrupts

scripts/run_cargo_tests.sh, vm-virtio/src/lib.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
The build is run against "--all-features", "pci,acpi", "pci" and "mmio"
separately. The clippy validation must be run against the same set of
features in order to validate the code is correct.
Because of these new checks, this commit includes multiple fixes
related to the errors generated when manually running the checks.
=> ci: Run clippy for each specific feature

src/main.rs, vmm/src/config.rs, vmm/src/device_manager.rs
This patch series add 'direct' support for virtio-blk, as requested by #631, and while I was there I also added 'readonly' support, for feature parity with vhost-user-blk.
=> Add 'readonly' and 'direct' support for virtio-blk

vmm/src/memory_manager.rs
There are many warnings of unexpected IO port access on boot. In my case, 
```
cloud-hypervisor: 115.750067ms: WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12
```
and 
```
cloud-hypervisor: 116.776781ms: WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 15
```
The former is caused by a wrong offset of IO port and should be fixed by the pull request. The latter should be a conflict IO port range with a driver named telco_clock.
```
root@cloud-hypervisor ~ # cat /proc/ioports 
0000-0cf7 : PCI Bus 0000:00
0000-001f : dma1
0020-0021 : pic1
0040-0043 : timer0
0050-0053 : timer1
0060-0060 : keyboard
0064-0064 : keyboard
0070-0071 : rtc_cmos
0080-008f : dma page reg
00a0-00a1 : pic2
00c0-00df : dma2 …
```
=> vmm: Fix LENGTH_OFFSET_HIGH of MemoryManager

Cargo.lock, devices/Cargo.toml, devices/src/ioapic.rs, devices/src/lib.rs, vmm/src/device_manager.rs, vmm/src/interrupt.rs
Through this PR, the IOAPIC and the `devices` crate are freed from `kvm_ioctls` and `kvm_bindings` dependencies.
By relying on the `InterruptManager`, the IOAPIC does not need to know about the type of hypervisor, and how the update and delivery of an interrupt should be managed.
This simplifies the IOAPIC code and the chain of dependencies.
=> ioapic: Rely on the InterruptManager

vfio/src/vfio_pci.rs
The way to get the BAR size is by writing all 1's to the BAR register in
the PCI config space. The mechanism was in place but the parameters were
swapped. The data buffer was provided with the actual offset, while the
offset was provided with the actual all 1's dword. We were effectively
trying to write the real offset at the offset 0xffffffff, which was
failing and resulting in the size being wrong.
=> vfio: Fix 64bits BAR size reading

devices/src/acpi.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/memory_manager.rs
Don't put these devices on the I/O bus where they might collide with fixed allocations instead make them MMIO devices.
Fixes: #647
=> Move CpuManager, MemoryManager and GED to MMIO space

scripts/run_integration_tests.sh
When the CI runs in a brand new VM, there's no problem with the validity
of the images as they just got downloaded from the Azure bucket.
In case of a user who runs the CI locally, while doing some debug, he
might provision the images with cloudinit at some point, and later try
to run the CI based on these same images. What happens is that the CI
might randomly fail because the provisioning will not happen again as
it already happened.
This patch ensures the CI to fail early and show an error message to
notify the user about the validity of the images, based on their
sha1sum.
Fixes #112
=> ci: Make the integration tests fail if images are not valid

vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/device.rs, vm-virtio/src/iommu.rs, vm-virtio/src/net.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/vhost_user/blk.rs, vm-virtio/src/vhost_user/fs.rs, vm-virtio/src/vhost_user/net.rs, vm-virtio/src/vsock/device.rs
In order to simplify and avoid duplication with the virtio Pausable macros, we need to extend all virtio potentially support multi threading.
Then we can add a hidden abstraction layer and factorize all common Pausable virtio code through the macros.
=> vm-virtio macro simplifications

docs/device_model.md, src/main.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs
Deprecate the "--vhost-user-net" command by providing the necessary parameters to "--net"
See #630 for context.
=> Allow "--net" to be used for controlling vhost-user-net

docs/device_model.md, src/main.rs, vmm/src/config.rs, vmm/src/device_manager.rs
Deprecate the "--vhost-user-blk" command by providing the necessary parameters to "--disk"
See #630 for context.
=> Allow "--disk" to be used for controlling vhost-user-block

pci/src/bus.rs, pci/src/device.rs, vfio/src/vfio_pci.rs, vm-virtio/src/transport/pci_device.rs
The virtio capability VIRTIO_PCI_CAP_PCI_CFG is exposed through the device's PCI config space the same way other virtio-pci capabilities are exposed.
The main and important difference is that this specific capability is designed as a way for the guest to access virtio capabilities without mapping the PCI BAR. This is very rarely used, but it can be useful when it is too early for the guest to be able to map the BARs.
One thing to note, this special feature MUST be implemented, based on the virtio specification.
=> Implement VIRTIO_PCI_CAP_PCI_CFG

README.md, resources/Dockerfile, scripts/dev_cli.sh, scripts/run_cargo_tests.sh
The script is a development tool that runs all commands in a dedicated
container. This allows for containerized, isolated and reproducible
builds and CI runs.
The script supports the following command:
* build: Build Cloud Hypervisor binaries (debug and release)
* build-container: Build the container used by the script
* tests: Run unit, cargo and integration tests
```
$ ./scripts/dev_cli.sh help
Cloud Hypervisor dev_cli.sh
Usage: dev_cli.sh <command> [<command args>]
Available commands:
build [--debug|--release] [-- [<cargo args>]]
Build the Cloud Hypervisor binaries.
--debug               Build the debug binaries. This is the default.
--release             Build the release binaries.
tests [--unit|--cargo|--all]
Run the Cloud Hypervisor tests.
--unit               Run the unit tests. …
```
=> scripts: Add container based development script

Cargo.lock, vfio/Cargo.toml, vfio/src/vfio_device.rs
It's less unsafe and makes the code more readable.
=> vfio: Use the vfio-binding FAM wrappers

vmm/src/device_manager.rs, vmm/src/vm.rs
Refactor DeviceManager to make the functions that build up the device state methods. This is in preparation for the work to support both PCI device hotplug and vhost-user backend spawning.
=> Refactor DeviceManager

src/main.rs
As this can happen during the running of the VMM we should be very
careful not to panic() as that can lead to a thread being used by the VM
disappearing.
=> main: Don't panic (by calling .expect()) if writing to the log fails

src/main.rs
A previous version of this change attempted to avoid panicking by not
using .expect() when handling an error when attempting to write to the
log file. Unfortunately the macro eprintln!() that was used to replace
the .expect() also has the behaviour of panicking if stderr cannot be
used. Instead swallow the error completely as if writing to the log has
failed at logging time it is almost certainly the case that any message
about the log would also not be seen.
=> main: Ignore error on log writing

scripts/dev_cli.sh, scripts/run_integration_tests.sh, scripts/run_unit_tests.sh
In order, among other things, to use the development CLI to run specific
integration tests. For example, to run only the memory_overhead
integration test:
./scripts/dev_cli.sh tests --integration -- memory_overhead
=> scripts: dev_cli: Pass unit and integration test args to cargo test

scripts/run_cargo_tests.sh, src/main.rs
Check the rust formatting rather than just reformatting code on the CI
agent.
Also fix a formatting error that slipped in whilst the cargo fmt check
was not working correctly.
=> scripts: Check the Rust formatting is valid

devices/src/ioapic.rs, vfio/src/vfio_pci.rs, vm-device/src/interrupt/mod.rs, vm-virtio/src/transport/pci_device.rs, vmm/src/device_manager.rs, vmm/src/interrupt.rs
Having the InterruptManager trait depend on an InterruptType forces
implementations into supporting potentially very different kind of
interrupts from the same code base. What we're defining through the
current, interrupt type based create_group() method is a need for having
different interrupt managers for different kind of interrupts.
By associating the InterruptManager trait to an interrupt group
configuration type, we create a cleaner design to support that need as
we're basically saying that one interrupt manager should have the single
responsibility of supporting one kind of interrupt (defined through its
configuration).
=> vm-device: interrupt: Remove InterruptType dependencies and  definitions

Cargo.lock, arch/src/x86_64/mod.rs, arch/src/x86_64/mptable.rs, arch/src/x86_64/regs.rs, vhost_user_backend/src/lib.rs, vhost_user_fs/src/descriptor_utils.rs, vm-device/src/lib.rs, vm-virtio/src/queue.rs, vm-virtio/src/vsock/mod.rs, vmm/src/vm.rs
This commit updates Cloud-Hypervisor to rely on the latest version of
the vm-memory crate.
=> dependencies: bump vm-memory from `4237db3` to `f3d1c27`

README.md
Fix the typo for the instructions of using cli_dev to run unit tests.
=> README: Fix a typo for using cli_dev

scripts/dev_cli.sh
To mitigate Azure slow disk IO, we mount /tmp on tmpfs.
This is a reproduction of our CI environment, as setup by the
Jenkinsfile.
=> scripts: dev_cli: Use a tmpfs mount for /tmp

scripts/dev_cli.sh
By default our dev container commands run as root inside the container, which means any build artifact will be owned by root on the *host*. This prevents Jenkins from being able to properly clean the build directory up.
This PR does 2 things, in order to fix that:
1. For commands that do not need to be run as root, run the container as the host user. The build directory will then not be owned by root.
2. For commands that do need to be run as root, fix the build directory permissions after the container is done.
=> scripts: dev_cli: Fix build directory permissions

scripts/run_integration_tests.sh, src/main.rs
test_vfio has been failing consistently on the CI so mark it with
a "#[ignore]" and then forceably build it again but ignore the build
result.
=> build: Don't fail build on test_vfio failure

docs/networking.md, net_util/src/tap.rs, vm-virtio/src/net_util.rs
The goal for this PR is to improve the error messages regarding an existing TAP interface, and how some configuration are not appropriate depending on the fact the interface might support multiqueue or not.
Fixes #738
=> network: Improve checks regarding TAP interface configuration

scripts/run_integration_tests.sh
The placement of the explicit run of "test_vfio" meant it was run with
MMIO rather than PCI which meant it always failed.
=> tests: Run test_vfio with PCI binary     

scripts/run_integration_tests.sh, src/main.rs, test_data/cloud-init/clear/openstack/latest/user_data
Using hugepages with VFIO and virtiofs can improve the performance of
the test_vfio test.
=> tests: Use hugepages for test_vfio

Cargo.toml, build.rs, src/main.rs
Add a build-script to propagate the git commit hash to other crates at
compile time through environment variables, and display the hash along
with the '--version' option.
Fixes #729
=> main: Display git commit hash with the '--version' option

Cargo.lock, src/main.rs, vhost_rs/src/vhost_user/master.rs, vm-virtio/src/device.rs, vm-virtio/src/vhost_user/net.rs, vmm/Cargo.toml, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/vm.rs
If "vhost_user=true" is set but no socket is provided respawn the cloud-hypervisor binary as a network backend and use that.
See #630
=> Add "self spawning" support to --net

scripts/run_integration_tests.sh, src/main.rs
This reverts commit 014844d0daef115fb9b51ea8bdd9f6f596776653.
=> Revert "build: Don't fail build on test_vfio failure"

vmm/src/device_manager.rs
When a virtio-fs device is created with a dedicated shared region, by
default the region should be mapped as PROT_NONE so that no pages can be
faulted in.
It's only when the guest performs the mount of the virtiofs filesystem
that we can expect the VMM, on behalf of the backend, to perform some
new mappings in the reserved shared window, using PROT_READ and/or
PROT_WRITE.
Fixes #763
=> vmm: Prevent memory overcommitment through virtio-fs shared regions

Jenkinsfile
The unit tests require higher privileges so for safety run on the worker
nodes.
=> build: Run unit tests on worker node

scripts/dev_cli.sh
The unit tests require some specific Linux capabilities and also to have
access to /dev/kvm device. This commit makes sure we enable only what's
necessary instead of blindly enable full priviliges with --privileged
option.
=> ci: Don't run unit tests in a privileged container

vhost_rs/src/vhost_user/connection.rs
The unit tests are run from cargo test through multiple threads of the
same process. For this reason, all these threads share their file
descriptors (because that's how this works on Linux), which means that
any of them can close a file descriptor opened from another thread.
In the context of create_listener() and accept_connection() tests, they
can run concurrently and this generates some failure when the file
descriptor create_listener() is binding to is being closed from the
accept_connection() test.
In order to avoid such race condition, this patch simply removes the
part of the unit test performing an explicit and unsafe file descriptor
closure.
Fixes #759
=> vhost_rs: Fix unit test race condition

Cargo.lock, src/bin/vhost_user_fs.rs, src/main.rs, vhost_rs/src/vhost_user/mod.rs, vhost_rs/src/vhost_user/slave_fs_cache.rs, vhost_rs/src/vhost_user/slave_req_handler.rs, vhost_user_backend/src/lib.rs, vhost_user_fs/Cargo.toml, vhost_user_fs/src/filesystem.rs, vhost_user_fs/src/fs_cache_req_handler.rs, vhost_user_fs/src/fuse.rs, vhost_user_fs/src/lib.rs, vhost_user_fs/src/passthrough.rs, vhost_user_fs/src/server.rs
This attempts to let clh's `vhost_user_fs` binary work with guest's dax mode so that we can get the benefits of using dax mode.
Issue: #481 
Signed-off-by: Liu Bo <bo.liu@linux.alibaba.com>
=> Implement virtio-fs DAX in cloud-hypervisor backend

src/main.rs
The integration test test_memory_mergeable_on has been fairly unstable
for quite some time now. Because it can take some time for the VM to be
spawned and to be able to perform a correct measure of the PSS, this
commit simply increases the time before such measure is done.
This should return more accurate PSS results, which should help
stabilize the test.
Fixes #781
=> ci: Improve test_memory_mergeable_on stability

Cargo.lock, vfio/src/vfio_device.rs, vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/device.rs, vm-virtio/src/iommu.rs, vm-virtio/src/net.rs, vm-virtio/src/net_util.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/transport/mmio.rs, vm-virtio/src/transport/pci_common_config.rs, vm-virtio/src/transport/pci_device.rs, vm-virtio/src/vhost_user/blk.rs, vm-virtio/src/vhost_user/fs.rs, vm-virtio/src/vhost_user/net.rs, vm-virtio/src/vsock/device.rs, vm-virtio/src/vsock/mod.rs, vmm/Cargo.toml, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
Relying on the latest vm-memory version, including the freshly
introduced structure GuestMemoryAtomic, this patch replaces every
occurrence of Arc<ArcSwap<GuestMemoryMmap> with
GuestMemoryAtomic<GuestMemoryMmap>.
The point is to rely on the common RCU-like implementation from
vm-memory so that we don't have to do it from Cloud-Hypervisor.
Fixes #735
=> vmm: Move codebase to GuestMemoryAtomic from vm-memory

Cargo.lock, src/bin/vhost_user_blk.rs, src/bin/vhost_user_fs.rs, src/main.rs, vhost_user_backend/Cargo.toml, vhost_user_backend/src/lib.rs, vhost_user_block/src/lib.rs, vhost_user_net/src/lib.rs, vm-virtio/src/queue.rs, vm-virtio/src/vhost_user/blk.rs
This patch series implements EVENT_IDX, a virtio feature that allows reducing the number of driver <-> device notifications and thus, reducing the number of vm exits needed while processing requests. This is specially useful when actively polling the virtqueues.
=> Implement EVENT_IDX and polling for vhost_user_block

vmm/src/lib.rs
The kernel does not adhere to the ACPI specification (probably to work
around broken hardware) and rather than busy looping after requesting an
ACPI reset it will attempt to reset by other mechanisms (such as i8042
reset.)
In order to trigger a reset the devices write to an EventFd (called
reset_evt.) This is used by the VMM to identify if a reset is requested
and make the VM reboot. As the reset_evt is part of the VMM and reused
for both the old and new VM it is possible for the newly booted VM to
immediately get reset as there is an old event sitting in the EventFd.
The simplest solution is to "drain" the reset_evt EventFd on reboot to
make sure that there is no spurious events in the EventFd.
Fixes: #783
=> vmm: Workaround double reboot triggered by the kernel

vmm/src/api/openapi/cloud-hypervisor.yaml
It's missing a few knobs (readonly, vhost, wce) that should be exposed
through the rest API.
Fixes: #790
=> vmm: openapi: Update DiskConfig

vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs
This fixes a couple of typos and the `VmResize` returned error.
=> Minor fixes for the VM resize path

vhost_rs/src/vhost_user/sock_ctrl_msg.rs, vhost_user_backend/src/lib.rs
When the backend was terminating and the VMM closed the connection it was printing out an alarming and unhelpful error message.
Identify situations where the connection has been broken and don't report that error.
=> Avoid error spew during "vhost_user=true" reboots/shutdown

vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs
This patch series adds the `poll_queue` property to `DiskConfig` and, while there, it also fixes a couple of issues with the `DiskConfig` representation in `cloud-hypervisor.yaml`.
=> Add poll_queue and fix some openapi properties

vmm/src/api/openapi/cloud-hypervisor.yaml
Fix "readonly" and "wce" defaults in cloud-hypervisor.yaml to match
their respective defaults in config.rs:DiskConfig.
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> vmm: openapi: Fix "readonly" and "wce" defaults in DiskConfig

pci/src/bus.rs, pci/src/configuration.rs
The entire MMCONFIG space is broken since we are regarding it as legacy PCI port io address format. Accessing registers in the extended configuration space results to 0xffffffff in most cases since the bus number is decoded to a number above 0 by mistake. Most devices except VFIO devices with extended configuration space work fine since they are not trying to access the memory mapped MMCONFIG space and accessing PCI config space by port io. 
I can just list the extended capability by `lspci -vvv`. But I'm not sure whether the device is functional properly. 
Fixes #716
=>  pci: fix pci MMCONFIG address parsing 

pci/src/msi.rs, pci/src/msix.rs, vmm/src/interrupt.rs
We want to prevent from losing interrupts while they are masked. The
way they can be lost is due to the internals of how they are connected
through KVM. An eventfd is registered to a specific GSI, and then a
route is associated with this same GSI.
The current code adds/removes a route whenever a mask/unmask action
happens. Problem with this approach, KVM will consume the eventfd but
it won't be able to find an associated route and eventually it won't
be able to deliver the interrupt.
That's why this patch introduces a different way of masking/unmasking
the interrupts, simply by registering/unregistering the eventfd with the
GSI. This way, when the vector is masked, the eventfd is going to be
written but nothing will happen because KVM won't consume the event.
Whenever the unmask happens, …
=> msi/msi-x: Prevent from losing masked interrupts

vhost_rs/src/vhost_user/mod.rs
We import slave_fs_cache mod under vhost-user-slave feature control,
but not the self::slave_fs_cache::SlaveFsCacheReq import.
Fixes: #814
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> vhost_rs: control SlaveFsCacheReq with vhost-user-slave feature

src/bin/vhost_user_fs.rs, vhost_rs/src/vhost_user/slave_req_handler.rs, vhost_user_fs/src/descriptor_utils.rs, vm-virtio/Cargo.toml, vm-virtio/src/lib.rs, vm-virtio/src/queue.rs
This patch series enables vhost_user_fs to use EVENT_IDX and INDIRECT_DESC virtio features, making it compatible with QEMU.
=> Add support for indirect descriptors and use them in vhost_user_fs

scripts/run_integration_tests.sh
There is no reason to give some special capabilities to the Rust version
of virtiofsd since it behaves slightly differently and does not require
neither DAC_OVERRIDE nor SYS_ADMIN.
=> ci: Don't give special capabilities to Rust vhost-user-fs backend

vmm/src/acpi.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/vm.rs
In anticipation of the support for device hotplug, this commit moves the
DeviceManager object into an Arc<Mutex<>> when the DeviceManager is
being created. The reason is, we need the DeviceManager to implement the
BusDevice trait and then provide it to the IO bus, so that IO accesses
related to device hotplug can be handled correctly.
=> vmm: Move DeviceManager into an Arc<Mutex<>>

vmm/src/api/openapi/cloud-hypervisor.yaml
Update cloud-hypervisor.yaml with latest code.
Fixes: #841
Signed-off-by: liubin <liubin0329@gmail.com>
=> vmm/api: Fix vm.info response definition

vm-virtio/src/vhost_user/blk.rs
Current device configuration space offset value is 0, we need to
update that value to VHOST_USER_CONFIG_OFFSET(0x100) to follow the spec
Fixes #844
Signed-off-by: Arron Wang <arron.wang@intel.com>
=> vm-virtio: vhost_user: Fix blk device configuration space offset value

tests/integration.rs, vm-virtio/src/transport/mmio.rs
Add the missing virtio-mmio configuration fields to support shm regions which is necessary for virtio-fs. Enable the virtio-fs tests to run with virtio-mmio.
Fixes: #750
=> Support virtio-mmio with virtio-fs 

devices/src/bus.rs, pci/src/bus.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/vm.rs
By moving the weak references to the Bus structure, the whole codebase gets simplified and cleaned up through this pull request.
=> vmm: Move Weak BusDevice references to Bus structure

Cargo.lock, Cargo.toml, acpi_tables/Cargo.toml, arch/Cargo.toml, devices/Cargo.toml, pci/Cargo.toml, vfio/Cargo.toml, vhost_user_backend/Cargo.toml, vhost_user_block/Cargo.toml, vhost_user_fs/Cargo.toml, vhost_user_net/Cargo.toml, vm-allocator/Cargo.toml, vm-device/Cargo.toml, vm-virtio/Cargo.toml, vmm/Cargo.toml
linux-loader now uses the released vm-memory so we must move to that
version at the same time.
=> build: Bump linux-loader and vm-memory dependencies

Jenkinsfile
If a new build request for master comes in don't cancel the older
builds. Cancelling older builds is very useful for PRs that are being
updated but less so for a build of the master branch that has been
triggered via a merge or a periodic build.
=> build: Don't cancel older master builds

scripts/run_integration_tests.sh, src/bin/vhost_user_net.rs, src/main.rs, tests/integration.rs, vhost_user_net/src/lib.rs
Add tap option for vhost-user-net backend, it will allow to use the existing Tap interface.
Fix #742
=> vhost-user-net: Allow reuse of existing tap interface

scripts/run_integration_tests.sh
As it's not possible to use "set -e" explicitly mark the important
commands with "|| exit 1"
=> scripts: Make integration tests fail if some important commands fail

vm-virtio/src/net_util.rs
If tun_flags file does not exist, check should not be fatal.
=> net: Do not check multiqueue for new interface

src/bin/ch-remote.rs, tests/integration.rs
This is a tool for talking to the VMM over the API socket. Currently the following functionality is implemented:
```
rob@artemis:~/src/cloud-hypervisor (2020-03-06-implement-ch-remote)$ target/debug/ch-remote --help
ch-remote 
The Cloud Hypervisor Authors
Remotely control a cloud-hypervisor VMM.
USAGE:
ch-remote --api-socket <api-socket> <SUBCOMMAND>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
--api-socket <api-socket>    HTTP API socket path (UNIX domain socket).
SUBCOMMANDS:
help        Prints this message or the help of the given subcommand(s)
info        Info on the VM
pause       Pause the VM
reboot      Reboot the VM
resume      Resume the VM
shutdown    Shutdown the VM
rob@artemis:~/src/cloud-hypervisor …
```
=> Add initial version of "ch-remote"

vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/iommu.rs, vm-virtio/src/net.rs, vm-virtio/src/net_util.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/vhost_user/handler.rs, vm-virtio/src/vsock/device.rs
When a virtio device is paused an event is written to the appropriate
"pause" EventFd for the device. This will be noticed by the the device's
epoll_wait(), an atomic bool checked an if true then the thread is
parked(). When resuming the bool is reset and the thread is unpark()ed.
However the event triggering the pause is still in the EventFd so the
epoll_wait() will continue to return but because the boolean is not set
the thread will not be park()ed but instead we will busy loop around an
event that is not being consumed.
The solution is to drain the "pause" EventFd when the event is first
received and thus the epoll_wait() will only return for the pause event
once. This resolves the infinite epoll_wait() wake-ups.
Fixes: #869
=> vm-virtio: Consume pause events to prevent infinite epoll_wait calls

devices/src/bus.rs, docs/api.md, pci/src/bus.rs, tests/integration.rs, vmm/src/api/http.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/vm.rs
This pull request adds support for the removal of VFIO PCI devices while the VM is running. It does not matter if the VFIO device has been hotplugged or not, as any VFIO device can now be removed.
=> vmm: Add support for VFIO unplug

pci/src/device.rs, vfio/src/vfio_pci.rs, vm-allocator/src/system.rs, vmm/src/device_manager.rs
I noticed some bugs when playing with hotplug/hotunplug of VFIO devices. The reasons behind these issues were all related to an incomplete cleanup. This PR fills all the blanks by removing a device from every place left, in particular from the vm-allocator where the range were not removed.
=> vmm: Improve VFIO unplug

src/main.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs
Add the ability to specify the "id" associated with a device, by adding
an extra option to the parameter --device.
This new option is not mandatory, and by default, the VMM will take care
of finding a unique identifier.
If the identifier provided by the user through this new option is not
unique, an error will be thrown and the VM won't be started.
Fixes #881
=> vmm: Add id field to --device through CLI

tests/integration.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/vm.rs
Add a new id option to the VFIO hotplug command so that it matches the
VFIO coldplug semantic.
=> vmm: Add id option to VFIO hotplug

src/bin/vhost_user_fs.rs, vhost_user_backend/src/lib.rs, vhost_user_block/src/lib.rs, vm-virtio/src/queue.rs
When EVENT_IDX is enabled, users may rely on `Queue::get_used_event` to check if a notification should be delivered to the guest. But, if the window before the call to that function and the actual check is too wide, it's possible to miss an update and wrongly omit a notification. This issue only manifest when putting a lot of pressure on a vring by continuously issuing a significant number of parallel requests that complete very fast.
This patch series fixes the issue by hinting the compiler that `Queue::get_used_event` needs to be inlined, and by calling to this function directly from `Vring::needs_notification`.
=> Fix Queue EVENT_IDX check to avoid missing notifications

Cargo.lock, Cargo.toml, src/bin/vhost_user_blk.rs, src/bin/vhost_user_net.rs, src/main.rs
New result:
```
rob@artemis:~/src/cloud-hypervisor (2020-03-12-fix-help-wrapping)$ target/debug/cloud-hypervisor --help
cloud-hypervisor v0.5.0-235-g3ec040cd-dirty
The Cloud Hypervisor Authors
Launch a cloud-hypervisor VMM.
USAGE:
cloud-hypervisor [FLAGS] [OPTIONS]
FLAGS:
-h, --help       Prints help information
-v               Sets the level of debugging output
-V, --version    Prints version information
OPTIONS:
--api-socket <api-socket>            HTTP API socket path (UNIX domain socket). [default: /run/user/1000/cloud-hypervisor.66188]
--block-backend <block-backend>      vhost-user-block backend parameters "image=<image_path>,sock=<socket_path>,num_queues=<number_of_queues>,readonly=true|false,direct=true|false,poll_queue=true|false"
--cmdline <cmdline>                  Kernel …
```
=> Clean up --help wrapping

docs/hotplug.md, vmm/src/api/openapi/cloud-hypervisor.yaml
The option desired_ram is in byte, make larger the amount of memory to
add.
=> openapi: Make desired_ram int64 format

pci/src/bus.rs, vmm/src/device_manager.rs
By using a Vec to hold the list of devices on the PciBus, there's a
problem when we use unplug. Indeed, the vector of devices gets reduced
and if the unplugged device was not the last one from the list, every
other device after this one is shifted on the bus.
To solve this problem, a HashMap is used. This allows to keep track of
the exact place where each device stands on the bus.
=> pci: Fix the PciBus using HashMap instead of Vec

src/main.rs
This option was superseded by using "--net" with "vhost_user=true". This
option wasn't being parsed any more but was left over.
Fixes: #806
=> main: Remove "--vhost-user-net"

.github/workflows/build.yaml
So that we can run our builds against several toolchains (beta, stable,
nightly).
=> github: Build from a rust toolchain matrix

arch/src/x86_64/gdt.rs, arch/src/x86_64/interrupts.rs, qcow/src/vec_cache.rs, resources/Dockerfile
To the latest stable version: 1.42.0
This PR also includes 1.42 clippy warning fixes.
Fixes: #909
=> resources: Dockerfile: Update Rust toolchain

Cargo.lock, Cargo.toml
@dependabot bumped the dependency to 0.4.10 but this is no longer a
valid version so downgrade appropriately.
=> build: Fix log dependency

Cargo.lock, Cargo.toml, arch/src/lib.rs, arch/src/x86_64/gdt.rs, arch/src/x86_64/layout.rs, arch/src/x86_64/mod.rs, arch/src/x86_64/regs.rs, scripts/run_integration_tests.sh, tests/integration.rs, vmm/Cargo.toml, vmm/src/cpu.rs, vmm/src/vm.rs
Minimal changes for booting guests using the PVH boot protocol. Relies on proposed patches to RustVMM linux-loader, see issue and linked PR: https://github.com/rust-vmm/linux-loader/issues/3
I have done basic testing of booting a guest successfully using the PVH entry point. Will be focusing next on benchmarking boot times against typical 64 bit boot protocol.
I have similar questions to the ones posted in the linux-loader PR concerning the copyright messages. With regard to design decisions, I would particularly like feedback regarding the addition of the new EntryPoint struct, and the changes made to get_limit() which are documented in the comment.
Closes #131
=> Add basic support for PVH boot

Cargo.lock, vm-virtio/src/vhost_user/fs.rs
Virtiofs's dax window can be used as read/write's source (e.g. mmap a file
on virtiofs), but the dax window area is not shared with vhost-user
backend, i.e. virtiofs daemon.
To make those IO work, addresses of this kind of IO source are routed to
VMM via FS_IO requests to perform a read/write from an fd directly to the
given GPA.
This adds the support of FS_IO request to clh's vhost-user-fs master part.
Fix: #892
Signed-off-by: Liu Bo <bo.liu@linux.alibaba.com>
=> vhost-user-fs: handle FS_IO request

vmm/src/acpi.rs
The IORT table for virtio-iommu use was removed and replaced with a
purely virtio based solution. Although the table construction was
removed these structures were left behind.
=> vmm: acpi: Remove unused IORT related structures

arch/src/x86_64/mod.rs
We set it to 0xff, which is for unregistered loaders.
The kernel checks that the bootloader ID is set when e.g. loading
ramdisks, so not setting it when we get a bootparams header from the
loader will prevent the kernel from loading ramdisks.
Fixes: #918
=> arch: x86: Always set the bootloader type

vmm/src/vm.rs
I spent a few minutes trying to understand why we were unconditionally
updating the VM config memory size, even if the guest memory resizing
did not happen.
=> vm: Comment on the VM config update from memory hotplug

vm-virtio/src/queue.rs
On x86_64, a hint to the compiler is not enough, we need to issue a
MFENCE instruction. Replace the Acquire fence with a SeqCst one.
Without this, it's still possible to miss an used_event update,
leading to the omission of a notification, possibly stalling the
vring.
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> vm-virtio: queue: Use a SeqCst fence on get_used_event

docs/vhost-user-net-testing.md
Add a document to explain how to test vhost-user-net function with OpenVSwitch + DPDK as backend.
Signed-off-by: Cathy Zhang <cathy.zhang@intel.com>
To address #720
=> docs: Add document for vhost-user-net test with OVS/DPDK

vhost_user_fs/src/filesystem.rs, vhost_user_fs/src/passthrough.rs, vhost_user_fs/src/server.rs
Implement missing support for FUSE_LSEEK, which basically implies
calling to libc::lseek on the file handle. As this operation alters
the file offset, we take a write lock on the File's RwLock.
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> vhost_user_fs: Implement support for FUSE_LSEEK

vmm/src/api/openapi/cloud-hypervisor.yaml
Add hotplug_size, needed to be defined when hotplug is used.
=> openapi: Add hotplug_size for memory hotplug

src/bin/ch-remote.rs, src/main.rs, vmm/src/config.rs
=> bin: Share VFIO device syntax between cloud-hypervisor and ch-remote

Cargo.toml, scripts/run_integration_tests.sh, tests/integration.rs, vmm/Cargo.toml, vmm/src/vm.rs
This feature is stable and there is no need for this to be behind a
flag. This will also reduce the time needed to run the integration test
as we will not be running them all again under the flag.
=> build: Remove "pvh_boot" feature flag

vmm/src/device_manager.rs
According to `asm-generic/termios.h`, the `struct winsize` should be:
struct winsize {
unsigned short ws_row;
unsigned short ws_col;
unsigned short ws_xpixel;
unsigned short ws_ypixel;
};
The ioctl of TIOCGWINSZ will trigger a segfault on aarch64.
Signed-off-by: Qiu Wenbo <qiuwenbo@phytium.com.cn>
=> vmm: fix a corrupted stack caused by get_win_size

.github/workflows/build.yaml, Cargo.lock, Cargo.toml, release-notes.md
Expand the release notes and bump Cargo.toml.
We also amend the github action to upload `ch-remote` to the release assets.
=> release: v0.6.0

Cargo.lock, Cargo.toml, src/main.rs, tests/integration.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/memory_manager.rs
Unfortunately there lacks the ability to mark a virtio-pmem device readonly however we instead get "discard-on-write" behaviour where changes are not persisted after a reboot.
=> Add "discard_writes" option to --pmem

Cargo.lock, Cargo.toml, acpi_tables/Cargo.toml, arch/Cargo.toml, devices/Cargo.toml, pci/Cargo.toml, vfio/Cargo.toml, vhost_user_backend/Cargo.toml, vhost_user_block/Cargo.toml, vhost_user_fs/Cargo.toml, vhost_user_net/Cargo.toml, vm-allocator/Cargo.toml, vm-device/Cargo.toml, vm-virtio/Cargo.toml, vmm/Cargo.toml
linux-loader depends on vm-memory so must be updated at the same time.
=> build: Bump vm-memory and linux-loader dependencies

resources/Dockerfile, scripts/dev_cli.sh
* Always try to pull the latest container image.
* Add the cpio and bsdtar packages to the container image to support building initrd images.
=> Development container updates

devices/src/ioapic.rs
=> devices: ioapic: Remove unused MsiMessage structure

Cargo.lock, vhost_user_fs/src/fs_cache_req_handler.rs, vm-virtio/src/vhost_user/fs.rs
Virtio-fs daemon expects fs_slave_io() returns the number of bytes
read/written on success, but we always return 0 and make userspace think
nothing has been read/written.
Fix it by returning the actual bytes read/written. Note that This
depends on the corresponding fix in vhost crate.
[The vm-virtio/Cargo.toml and Cargo.lock updates are only for testing,
will update when vhost changes get merged]
Fixes: #949
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> vhost-user-fs: return correct result of fs_slave_io()

scripts/run_integration_tests.sh, tests/integration.rs, vm-virtio/src/device.rs, vm-virtio/src/lib.rs, vm-virtio/src/vhost_user/blk.rs, vm-virtio/src/vhost_user/fs.rs, vm-virtio/src/vhost_user/net.rs, vm-virtio/src/vhost_user/vu_common_ctrl.rs, vmm/src/device_manager.rs, vmm/src/vm.rs
This PR fills the lack of support regarding memory hotplug and vhost-user backends. The vhost-user device must explicitly notify the backend with the new regions whenever the guest memory changes.
This is important as it will let virtio-fs work with memory hotplug, which is a use case for Kata Containers.
=> Make vhost-user devices compatible with memory hotplug

src/main.rs, tests/integration.rs, vm-virtio/src/lib.rs, vm-virtio/src/mem.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
The basic idea of virtio-mem is to provide a flexible, cross-architecture memory hot plug and hot unplug solution that avoids many limitations imposed by existing technologies, architectures, and interfaces. More details can be found in https://lkml.org/lkml/2019/12/12/681.
This commit adds virtio-mem support.
Then clh can use virtio-mem support memory resize.
To enable this function, need the Linux that support virtio-mem.
https://github.com/davidhildenbrand/linux/tree/virtio-mem-rfc-v4
Add virtio-mem size to memory option, for example:
```
./cloud-hypervisor/target/release/cloud-hypervisor \
--kernel ./hypervisor-fw \
--disk path=clear-31890-kvm.img \
--cpus boot=4 \
--cmdline "memhp_default_state=online" \
--memory size=1024M,virtiomem_size=128M \
--net "tap=,mac=,ip=,mask=" \
--rng \ …
```
=> vm-virtio: Add virtio-mem support

docs/api.md, src/bin/ch-remote.rs, src/main.rs, tests/integration.rs, vmm/src/api/http.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/vm.rs
The integration test is kinda novel. It boots without a network and then adds one with the details it would have used for the boot one. This means the existing cloud init infrastructure is reused and it isn't necessary to add another special purpose network device to our tests.
=> Add network device hotplug

Cargo.lock, arch/src/x86_64/mod.rs, vmm/src/vm.rs
Commit 2adddce2 reorganized the crate for a cleaner multi architecture
(x86_64 and aarch64) support.
=> vmm: Move to the latest linux-loader

vm-virtio/src/vhost_user/fs.rs
In fs_slave_map/unmap/sync, we only made sure offset < cache_size, but
didn't validate (offset + len). We should ensure [offset, offset+len]
is within cache range as well.
And while we're at it, return libc::EINVAL instead of custom "Wrong
offset" error, as mmap(2) returns EINVAL when offset/len is invalid.
Fixes: #967 
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> vhost-user-fs: validate fs_slave_map/unmap/sync request

vmm/src/seccomp_filters.rs
On some systems, the open() system call is used by Cloud-Hypervisor,
that's why it should be part of the seccomp filters whitelist.
=> vmm: seccomp: Add missing open() syscall

Cargo.lock, devices/Cargo.toml, devices/src/ioapic.rs, devices/src/legacy/serial.rs, devices/src/lib.rs
This pull request implements the `Snapshottable` trait for both `Ioapic` and `Serial` devices. This will allow a VM containing these devices to be properly snapshotted and restored.
=> devices: Implement snapshot/restore

.gitignore
This directory contains the source code for crates that we pull in and
should be excluded.
=> .gitignore: Add build directory

net_util/src/mac.rs, src/main.rs, vmm/src/config.rs
Introduce a new helper infrastructure for parsing the command line arguments: `OptionParser` which handles the comma separated `key=value` syntax and use that for our command line options.
I added unit testing for the command line arguments and fix any issues that arise prior to the porting and then ported so that the behaviour was consistent.
This change also improves the error messages we get from command line parsing errors making then human readable!
Fixes: #367
=> Improve command line parsing

arch/src/x86_64/layout.rs, vhost_user_fs/src/server.rs, vm-virtio/src/mem.rs
Remove unnecessary parentheses from code and this will cleanup
the warning from cargo build.
=> vmm: Cleanup warning from build

src/bin/ch-remote.rs, src/main.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/lib.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
This pull request prevents the VMM from doing a full copy of the source memory's VM by adding support for CoW. This works by memory mapping the backing files with MAP_PRIVATE instead of MAP_SHARED. And this can only happen if the migrated VM wasn't using a shared backing file before.
In case the source VM was relying on a shared backing file, the code falls back onto the default behavior, which is to copy the memory content to the new VM.
=> migration: Add support to restore from Copy-on-Write backing file

arch/src/lib.rs, arch/src/x86_64/layout.rs, arch/src/x86_64/mod.rs, tests/integration.rs, vmm/src/vm.rs
Setup the required data structures in guest memory so an initrafms can be loaded by the PVH boot protocol. Remove the restriction added by https://github.com/cloud-hypervisor/cloud-hypervisor/commit/785812d976ef08d9d3ab83d7ac439ace595963b2, and modify the code as per @sboeuf suggestion in a previous discussion. 
Closes #963
=> Enable initramfs support when using PVH boot protocol

vmm/src/config.rs
This ensures that the field is filled with None when it is not specified
as part of the deserialisation step.
Fixes: #1015
=> vmm: config: Use Default::default() value for initramfs field

vmm/src/api/openapi/cloud-hypervisor.yaml
This should make it a pointer in the Go generated code so that it will
be ommitted and thus not populated with an unhelpful default value.
Fixes: #1015
=> vmm: openapi: Mark "initramfs" field nullable

src/bin/vhost_user_fs.rs, vhost_user_backend/src/lib.rs, vhost_user_block/src/lib.rs, vhost_user_net/src/lib.rs, vmm/src/seccomp_filters.rs
This pull request updates the vhost_user_backend crate (and each backend implementation accordingly) so that multiqueues on multiple threads can be supported without hitting a contention point that causes no performance benefit.
It also includes the modification of the vhost-user-net backend so that multithreaded multiqueue can be supported.
=> vhost_user_backend: Make sure multiqueue/multithread can be supported without contention

vm-virtio/src/pmem.rs, vm-virtio/src/vhost_user/fs.rs, vmm/src/device_manager.rs
virtio-pmem and vhost-user-fs both have special memory allocated for their need. This allocation is done by `DeviceManager` but in order to support device unplug the freeing of the memory  should be done inside the device itself.
=> Move mmap() region ownership to devices

vhost_user_block/src/lib.rs, vhost_user_net/src/lib.rs
Following the refactoring of the `vhost_user_backend` crate in order to support multithreaded multiqueue backends, this pull request modifies the `vhost_user_blk` backend to support it too.
=> vhost_user_blk: Add multithreaded multiqueue support

Cargo.toml, devices/Cargo.toml, devices/src/legacy/fwdebug.rs, devices/src/legacy/mod.rs, vmm/Cargo.toml, vmm/src/device_manager.rs
OVMF and other standard firmwares use I/O port 0x402 as a simple debug
port by writing ASCII characters to it. This is gated under a feature
that is not enabled by default.
=> vmm, devices: Add firmware debug port device

pci/src/bus.rs, pci/src/configuration.rs, vfio/src/vfio_pci.rs, vm-virtio/src/transport/pci_device.rs
Add support for specifying the PCI revision in the PCI configuration and
populate this with the value of 1 for virtio-pci devices.
The virtio-pci specification is slightly ambiguous only saying that
transitional (i.e. devices that support legacy and virtio 1.0) should
set this to 0. In practice it seems that software expects the revision
to be set to 1 for modern only devices.
=> pci, vfio, vm-virtio: Specify a PCI revision ID of 1 for virtio-pci

vhost_user_fs/src/filesystem.rs, vhost_user_fs/src/fuse.rs, vhost_user_fs/src/passthrough.rs, vhost_user_fs/src/server.rs
This patchset updates the vhost_user_fs FUSE personality to add the features required by the last version available at this moment, 7.31.
=> vhost_user_fs: Update FUSE API to 7.31

Cargo.lock, vm-virtio/Cargo.toml, vm-virtio/src/block.rs, vm-virtio/src/lib.rs, vm-virtio/src/queue.rs, vm-virtio/src/rng.rs, vm-virtio/src/transport/mmio.rs, vmm/src/device_manager.rs
This pull request introduces snapshot/restore support to all virtio devices using the virtio-mmio transport layer. It only contains support for virtio-rng and virtio-blk for now, but more devices will be added through follow up pull requests.
=> Add snapshot/restore support for virtio-mmio

vm-virtio/src/device.rs, vm-virtio/src/lib.rs, vm-virtio/src/transport/pci_device.rs, vm-virtio/src/vhost_user/fs.rs, vmm/src/device_manager.rs
This pull request tackles the problem of PCI BAR remapping associated with the shared memory region as it needs to be updated according to the new BAR location in guest address space.
=> Support BAR remapping for virtio-fs

docs/api.md, src/bin/ch-remote.rs, src/main.rs, tests/integration.rs, vmm/src/api/http.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/vm.rs
Adds an API method for creating vhost-user-fs devices after the VM is launched.
This is mostly just copypasta'd from `vm.add-disk`.
=> vmm: Add vm.add-fs route

vm-virtio/src/device.rs, vm-virtio/src/pmem.rs, vm-virtio/src/vhost_user/fs.rs, vmm/src/device_manager.rs, vmm/src/memory_manager.rs
This pull request fixes the previous implementation of hot-unplugging virtio device. One piece was missing, as we were not removing the userspace mappings from virtio-pmem devices.
This is a generic fix so that further work adding the support of hot-unplug to virtio-fs will be transparently benefiting from this patch.
=> Remove userspace mapping when unplugging VirtioDevice

vmm/src/memory_manager.rs
Replace alignment calculation of start address with functionally
equivalent version that does not assume that the block size is a power
of two.
Signed-off-by: Martin Xu <martin.xu@intel.com>
=> vmm: memory_manager: Support non-power-of-2 block sizes

vm-virtio/src/pmem.rs
This brings the migration support to virtio-pmem device.
Signed-off-by: Yi Sun <yi.y.sun@linux.intel.com>
=> vm-virtio: Implement Snapshottable trait for Pmem

tests/integration.rs
The newly added integration test "test_snapshot_restore" is very
unstable, which causes our CI to fail on most pull requests, which is
not acceptable. That's why we ignore this test until we can fix the
stability issue.
=> ci: Ignore test_snapshot_restore

.github/workflows/build.yaml, .github/workflows/release.yaml
The release one is always skipped for PRs which can be confusing for
e.g. dependabot.
=> gh: Separate the build and release jobs

src/main.rs, tests/integration.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/memory_manager.rs, vmm/src/seccomp_filters.rs
The new 'shared' and 'hugepages' controls aim to replace the 'file'
option in MemoryConfig. This patch also updated all related integration
tests to use the new controls (instead of providing explicit paths to
"/dev/shm" or "/dev/hugepages").
Fixes: #1011
=> vmm: Add the 'shared' and 'hugepages' controls to MemoryConfig

src/main.rs, vmm/src/config.rs
Check that if any device using vhost-user (net & disk with vhost_user=true) or virtio-fs is enabled then check shared memory is also enabled.
Fixes: #848
=> vmm: config: Validate that shared memory is enabled if using vhost-user

tests/integration.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs
If a size is specified use it (in particular this is required if the
destination is a directory) otherwise seek in the file to get the size
of the file.
Add a new check that the size is a multiple of 2MiB otherwise the kernel
will reject it.
=> vmm, tests: Make specifying a size optional for virtio-pmem

vmm/src/api/openapi/cloud-hypervisor.yaml
NetConfig/DiskConfig/PmemConfig/FsConfig were all missing the id field
in the API yaml file.
=> openapi: Add missing "id" field

src/main.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs
The Linux kernel does not support multiple virtio-vsock devices.
=> vmm, main: Support only zero or one vsock devices

devices/src/ioapic.rs, devices/src/legacy/serial.rs, vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/iommu.rs, vm-virtio/src/mem.rs, vm-virtio/src/net.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/transport/mmio.rs, vm-virtio/src/transport/pci_device.rs, vm-virtio/src/vhost_user/blk.rs, vm-virtio/src/vhost_user/fs.rs, vm-virtio/src/vhost_user/net.rs, vm-virtio/src/vsock/device.rs, vm-virtio/src/vsock/mod.rs, vmm/src/device_manager.rs
As a preparatory work to support a full tree containing the resources associated with each device, which is going to be mandatory to perform proper snapshot/restore, we need to identify each virtio device with a unique id.
=> Add identifiers to virtio devices

src/bin/vhost_user_blk.rs, src/main.rs, tests/integration.rs, vhost_user_block/src/lib.rs, vmm/src/device_manager.rs
Make the --block-backend parameters match the --disk parameters.
Fixes: #898
=> vmm, vhost_user_block: Make parameter names match --disk

vmm/src/config.rs
Migrate missing boolean controls over to the Toggle to handle all
values.
Fixes: #936
=> vmm: config: Support on/off/true/false for all booleans

vm-virtio/src/lib.rs, vm-virtio/src/mem.rs
Remove unwrap for tx.send.
Change this part to should output error and break epoll.
Fixes: #1081
=> virtio-mem: Remove unwrap for tx.send

tests/integration.rs
This test is flaky. Add some debugging to identify what the bad value
is.
See: #760
=> tests: Add some debugging to test_memory_overhead

tests/integration.rs, vm-virtio/src/vsock/device.rs, vm-virtio/src/vsock/mod.rs, vmm/src/device_manager.rs
Delete the unix socket on shutdown (we can't relisten on existing files) and add integration test to check the reboot functionality.
Fixes: #1083
=> Support rebooting with virtio-vsock

Cargo.lock, vm-device/src/lib.rs, vmm/Cargo.toml, vmm/src/device_manager.rs, vmm/src/device_tree.rs, vmm/src/lib.rs, vmm/src/vm.rs
By introducing some refactoring of the `DeviceManager`, and by adding a device tree to the DeviceManager, this pull request managed to improve the snapshot/restore mechanism to make it foolproof.
The device tree contains each device along with its resources. Based on these resources, the DeviceManager can restore each device exactly where it was located before the snapshot.
The pull request only takes care of the virtio devices and the virtio-mmio transport layer, a follow up PR will be needed to handle everything related to PCI.
=> vmm: Improve snapshot/restore reliability

vmm/src/cpu.rs, vmm/src/vm.rs
The initial solution to this problem had the right idea by resuming the vCPU and device threads upon a shutdown from a paused state. However this unfortunately has the effect of making the vCPU threads start running again which is not desirable.
Instead this version modifies the vCPU shutdown to process so that the kill state is set, pause state cleared and then the thread is unparked if necessarily with the kill state being checked immediately after the thread is resumed.
For the device threads we call `resume()` on the DeviceManager and allow those threads to cleanly terminate as part of the `drop()` driven approach.
Fixes: #816
=> Shutdown all threads if VM is paused

.github/workflows/release.yaml, scripts/run_integration_tests.sh
Stripping the release build for glibc shrinks the size considerably:
$ du -h target/release/cloud-hypervisor
8.5M    target/release/cloud-hypervisor
$ strip target/release/cloud-hypervisor
$ du -h target/release/cloud-hypervisor
5.2M    target/release/cloud-hypervisor
=> build: Strip the binaries before using/releasing them

tests/integration.rs
The current tests support giving a tap name but they only test with tap
interfaces that already exist.
Fixes: #871
=> tests: Add tests that use (non-existing) named tap

src/bin/ch-remote.rs
The ch-remote usage says:
OPTIONS:
--api-socket <api-socket>    HTTP API socket path (UNIX domain socket).
However it doesn't seem to actually accept that syntax, instead
requiring "--api-socket=". This may be a clap bug however it is resolved
by setting the number of arguments requires to exactly one. Which is
also the actual correct number.
Fixes: #1117
Fixes: #1116
=> bin: ch-remote: Ensure ch-remote supports syntax it advertises

vm-virtio/src/transport/mmio.rs
All our virtio devices support to be reset, but the virtio-mmio
transport layer was not implemented for it. This patch fixes this
lack of support.
=> vm-virtio: Add virtio reset() support to MmioDevice

vm-virtio/src/queue.rs
Upon a virtio reset, the driver expects that available and used indexes
will be reset to 0. That's why we need to reset these values from the
VMM for any virtio device that might get reset.
This issue was not detected before because the Vec<Queue> maintained
through VirtioPciDevice or MmioDevice was never updated from the virtio
device thread after the device had been actived. For this reason, upon
reset, both available and used indexes were already at the value 0.
The issue arose when trying to reset a device after the VM was restored.
That's because during the restore, each queue is assigned with the right
available and used indexes before it is passed to the device through the
activate function. And that's why upon reset, each queue was still
assigned with these indexes while it should …
=> vm-virtio: Correctly reset the virtqueues

tests/integration.rs
Continue to try and track down the instability in the numbers generated
by this test by removing the (unused) network interface. It's possible
we are getting broadcast packets into the tap device and generating a
variable size of allocations.
See: #760
=> tests: Remove network interface from test_memory_overhead

Cargo.lock, pci/Cargo.toml, pci/src/configuration.rs, pci/src/lib.rs, pci/src/msix.rs, vm-virtio/src/transport/pci_common_config.rs, vm-virtio/src/transport/pci_device.rs
This pull request enables snapshot/restore support for virtio-pci transport layer. With this code, Cloud-Hypervisor can now restore a VM with virtio-pci devices attached to it.
This takes care of updating MSI-X vectors so that they are enabled the way they were right before the snapshot has been taken.
One missing part is the `DeviceManager` implementation to make sure these virtio-pci devices are assigned with the same PCI resources compared to the source VM they have been snapshotted from. This will come as a follow up pull request.
=> Implement snapshot/restore for virtio-pci

arch/Cargo.toml, arch/src/lib.rs, arch/src/x86_64/mod.rs, tests/integration.rs, vmm/Cargo.toml
Use the ACPI feature to control whether to build the mptable. This is
necessary as the mptable and ACPI RSDP table can easily overwrite each
other leading to it failing to boot.
TEST=Compile with default features and see that --cpus boot=48 now
works, try with --no-default-features --features "pci" and observe the
--cpus boot=48 also continues to work.
Fixes: #1132
=> arch, vmm: Don't build mptable when using ACPI

pci/src/bus.rs, vm-virtio/src/transport/pci_device.rs, vmm/src/device_manager.rs, vmm/src/device_tree.rs
This pull request takes care of storing and restoring important resource information such as the PCI `b/d/f` or the addresses of the PCI BARs in order to restore every `virtio-pci` device at the right place on the PCI bus, and at the right location in the guest address space.
It also takes care of updating the device tree upon PCI BAR reprogramming related to a virtio-pci device.
This means with this pull request, Cloud-Hypervisor can now fully support being snapshot and restored, no matter how complex the situation will be (different location in guest address space will be handled).
=> Store and restore resources related to virtio-pci devices

Cargo.lock, vmm/src/vm.rs
The ch branch has been rebased to incorporate the latest upstream code
requiring a small change to the unit tests.
=> build, vmm: Update to latest kvm-ioctls

tests/integration.rs
Now that snapshot/restore feature is stable for both virtio-mmio and
virtio-pci devices, we re-enable the integration test for validating
snapshot/restore does not get broken.
=> ci: Enable snapshot/restore integration test

Cargo.lock, src/bin/vhost_user_fs.rs, vhost_user_backend/src/lib.rs, vhost_user_block/src/lib.rs, vhost_user_fs/Cargo.toml, vhost_user_fs/src/lib.rs, vhost_user_fs/src/passthrough.rs, vhost_user_fs/src/sandbox.rs, vhost_user_net/src/lib.rs
This patch series implements the ability for vhost_user_fs to sandbox itself, by switching to new mount, pid and network namespaces. Future changes can further extend the hardening by dropping capabilities and/or using seccomp filters.
This PR requires an unmerged PR in vhost (https://github.com/cloud-hypervisor/vhost/pull/19), but I thought it was still worth creating it now so it can be reviewed in advance.
=> vhost_user_fs: Implement support for optional sandboxing

vmm/src/seccomp_filters.rs
The clock_nanosleep system call needs to be whitelisted since the commit
12e00c0f4539879be4622da93f941035c14561ae introduced the use of a sleep()
function. Without this patch, we can see an error when the VM is paused
or killed.
=> vmm: Update seccomp filters with clock_nanosleep

Cargo.lock, Cargo.toml, net_util/src/tap.rs, src/main.rs, tests/integration.rs, vhost_user_net/src/lib.rs, vm-virtio/src/net.rs, vm-virtio/src/net_util.rs, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/seccomp_filters.rs
Provide options to let the user choose their host MAC address. If the user does not provide one we generate one and store it in the config.
Fixes: #1177
=> Support setting host MAC address

vhost_user_fs/src/seccomp.rs
Add missing syscall used by the musl build.
TEST=scripts/dev_cli.sh tests --libc musl --integration -- vhost_user_fs_daemon
=> vhost_user_fs: Fix seccomp filter for musl

vhost_user_block/src/lib.rs
As the parsing code is reused the flush feature is already implemented
and ready to be used.
Fixes: #1197
=> vhost_user_block: Implement VIRTIO_BLK_F_FLUSH

vhost_user_net/src/lib.rs, vm-virtio/src/net.rs
According to the virtio spec the guest should always be interrupted when
"used" descriptors are returned from the device to the driver. However
this was not the case for the TX queue in either the virtio-net
implementation or the vhost-user-net implementation.
This would have meant that the guest could end up with a reduced TX
throughput as it would not know that the packets had been dispatched via
the VMM.
=> vhost_user_net, vm-virtio: Interrupt guest when TX queue is updated

tests/integration.rs, vhost_user_backend/src/lib.rs, vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/iommu.rs, vm-virtio/src/mem.rs, vm-virtio/src/net.rs, vm-virtio/src/net_util.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/vhost_user/handler.rs, vm-virtio/src/vsock/device.rs, vm-virtio/src/vsock/unix/muxer.rs, vmm/src/lib.rs
This patch fixes file descriptor leak related to epoll::create() from
various virtio devices.
Fixes: #1124
=> vhost_user_backend, vm-virtio, vmm: Close leaked file descriptors from 'epoll::create()'

vm-virtio/src/block.rs
The implementation of this virtio block (and vhost-user block) command
called a function that was a no-op on Linux. Use the same function as
virtio-pmem to ensure that data is not lost when the guest asks for it
to be flused to disk.
Fixes: #399
=> vm-virtio: block: Ensure that VIRTIO_BLK_T_FLUSH requests actually sync

Cargo.lock, Cargo.toml, vm-virtio/Cargo.toml
Consistently use the crates.io 0.1.0 version based on Linux 5.0.0
Fixes: #1192
=> build: Use same virtio-bindings version

src/bin/vhost_user_fs.rs, vhost_user_backend/src/lib.rs, vhost_user_block/src/lib.rs, vm-virtio/src/block.rs, vm-virtio/src/queue.rs
Move the method that is used to decide whether the guest should be
signalled into the Queue implementation from vm-virtio. This removes
duplicated code between vhost_user_backend and the vm-virtio block
implementation.
=> vm-virtio, vhost_user_{fs,block,backend}: Move EVENT_IDX handling

.github/workflows/cross-build.yaml, arch/src/aarch64/mod.rs, arch/src/lib.rs, arch/src/x86_64/mod.rs, net_util/src/tap.rs, resources/Dockerfile, scripts/dev_cli.sh, vhost_user_fs/src/seccomp.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/memory_manager.rs, vmm/src/seccomp_filters.rs, vmm/src/vm.rs
This PR is splitted from https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1126. 
It prepares for upcoming PR's to enable AArch64. All building issues were fixed, but no functionality was introduced. A lot of `#[cfg(target_arch = "xxx")]` were used in source files to separate architecture specific code. Some utility files were updated as well.
For X86, the logic of code was not changed at all. Nothing should be broken.
For ARM, the architecture specific part is still empty. Some new added ARM-specific code may looks weird, because they were added temporarily to workaround lint warnings. But they will be replaced later by other commits with real functionality.
A workflow for "Checks" was setup to cross-build for AArch64. But now the cross-build fails, which is related to Serde in …
=> AArch64 initial build

devices/src/gic.rs, devices/src/interrupt_controller.rs, devices/src/ioapic.rs, devices/src/lib.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/interrupt.rs
The PR refactors IOAPIC to work with other architectures.
2 commits are included:
1. Introduces trait InterruptController to provide architecture agnostic functions.
2. Implement InterruptController for AArch64.
This PR is split from https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1126.
=> Refactor IOAPIC

src/main.rs, vmm/src/seccomp_filters.rs
This ensures that all created filed are only read/write for the current user.
Fixes: #1240
=> main: Set the umask to 0077

vmm/src/api/http.rs
Instead of responding only headers with error code, we now return
complete error responses to HTTP requests with errors (e.g. undefined
endpoints and InternalSeverError).
Fixes: #472
=> vmm: api: Return complete error responses in handle_http_request()

arch/src/aarch64/mod.rs, arch/src/lib.rs, arch/src/x86_64/mod.rs, vmm/src/cpu.rs, vmm/src/vm.rs
Splits from https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1126.
To enable CH on AArch64, we need to change the process of creating and activating VCPU's. 
To make it easy to review, this PR contains the modifications for X86 only, ARM code will be added later.
Between X86 and AArch64, there is some differences in booting a VM:
- X86_64 can setup IOAPIC before creating any VCPU.
- AArch64 have to create VCPU's before creating GIC.
The old booting process is:
1. load_kernel()
load kernel binary
configure system
2. activate_vcpus()
create & start VCPU's
So we need to separate "activate_vcpus()" into "create_vcpus()" and "activate_vcpus()" (to start VCPUS's only). We also separate load_kernel() into "load_kernel()" and "configure system()" (GIC setup and FDT generating is included …
=> vmm: Change booting process to cover AArch64 requirements

tests/integration.rs
Reverts cloud-hypervisor/cloud-hypervisor#1271
Fixes: #1276
=> Revert "tests: Extend test_*_reboot with checks on fd leaking"

.github/workflows/cross-build.yaml, arch/src/aarch64/fdt.rs, arch/src/aarch64/gic.rs, arch/src/aarch64/gicv2.rs, arch/src/aarch64/gicv3.rs, arch/src/aarch64/layout.rs, arch/src/aarch64/mod.rs, arch/src/aarch64/regs.rs, arch/src/lib.rs
This PR adds the AArch64 arch-related files for the Cloud-Hypervisor AArch64 enabling, including:
- AArch64 memory layout 
- Ported Firecracker AArch64 files with some modifications
- libfdt dependancy for cross-building in the Github action
The commits in this PR are splited from #1126.
Signed-off-by: Henry Wang <<Henry.Wang@arm.com>>
=> AArch64: Adding AArch64 arch-related files

docs/fs.md, src/bin/vhost_user_fs.rs, src/main.rs, tests/integration.rs, vm-virtio/src/vhost_user/blk.rs, vm-virtio/src/vhost_user/net.rs, vm-virtio/src/vhost_user/vu_common_ctrl.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs
This patch unifies the inconsistent uses of 'socket' and 'sock' from our
CLI/API parameters.
Fixes: #1091
=> tests,vm-virtio,vmm: Use 'socket' for all CLI/API parameters

net_util/src/tap.rs, scripts/run_integration_tests.sh, tests/integration.rs, vhost_user_net/src/lib.rs, vm-virtio/src/net.rs, vm-virtio/src/net_util.rs, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/seccomp_filters.rs
There were two places that prevented CH from running without CAP_NET_ADMIN. Always attempting to enable the interface if it was already up and always setting the host MAC address by autogenerating.
It's worth noting that even if there is an existing tap interface if the user tries to configure the IP/mask/host MAC it will continue to fail as those require privileged ioctl calls. The basis of using an existing tap device has always been on the assumption that the user has already configured it appropriately.
Fixes: #1274
=> Fix issues preventing Cloud Hypervisor running without CAP_NET_ADMIN

docs/api.md, vmm/src/lib.rs
The action of "vm.delete" should not report errors on non-booted
VMs. This patch also revised the "docs/api.md" to reflect the right
'Prerequisites' of different API actions, e.g. on "vm.delete" and
"vm.boot".
Fixes: #1110
=> vmm: api: Allow to delete non-booted VMs

devices/src/legacy/mod.rs, devices/src/legacy/rtc_pl031.rs
This commit adds the implementation (most of code are ported from Firecracker, with modifications to pass build and unit tests) for the AArch64 PL031 Real Time Clock (RTC) that provides a long time base counter. This is achieved by generating an interrupt signal after counting a programmed number of cycles of a real-time clock input. The AArch64 guest VM of the cloud-hypervisor will use this RTC to sync the time in itself.
This PR is splited from #1126. 
=> device: Add AArch64 RTC PL031 implementation

Cargo.lock, Cargo.toml
Currently released vm-memory uses aligned and volatile copying for all
data. The version in the fork only uses the assured (and slower) path
for data upto the natural data width.
Fixes: #1258
=> build: Use fork of vm-memory with less performance impact

arch/src/x86_64/layout.rs, arch/src/x86_64/regs.rs
For correctness, when the CPUID supports the LA57 feature, the VMM sets
the CR4.LA57 register, which means a fifth level of page table might be
needed. Even if it's not needed because the kernel should not use
addresses over 1GiB, it's better to define this new level anyway.
This patch only applies to the Linux boot codepath, which means it
affects both vmlinux without PVH and bzImage binaries. The bzImage
does not need this since the page tables and CR4 registers are set in
the decompression code from the kernel.
And for vmlinux with PVH, if we follow the PVH specification, the kernel
must be responsible for setting things up, but the implementation is
missing. This means for now that PVH does not support LA57 with 5 levels
of paging.
Signed-off-by: Sebastien Boeuf …
=> arch: x86_64: Add 5th level of paging when needed

net_util/src/tap.rs
This cleans out the test compilation warning
```
warning: use of deprecated item 'tap::tests::pnet::datalink::NetworkInterface::mac_address': Please use NetworkInterface's field 'mac' instead.
--> net_util/src/tap.rs:530:24
|
530 |             (interface.mac_address(), tx, rx)
|                        ^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
```
Signed-off-by: Anatol Belski <ab@php.net>
=> net_util: Fix deprecated `mac_address()` call in test

arch/src/aarch64/layout.rs, arch/src/aarch64/mod.rs, docs/arm64.md, scripts/dev_cli.sh, vm-allocator/Cargo.toml, vm-allocator/src/gsi.rs, vm-allocator/src/lib.rs, vm-allocator/src/system.rs, vmm/Cargo.toml, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
This pull request contains the code to enable the basic functionalities of Cloud-hypervisor on AArch64.
Summary of the major changes:
- Enabled vm-allocator, device manager, memory manager and vcpu manager for AArch64.
- Enabled Virtio devices with MMIO transport option.
- Configured VM: load kernel, setup GIC setup and generate FDT.
- Exit VMM when guest shutdown on AArch64.
- Added a guide for testing on Arm64.
What was tested:
- Booting a VM (Ubuntu 18.04) with up to 4 VCPUs.
- Booting a VM with up to 256 GiB memory.
- Serial I/O.
- Virtio devices with MMIO transport option: virtio-blk and virtio-console devices were tested.
=> Enable AArch64

Cargo.lock
An update to the Cargo.lock file was missing from a previous commit.
=> build: Update Cargo.lock

vmm/src/vm.rs
We should break out from the loop after getting the HLT exit, otherwise
the VM hangs forever.
=> vmm: vm: fix test_vm test case

.github/workflows/build.yaml
Rust nightly builds are currently failing due to a crate outside of
our control not meeting the latest cargo requirements.
See XAMPPRocky/remove_dir_all#19
=> build: Temporarily disable nightly builds

pci/src/vfio.rs
cloud-hypervisor: 763.978581807s: ERROR:pci/src/vfio.rs:651 -- failed to remove all guest memory regions from iommu table
when poweroff a vm with vfio device, clh will finally remove all guest memory region from iommu table
with the method unset_dma_map, not method setup_dma_map.
Signed-off-by: LiYa'nan <oliverliyn@gmail.com>
=> vfio: fix for bug as below: failed to remove all guest memory regions from iommu table

vmm/src/device_tree.rs
Its test case calls remove unconditionally. Instead of making the test
code call remove conditionally, removing the pci_support dependency
simplifies things -- that function is just a wrapper around HashMap's
remove function anyway.
=> vmm: device_tree: make available remove function unconditionally

arch/src/aarch64/fdt.rs, docs/arm64.md, pci/src/vfio.rs, scripts/run_unit_tests.sh, src/main.rs, vm-allocator/src/system.rs
Currently, not every feature of the cloud-hypervisor is enabled on AArch64, which means that on AArch64 machines, the `run_unit_tests.sh` needs to be tailored and some unit test cases should be run on x86_64 only.
Also this commit fixes the typo and unifies `Arm64` and `AArch64` in the AArch64 document. As asked in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1126#discussion_r438809410, @michael2012z 
=> unit tests: Fix unit tests and docs for AArch64

vm-virtio/src/vsock/csm/connection.rs, vm-virtio/src/vsock/csm/mod.rs, vm-virtio/src/vsock/csm/txbuf.rs, vm-virtio/src/vsock/unix/muxer.rs, vm-virtio/src/vsock/unix/muxer_rxq.rs
This PR fixes #1001 backporting Firecracker's patches included in https://github.com/firecracker-microvm/firecracker/pull/1910
I tested with iperf-vsock for more than 1000 seconds without stalls. Before this patch, the stall happened in a very few seconds especially with reverse test:
```shell
guest$ ./iperf3 --vsock -s
host$ ./iperf3 --vsock -c /tmp/vm4.vsock -t 10000 -R
```
=> Backport FC vsock patches to address stalling problems

arch/src/x86_64/mod.rs, src/main.rs, tests/integration.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/cpu.rs
Add support for specifying the CPU topology in terms of threads per core, cores per die, dies per package and total packages/sockets. This is exposed through CPUID leaves.
Although the Linux kernel does read the dies per package field it doesn't expose it to the user in `/proc/cpuinfo`. In practice the user will almost always want to set this to 1.
Fixes: #1284
=> Add basic CPU topology support

Cargo.toml
This results in ~20% reduction of stripped binary size:
Default release build: 8.7M -> stripped: 5.3M
LTO release build: 5.9M -> stripped: 4.3M
=> build: Enable LTO for release build

vmm/src/cpu.rs
The aarch64 build has no use for this structure at the moment.
=> vmm: cpu: Import CpuTopology conditionally on x86_64 only

arch/src/aarch64/gic.rs, arch/src/aarch64/mod.rs, arch/src/aarch64/regs.rs, hypervisor/src/hypervisor.rs, hypervisor/src/kvm/mod.rs, vmm/src/cpu.rs
This commit fixes some warning introduced in the previous
hyperviosr crate PR.Removed some unused variables from arch/aarch64
module.
=> hypervisor, arch: Fix warnings introduced in hypervisor crate

tests/integration.rs, vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/iommu.rs, vm-virtio/src/mem.rs, vm-virtio/src/net.rs, vm-virtio/src/net_util.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/vhost_user/handler.rs, vm-virtio/src/vsock/device.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/vm.rs
In order to stay symmetrical between snapshot and restore, and because the VM must be paused before we can perform a snapshot, the VM is now restored in a paused state. This means after the restore, we must resume it to get it in a running state.
=> vmm: Restore a VM in a paused state

tests/integration.rs, vmm/src/cpu.rs
When a request is made to increase the number of vCPUs in the VM attempt
to reuse any previously removed (and hence inactive) vCPUs before
creating new ones.
This ensures that the APIC ID is not reused for a different KVM vCPU
(which is not allowed) and that the APIC IDs are also sequential.
The two key changes to support this are:
* Clearing the "kill" bit on the old vCPU state so that it does not
immediately exit upon thread recreation.
* Using the length of the vcpus vector (the number of allocated vcpus)
rather than the number of active vCPUs (.present_vcpus()) to determine
how many should be created.
This change also introduced some new info!() debugging on the vCPU
creation/removal path to aid further development in the future.
TEST=Expanded test_cpu_hotplug test.
Fixes: #1338
=> vmm: cpu: Reuse already allocated vCPUs if available     

hypervisor/src/kvm/mod.rs, hypervisor/src/vm.rs, vmm/src/lib.rs, vmm/src/migration.rs, vmm/src/seccomp_filters.rs, vmm/src/vm.rs
The KVM clock can be used as a clock source from the guest, that's why it's important to store it when the VM is being paused and restore it when the VM is being resumed.
Because the snapshot/restore operations expect the VM to go through pause/resume states, this use case is covered by this PR.
=> vmm: Get and set KVM clock during pause/resume operations

Cargo.lock, hypervisor/src/cpu.rs, hypervisor/src/kvm/mod.rs, vmm/src/cpu.rs, vmm/src/seccomp_filters.rs
Extend the Vcpu trait to be able to notify a guest that it is being paused. This is useful to avoid watchdogs running in the guest to complain when the guest is resumed after a certain period of time.
=> vmm: Add support for notifying guest is being paused

vmm/src/interrupt.rs
Microsoft Hypervisor will use more or less the same architecture like KVM for interrupt handling, yet the data structures and function calls may be different.
The first patch makes clear MsiInterruptGroup is KVM specific. The second patch is a minor clearnup patch I come up with while reading the code.
=> Patches for interrupt.rs

vhost_user_fs/src/seccomp.rs
This corresponds to QEMU's 63659fe74e76f5c52854 commit.
the setattr code uses both fchmod and fchmodat in different cases,
however we only had fchmodat in the whitelist.
Signed-off-by: Dr. David Alan Gilbert <dgilbert@redhat.com>
=> vhost_user_fs: Allow fchmod in seccomp

src/bin/ch-remote.rs, tests/integration.rs, vhost_user_net/src/lib.rs, vm-virtio/src/block.rs, vm-virtio/src/device.rs, vm-virtio/src/net.rs, vm-virtio/src/net_util.rs, vmm/src/api/http.rs, vmm/src/api/http_endpoint.rs, vmm/src/api/mod.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/vm.rs
Add counters for key virtio devices (block and net) and expose them through a newly added HTTP API entry point.
See: #1287
=> Add virtio device counters

vm-virtio/src/block.rs, vm-virtio/src/console.rs, vm-virtio/src/iommu.rs, vm-virtio/src/mem.rs, vm-virtio/src/net.rs, vm-virtio/src/net_util.rs, vm-virtio/src/pmem.rs, vm-virtio/src/rng.rs, vm-virtio/src/vhost_user/handler.rs, vm-virtio/src/vsock/device.rs, vmm/src/cpu.rs, vmm/src/vm.rs
We need consistency between pause/resume and snapshot/restore operations. The symmetrical behavior of pausing/snapshotting and restoring/resuming has been introduced recently, and we must now ensure that no matter if we're using pause/resume or snapshot/restore features, the resulting VM should be running in the exact same way.
That's why the vCPU state is now stored upon VM pausing. The snapshot operation being a simple serialization of the previously saved state. The same way, the vCPU state is now restored upon VM resuming. The restore operation being a simple deserialization of the state.
It's interesting to note that this patch ensures time consistency from a guest perspective, no matter which clocksource is being used. From a previous patch, the KVM clock was saved/restored upon VM …
=> vmm: Save and restore vCPU states during pause/resume operations

hypervisor/src/arch/mod.rs, hypervisor/src/arch/x86/mod.rs, hypervisor/src/cpu.rs, hypervisor/src/hypervisor.rs, hypervisor/src/kvm/aarch64/mod.rs, hypervisor/src/kvm/mod.rs, hypervisor/src/kvm/x86_64/mod.rs, hypervisor/src/lib.rs, hypervisor/src/vm.rs
Initially the licensing was just Apache-2.0. This patch changes
the licensing to dual license Apache-2.0 AND BSD-3-Clause
=> hypervisor: Update license to Apache-2.0 AND BSD-3-Clause

.github/workflows/cross-build.yaml, Jenkinsfile, arch/src/aarch64/fdt.rs, arch/src/aarch64/gic.rs, arch/src/aarch64/regs.rs, scripts/dev_cli.sh, scripts/run_unit_tests.sh
This commit enables the AArch64 Jenkins CI with build and running unit tests for the GNU toolchain.
=> tests: Enable AArch64 Jenkins CI with unit tests

scripts/dev_cli.sh
`./scripts/dev_cli.sh shell`
drops the caller into a privileged, root shell.
=> dev_cli: Add a shell command

arch/src/x86_64/layout.rs, arch/src/x86_64/mod.rs, arch/src/x86_64/smbios.rs
Taken from crosvm: 44336b913126d73f9f8d6854f57aac92b5db809e and adapted
for Cloud Hypervisor.
This is basic and incomplete support but Linux correctly finds the DMI
data based on this:
root@clr-c6ed47bc1c9d473d9a3a8bddc50ee4cb ~ # dmesg | grep -i dmi
[    0.000000] DMI: Cloud Hypervisor cloud-hypervisor, BIOS 0
root@clr-c6ed47bc1c9d473d9a3a8bddc50ee4cb ~ # dmesg | grep -i smbio
[    0.000000] SMBIOS 3.2.0 present.
=> arch: x86_64: Add basic SMBIOS support

vmm/src/device_manager.rs, vmm/src/interrupt.rs
The core logic of the interrupt module is applicable to any hypervisor implementation.
This patch series splits KVM specific logic from the core logic.
=> Generify interrupt module

hypervisor/src/cpu.rs, hypervisor/src/hypervisor.rs, hypervisor/src/kvm/mod.rs, hypervisor/src/kvm/x86_64/mod.rs, tests/integration.rs, vmm/src/seccomp_filters.rs
This pull request, mainly by saving all supported MSRs, fixes all the remaining issues related to vCPU snapshot/restore. Thanks to this pull request, we can now correctly snapshot and restore a VM with one or more vCPUs.
Fixes #1176
=> vmm: Stabilize vCPU snapshot/restore

arch/src/x86_64/smbios.rs
The other types use a symbolic constant so do the same for consistency.
=> arch: x86_64: Use symbolic constant for end of table

README.md
0.2.6 release doesn't work for me while 0.2.8 does. Since the CI is using 0.2.8 anyway, update README to reflect reality.
=> README: update hypervisor-fw release

resources/Dockerfile
As requested in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1395#issuecomment-651728247. This update of Dockerfile will add support to the AArch64 integration tests and musl building, including:
1. Installation of the missing `setcap` binary on AArch64. On AArch64, `setcap` binary should be installed via `libcap2-bin`.
This binary is needed in the integration test.
2. Related support for the cloud-hypervisor binary building by musl toolchain. Details can be found in https://github.com/rust-lang/rust/issues/73493#issuecomment-651916925
Test building with musl using the updated container:
```
~/cloud-hypervisor-dev/cloud-hypervisor-build# ./scripts/dev_cli.sh build --release --libc musl
...
Successfully tagged cloudhypervisor/dev:v4
...
Compiling cloud-hypervisor v0.8.0 …
```
=> resources: Dockerfile: Update Dockerfile for AArch64

Cargo.lock, hypervisor/src/kvm/mod.rs
ch branch is now rebased on latest upstream master
=> build: Bump kvm-ioctls dependency after rebase

arch/src/x86_64/regs.rs
This makes setup_msrs hypervisor agnostic.
There is more we could do in this area --  I notice is that the initial state of MSRs isn't really tied to KVM. It would be more appropriate to have `boot_msr_entries` in the `vmm` crate. But then that creates cyclic dependency between `arch` and `vmm`.
Another way to solve this would be to make `configure_vcpu` accept a list of MSRs. The downside is that it makes Aarch64 and x86 have different function signatures for `configure_vcpu`.
Neither of the two solutions looks satisfactory to me. Let me know what you think.
=> arch: drop one level of indirection for boot_msr_entries

README.md, docs/api.md, docs/custom-image.md, docs/debug-port.md, docs/fs.md, docs/hotplug.md, docs/iommu.md, docs/networking.md, docs/vfio.md, docs/vhost-user-blk-testing.md, docs/vhost-user-net-testing.md
Now that the project relies on Ubuntu images, the documentation related
to the creation of a custom image has been updated. It's important to
note this procedure could be applied to any other distribution, given
that the package manager's commands would be slightly different.
=> docs: Update custom image instructions

hypervisor/src/cpu.rs, hypervisor/src/kvm/mod.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/interrupt.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
Many of our VMM structures fields are now pointing to the abstracted `hypervisor` crate traits, so we should rename them in a more generic, hypervisor agnostic way.
The PR also makes the code slightly more readable by no longer using the KVM specific `fd` name for either vcpu or vm.
=> vmm: KVM specific variables and fields renaming

Cargo.lock, Cargo.toml
There are several dependencies that need updating so update them
manually rather than relying on dependabot. This will reduce the load on
the CI.
=> build: Bulk upgrade dependencies

hypervisor/src/cpu.rs, hypervisor/src/kvm/mod.rs, hypervisor/src/lib.rs, vmm/src/cpu.rs, vmm/src/vm.rs
In order to move the hypervisor specific parts of the VM exit handling
path, we're defining a generic, hypervisor agnostic VM exit enum.
This is what the hypervisor's Vcpu run() call should return when the VM
exit can not be completely handled through the hypervisor specific bits.
For KVM based hypervisors, this means directly forwarding the IO related
exits back to the VMM itself. For other hypervisors that e.g. rely on the
VMM to decode and emulate instructions, this means the decoding itself
would happen in the hypervisor crate exclusively, and the rest of the VM
exit handling would be handled through the VMM device model implementation.
Fix test_vm unit test by using the new abstraction and dropping some
dead code.
Signed-off-by: Wei …
=> hypervisor: Define a VM-Exit abstraction

vmm/src/seccomp_filters.rs
Echoing comment https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1407#discussion_r448812583
Refactored the construction of KVM IOCTL rules for Seccomp.
Separating the rules by architecture can reduce the risk of bugs and attacks.
=> vmm: Divide Seccomp KVM IOCTL rules by architecture

Cargo.lock, Cargo.toml, option_parser/Cargo.toml, option_parser/src/lib.rs, vhost_user_block/Cargo.toml, vhost_user_block/src/lib.rs, vhost_user_net/Cargo.toml, vhost_user_net/src/lib.rs, vmm/Cargo.toml, vmm/src/config.rs, vmm/src/lib.rs
Remove the vmm dependency from vhost_user_block and vhost_user_net where
it was existing to use config::OptionParser. By moving the OptionParser
to its own crate at the top-level we can remove the very heavy
dependency that these vhost-user backends had.
=> vhost_user_net, vhost_user_block, option_parser: Remove vmm dependency

tests/integration.rs
Check if increasing the time after the VM is spawned help with getting
more stable numbers for the base PSS.
=> ci: Increase time to stabilize memory measurement

Cargo.lock, net_util/Cargo.toml, net_util/src/lib.rs, net_util/src/open_tap.rs, net_util/src/queue_pair.rs, scripts/run_cargo_tests.sh, vhost_user_net/Cargo.toml, vhost_user_net/src/lib.rs, virtio-devices/src/lib.rs, virtio-devices/src/net.rs, virtio-devices/src/net_util.rs
Move code into the common, shared, pre-existing `net_util` crate to remove the dependency from the vhost-user-net crate on virtio-devices. This simplifies the dependency chain and means that the backend doe not depend on e.g. pci or qcow crates.
=> Remove vhost-user-net dependency on virtio-devices

tests/integration.rs
Try and enable virtio-mem testing when using the virtio-mmio transport.
=> tests: Enable virtio-mem testing with virtio-mmio

tests/integration.rs
This test makes use of MQ support in virtio-block so it is advisable to
test with virtio-mmio.
=> tests: Enable test_virtio_blk with virtio-mmio transport

tests/integration.rs
Ensure that multiple network interfaces function correctly when using
virtio-mmio.
=> tests: Enable test_multiple_network_interfaces with virtio-mmio

tests/integration.rs
As compiling without acpi (implied by mmio) means that the VM will
terminate on i8042 reset we cannot test the reboot.
=> tests: Enable virtio-vsock testing with virtio-mmio transport

tests/integration.rs
This is primarily useful to ensure that virtio-console support is
covered.
=> tests: Enable virtio-mmio tests for virtio-console

arch/src/aarch64/mod.rs, pci/src/vfio.rs
The type is now hypervisor::Vm. Switch from KVM specific name vm_fd to a
generic name just like 8186a8eee68f ("vmm: interrupt: Rename vm_fd").
=> arch, pci: rename vm_fd to vm

arch/Cargo.toml, arch/src/aarch64/fdt.rs, arch/src/aarch64/gic.rs, arch/src/aarch64/gicv2.rs, arch/src/aarch64/gicv3.rs, arch/src/aarch64/gicv3_its.rs, arch/src/aarch64/mod.rs, devices/src/ioapic.rs, docs/arm64.md, hypervisor/src/kvm/mod.rs, hypervisor/src/vm.rs, pci/src/bus.rs, pci/src/msi.rs, pci/src/msix.rs, pci/src/vfio.rs, virtio-devices/src/transport/pci_device.rs, vm-device/src/interrupt/mod.rs, vmm/src/device_manager.rs, vmm/src/interrupt.rs, vmm/src/vm.rs
The PR includes:
-  Creating virtual GICv3-ITS
- Updating FDT to include ITS and PCI node
- Setting `devid` in `kvm_irq_routing_msi` on AArch64
- Documentation
In current implementation, PCI requires GICv3-ITS device on host for MSI handling. On AArch64, GICv2M and GICv3-ITS handles MSI. GICv2M is old, its capability is quite limited, and it's not commonly seen nowadays. While GICv3-ITS is dorminant, it is common in modern AArch64 servers. So we implemented GICv3-ITS only.
=> Enable PCI on AArch64

Jenkinsfile, scripts/dev_cli.sh
This commit adds a Jenkins stage to enable AArch64 CI with musl toolchain.
=> tests: Enable AArch64 CI with musl toolchain

Cargo.toml
Also rearrange the workspace members so they are in alphabetical order.
=> build: Add missing "hypervisor" crate from workspace

Cargo.lock, arch/Cargo.toml, arch/src/lib.rs, arch/src/x86_64/mod.rs, hypervisor/src/kvm/mod.rs, hypervisor/src/kvm/x86_64/mod.rs, src/main.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/cpu.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
This pull request brings the support for SGX capable hosts to Cloud-Hypervisor. An SGX application can be run in a Cloud-Hypervisor VM, leveraging the hardware support of SGX.
Fixes #1311
=> vmm: Add Intel SGX support

docs/api.md
With recent changes (#1030 #1084), the '/vm.remove-device' API is no
longer restricted to remove VFIO PCI devices. It now supports (almost)
all hotpluggable devices, e.g. disk/net/pmem/fs/vsock.
=> docs: Update API documentation about '/vm.remove-device'

arch/src/aarch64/gic.rs, docs/arm64.md
Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1469
Updated build instructions to use `kvm` feature.
Fixed a build warning for unused `log `crate.
=> Update docs and fix a build warning for AArch64

virtio-devices/src/balloon.rs, virtio-devices/src/block.rs, virtio-devices/src/console.rs, virtio-devices/src/device.rs, virtio-devices/src/iommu.rs, virtio-devices/src/mem.rs, virtio-devices/src/net.rs, virtio-devices/src/pmem.rs, virtio-devices/src/rng.rs, virtio-devices/src/vhost_user/blk.rs, virtio-devices/src/vhost_user/fs.rs, virtio-devices/src/vhost_user/net.rs, virtio-devices/src/vsock/device.rs
Clean up the `read_config()` and `write_config()` in our virtio devices:
* Remove `write_config()` for devices that don't support it
* Use helper function for `read_config()`
* For the block devices check the offset matches the only mutable field.
Fixes: #1217
=> Cleanup virtio device configuration

vmm/src/device_manager.rs
Hyper-V may have different field names. Use make_user_memory_region
instead.
=> device_manager: avoid manipulating MemoryRegion fields directly

docs/fuzzing.md, fuzz/.gitignore, fuzz/Cargo.toml, fuzz/fuzz_targets/qcow.rs
Add the basic infrastructure for fuzzing along with a qcow fuzzer ported
from crosvm and adapted to our code.
=> fuzz: Add fuzzing infrastructure and QCOW fuzzer

hypervisor/src/kvm/mod.rs, hypervisor/src/vm.rs, vmm/src/device_manager.rs
Hyper-V doesn't have VFIO support yet.
~~I've cobbled together a patch that puts VFIO under kvm feature guard. I'm not sure if it is better to introduce a separate `vfio` feature guard.~~
~~Would love to hear upstream's opinions on this.~~
Patches updated. Only create_kvm_device's internal is put under "kvm" feature.
=> Put KVM specific VFIO code under "kvm" feature guard

hypervisor/src/kvm/mod.rs, hypervisor/src/vm.rs, vmm/src/interrupt.rs
Make set_gsi_routing take a vector of IrqRoutingEntry. The construction
of hypervisor specific structure is left to set_gsi_routing.
Now set_gsi_routes, which is part of the interrupt module, is only
responsible for constructing a list of routing entries.
This further splits hypervisor specific code from hypervisor agnostic
code.
=> vmm, hypervisor: adjust set_gsi_routing / set_gsi_routes

docs/intel_sgx.md
Adding a few notes and links about how to enable and use SGX through
Cloud-Hypervisor.
=> docs: Add Intel SGX documentation

arch/src/aarch64/fdt.rs, scripts/run_integration_tests_aarch64.sh, tests/integration.rs
This commit enables mmio-related integration test cases on AArch64, including:
* vhost_user test cases
* virtio-blk test cases
* pmem test cases
Also this commit contains a bug fix in creating virtio-blk device. Previously, when creating the FDT, the virtio-blk device was
labeled in the reverse order of address allocation.
=> ci: AArch64: Enable AArch64 mmio-related integration test cases

vmm/src/device_manager.rs
It is not immediately obvious why the conversion is safe. Document the
safety guarantee.
=> device_manager: document unsafe block in add_vfio_device

devices/src/acpi.rs, devices/src/lib.rs, vmm/src/acpi.rs, vmm/src/device_manager.rs
This is a counter exposed via an I/O port that runs at 3.579545MHz. Here
we use a hardcoded I/O and expose the details through the FADT table.
TEST=Boot Linux kernel and see the following in dmesg:
[    0.506198] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
=> devices: vmm: Add ACPI PM timer

acpi_tables/src/sdt.rs, vmm/src/acpi.rs
Ensure that the width of the I/O port is correctly set to 32-bits in the
generic address used for the X_PM_TMR_BLK. Do this by type
parameterising GenericAddress::io_port_address() fuction.
TEST=Boot with clocksource=acpi_pm and observe no errors in the dmesg.
Fixes: #1496
=> vmm: acpi_tables: Fix PM timer I/O port width

net_util/src/lib.rs, net_util/src/queue_pair.rs, vhost_user_net/src/lib.rs, virtio-devices/src/epoll_helper.rs, virtio-devices/src/net.rs
This allows the removal of duplicate epoll loop handling code. As a side effect the error reporting is slightly improved and if an error occurs during the network queue processing it will be logged.
=> Port virtio-net to EpollHelper

vmm/src/seccomp_filters.rs
This commit fixes an "Bad syscall" error when shutting down the VM
on AArch64 by adding the SYS_unlinkat syscall to the seccomp
whitelist.
@michael2012z  @rbradford @MrXinWang @sboeuf
=> seccomp: AArch64: add SYS_unlinkat to seccomp whitelist

Cargo.lock, scripts/run_integration_tests_aarch64.sh, scripts/run_integration_tests_x86_64.sh
The virtio-fs specific commands which can be issued by the slave to the master have been recently changed as the vhost-user specification evolved. Additionally, the list of vhost-user protocol features has been updated from the specification.
The pull request aims to fix these two recent changes by relying on the latest vhost crate, but also relying on the latest virtiofsd version from the maintainer repository, based on the branch `virtio-fs-dev`.
With these changes, Cloud-Hypervisor will now follow the latest virtiofsd binary.
=> Update virtio-fs definitions

docs/arm64.md
The rootfs name in "Image" section and "Run"  section.
=> doc: AArch64: align rootfs name in arm64.md

vmm/src/device_manager.rs, vmm/src/vm.rs
Some imports are only used by KVM. Some variables and code become dead
or unused when KVM is not enabled.
=> vmm: fix warnings when KVM is not enabled

README.md
The command which is mentioned in the README is wrong. We have two
cofigs one for x86_64 and another for aarh64. Previously it was a single
config. After adding the configs the read me was not modified. This
patch fixes the issue.
=> README: Fix copy command when using config from Cloud-hypervisor

scripts/dev_cli.sh, scripts/run_integration_tests_aarch64.sh
Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1507
Lock "work_loads" folder when one job is syncing files. If another job arrives, wait until the lock is released.
Change container network option `bridge` on AArch64.
=> Improve AArch64 CI for multiple executors

vmm/src/device_manager.rs
The logic to create an MSI interrupt manager is applicable to Hyper-V as
well.
=> device_manager: eliminate KvmMsiInterruptManager from the new function

.github/workflows/cross-build.yaml, Cargo.lock, docs/arm64.md, scripts/dev_cli.sh, scripts/run_integration_tests_aarch64.sh
Having https://github.com/cloud-hypervisor/kvm-bindings/pull/1 merged, now we can remove all the workarounds for fixing build error with `with-serde` feature.
=> Remove the workaround for "with-serde" build error on AArch64

scripts/run_integration_tests_aarch64.sh
PR #1511 introduced a `flock` command in order to let AArch64 CI can be executed with multiple executors. However the command:
```
(
echo "try to lock $WORKLOADS_DIR folder and update"
flock -x 12 && update_workloads
)
```
will introduce an abnormal behavior: If any error happened in function `updated_workloads`, the sub-shell opened by the pair of parentheses will be killed instead of the main shell, which is not right.
This commit fixes this abnormal execution behaviour.
=> scripts: AArch64: Fix abnormal integration script behaviour

Cargo.lock, Cargo.toml, block_util/Cargo.toml, block_util/src/lib.rs, virtio-devices/Cargo.toml, virtio-devices/src/block_io_uring.rs, virtio-devices/src/lib.rs, vmm/Cargo.toml, vmm/src/device_manager.rs, vmm/src/seccomp_filters.rs
This pull request tackles one part of the issue https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1037, by creating a `virtio-blk` device dedicated for asynchronous handling of the queues relying on the `io_uring` feature from recent kernels.
=> virtio-devices: Add an asynchronous version of virtio-blk relying on io_uring

tests/integration.rs
This commit enables the `api_create_boot` case in the integration test as the test for the Cloud Hypervisor API server functionality on AArch64.
=> ci: AArch64: Enable `api_create_boot` for AArch64

src/main.rs, virtio-devices/Cargo.toml, virtio-devices/src/block.rs, virtio-devices/src/epoll_helper.rs, virtio-devices/src/lib.rs, virtio-devices/src/seccomp_filters.rs, vmm/src/api/http.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/seccomp_filters.rs, vmm/src/vm.rs
This patch added the seccomp_filter module to the virtio-devices crate
by taking reference code from the vmm crate. This patch also adds
allowed-list for the virtio-block worker thread.
Partially fixes: #925
This patch also extends the CLI option '--seccomp' to accept the 'log'
parameter in addition 'true/false'. It also refactors the
vmm::seccomp_filters module to support both "SeccompAction::Trap" and
"SeccompAction::Log".
Fixes: #1180
=> virtio-devices: seccomp: Add seccomp_filter module

scripts/run_integration_tests_aarch64.sh, scripts/sha1sums-aarch64, tests/integration.rs
This commit enables the test case for testing the basic function of virtio_vsock (i.e. without the hotplug).
=> ci: AArch64: Enable basic virtio_vsock test case for AArch64

vhost_user_fs/src/sandbox.rs
This change increases the limit of open files for the vhost_user_fs sandboxed process to the maximum allowed in the system. This change is based on this QEMU/virtio-fs commit [1]. One easy way to hit the limit is by creating more than 1024 files (the default is typically 1024) [2] in the vhost_user_fs mount. The last attempts will fail with a "Too many open files" error.
The system maximum is obtained by reading the `/proc/sys/fs/nr_open` sysctl file, and the setting is done using the `setrlimit` syscall. Failure to read or parse the nr_open file, or to set the limit results in a panic.
[1] https://gitlab.com/virtio-fs/qemu/-/commit/ddd21b95215342f5f2d9b94b0960c7292966c075
[2] ```for i in `seq 1 1025`; do touch $i; done```
=> vhost_user_fs: increase RLIMIT_NOFILE

virtio-devices/src/rng.rs
=> virtio-devices: rng: Port to EpollHelper

virtio-devices/src/block.rs, virtio-devices/src/console.rs, virtio-devices/src/lib.rs, virtio-devices/src/net.rs, virtio-devices/src/pmem.rs, virtio-devices/src/rng.rs, virtio-devices/src/seccomp_filters.rs, vmm/src/device_manager.rs
This patch enables the seccomp filters for the rng/console/net/pmem worker threads.
Partially fixes: #925
=> virtio-devices: seccomp: Add virtio filters for the rng/console/net/pmem worker thread

virtio-devices/src/block.rs, virtio-devices/src/epoll_helper.rs, virtio-devices/src/pmem.rs, virtio-devices/src/rng.rs, virtio-devices/src/seccomp_filters.rs
Currently any messages generated during the worker thread are not
shown anywhere as the thread is never join()ed on. Instead output the
error immediately.
For now only cover the subset where the work to port to EpollHandler
clashed with the seccomp filtering for virtio devices.
=> virtio-devices: Print out worker error messages

virtio-devices/src/iommu.rs
=> virtio-devices: iommu: Port to EpollHelper

Jenkinsfile
Turns out that "when" blocks are permitted but not effectual in "post"
sections so instead use a script behaviour to make the message
conditional on build change.
=> build: Fix Jenkinsfile syntax

Cargo.lock, hypervisor/Cargo.toml, hypervisor/src/kvm/mod.rs, hypervisor/src/lib.rs
Based on the way KVM_GET_MSRS and KVM_SET_MSRS work, both function are
very unlikely to fail, as they simply stop looping through the list of
MSRs as soon as getting or setting one fails. This is causing some
issues with the snapshot/restore feature, as on some platforms, we only
save a subset of the list of MSRs, leading to unproper way of saving the
VM.
The way to address this issue is by checking the number of MSRs get/set
matches the expected amount from the list. In case it does not match, we
simply ignore the failing MSR and continue getting/setting the rest of
the list. By doing this by iterations, we end up getting/setting as many
MSRs as the platform can support.
=> hypervisor: kvm: Make MSRs set/get more flexible

Cargo.lock, pci/Cargo.toml
This fixes `cargo vendor` throwing an error
```
$ cargo vendor
error: failed to sync
Caused by:
found duplicate version of package `vfio-bindings v0.2.0` vendored from two sources:
source 1: https://github.com/rust-vmm/vfio-bindings#f08cbcbf
source 2: registry `https://github.com/rust-lang/crates.io-index`
```
Both sources are indeed same, the conflict is only cause by the
different URLs.
Signed-off-by: Anatol Belski <ab@php.net>
=> pci: use vfio-bindings from crates.io

vmm/src/seccomp_filters.rs
Add `mprotect` to API thread rules. Prevent the VMM is killed when it is used.
=>  vmm: seccomp: add mprotect to API thread filter

scripts/dev_cli.sh
The '$libc' value is missing but is used to start the container
shell. This patch removes it from the `shell` command.
=> dev_cli: Remove the use of undefined '$libc' for the 'shell' command

Jenkinsfile
Both gnu and musl workers will retry integration tests up to 3 times if
they fail. This should give us a better pass rate, without having to
restart the entire build every time a single glitch happens.
=> ci: Retry integration tests if failing

rpm/cloud-hypervisor.spec
Packaging the cloud-hyperviosr binary is useful for enterprise use.
This patch adds the spec file for x86_64. Aarch64 support is not added
yet.
=> rpm: Add spec file for packaging cloud-hypervisor

Jenkinsfile
This reverts commit 743ebe2fa64f09bd83924b45a59296fec4e46835.
ARM64 builder is now back online.
=> Revert "build: Temporarily disable ARM64 builds"

Cargo.toml
These are required by some tools, but also by crates.io one day.
Signed-off-by: Anatol Belski <ab@php.net>
=> Cargo.toml: add missing [package] entries

Cargo.lock, block_util/Cargo.toml, virtio-devices/Cargo.toml
Now that io-uring crate has been stabilized, let's move to the latest
release 0.4.0 from crates.io.
=> io-uring: Move to the crates.io 0.4.0 version

Jenkinsfile
This prevents the builder from running out of disk space.
=> build: Remove job directory on ARM64 build

scripts/run_integration_tests_aarch64.sh, scripts/run_integration_tests_x86_64.sh, tests/integration.rs
Now we monitor the child binary to see if it exits cleanly or is killed by something other than `child.kill()`. The output of the tests is only shown if the tests fail.
=> Port test_snapshot_restore and test_counters to new methodology

vhost_user_net/src/lib.rs
Even if the vhost-user-net device did implement all currently-defined
features, it would be very short-sighted to use ::all(), because if a
new feature was defined later, the device would start claiming to
implement it even though it didn't.
More practically, claiming to implement all features breaks using QEMU
with the cloud-hypervisor vhost-user-net backend, because QEMU will
negotiate VHOST_USER_PROTOCOL_F_SLAVE_REQ, and then break when the
communication channel isn't actually set up.
I wasn't sure exactly which features the backend should claim to
implement, though.  Definitely MQ, and I'm fairly certain none of the
features I've ommitted are implemented.  But I'm not sure about
REPLY_ACK and INBAND_NOTIFICATIONS.  As far as I can tell they should
be implemented entirely by the vhost …
=> vhost_user_net: don't claim to impl all features

vmm/src/seccomp_filters.rs
The brk syscall is not always called as the system might not need it.
But when it's needed from the API thread, this causes the thread to
terminate as it is not part of the authorized list of syscalls.
This should fix some sporadic failures on the CI with the musl build.
=> vmm: Add brk syscall to the API thread

virtio-devices/src/console.rs, virtio-devices/src/seccomp_filters.rs
=> virtio-devices: console: Port to EpollHelper

virtio-devices/src/balloon.rs, virtio-devices/src/block.rs, virtio-devices/src/block_io_uring.rs, virtio-devices/src/console.rs, virtio-devices/src/epoll_helper.rs, virtio-devices/src/iommu.rs, virtio-devices/src/mem.rs, virtio-devices/src/net.rs, virtio-devices/src/pmem.rs, virtio-devices/src/rng.rs, virtio-devices/src/vsock/device.rs, virtio-devices/src/vsock/mod.rs
=> virtio-devices: vsock: Port to EpollHelper

scripts/run_integration_tests_x86_64.sh, test_data/cloud-init/ubuntu/user-data, tests/integration.rs
This reduces the complexity of the test slightly. The PCI BDFs in the L1
needed changing as the block devices come before the network ones.
=> tests: Use a disk image for test_vfio rather than virtio-fs

virtio-devices/src/vhost_user/blk.rs, virtio-devices/src/vhost_user/fs.rs, virtio-devices/src/vhost_user/handler.rs, virtio-devices/src/vhost_user/mod.rs, virtio-devices/src/vhost_user/net.rs
Migrate all vhost-user devices to EpollHelper so as to remove code that
is duplicated between multiple virtio devices.
=> virtio-devices: vhost-user: Port to EpollHelper

virtio-devices/src/net.rs, virtio-devices/src/net_util.rs, virtio-devices/src/seccomp_filters.rs, virtio-devices/src/vhost_user/net.rs
Migrate virtio-net and vhost-user-net control queue to EpollHelper so
as to remove code duplication.
=> virtio-devices: net_ctrlq: Port to EpollHelper

Jenkinsfile
If the build was aborted then the dev_cli.sh code that is responsible
for changing the file ownership will not get run. This results in the
failure to delete some of the files in the workspace.
=> Jenkinsfile: chown the workspace before cleaning up

virtio-devices/src/balloon.rs, virtio-devices/src/block.rs, virtio-devices/src/block_io_uring.rs, virtio-devices/src/console.rs, virtio-devices/src/device.rs, virtio-devices/src/epoll_helper.rs, virtio-devices/src/iommu.rs, virtio-devices/src/mem.rs, virtio-devices/src/net.rs, virtio-devices/src/net_util.rs, virtio-devices/src/pmem.rs, virtio-devices/src/rng.rs, virtio-devices/src/vhost_user/blk.rs, virtio-devices/src/vhost_user/fs.rs, virtio-devices/src/vhost_user/handler.rs, virtio-devices/src/vhost_user/net.rs, virtio-devices/src/vsock/device.rs
Using the Rust Barrier mechanism, this patch forces each virtio device
to acknowledge they've been correctly paused before going further.
Fixes #1556 
=> virtio-devices: Acknowledge a device being paused

vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/memory_manager.rs
Some OS might check for duplicates and bail out, if it can't create a
distinct mapping. According to ACPI 5.0 section 6.1.12, while _UID is
optional, it becomes required when there are multiple devices with the
same _HID.
Signed-off-by: Anatol Belski <ab@php.net>
=> devices: acpi: Add UID to devices with common HID

Jenkinsfile
We recently added the ability for the gnu and musl workers to retry if
integration test were not passing, relying on some simple Jenkins
options. Unfortunately, this is not working as expected as the retries
never pass either. The suspected reason is the machine itself, which
might be scheduled on some specific hardware, which makes our VMs more
error prone.
Bottom line, on a faulty machine, the tests will always fail, therefore
there is no added value in retrying on the same machine.
=> Jenkinsfile: Don't retry integration tests on failure

virtio-devices/src/iommu.rs, virtio-devices/src/net.rs, virtio-devices/src/seccomp_filters.rs, vmm/src/device_manager.rs
This patch enables the seccomp filters for the iommu/net worker thread.
Partially fixes: #925
This patch also prints out error message from the iommu/net worker thread.
Partially fixes: #1551
=> virtio-devices: seccomp: Add seccomp filters for iommu/net thread

virtio-devices/src/balloon.rs, virtio-devices/src/block_io_uring.rs, virtio-devices/src/mem.rs, virtio-devices/src/vhost_user/blk.rs, virtio-devices/src/vhost_user/fs.rs, virtio-devices/src/vhost_user/net.rs, virtio-devices/src/vsock/device.rs
As we never join the spawned virtio-devices worker threads, the error
returned from each worker thread is lost. For now, we simply print out
the error from each worker thread.
Fixes: #1551
=> virtio-devices: Print out worker thread errors

virtio-devices/src/balloon.rs, virtio-devices/src/mem.rs, virtio-devices/src/seccomp_filters.rs, virtio-devices/src/vhost_user/blk.rs, virtio-devices/src/vhost_user/fs.rs, virtio-devices/src/vhost_user/net.rs, vmm/src/device_manager.rs
This patch enables the seccomp filters for the balloon/mem/vhost worker thread.
Partially fixes: #925
=> virtio-devices: seccomp: Add seccomp filters for balloon/mem/vhost worker threads

docs/fs.md
Use updated --memory option parameters. The field `size` needs
M/G suffix. Without the suffix cloud-hypervisor panics at
src/main.rs:353
Also the use of backing file is deprecated so use `shared` field
Signed-off-by: Amey Narkhede <ameynarkhede02@gmail.com>
=> docs/virtio-fs: Update --memory option parameters

Jenkinsfile
Cleanup of the Aarch64 machine can't be done as part of the parallel
stage as this is often skipped. When the build is aborted because
another parallel stage failed, the post actions are simply not
performed. That's why we need a dedicated stage, out of the parallel
ones, to cleanup the Aarch64 machine.
=> Jenkinsfile: Add a cleanup stage

virtio-devices/src/seccomp_filters.rs
"debug!" macro is used in `virtio-devices/src/epoll_helper.rs` for logging. When `-vvv` and `--log-file` options were specified, the missing `SYS_write` rule caused a "bad system call" crash.
=> virtio-devices: Allow SYS_write syscall for virtio-net-ctl thread

Jenkinsfile
Problem with the previous solution was that Cleanup stage was not
executed when previous stages failed. We fix this by adding a post
section that executes always after the Aarch64 build completed, no
matter if it has failed, succeeded or been aborted.
=> Jenkinsfile: Force the cleanup after stages are aborted

docs/iommu.md
Use of backing file is deprecated hence use the `hugepages` field.
Also use the `boot` field for specifying number of cpus
Signed-off-by: Amey Narkhede <ameynarkhede02@gmail.com>
=> docs/iommu: Update cpu and memory option parameters

.github/workflows/quality-aarch64.yaml, arch/src/aarch64/fdt.rs, arch/src/aarch64/gic.rs, arch/src/aarch64/gicv2.rs, arch/src/aarch64/gicv3.rs, arch/src/aarch64/gicv3_its.rs, arch/src/aarch64/mod.rs, arch/src/aarch64/regs.rs, devices/src/gic.rs, hypervisor/src/kvm/mod.rs, scripts/run_unit_tests.sh, vm-allocator/src/gsi.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
Added quality check workflow for AArch64;
Fixed all clippy warnings;
Removed the workaround for "with-serde" in unit tests script, by the way.
=> Enable quality checks for AArch64

vmm/src/device_manager.rs
It is otherwise seems to be able to cause resource conflicts with
Windows APCI_HAL. The OS might do a better job on assigning resources to this
device, withouth them to be requested explicitly. 0xcf8 and 0xcfc are
only what is certainly needed for the PCI device enumeration.
Signed-off-by: Anatol Belski <anatol.belski@microsoft.com>
=> pci: device_manager: Remove hardcoded I/O port assignment

devices/src/gic.rs, devices/src/ioapic.rs, devices/src/legacy/serial.rs, pci/src/configuration.rs, pci/src/msix.rs, src/main.rs, test_data/cloud-init/ubuntu/user-data, tests/integration.rs, virtio-devices/src/block.rs, virtio-devices/src/block_io_uring.rs, virtio-devices/src/console.rs, virtio-devices/src/iommu.rs, virtio-devices/src/net.rs, virtio-devices/src/pmem.rs, virtio-devices/src/rng.rs, virtio-devices/src/transport/mmio.rs, virtio-devices/src/transport/pci_common_config.rs, virtio-devices/src/transport/pci_device.rs, virtio-devices/src/vsock/device.rs, vm-migration/src/lib.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/cpu.rs, vmm/src/device_manager.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
The goal for this pull request is to introduce a new CLI/API option called `--memory-zone`. This new option works together with the existing `--memory` option, as it gives the user more control over the way the guest memory is backed from a host perspective.
This is an option dedicated for advanced users who want to push the limits of what is possible with Cloud-Hypervisor.
The use of `--memory-zone` will be allowed only when the memory size is 0. Here is a quick example how this option can be used:
```
--memory size=0 --memory-zone size=1G size=4G
```
Fixes #1601
=> vmm: Introduce user-defined memory regions

vmm/src/api/openapi/cloud-hypervisor.yaml
The 'cmdline' parameter should not be required as it is not needed when
the 'kernel' parameter is the rust-hypervisor-fw, which means the kernel
and the associated command line will be found from the EFI partition.
=> vmm: openapi: Don't expect cmdline to be always there

src/main.rs, vmm/src/config.rs, vmm/src/memory_manager.rs
The flag 'mergeable' should only apply to the entire guest RAM, which is
why it is removed from the MemoryZoneConfig as it is defined as a global
parameter at the MemoryConfig level.
=> vmm: Remove 'mergeable' from memory zones

src/main.rs, tests/integration.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/memory_manager.rs, vmm/src/seccomp_filters.rs
Now that it is possible to specify with a fine granularity how to back the guest RAM through `--memory-zone`, this pull request extends the capability of this parameter by adding the new option `host_numa_nodes`. When specifying this new option, the user can specify which NUMA node from the host should be used to allocate the memory of each memory zone.
With this new feature, any user having access to a system with 2 NUMA nodes might choose to back a 4G guest memory with half of it from the first node and the second half from the second node. Here is how this can be described from the CLI:
```
./cloud-hypervisor ... --memory size=0 --memory-zone size=2G,host_numa_nodes=0 size=2G,host_numa_nodes=1
```
Fixes #1603
=> Add host NUMA nodes support

arch/src/aarch64/fdt.rs
Change sort_by to sort_by_key in create_devices_node.
Fixes: #1646
=> aarch64: fdt.rs: create_devices_node: Change sort_by to sort_by_key

vmm/src/api/openapi/cloud-hypervisor.yaml
"struct MemoryConfig" has balloon_size but not in MemoryConfig
of cloud-hypervisor.yaml.
This commit adds it.
=> cloud-hypervisor.yaml: MemoryConfig: Add balloon_size

tests/integration.rs, virtio-devices/src/seccomp_filters.rs, vmm/src/seccomp_filters.rs
Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1650.
The PR includes:
- Adding the missing seccomp rules needed for starting self-spawned vhost-user-net back-end
- Adding the missing seccomp rules needed in back-end shutdown
- Enabling integration test cases
=> Enable vhost-user-net self-spawn test cases on Aarch64

vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/memory_manager.rs
Given that ACPI uses u32 as the type for the Proximity Domain, we can
use u32 instead of u64 as the type for 'host_numa_node' option.
=> vmm: Use u32 instead of u64 for host_numa_node option

src/main.rs, tests/integration.rs, vmm/src/acpi.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/memory_manager.rs
This pull request adds a new option `guest_numa_node` to the parameter `--memory-zone`, allowing a user to specify which NUMA node a memory zone should belong to.
With the following command line example:
```
./cloud-hypervisor ... --memory size=0 --memory-zone size=1G,guest_numa_node=0 size=2G,guest_numa_node=1
```
we can find 2 NUMA nodes detected in the guest, with the first node attached to a memory range of 1G, while the second node is attached to a memory range of 2G.
=> vmm: Expose NUMA nodes to the guest

option_parser/src/lib.rs, src/main.rs, tests/integration.rs, vmm/src/acpi.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
By introducing a new `--numa` parameter, this pull request allows users to specify some settings associated with the NUMA nodes created through `--memory-zone`.
The first setting supported through this pull request is `cpus=`, which let the user choose which vCPU should be associated with which NUMA node from the guest.
For instance, if one wants to create a VM with 4vCPUs, 2 NUMA nodes, with the first NUMA node being assigned with the vCPU 0 and the second node with the rest of the vCPUs, here is what the command line would look like:
```
./cloud-hypervisor
--cpus boot=4
--memory size=0
--memory-zone size=1G,guest_numa_node=0 size=1G,guest_numa_node=1
--numa id=0,cpus=0 id=1,cpus=1-3
```
The plan is to extend this `--numa` parameter through follow up pull requests, so that we can …
=> vmm: Associate vCPUs with specific guest NUMA node

option_parser/src/lib.rs, tests/integration.rs, vmm/src/acpi.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
In order to let the user choose the distance between the NUMA nodes exposed to the guest, two complementary options `destination` and `distance` have been added to the existing `--numa` parameter. This let the user specify a list of destination nodes for a given node represented by `id`, which must come with the associated list of distances. It's mandatory that both options contain the same amount of elements. Any existing node that is not referenced through the list will be replaced with the distance 20 by default, unless it's the identity (which is always located at a distance of 10).
If any non-existing node is referenced from the list of destinations, an error will be thrown.
Here is an example of a VM exposing 3 NUMA nodes with each node being located at a different distance from the …
=> vmm: Allow distances to be specified between NUMA nodes

vm-virtio/src/queue.rs
Some of the fields on the queue were not being cleared up on device
reset.
=> vm-virtio: queue: Clear all queue fields on reset

docs/memory.md
Writing some new documentation to help users understand how the guest
memory can be described through Cloud-Hypervisor parameters.
Fixes #1659
=> docs: Add documentation about memory in Cloud-Hypervisor

virtio-devices/src/balloon.rs, virtio-devices/src/block.rs, virtio-devices/src/block_io_uring.rs, virtio-devices/src/console.rs, virtio-devices/src/device.rs, virtio-devices/src/iommu.rs, virtio-devices/src/mem.rs, virtio-devices/src/net.rs, virtio-devices/src/pmem.rs, virtio-devices/src/rng.rs, virtio-devices/src/vhost_user/blk.rs, virtio-devices/src/vhost_user/fs.rs, virtio-devices/src/vhost_user/net.rs, virtio-devices/src/vsock/device.rs
There is lots of duplicated code in our virtio devices. The goal is to consolidate this into a common location. This PR starts with doing that for the feature handling. In a subsequent PR I will follow-up with device reset and (probably) pause.
=> Introduce VirtioCommon and start using it for features

tests/integration.rs
This PR depends on another PR #1661, and it ports the following tests:
```
test_serial_null 
test_serial_tty
test_serial_file 
test_virtio_console
test_console_file
test_bzimage_reboot
```
There are two more tests to port, e.g. `test_luanch_simple` and `test_reboot`, both of which are failing when the `capture_output()` option is enabled while spawning child process. I will take a closer look into them.
=> tests: Port integration tests to the new methodology - batch 2

docs/memory.md, option_parser/src/lib.rs, src/main.rs, tests/integration.rs, vmm/src/acpi.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
In order to give more flexibility to the user, and in order to follow what's possible to describe through ACPI, this pull request introduces new options to both `--memory-zone` and `--numa` to modify the way NUMA nodes are described to the guest.
One can more freely describe the expected NUMA topology, while before a memory range had to be attached to a NUMA node.
Fixes #1665
=> vmm: Improve NUMA nodes parameters and options

Cargo.toml, build.rs
In our build-script (build.rs), we won't set the environment variable
'BUILD_VERSION' when the 'git describe' command failed (e.g. when the
current source tree does not contain git information). This patch added
a fall back path where the default value of 'BUILD_VERSION' is based on
the 'cloud-hypervisor' crate version.
Fixes: #1669
=> build: Use the crate version when the 'git describe' command failed

hypervisor/src/hypervisor.rs, hypervisor/src/kvm/mod.rs
Check KVM API version and make sure the version is what CH expects before returning a KVM object to `vmm`.
Furthermore this allows us to remove one public API from the `Hypervisor` trait.
See https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1677 .
=> Check KVM API version

Cargo.lock, Cargo.toml, option_parser/src/lib.rs, src/bin/ch-remote.rs
Remove the requirement for the user to calculate the size they want in
bytes.
Fixes: #1596
=> ch-remote: Support using unit suffices for "resize"

Jenkinsfile, scripts/dev_cli.sh, scripts/run_integration_tests_sgx.sh, tests/integration.rs
Extending the Cloud-Hypervisor CI to allow for testing SGX on a
dedicated machine where special image and kernels are ready.
=> ci: Introduce SGX integration testing

virtio-devices/src/block_io_uring.rs, virtio-devices/src/seccomp_filters.rs, virtio-devices/src/vsock/device.rs, virtio-devices/src/vsock/mod.rs, vmm/src/device_manager.rs
We now covered all virtio-devices worker threads with seccomp filters.
=> virtio-devices: seccomp: Add seccomp filters for virtio_io_uring and virtio_vsock threads

vmm/src/cpu.rs, vmm/src/seccomp_filters.rs, vmm/src/vm.rs
Those two are the last two worker threads we need to add dedicated seccomp filters.
=> vmm: seccomp: Add seccomp filters for the vcpu and signal_handler threads

virtio-devices/src/seccomp_filters.rs
We observed CI instability for the past couple of days. This
instability is confirmed to be a result of incomplete seccomp
filters. Given the filter on 'virtio_vsock' is recently added and
is missing 'brk', it is likely to be the root cause of the
instability.
=> virtio-devices: vsock: Add 'brk' to the seccomp list

block_util/src/lib.rs, virtio-devices/src/block.rs, virtio-devices/src/block_io_uring.rs
The Windows virtio block driver puts multiple data descriptors between
the header and the status footer. To handle this when parsing iterate
over the descriptor chain until the end is reached accumulating the
address and length pairs in a vector. For execution iterate over the
vector and make sequential reads from the disk for each data descriptor.
=> virtio-devices: block: Support multiple data descriptors

Jenkinsfile
Build testing of changes happens on GitHub actions and the integration
tests will build the binary (with different feature flags) again. So
these earlier build operations are just wasted time on the critical
path.
=> Jenkinsfile: Remove "Build" steps from Jenkinsfile

vmm/src/device_manager.rs, vmm/src/seccomp_filters.rs
If after the creation of the self-spawned backend, the VMM cannot create
the corresponding vhost-user frontend, the VMM must kill the freshly
spawned process in order to ensure the error propagation can happen.
In case the child process would still be around, the VMM cannot return
the error as it waits onto the child to terminate.
This should help us identify when self-spawned failures are caused by a
connection being refused between the VMM and the backend.
=> vmm: Kill vhost-user self-spawned process on failure

vmm/src/memory_manager.rs
Use zone.host_numa_node to create memory zone, so that memory zone
can apply memory policy in according with host numa node ID
Fixes: #1733
Signed-off-by: Jiangbo Wu <jiangbo.wu@intel.com>
=> mm: Apply memory policy for virtio-mem region

Cargo.lock, vmm/Cargo.toml, vmm/src/acpi.rs, vmm/src/vm.rs
virtio-mem device would use 'VIRTIO_MEM_F_ACPI_PXM' to add memory to NUMA
node, which MUST be existed, otherwise it will be assigned to node id 0,
even if user specify different node id.
According ACPI spec about Memory Affinity Structure, system hardware
supports hot-add memory region using 'Hot Pluggable | Enabled' flags.
Fixes: #1736
Signed-off-by: Jiangbo Wu <jiangbo.wu@intel.com>
=> acpi: Add hotplug numa node

scripts/run_integration_tests_aarch64.sh, scripts/run_integration_tests_x86_64.sh
While we figure out the details on how to correctly build virtiofsd from
the latest rebase from the branch "virtio-fs-dev" (which now relies on
QEMU's new build system), let's fix the CI by relying on an older branch
which still relies on the previous build system.
=> ci: Fix virtiofsd build by staying on older branch

pci/src/msix.rs
By looking at Linux kernel boot time, we identified that a lot of time
was spent registering and unregistering IRQ fds to KVM. This is not
efficient and certainly not a wrong behavior from the Linux kernel,
but rather a problem with the Cloud-Hypervisor's implementation of
MSI-X.
The way to fix this issue is by ensuring the initial conditions are
correct, which means the entire MSI-X vector table must be disabled
and masked. Additionally, each vector must be individually masked.
With these correct conditions, Linux won't start masking interrupt
vectors, and later unmask them since they will be seen as masked from
the beginning. This means the OS will simply have to unmask them when
needed, avoiding the extra operation.
Another aspect of this patch is to prevent Cloud-Hypervisor from …
=> pci: msix: Fix masking/enabling semantics

virtio-devices/src/balloon.rs
error!("Unknown event for virtio-mem");
This error should be
error!("Unknown event for virtio-balloon");
=> balloon.rs: BalloonEpollHandler: Fix wrong error in handle_event

tests/integration.rs
Besides porting the last two tests `test_simple_launch` and `test_reboot`, this patch also sets the pipe size as 256K when we capture/pipe the cloud-hypervisor child process stdout/stderr. This is the work-around for the the `vcpu` thread stall issue when using `--serial tty` (details #1707). 
Note that the pipe size (256K) is chosen based on the output size of our integration tests at this point (`test_reboot` now has the largest stdout size). The pipe size may need to be increased in the future.
=> Port the last two integration tests to the new methodology

src/main.rs
The ::new() does very little beyond trying to open the /dev/kvm device
so provide a hint to the user about what has gone wrong.
=> main: Improve the error reporting when creating the hypervisor object

vmm/src/cpu.rs
The MTRR feature was missing from the CPUID, which is causing the guest
to ignore the MTRR settings exposed through dedicated MSRs.
Fixes #1752 
=> vmm: cpu: x86: Enable MTRR feature in CPUID

src/main.rs
Add the option 'balloon' to --memory.
=> vmm: Add 'balloon' to memory parameters

arch/src/x86_64/mod.rs, arch/src/x86_64/mptable.rs, arch/src/x86_64/smbios.rs
In order to speed up the Linux boot (so as to avoid it having to scan a
large number of pages) place the MP table directly after the SMBIOS
table if there is sufficient room. The start address of the SMBIOS table
is one of the three (and the largest) location that the MP table can
also be located at.
Before:
[    0.000399] x86/PAT: Configuration [0-7]: WB  WC  UC- UC  WB  WP  UC- WT
[    0.014945] check: Scanning 1 areas for low memory corruption
After:
[    0.000284] x86/PAT: Configuration [0-7]: WB  WC  UC- UC  WB  WP  UC- WT
[    0.000421] found SMP MP-table at [mem 0x000f0090-0x000f009f]
=> arch: x86_64: Create MP table after SMBIOS table if space

vmm/src/api/openapi/cloud-hypervisor.yaml
According to openAPI specification[1], the format for `integer` types
can be only `int32` or `int64`, unsigned integers are not supported.
This patch replaces `uint64` with `int64`.
[1]: https://swagger.io/specification/#data-types
Signed-off-by: Julio Montes <julio.montes@intel.com>
=> vmm: openapi: fix integers format

.github/workflows/docker-image.yaml
The idea is to rely on this new Github Action to detect when the
Dockerfile is updated after a push to the master branch on the
repository.
Once triggered, this action builds the Docker image for both
linux/amd64 and linux/arm64 platforms, and updates it directly
on Docker Hub.
=> github: Add a new action to update the Docker image

resources/Dockerfile
In order to build virtiofsd from the latest build system, the Python
package python3-setuptools is required.
=> resources: Update Dockerfile to install missing Python packages

.github/workflows/docker-image.yaml, resources/Dockerfile
In order to support both amd64 and arm64, we rely on the TARGETARCH
variable that is passed from the docker buildx command, based on the
platform used to build the container image.
There is no way to rely directly on $(uname -m) to assign a variable
with the correct x86_64 or aarch64 values we're looking for. Both ENV
and ARG don't evaluate the command, which means they see it as a simple
string. Using RUN is the only way to evaluate a command.
=> resources: Fix Dockerfile to support multi-architecture

vmm/src/vm.rs
This allows the CMD prompt under SAC to be used without affecting getty
on Linux.
Fixes: #1770
=> vmm: vm: Replace \n newline character with \r

vmm/src/api/openapi/cloud-hypervisor.yaml
This patch adds the missing the `iommu` and `id` option for
`VmAddDevice` in the openApi yaml to respect the internal data structure
in the code base. Also, setting the `id` explicitly for VFIO device
hotplug is required for VFIO device unplug through openAPI calls.
=> vmm: openapi: Add the 'iommu' and 'id' option to 'VmAddDevice'

scripts/dev_cli.sh, scripts/run_integration_tests_aarch64.sh, scripts/run_integration_tests_x86_64.sh
This commit moves back to the branch "virtio-fs-dev" from virtiofsd, as
we figured the changes needed to use this branch and the requirements
from the new meson build from QEMU.
It updates the container version to ensure the dev_cli.sh script will
rely on the latest container which contains the needed packages.
Fixes #1738 
=> ci: Move back to latest virtiofsd version

vmm/src/device_manager.rs
=> vmm: device_manager: Warn that vhost-user self spawning is deprecated

scripts/dev_cli.sh
Now that Docker images are automatically generated for both amd64 and
arm64 architectures, there's no need to generate the arm64 image locally
on the ARM CI during a CI run. The image should be available from
DockerHub instead.
=> ci: No need to build Docker image locally for arm64

src/main.rs
Further mark this argument as required as it it necessary.
Fixes: #1712
=> main: Improve documentation for --kernel

.github/workflows/fuzz-build.yaml, fuzz/Cargo.toml, fuzz/fuzz_targets/block.rs
This patch adds two required dependencies to fuzz/Cargo.toml, and fixes
the building error on the 'block' fuzzer.
=> fuzz: Fix the building errors with recent changes

devices/src/interrupt_controller.rs, devices/src/ioapic.rs
When the destination mode is physical, the destination field should
only be defined through bits 56-59, as defined in the IOAPIC spec. But
from the APIC specification, the APIC ID is always defined on 8 bits no
matter which destination mode is selected. That's why we always retrieve
the destination field based on bits 56-63.
Fixes #1767
=> devices: ioapic: Always retrieve destination field on 8 bits

qcow/src/qcow.rs
When all refblocks are consumed, the loop looking for the first free
cluster would access the element at refcounts[refcounts.len()], which is
out of bounds.  Modify the free cluster search loop to check that the
index is in bounds before accessing it.
~~BUG=chromium:1030751~~
~~TEST=qcow_fuzzer~~
~~Change-Id: Ib2384b9cf1edeaadb99be5fc67c27a55c03fc6e9~~
~~Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/crosvm/+/1953766~~
Tested-by: Daniel Verkamp <dverkamp@chromium.org>
Tested-by: kokoro <noreply+kokoro@google.com>
Reviewed-by: Dylan Reid <dgreid@chromium.org>
Commit-Queue: Daniel Verkamp <dverkamp@chromium.org>
(cherry picked from crosvm commit f21572c7187c8beb9c6bfea6446351ae93200d01)
Fixes: #1792
=> qcow: avoid out-of-bounds access in alloc_refblocks

vmm/src/device_manager.rs
The PMEM support has an option called "discard_writes" which when true
will prevent changes to the device from hitting the backing file. This
is trying to be the equivalent of "readonly" support of the block
device.
Previously the memory of the device was marked as KVM_READONLY. This
resulted in a trap when the guest attempted to write to it resulting a
VM exit (and recently a warning). This has a very detrimental effect on
the performance so instead make "discard_writes" truly CoW by mapping
the memory as `PROT_READ | PROT_WRITE` and using `MAP_PRIVATE` to
establish the CoW mapping.
Fixes: #1795
=> vmm: device_manager: Make PMEM "discard_writes" mode true CoW

Cargo.lock, acpi_tables/Cargo.toml, arch/Cargo.toml, block_util/Cargo.toml, devices/Cargo.toml, fuzz/Cargo.toml, hypervisor/Cargo.toml, net_util/Cargo.toml, pci/Cargo.toml, vhost_user_backend/Cargo.toml, vhost_user_block/Cargo.toml, vhost_user_fs/Cargo.toml, vhost_user_net/Cargo.toml, virtio-devices/Cargo.toml, vm-allocator/Cargo.toml, vm-device/Cargo.toml, vm-virtio/Cargo.toml, vmm/Cargo.toml
A new version of vm-memory was released upstream which resulted in some
components pulling in that new version. Update the version number used
to point to the latest version but continue to use our patched version
due to the fix for #1258
=> build: Fix vm-memory bump build error

Cargo.lock, hypervisor/Cargo.toml, hypervisor/src/kvm/mod.rs, hypervisor/src/vm.rs, vmm/src/cpu.rs, vmm/src/vm.rs
Run loop in hypervisor needs a callback mechanism to access resources
like guest memory, mmio, pio etc.
VmmOps trait is introduced here, which is implemented by vmm module.
While handling vcpuexits in run loop, this trait allows hypervisor
module access to the above mentioned resources via callbacks.
Signed-off-by: Praveen Paladugu <prapal@microsoft.com>
=> hypervisor, vmm: Introduce VmmOps trait

Cargo.lock, Cargo.toml
The Cloud-Hypervisor fork of the vhost crate contains one small
additional patch compared to the rust-vmm upstream version, meant for
increasing the connection timeout.
This patch is intended to be merged in order to check if it helps our CI
fixing the vhost-user-blk flakes that we've been observing recently.
If it fixes it, we'll submit a similar patch upstream and switch back to
the upstream vhost crate, otherwise we'll simply switch back to the
upstream crate, discarding this patch.
=> virtio-devices: Rely on vhost crate from Cloud-Hypervisor fork

.github/workflows/build.yaml
It's important to ensure Cloud-Hypervisor's Git tree is bisectable, and
that's why this commit extends the existing build.yaml Github action.
This will validate that each commit from an incoming pull request can be
built.
Fixes #1808
=> ci: Validate each commit can be built

vmm/src/seccomp_filters.rs
Without the unlink(2) syscall being allowed, Cloud-Hypervisor crashes
when we remove a virtio-vsock device that has been previously added.
=> vmm: Allow unlink syscall for vCPU threads

docs/logging.md, src/main.rs
I thought it would be nice to codify when the different logging levels should be used for.  I know this document is "wrong" in the sense that we jave a lot of use of `error!` when we probably should be using `warn!` but I want this to be our ambition.
=> Logging documentation / default log level change.

tests/integration.rs
The existing virtio-blk hotplug test is extended by removing and
re-adding the virtio-blk device. This ensures the unplug/re-plug
feature is properly tested.
Fixes #1809
=> ci: Extend virtio-blk hotplug integration test

scripts/run_integration_tests_aarch64.sh, scripts/run_integration_tests_x86_64.sh, scripts/run_unit_tests.sh, tests/integration.rs
Since all unit and integration tests are run inside containers because
they are called from dev_cli.sh, they always run as root. That's why
both unit and integration scripts can be simplified as they don't need
to apply specific capabilities and run cargo tests in a dedicated 'kvm'
group.
Fixes #1683
=> ci: Simplify test scripts

.github/workflows/build.yaml
The purpose of that step is to make sure each commit builds. The `check`
command is much faster for that purpose.
On my 32-core machine `cargo check --all` takes around 25 seconds while
`cargo build --all` takes around 35 seconds, so that's quite a bit of
time saving there.
=> ci: use `cargo check` to validate building commits

block_util/src/lib.rs, virtio-devices/src/lib.rs, vmm/src/device_manager.rs
Small patch creating a dedicated `block_io_uring_is_supported()`
function for the non-io_uring case, so that we can simplify the
code in the DeviceManager.
=> vmm: Simplify some of the io_uring code

virtio-devices/src/mem.rs, virtio-devices/src/pmem.rs
The goal here is to replace anywhere possible a virtio structure
with a "C, packed" representation by a "C" representation. Some
virtio structures are not expected to be packed, therefore there's
no reason for using the more restrictive "C, packed" representation.
This is important since "packed" representation can still cause
undefined behaviors with Rust 2018.
By removing the need for "packed" representation, we can simplify a
bit of code by deriving the Serialize trait without writing the
implementation ourselves.
=> virtio: Replace some repr(C, packed) with repr(C)

hypervisor/src/kvm/aarch64/mod.rs
Without that capability save / restore for aarch64 won't work.
=> aarch64: Add OneReg to the list required extensions for KVM

arch/src/aarch64/regs.rs, hypervisor/src/cpu.rs, hypervisor/src/kvm/aarch64/mod.rs, hypervisor/src/kvm/mod.rs, vmm/src/cpu.rs
The OneRegister literally means "one (arbitrary) register". Just call it
"Register" instead. There is no need to inherit KVM's naming scheme in
the hypervisor agnostic code.
=> hypervisor, arch: rename "OneRegister" and relevant code

docs/uefi.md, docs/windows.md
This changeset extends the documentation with the UEFI and Windows related info. The focus is on providing consumer with a minimum necessary and proper piece of the information to enter the features quickly. While UEFI is a cross platform topic, it is a required prerequisite for the Windows usage. Please let me know if i missed something or something seems mistaken.
In further, I plan to work on the Windows debugging documentation part and expand more on the ISO preparation for the VirtIO driver integration. Also, please let me know if adding some graphics for the Windows installation parts or else would make sense. For now, i've ommited using any images as none are used in the documentation till now.
Thanks.
=> doc: Add UEFI and Windows consumer pages

Cargo.toml, fuzz/Cargo.toml, hypervisor/Cargo.toml
Instead of having the hypervisor crate embedding Cloud-Hypervisor forks
from the rust-vmm project, it's more appropriate to leave the rust-vmm
references in the hypervisor crate, and have the root Cargo.toml being
patched.
=> deps: Patch kvm-ioctls and kvm-bindings crates

vmm/src/memory_manager.rs
The start address after the hottplugged memory can be the start address of
device area.
Fixes: #1803
=> vmm: Support resizing memory >= hotplug size

vmm/src/memory_manager.rs
We now try to create a ram region of size 0 when the requested memory
size is the same as current memory size. It results in an error of
`GuestMemoryRegion(Mmap(Os { code: 22, kind: InvalidInput, message:`
`"Invalid argument" }))`. This error is not meaningful to users and we
should not report it.
=> vmm: Report no error when resizing to current memory size with ACPI

scripts/dev_cli.sh
In previous dev_cli.sh, the `uname -m` command will generate either `x86_64` or `aarch64`, which is inconsistent with the architectures in the Dockerfile, namely `amd64` and `arm64`.
This will cause some dependancy missing in the docker container when the docker image is built locally.
This commit fixes this inconsistancy.
=> dev_cli: Fix TARGETARCH inconsistancy

arch/src/aarch64/mod.rs, arch/src/x86_64/mod.rs, src/main.rs, tests/integration.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/cpu.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
The goal for this pull request is to provide the user with the ability to limit the guest address space to a specific value.
By introducing new option `phys_bits` to the `--cpus` parameter, one can specify the amount of physical bits exposed to the guest, which will have the effect of limiting the CPU addressable space as well as the available address space for devices.
=> vmm: Manually override CPU physical bits

virtio-devices/src/seccomp_filters.rs
While using the virtio-iommu device involving L2 scenario, and tearing
things down all the way from L2 back to L0 exposed some bad syscalls
that were not part of the authorized list.
=> virtio-devices: iommu: Update the list of seccomp filters

vmm/src/cpu.rs
We turn on that emulation for Windows. Windows does not have KVM's PV
clock, so calling notify_guest_clock_paused results in an error.
=> vmm: don't call notify_guest_clock_paused when Hyper-V emulation is on

hypervisor/src/kvm/mod.rs
This will trigger Vm::vm_reboot to make the VM reboot.
=> hypervisor: kvm: aarch64: Trigger reset upon KVM_SYSTEM_EVENT_RESET

tests/integration.rs
This patch prints the complete commandline when launching
cloud-hypervisor. It also prints the details of the `ssh` command if
the command is failing.
This patch enable the `INFO` (`-v`) level logging. Given the increased 
amount of output from cloud-hypervisor, it also increased the 
PIPE_SIZE to 32MB (from 256KB).
=> tests: Capture more logs for better debugging

arch/src/aarch64/fdt.rs, arch/src/aarch64/mod.rs, vmm/src/vm.rs
Before Virtio-mmio was removed, we passed an optional PCI space address parameter to AArch64 code for generating FDT. The address is none if the transport is MMIO. Now Virtio-PCI is the only option, the parameter is mandatory.
=> Simplify PCI space address handling in AArch64 FDT

hypervisor/src/kvm/mod.rs, hypervisor/src/kvm/x86_64/mod.rs, vmm/src/cpu.rs, vmm/src/seccomp_filters.rs
The snasphot/restore feature is not working because some CPU states are
not properly saved, which means they can't be restored later on.
First thing, we ensure the CPUID is stored so that it can be properly
restored later. The code is simplified and pushed down to the hypervisor
crate.
Second thing, we identify for each vCPU if the Hyper-V SynIC device is
emulated or not. In case it is, that means some specific MSRs will be
set by the guest. These MSRs must be saved in order to properly restore
the VM.
=> vmm, hypervisor: Fix snapshot/restore for Windows guest

docs/memory.md, src/bin/ch-remote.rs, src/main.rs, tests/integration.rs, vmm/src/api/mod.rs, vmm/src/api/openapi/cloud-hypervisor.yaml, vmm/src/config.rs, vmm/src/device_manager.rs, vmm/src/lib.rs, vmm/src/memory_manager.rs, vmm/src/vm.rs
This pull request fully moves the `virtio-balloon` code from the `MemoryManager` to the `DeviceManager`. Before that, the code was split across managers' code, implying extra complexity. In order to make the `virtio-balloon` a fully standalone virtio device, the CLI and OpenAPI have been extended with a new `--balloon` parameter, while the options `balloon=on|off` and `balloon_size=` have been removed from `--memory` parameter.
The behavior for resizing the balloon has been simplified and decoupled from the `MemoryManager` by accepting the expected balloon size as value (instead of the expected RAM size as before).
Fixes #1844
=> vmm: Move virtio-balloon out of the MemoryManager

Cargo.lock, Cargo.toml, api_client/Cargo.toml, api_client/src/lib.rs, src/bin/ch-remote.rs
This code will be reused when streaming data from one VMM to another via the HTTP socket in order to support paused migration.
=> Split API/HTTP client into own crate

Jenkinsfile
This is an interim step to be able to test io_uring on our CI system.
See: #1561
=> build: Move on-demand workers from bionic to groovy

Cargo.toml, virtio-devices/src/seccomp_filters.rs
Now that we that our CI is running with a kernel that is new enough to
support io_uring we can turn this feature on by default.
See: #1561
=> build: Enable io_uring feature by default

vmm/src/memory_manager.rs
As a mirror of bdbea19e239b22e781a7df3caf8db04675e15553 which ensured
that GuestMemoryMmap::read_exact_from() was used to read all the file to
the region ensure that all the guest memory region is written to disk.
=> vmm: memory_manager: Write all guest region to disk

Cargo.lock, Cargo.toml, test_data/cloud-init/ubuntu/user-data, tests/integration.rs
Instead of blindly waiting for 20-40s for the guest VM to boot, this
patch waits the notification from the guest VM explicitly by using a
simple TcpListener on the host and a custom systemd service in the
guest.
This patch also ported few tests to use this new machanism, while more
tests are to be ported.
=> tests: Wait explicitly for the guest vm to boot

scripts/run_integration_tests_aarch64.sh, scripts/run_integration_tests_x86_64.sh
Address build failure from activity in the development virtio-fs branch
by using the stable fork.
=> build: Use stable virtio-fs QEMU branch

build.rs
This patch makes the `--version` information consistent when 
using `git describe` and 'cloud-hypervisor' crate version.
=> build: Add the 'v' prefix when using the crate version
