cloud-hypervisor/cloud-hypervisor

Cargo.lock
Cargo.toml
tests/integration.rs

Instead of waiting blindly with fixed amount of sleeping time, we can
use the `wait-timeout` crate to explicitly wait VM shutdown (with a
timeout). It can reduces the execution time of some tests
substantially. Also, this patch increases the `shutdown` timeout for
'test_reboot', which should fix the recent sporadic failures on this
test.
This patch also ports more tests to use `wait_vm_boot` for reducing
blind waiting time for VM booting.

tests: Reduce blind waiting time

---

vmm/src/memory_manager.rs
vmm/src/vm.rs

Rather than filling the guest memory from a file at the point of the the
guest memory region being created instead fill from the file later. This
simplifies the region creation code but also adds flexibility for
sourcing the guest memory from a source other than an on disk file.

vmm: memory_manager: Move the restoration of guest memory later

---

docs/uefi.md

This part expands on building OVMF with CSM support. 

doc: Add notes to compile OVMF with legacy support

---

vmm/src/api/openapi/cloud-hypervisor.yaml

Due to a known limitation in OpenAPITools/openapi-generator tool,
it's impossible to send go zero types, like false and 0 to
cloud-hypervisor because `omitempty` is added if a field is not
required.
Set cache_size, dax, num_queues and queue_size as required to remove
`omitempty` from the json tag.
fixes #1961
Signed-off-by: Julio Montes <julio.montes@intel.com>

vmm: openapi: remove `omitempty` json tag

---

src/bin/ch-remote.rs
vm-migration/src/lib.rs
vm-migration/src/protocol.rs
vmm/src/api/http.rs
vmm/src/api/http_endpoint.rs
vmm/src/api/mod.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

This is an intermediate step towards live migration. Live migration would build on this by recording the pages touched using a KVM API and sending multiple "Memory" commands to send just those changed pages.
After this PR is merged:

Add support for migrating a paused VM

---

Cargo.lock
hypervisor/Cargo.toml
hypervisor/src/kvm/mod.rs
virtio-devices/Cargo.toml
vmm/Cargo.toml

`ArcSwap::clone()` doesn't do what we or most users expected. arc-swap upstream have removed it.

Correctly share VmmOps &  bump arc-swap dependency

---

tests/integration.rs
vmm/src/memory_manager.rs

While the addressable space size reduction of 4k in necessary due to
the Linux bug, the 64k alignment of the addressable space size is
required by Windows. This patch satisfies both.

memory_manager: Make addressable space size 64k aligned

---

hypervisor/src/kvm/mod.rs
hypervisor/src/vm.rs
pci/src/vfio.rs
vm-migration/src/protocol.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

Add initial support for migrating a VM with minimal downtime:
Now the VM is paused/resumed by the migration process itself.
0. The guest configuration is sent to the destination
1. Dirty page log tracking is started by start_memory_dirty_log()
2. All guest memory is sent to the destination
3. Up to 5 attempts are made to send the dirty guest memory to the destination...
4. ...before the VM is paused
5. One last set of dirty pages is sent to the destination
6. The guest is snapshotted and sent to the destination
7. When the migration is completed the destination unpauses the received VM.
Things not handled/tested:

Initial live migration support

---

Cargo.lock
Cargo.toml
src/main.rs
tests/integration.rs

As we no longer support self spawning we can remove this code and this gives us a 4.1% reduction in the size of our cloud-hypervisor binary (stripped).

Remove `--net-backend` and `--block-backend` from cloud-hypervisor binary

---

tests/integration.rs
vmm/src/config.rs
vmm/src/device_manager.rs

This ensures we can continue to test the original virtio-block code even when running on a host that supports io_uring.

Support forcing io_uring off for testing

---

hypervisor/src/kvm/mod.rs
hypervisor/src/vm.rs
vmm/src/cpu.rs
vmm/src/interrupt.rs
vmm/src/vm.rs

This interface is used by the vCPU thread to delegate responsibility for
handling MMIO/PIO operations and to support different approaches than a
VM exit.
During profiling I found that we were spending 13.75% of the boot CPU
uage acquiring access to the object holding the VmmOps via
ArcSwap::load_full()
13.75%     6.02%  vcpu0            cloud-hypervisor    [.] arc_swap::ArcSwapAny<T,S>::load_full
|
---arc_swap::ArcSwapAny<T,S>::load_full
|
--13.43%--<hypervisor::kvm::KvmVcpu as hypervisor::cpu::Vcpu>::run
std::sys_common::backtrace::__rust_begin_short_backtrace
core::ops::function::FnOnce::call_once{{vtable-shim}}
std::sys::unix::thread::Thread::new::thread_start
However since the object implementing VmmOps does not need to be mutable
and it is only used from the vCPU side we can change …

hypervisor, vmm: Remove shared ownership of VmmOps

---

arch/src/aarch64/gic/mod.rs
arch/src/aarch64/layout.rs
arch/src/x86_64/layout.rs
pci/src/configuration.rs
pci/src/vfio.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs
virtio-devices/src/vsock/packet.rs

The stable toolchain moved to 1.48.0, which triggered 2 new clippy warnings.

Rust 1.48.0 clippy warnings fixes

---

Cargo.lock
Cargo.toml
acpi_tables/Cargo.toml
arch/Cargo.toml
block_util/Cargo.toml
devices/Cargo.toml
fuzz/Cargo.toml
hypervisor/Cargo.toml
net_util/Cargo.toml
pci/Cargo.toml
vhost_user_backend/Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_fs/Cargo.toml
vhost_user_net/Cargo.toml
virtio-devices/Cargo.toml
vm-allocator/Cargo.toml
vm-device/Cargo.toml
vm-virtio/Cargo.toml
vmm/Cargo.toml

vm-memory 0.4.0 now contains all our fixes.

cargo: Move to crates.io vm-memory 0.4.0

---

Cargo.lock
Cargo.toml
vmm/Cargo.toml
vmm/src/vm.rs

Includes updates for ssh2, cc, syn, tinyvec, backtrace micro-http and libssh2.

cargo: Bulk update

---

src/bin/ch-remote.rs
vm-device/src/bus.rs
vmm/src/lib.rs
vmm/src/seccomp_filters.rs

This PR fixes two issues in the live migration code (plus a typo I spotted):
* Add the new ioctl to the permitted list for the VMM process (`KVM_GET_DIRTY_LOG`)
* Fix the panic from the vcpu thread due to the VM not being shutdown correctly because the configuration wasn't saved into the VMM.

Live migration fixes

---

Cargo.lock
arch/src/x86_64/mod.rs
arch/src/x86_64/regs.rs
hypervisor/Cargo.toml
hypervisor/src/arch/emulator/mod.rs
hypervisor/src/arch/mod.rs
hypervisor/src/arch/x86/emulator/instructions/mod.rs
hypervisor/src/arch/x86/emulator/instructions/mov.rs
hypervisor/src/arch/x86/emulator/mod.rs
hypervisor/src/arch/x86/gdt.rs
hypervisor/src/arch/x86/mod.rs

The framework relies on:
1. The iced_x86 crate for instructions decoding.
1. An `IOEmulator` trait for getting access to the platform's register and memory.
1. An `InstructionHandler` trait that each emulated instruction must implement
Instructions are decoded through `iced_x86`, then the framework tries to resolve an instruction handler for the decoded mnemonic.
The handler then uses the `IOEmulator` implementation to emulate the instruction semantics.
The first and only instruction that is emulated in this PR is the x86 `MOV`.

hypervisor: x86 code emulator framework

---

vmm/src/device_manager.rs

This was used for vhost-user self spawning but no longer has any users.

vmm: device_manager: Remove ActivatedBackend struct

---

.github/workflows/quality.yaml
arch/src/x86_64/mod.rs
arch/src/x86_64/regs.rs
arch_gen/src/x86/mpspec.rs
devices/src/legacy/serial.rs
qcow/src/qcow.rs
vhost_user_block/src/lib.rs
vm-device/src/bus.rs
vmm/src/cpu.rs

Extend to include tests (`--tests`) and also all crate in the workspace (`--all`)

Expand clippy coverage

---

hypervisor/src/arch/x86/emulator/instructions/mod.rs
hypervisor/src/arch/x86/emulator/instructions/mov.rs
hypervisor/src/arch/x86/emulator/mod.rs

The observation here is PlatformEmulator can be seen as the context for
emulation to take place. It should be rather easy to construct a context
that satisfies the lifetime constraints for instruction emulation.
The thread doing the emulation will have full ownership over the
context, so this removes the need to wrap PlatformEmulator in Arc and
Mutex, as well as the need for the context to be either Clone or Copy.

hypervisor: x86: reference PlatformEmulator in Emulator

---

hypervisor/src/arch/x86/emulator/instructions/mod.rs

There is no need to put a box into another box.

hypervisor: x86: drop an extraneous box indirection

---

hypervisor/src/arch/x86/emulator/instructions/mov.rs
hypervisor/src/arch/x86/emulator/mod.rs

Potentially all emulated instruction unit testing will re-use the current MOV `MockVMM` platform. 
This PR factorizes it into its own test only module for easier sharing.

emulator: Factorize the mock VMM

---

Jenkinsfile

If we rely on timeouts at the top level we can get builds being aborted
simply because they took too long to be scheduled rather than because
the actual integration tests took too long.

build: Move timeouts to integration test blocks

---

arch/src/x86_64/regs.rs
hypervisor/src/arch/emulator/mod.rs
hypervisor/src/arch/x86/emulator/instructions/mod.rs
hypervisor/src/arch/x86/emulator/instructions/mov.rs
hypervisor/src/arch/x86/emulator/mod.rs
hypervisor/src/arch/x86/mod.rs
hypervisor/src/arch/x86/regs.rs
hypervisor/src/kvm/x86_64/mod.rs

On x86 instruction lengths and thus instruction bytes boundaries are not necessarily page aligned. As a consequence, hypervisors may fetch and pass only part of an instruction if said crosses a page boundary. This is why we need to add to the current emulator the ability to fetch instruction bytes from memory.
Adding instruction fetching means we are now allowing for reading memory from different segments, code or data. As a consequence, this PR also adds a generic address linearization (from segmented to virtual) method for the `CpuStateManager` trait, with basic segmentation checks.
With that new method in place, x86 `PlatformEmulator` implementations can linearize their `RIP` and call into `read_memory` with the translated virtual address for fetching instruction bytes.
The x86 …

Emulator instruction fetch

---

Cargo.lock
hypervisor/Cargo.toml

It is no longer needed after 0fec32658.

hypervisor: drop arc-swap dependency

---

hypervisor/Cargo.toml
hypervisor/src/arch/emulator/mod.rs
hypervisor/src/arch/x86/emulator/instructions/mod.rs
hypervisor/src/arch/x86/emulator/instructions/mov.rs
hypervisor/src/arch/x86/emulator/mod.rs

* Extend the `imm_op` macro and make it available to all instruction emulation implementations
* Format instructions on error paths, and display human readable assembly

hypervisor: emulator: Small improvements

---

hypervisor/src/kvm/mod.rs
vhost_user_block/src/lib.rs
virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/block_io_uring.rs
virtio-devices/src/console.rs
virtio-devices/src/mem.rs
virtio-devices/src/transport/pci_common_config.rs
virtio-devices/src/transport/pci_device.rs
vmm/src/cpu.rs
vmm/src/interrupt.rs

When a total ordering between multiple atomic variables is not required
then use Ordering::Acquire with atomic loads and Ordering::Release with
atomic stores.
This will improve performance as this does not require a memory fence
on x86_64 which Ordering::SeqCst will use.
Add a comment to the code in the vCPU handling code where it operates on
multiple atomics to explain why Ordering::SeqCst is required.

misc: Use a more relaxed memory model when possible

---

hypervisor/src/arch/x86/emulator/instructions/mod.rs
hypervisor/src/arch/x86/emulator/mod.rs

This allows the compiler to optimize it better. It also avoids the overhead of allocation and deallocation of the HashMap.

Use `match` to dispatch instruction emulation

---

hypervisor/src/arch/x86/emulator/instructions/mov.rs
hypervisor/src/arch/x86/emulator/mod.rs

There is no need to have a pair of curly brackets for structures without
any member.

hypervisor: x86: emulator: drop unneeded curly brackets

---

vmm/src/vm.rs

When using an PIO write to 0x80 which is a special case handle that and
then return without going through the resolve.
This removes an extra warning that is reported.

vmm: Don't continue to lookup debug I/O port

---

Cargo.toml
fuzz/Cargo.toml
hypervisor/Cargo.toml

Unfortunately it seems patch entries are ignored when obtaining
dependencies from another workspace.
Remove the problematic kvm-ioctls and kvm-bindings patch entries and use
the forked repository directly.

build: Fix cargo fuzz build

---

.github/workflows/build.yaml

nightly / beta are not required actions but if they fail then all other
builds will be cancelled and so prevent the PR from being cleared as
buildable.

build: Disable fast failing for build actions

---

hypervisor/src/arch/emulator/mod.rs
hypervisor/src/arch/x86/emulator/instructions/cmp.rs
hypervisor/src/arch/x86/emulator/instructions/mod.rs
hypervisor/src/arch/x86/emulator/instructions/mov.rs
hypervisor/src/arch/x86/emulator/mod.rs
hypervisor/src/arch/x86/regs.rs

Unfortunately Rust stable does not yet have inline ASM support the flag
calculation will have to be implemented in software.

hypervisor: emulator: emulate CMP

---

src/main.rs

main: provide a sensible error message when /dev/mshv is missing

---

hypervisor/src/arch/mod.rs
hypervisor/src/arch/x86/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
hypervisor/src/lib.rs
hypervisor/src/mshv/x86_64/mod.rs

Currently these two macros(msr, msr_data) reside both on kvm and mshv
module. Definition is same for both module. Moving them to arch/x86
module eliminates redundancy and makes more sense.

hypervisor: Move msr and msr_data macro to arch/x86

---

devices/src/acpi.rs
devices/src/ioapic.rs
devices/src/legacy/cmos.rs
devices/src/legacy/fwdebug.rs
devices/src/legacy/i8042.rs
devices/src/legacy/rtc_pl031.rs
devices/src/legacy/serial.rs
pci/src/bus.rs
pci/src/device.rs
pci/src/vfio.rs
tests/integration.rs
virtio-devices/src/transport/pci_device.rs
vm-device/src/bus.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

If a virtio device needs activation (because the device status field has been updated) signal to the VMM thread that there is a device that can be activated via an EventFd. Since the device must be ready when the write to the configuration register is completed use a barrier so that the CPU thread will wait until the VMM thread activates the device. This ensures that from the guest perspective the device is activated synchronously by the write that it made to the status register.
Fixes: #1863
This is based on an earlier PR: #1953 that didn't correctly handle the required synchronous behaviour.

Activate virtio devices via VMM thread

---

Cargo.lock
hypervisor/Cargo.toml
hypervisor/src/arch/x86/emulator/instructions/mod.rs

And fix related warnings: op_kind and op_register are being deprecated
as they might panic.

hypervisor: Bump iced-x86 to 1.10.0

---

docs/macvtap-bridge.md
net_util/src/open_tap.rs
net_util/src/tap.rs
tests/integration.rs
virtio-devices/src/net.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/seccomp_filters.rs

Allow creating a network device using an existing fd for the TAP device. This opens up the possibility of using a MACVTAP with Cloud Hypervisor which is now documented.
Fixes: #872
Fixes: #2052
Ping: kata-containers/runtime#2846

Add support for using TAP fd

---

src/main.rs
tests/integration.rs
virtio-devices/src/transport/pci_device.rs

Opt for using the faster (fewer KVM exits) virtio-console over serial and use direct boot for the majority of tests.

Minor integration test improvements

---

Cargo.lock
hypervisor/Cargo.toml

It is not used anywhere inside the hypervisor crate.

hypervisor: drop linux-loader dependency

---

vmm/src/seccomp_filters.rs

If the vCPU thread calls log!() the time difference between the call
time and the boot up time is reported. On most environments and
architectures this covered by a vDSO call rather than a syscall. However
on some platforms this turns into a syscall.
Fixes: #2080

vmm: seccomp: Allow clock_gettime() on the vCPU thread

---

Cargo.lock

Reverts cloud-hypervisor/cloud-hypervisor#2098
Breaks the compilation on Fedora/RedHat machines.

Revert "build(deps): bump linux-loader from `acf9c21` to `b18d387`"

---

docs/intel_sgx.md
vmm/src/memory_manager.rs

Based on the LKML feedback, the devices under /dev/sgx/* are
not justified. SGX RFC v40 moves the SGX device nodes to /dev/sgx_*
and this is reflected in kvm-sgx (next branch) too.
Update cloud-hypervisor code and documentation to follow this.
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

sgx: update virt EPC device path and docs

---

tests/integration.rs
virtio-devices/src/net.rs
vm-virtio/src/queue.rs

Improve the CI logs so that they become more useful. In particular we were losing the error from most SSH commands as it was not being allowed to panic at source.

Improve test logging for CI

---

tests/integration.rs

This reduces the amount of copying and disk space needed for each test. An explicit QCOW2 test is added.

Use raw images for the majority of tests

---

Jenkinsfile

They are already provisioned on the builder machine.

Jenkinsfile: Don't download the Windows images

---

virtio-devices/src/seccomp_filters.rs

On aarch64, the openat() syscall was missing from the seccomp filters
list, preventing the test_watchdog from running properly.
Fixes #2103

virtio-devices: Update seccomp filters for virtio-net thread

---

tests/integration.rs

Given we already check the connected IP address matches the expected
guest IP address, the check on the "booted" message is not needed.
Fixes: #2117

tests: Remove the check on the "booted" message in 'wait_vm_boot()'

---

virtio-devices/src/transport/pci_device.rs
vmm/src/lib.rs

Sometimes when running under the CI tests fail due to a barrier not
being released and the guest blocks on an MMIO write. Add further
debugging to try and identify the issue.
See: #2118

virtio-devices, vmm: Enhance debugging around virtio device activation

---

tests/integration.rs

This test is reliably failing on our CI and we need time to investigate
why.
See: #2126

tests: Teporarily disable test_windows_guest_snapshot_restore

---

Jenkinsfile

Because we're back on transient builder, let's download the image
everytime.
This reverts commit b5653d52787a0be5f58d557fb06ff798ac280c45.

ci: Always download the Windows image

---

tests/integration.rs

This reverts commit 49b49421d05329532ba066febe58a20cece853ba.
Probable solution was applied in f70852c04b65e7ae9f9a6edfa471bd00b9fead07
Fixes: #2103

Revert "tests: Temporarily disable test_watchdog on aarch64"

---

vmm/src/seccomp_filters.rs

Older libc (like RHEL7) uses open() rather than openat(). This was
demonstrated through a failure to open /etc/localtime as used by
gmtime() libc call trigged from the vCPU thread (CMOS device.)
Fixes: #2111

vmm: seccomp: Add open() to vCPU permitted syscalls

---

scripts/dev_cli.sh
scripts/run_integration_tests_x86_64.sh
tests/integration.rs

Using --net=host is not necessary for any of the integration tests, so
let's use the default network option called "bridge".

scripts: Run test container with the default bridge network

---

docs/custom-image.md
scripts/run_integration_tests_x86_64.sh
scripts/sha1sums-x86_64
test_data/cloud-init/ubuntu/user-data
tests/integration.rs

This service may fail to start and prevent SSH from starting resulting in test failures.
Fixes: #2113

Remove pollinate service from test image

---

Cargo.lock
Cargo.toml
src/main.rs

If we receive SIGSYS and identify it as a seccomp violation then give
friendly instructions on how to debug further. We are unable to decode
the siginfo_t struct ourselves due to https://github.com/rust-lang/libc/issues/716
Fixes: #2139

main: Give a friendly message when we get a seccomp violation

---

Cargo.lock

The tight coupling of these packages caused issues for dependabot trying
to update them separately so instead combine them together into one
update.

build: deps: Bump serde and serde_derive together

---

scripts/run_integration_tests_windows.sh
tests/integration.rs

The Windows image is quite large (about 20GiB), hence it takes some time
to copy it for every test in order to avoid potential corruption.
One way to mitigate that without compromising on safety between each
test is by using device mapper. By creating a read-only base, we ensure
the image won't be modified by any of the tests, and by creating one
snapshot for each test, we avoid copying the entire image each time.
A dedicated Copy On Write disk image is created to handle any change
that might be performed on the base image, letting the tests behave as
expected.
Fixes #2155

ci: Use device mapper to avoid copying Windows image

---

virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/block_io_uring.rs
virtio-devices/src/console.rs
virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/watchdog.rs

In order to make the thread naming more useful derive their name from
the device id (which can be supplied by the user) and a device specific
suffix that has details of the individual queue (or queue pair.)
e.g.
rob@artemis:~$ pstree -p -c -l -t `pidof cloud-hypervisor`
cloud-hyperviso(27501)─┬─{_console}(27525)
├─{_disk0_q0}(27529)
├─{_disk0_q1}(27532)
├─{_net1_ctrl}(27533)
├─{_net1_qp0}(27534)
├─{_net1_qp1}(27535)
├─{_rng}(27526)
├─{http-server}(27504)
├─{seccomp_signal_}(27502)
├─{signal_handler}(27523)
├─{vcpu0}(27520)
├─{vcpu1}(27522)
└─{vmm}(27503)
Fixes: #2077

virtio-devices: Derive thread names from device ids

---

virtio-devices/src/device.rs

We have killed the device thread by writing to the exit EventFd but we
should wait for them to quit to ensure consistency.

virtio-devices: Upon reset reap/join the device threads

---

virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/block_io_uring.rs
virtio-devices/src/console.rs
virtio-devices/src/device.rs
virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/transport/pci_device.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/watchdog.rs

Rather than having to give and return the ioeventfd used for a device
clone them each time. This will make it simpler when we start handling
the driver enabling fewer queues than advertised by the device.

virtio-devices: Simplify virtio device reset

---

vm-virtio/src/queue.rs

We should use full memory barrier to ensure both guest and us
can see the correct avail_idx and avail_event_idx. Something
like this pattern:
```
VM:                           CLH:
update vring.avail->idx       update avail_event_idx
mb()                          mb()
read avail_event_idx          read vring.avail->idx
```
Signed-off-by: Xie Yongji <xieyongji@bytedance.com>

vm-virtio: Fix update_avail_event() memory ordering

---

.github/workflows/cross-build.yaml

Remove unnecessary commands to simplify the cross-build action.

.github: Simplify cross-build action

---

virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/block_io_uring.rs
virtio-devices/src/console.rs
virtio-devices/src/device.rs
virtio-devices/src/mem.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/transport/pci_device.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/watchdog.rs

From the virtio 1.1 spec
> num_queues
is the total number of request virtqueues exposed by the device. The driver MAY use only one request queue, or it can use more to achieve better performance. 
Support this use case by allowing the driver to program fewer queues by only providing the device implementation with a list of queues that is filtered to only include those that are enabled.
Fixes: #2136

virtio-devices: Allow driver to program fewer queues

---

vmm/src/seccomp_filters.rs

This patch refines the sccomp filter list for the vCPU thread, as we are
no longer spawning virtio-device threads from the vCPU thread.
Fixes: #2170

vmm: Refine the seccomp filter list for the vCPU thread

---

devices/src/acpi.rs
devices/src/lib.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs

Move ACPI devices from fixed I/O ports to MMIO addresses which are dynamically allocated.
Fixes: #2181

Migrate ACPI devices to MMIO addresses

---

hypervisor/src/arch/x86/mod.rs

According to Intel SDM, #DE should be 0 and #DB should be 1.

hypervisor: fix exception vector numbers

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_sgx.sh
scripts/run_integration_tests_windows.sh
scripts/run_integration_tests_x86_64.sh
scripts/test-util.sh

e.g.
scripts/dev_cli.sh tests --integration -- --test-filter test_watchdog
This used to be supported by passing "$@" but was broken when multiple
hypervisor support was added.
Fixes: #2182

tests: Support filtering integration tests

---

vmm/src/acpi.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

This skeleton commit brings in the support for compiling aarch64 with
the "acpi" feature ready to the ACPI enabling. It builds on the work to
move the ACPI hotplug devices from I/O ports to MMIO and conditionalises
any code that is x86_64 only (i.e. because it uses an I/O port.)
Filling in the aarch64 specific details in tables such as the MADT it
out of the scope.
See: #2178

vmm: acpi: Support compiling ACPI code on aarch64

---

net_util/src/tap.rs

The unit tests ask the Linux kernel to generate a TAP device name on
demand by passing in a format string. I suspect, but haven't been able
to confirm that there might be a rare race that triggers when creating
lots of devices in a short period of time. This is appearing in our unit
test as the occassional flake of the test_tap_read() which although it
has successfully created the device it fails to set the IP address on it
when looking it back up by it's name.
Since this is the most frequent cause of failures on our CI use a lock
to ensure that multiple TAP devices are not created simultaneously.
Fixes: #2135

net_util: tests: Avoid trying to create TAP devices simultaenously

---

.github/workflows/quality.yaml
tests/integration.rs

Ensure that we try and keep the integration tests clippy clean.

tests: Add clippy check for integration test building

---

scripts/dev_cli.sh

Delay downloading the container until it is being used.
Fixes: #2065

scripts: Don't download container on help invocations

---

vmm/src/device_manager.rs

Building with 1.51 nightly produces the following warning:
warning: unnecessary trailing semicolon
--> vmm/src/device_manager.rs:396:6
|
396 |     };
|      ^ help: remove this semicolon
|
= note: `#[warn(redundant_semicolons)]` on by default
warning: 1 warning emitted

vmm: drop unnecessary semicolon

---

docs/vfio.md

Because of the behavior of the NVIDIA proprietary driver, we can't
expect NVIDIA cards with only MSI support to be functioning correctly
after they've been passed through with Cloud-Hypervisor.

docs: Clarify VFIO limitations regarding NVIDIA cards

---

net_util/src/open_tap.rs
net_util/src/tap.rs
tests/integration.rs
vhost_user_net/src/lib.rs
virtio-devices/src/net.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs

This patch enables multi-queue support for creating virtio-net devices by
accepting multiple TAP fds, e.g. '--net fds=3:7'. It also extends the existing
integration test `test_tap_from_fd()`.
Fixes: #2164

Accept multiple TAP fds for creating virtio-net devices

---

vmm/src/device_manager.rs

This unneeded return statement giving clippy warnings

vmm: Remove unneeded `return` statement

---

Cargo.lock
block_util/Cargo.toml
block_util/src/fixed_vhd_async.rs
block_util/src/fixed_vhd_sync.rs
block_util/src/lib.rs
block_util/src/raw_sync.rs
block_util/src/vhd.rs
tests/integration.rs
virtio-devices/src/seccomp_filters.rs
vmm/src/device_manager.rs
vmm/src/seccomp_filters.rs

This PR adds both synchronous and asynchronous support for fixed VHD disk files.
Fixes #2185

vmm: Add support for fixed VHD disk files

---

virtio-devices/src/mem.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs

Relying on the virtio-mem specification, this PR performs a few simplifications. At the same time, it cleans up the code to make it more readable.
Fixes #1883

virtio-mem: Cleanup the code based on specification

---

docs/memory.md
src/main.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/memory_manager.rs

Allow the user to control the huge page size; it is the responsibility of the user to ensure they have enough pages of the required size available to use.
No integration test changes as we cannot add new page sizes at runtime.

Allow controlling huge page size

---

vmm/src/device_manager.rs

Their last users were gone in af3c6c34c3d.

vmm: drop two unused error

---

virtio-devices/src/vhost_user/net.rs

This thread is virtio-net specific, so it is not handled in the common
virtio device code.
The non-vhost implementation resumes the thread itself. Do the same
thing for vhost-user-net.

virtio-devices: vhost-user-net: unpark control queue thread in resume

---

Cargo.lock
hypervisor/src/kvm/mod.rs

Update the version of the fork pointed to which has been rebased on the
latest upstream.

build: Update to latest kvm-ioctls

---

src/main.rs
tests/integration.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/seccomp_filters.rs
vmm/src/vm.rs

Add the ability for cloud-hypervisor to create, manage and monitor a
pty for serial and/or console I/O from a user. The reasoning for
having cloud-hypervisor create the ptys is so that clients, libvirt
for example, could exit and later re-open the pty without causing I/O
issues. If the clients were responsible for creating the pty, when
they exit the main pty fd would close and cause cloud-hypervisor to
get I/O errors on writes.
Ideally the main and subordinate pty fds would be kept in the main
vmm's Vm structure. However, because the device manager owns parsing
the configuration for the serial and console devices, the information
is instead stored in new fields under the DeviceManager structure
directly.
From there hooking up the main fd is intended to look as close to
handling stdin and …

Enable pty console

---

arch/src/aarch64/mod.rs
arch/src/x86_64/mod.rs
vmm/src/cpu.rs

For TDX enabling I need a set of common CPUID bits; rather than generate them afresh it would be nice to reuse the code. To facilitate this I move all the CPUID adjustments that are common for all vCPUs into one function.

Move most CPUID changes to common CPUID patching code

---

hypervisor/src/mshv/mod.rs

They were used to suppress warnings during development. At this stage
they aren't needed anymore.

hypervisor: mshv: drop some attributes

---

arch/src/lib.rs
arch_gen/src/x86/mod.rs
hypervisor/src/arch/x86/mod.rs

arch, arch_gen, hypervisor: Remove some unnecessary clippy attributes

---

Cargo.lock
Cargo.toml
event_monitor/Cargo.toml
event_monitor/src/lib.rs
src/main.rs
virtio-devices/Cargo.toml
virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/console.rs
virtio-devices/src/iommu.rs
virtio-devices/src/lib.rs
virtio-devices/src/mem.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/watchdog.rs
vmm/Cargo.toml
vmm/src/lib.rs
vmm/src/seccomp_filters.rs
vmm/src/vm.rs

For systems like libvirt that need to observe what the VMM is doing provide an infrastructure to report structured events by writing to a FD.
This is a simpler solution to #2273 as it does not require CH to maintain a set of locations to write event data to (and the requirement that that be in it's own thread to avoid blocking) and simpler for libvirt does not need to manage a web server for the callbacks.

Add structured event monitoring

---

hypervisor/Cargo.toml

This simplifies the Cloud Hypervisor dependency chain slightly.

build: Only build the {kvm,mshv}-{ioctls,bindings} needed

---

net_util/src/queue_pair.rs
vhost_user_net/src/lib.rs
virtio-devices/src/net.rs
virtio-devices/src/seccomp_filters.rs
vmm/src/seccomp_filters.rs

The main idea behind this commit is to remove all the complexity
associated with TX/RX handling for virtio-net. By using writev() and
readv() syscalls, we could get rid of intermediate buffers for both
queues.
The complexity regarding the TAP registration has been simplified as
well. The RX queue is only processed when some data are ready to be
read from TAP. The event related to the RX queue getting more
descriptors only serves the purpose to register the TAP file if it's not
already.
With all these simplifications, the code is more readable but more
performant as well. We can see an improvement of 3Gbits/s for a single
queue device.

net_util: Simplify TX/RX queue handling

---

hypervisor/src/arch/x86/emulator/instructions/mov.rs

According to Intel's mnemonic (which is used by iced-x86) the first
argument is destination while the second is source.

hypervisor: emulator: fix MOVZX

---

vmm/src/config.rs

The help information displayed for our `--disk` option is incorrect and
incomplete, e.g. missing the `direct` and `poll_queue` field.

vmm: config: Fix and complete the help info for the '--disk' option

---

Cargo.lock
Cargo.toml
pci/Cargo.toml
pci/src/vfio.rs
virtio-devices/Cargo.toml
virtio-devices/src/iommu.rs
virtio-devices/src/lib.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs
virtio-devices/src/vsock/packet.rs
vm-device/Cargo.toml
vm-device/src/dma_mapping/mod.rs
vm-device/src/dma_mapping/vfio.rs
vm-device/src/lib.rs
vmm/Cargo.toml
vmm/src/device_manager.rs

With this PR, we move Cloud Hypervisor away from its internal `vfio-ioctls` crate to the upstream one from the Rust-VMM project.

Move to rust-vmm vfio-ioctls crate

---

Cargo.lock
fuzz/Cargo.lock
vhost_user_backend/src/lib.rs
virtio-devices/src/vhost_user/fs.rs

Moving to the latest version of the rust-vmm/vhost crate, before it gets
published on crates.io.

vhost: Bump to latest version from upstream

---

Jenkinsfile

Since the SGX server is down for maintenance, all builds are waiting on
the node agent to answer, causing all PRs to be blocked.
Let's disable temporarily the SGX CI until the server is back up.

Jenkinsfile: Temporarily disable SGX CI

---

pci/src/vfio.rs
virtio-devices/src/mem.rs
virtio-devices/src/seccomp_filters.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs

Through some reorganization of the memory management code, this pull request ensures the VFIO devices are only mapped with the active guest memory. By active, we mean the memory that is plugged from a virtio-mem perspective.
Fixes #1884

vmm: Fine grained management of the VFIO DMA mappings

---

vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs

When a vm is created with a pty device, on reboot the pty fd (sub
only) will only be associated with the vmm through the epoll event
loop. The fd being polled will have been closed due to the vm itself
dropping the pty files (and potentially reopening the fd index to a
different item making things quite confusing) and new pty fds will be
opened but not polled on for input.
This change creates a structure to encapsulate the information about
the pty fd (main File, sub File and the path to the sub File). On
reboot, a copy of the console and serial pty structs is then passed
down to the new Vm  instance which will be used instead of creating a
new pty device.
This resolves the underlying issue from #2316.

Try to restore pty configuration on reboot

---

Cargo.lock
Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
hypervisor/Cargo.toml

These need to be updated together as the kvm-ioctls depends upon a
strictly newer version of kvm-bindings which requires a rebase in the CH
fork.

build: Update kvm-ioctls and kvm-bindings dependencies

---

vmm/src/seccomp_filters.rs

This is the basis for TDX based operations on the various KVM file
descriptors.

vmm: seccomp: Add KVM_MEMORY_ENCRYPT_OP ioctl to seccomp filter

---

scripts/run_integration_tests_windows.sh

In order to run Windows test on MSHV we need to build and test using
MSHV feature.

scripts: Fix windows test script for running on MSHV

---

vmm/src/vm.rs

The MMIO structure contains the length rather than the maximum address
so it is necessary to subtract the starting address from the end address
to calculate the length.

vmm: tdx: Correctly populate the 64-bit MMIO region

---

virtio-devices/src/lib.rs
virtio-devices/src/vhost_user/fs.rs

Originally, VhostUserSetup is only used by vhost-user-fs. While
vhost-user-blk and vhost-user-net have their own error messages,
we rename VhostUserSetup to VhostUserFsSetup.
Signed-off-by: Jiachen Zhang <zhangjiachen.jaycee@bytedance.com>

vhost-user: Make ActivateError messages more consistent

---

docs/io_throttling.md
fuzz/fuzz_targets/block.rs
virtio-devices/src/block.rs
virtio-devices/src/lib.rs
virtio-devices/src/rate_limiter.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs

This patch is based on the 'rate_limiter' module from firecracker [1].
[1]https://github.com/firecracker-microvm/firecracker/tree/master/src/rate_limiter
Fixes: #1285

virtio-devices: add I/O rate limiter on block device

---

vmm/src/memory_manager.rs
vmm/src/migration.rs
vmm/src/vm.rs

Extend the existing url_to_path() to take the URL string and then use
that to simplify the snapshot/restore code paths.

vmm: Simplify snapshot/restore path handling

---

Cargo.lock
vmm/Cargo.toml
vmm/src/lib.rs
vmm/src/memory_manager.rs

The url crate is a very complete implementation of URL handling which is much more than Cloud Hypervisor requires. Replace it with simpler code and remove a lot of transitive dependencies.

Remove use of url crate

---

virtio-devices/src/seccomp_filters.rs

The `timerfd_settime` syscall is required when I/O throttling is
enabled.

virtio-devices: seccomp: Add 'timerfd_settime' to block device

---

Jenkinsfile
scripts/dev_cli.sh
scripts/run_integration_tests_vfio.sh
tests/integration.rs

Relying on a NVIDIA Tesla T4 card present in the SGX machine, this patch
enables baremetal VFIO testing, validated by running several NVIDIA
tools in the guest. The guest image has been prepared to include all the
software needed to run these tests.

ci: Enable baremetal VFIO integration tests

---

virtio-devices/src/lib.rs
virtio-devices/src/transport/pci_device.rs
vm-virtio/src/lib.rs
vm-virtio/src/queue.rs

In case of the virtio frontend driver doesn't need interupts for
certain queue event, it may explicitly write VIRTIO_MSI_NO_VECTOR
to the virtio common configuration, or it may doesn't configure
the event type vector at all.
This patch initializes both MSI-X configuration vector and queue vector
with VIRTIO_MSI_NO_VECTOR, so that the backend drivers won't trigger
unexpected interrupts to the guest.
Signed-off-by: Zide Chen <zide.chen@intel.com>

vm-virtio: initialize MSI-X vectors with VIRTIO_MSI_NO_VECTOR

---

src/main.rs

Remove the startup message containing incomplete VM configuration
details. It's a bit unusual for a tool such as Cloud Hypervisor to print
those kind of details which are a direct representation of the command
line.

main: Remove messages from startup

---

Cargo.lock
hypervisor/Cargo.toml
hypervisor/src/arch/x86/emulator/instructions/mod.rs

Bumps iced-x86 from 1.10.3 to 1.11.0.
Manual update of the code was needed since memory_displacement() was
deprecated and replaced with either memory_displacement32() or
memory_displacement64().

deps: bump iced-x86 from 1.10.3 to 1.11.0

---

Cargo.lock
hypervisor/src/kvm/mod.rs
hypervisor/src/lib.rs
hypervisor/src/mshv/mod.rs
vmm/src/interrupt.rs

These changes in kernel moves MSI routing to kernel:
https://github.com/sunilmut/linux/commits/vineeth/msi_routing
This PR is to add support for the kernel changes to move MSI routing to kernel.
This brings the irqfd API in parity with the KVM API - we no longer pass the routing information through the API, but uses a separate ioctl to pass the routing info to kernel beforehand.
msh-ioctls PR: https://github.com/cloud-hypervisor/mshv/pull/16

Support in cloud-hypervisor for in-kernel MSI routing

---

docs/seccomp.md

Document that seccomp is on and how to disable it along with a pointer
on how to identify missing syscalls during development.
Fixes #993

docs: Add seccomp documentation

---

net_util/src/queue_pair.rs

There is no point in queueing an empty descriptor in the list of iovecs.
Let's simply ignore such case and avoid some unnecessary processing.

net_util: Check descriptor size

---

README.md

The 0.3.0 release (re)supports booting stock Ubuntu images so users
should be pointed towards that.

README.md: Update URL for hypervisor-fw

---

vm-virtio/src/queue.rs

This returns trues if this descriptor has another descriptor linked to
it. Not whether this descriptor chain has another one following it.

vm-virtio: queue: Fix comment for DescriptorChain::has_next()

---

virtio-devices/src/block.rs

These are residual enum members from a previous refactoring.

virtio-devices: block: Remove unused members of Error enum

---

vmm/src/interrupt.rs

With Vineeth's work committed (https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2414), MSHV and KVM now share a lot more in common.
Take this chance to simplify the interrupt module a bit.

Simplify interrupt module

---

arch/src/x86_64/mod.rs

With CONFIG_PVH in stable kernels for some time we should deprecate the
use of alternative boot methods since this will lead to a much simpler
boot flow and CI process.
See: #2231

arch: Report use of deprecated LinuxBoot protocol

---

vmm/src/cpu.rs

The actual issue is the missing cpuid bits for the CPU dynamic partitioning support. There are two points to follow up, however:
- Adding a test involving the reproduce way as per #1799, best way is to be figured out to avoid UI usage.
- CpuManager functionality seems currently to have a bug introduced in 55a3a38e140c32748ed49acdacf6d54e59933048 at least for Windows guest. The number of CPUs as passed in `boot=` doesn't currently match the factual number in the VM. This needs more investigation and perhaps a separate fix.
Closes #1799.

hyperv: Fix CPU hotadd

---

acpi_tables/src/aml.rs
api_client/src/lib.rs
net_util/src/tap.rs
virtio-devices/src/vhost_user/fs.rs
vmm/src/config.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs

Specifically, this PR:
- Changes usage of struct constructors to match the order of fields in the struct declaration (or vice versa)
- Introduces usages of Option::map (or Option::cloned) where appropriate
With this PR, `cargo +nightly clippy` runs without warnings.

Fix lints added in clippy nightly.

---

vmm/src/device_manager.rs
vmm/src/vm.rs

Remove duplicated copies from vmm.

vmm: Use definition of MmioDeviceInfo from arch

---

vm-virtio/src/queue.rs

DescriptorChain::is_valid() wrongly used .checked_offset() to attempt to
validate that the descriptor's data is in valid memory. This works in
all cases except where the guest has placed the data at the very end of
the guest memory as the offset + offset will be outside the range (as
the combined offset will be the next byte and as such out of the guest
memory). Instead use the function .check_range() takes an offset and a
length to validate
This fixes issues see with error messages featuring the
DescriptorChainTooShort error.
Fixes: #2424

vm-virtio: queue: Fix descriptor chain validation

---

Cargo.lock
Cargo.toml
docs/io_throttling.md
net_util/Cargo.toml
net_util/src/lib.rs
net_util/src/queue_pair.rs
rate_limiter/Cargo.toml
rate_limiter/src/lib.rs
vhost_user_net/src/lib.rs
virtio-devices/Cargo.toml
virtio-devices/src/block.rs
virtio-devices/src/lib.rs
virtio-devices/src/net.rs
virtio-devices/src/seccomp_filters.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs

This PR add the rate limiter for virtio-net devices. Also, to resolve a dependency issue, the `rate_limiter` module is now moved into its own crate  (from crate `virtio-devices`). Note: the RX and TX queue share the same `rate limit` from user inputs, but they are throttled independently.
Fixes: #1286

virtio-devices: Add rate limiter for the virtio-net device

---

vmm/src/seccomp_filters.rs

clock_nanosleep() is triggered when hot-unplugging a vCPU.

vmm: Add missing syscall for vCPU unplug

---

docs/windows.md
tests/integration.rs

<strike>An additional function has been implemented to allow executing ch-remote with an arbitrary argument list.</strike>
A note on the CPU hotplug has been added to the doc.
Closes #2438

tests: Add test for CPU hotplug for Windows guest

---

README.md
docs/intel_sgx.md
docs/iommu.md
docs/snapshot_restore.md
tests/integration.rs

Non CONFIG_PVH ELF binaries were deprecated in 0.14.0. Update documentation to not encourage new use of bzImage files and move non-bzImage specific tests to the generic direct boot code path.

Update for LinuxBoot deprecation

---

scripts/run_integration_tests_x86_64.sh
scripts/sha1sums-x86_64
test_data/cloud-init/ubuntu/user-data
tests/integration.rs

Update the Ubuntu Focal image used as the guest image. It's based on the
latest Focal image released on April 1st 2021, and customized to include
all the utilities we need. As usual, snapd and pollinate services have
been removed.

ci: Update Ubuntu Focal custom image

---

docs/windows.md
tests/integration.rs

Both changes aim to document the absence of the CPU hot-remove
functionality on Windows.
Closes #2457.

tests: Extend Windows guest CPU hotplug test and update doc

---

tests/integration.rs

Since using bzImage is now deprecated, let's update the SGX integration
test to rely on vmlinux instead.
Fixes #2476

ci: Update SGX test to rely on vmlinux

---

arch/src/aarch64/gic/gicv3.rs
devices/src/ioapic.rs
devices/src/legacy/gpio_pl061.rs
devices/src/legacy/serial.rs
devices/src/legacy/uart_pl011.rs
pci/src/configuration.rs
pci/src/msix.rs
virtio-devices/src/block.rs
virtio-devices/src/console.rs
virtio-devices/src/iommu.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/transport/pci_common_config.rs
virtio-devices/src/transport/pci_device.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/watchdog.rs
vm-migration/src/lib.rs

Simplify snapshot & restore code by using generics to specify helper
functions that take / make a Serialize / Deserialize struct

misc: Simplify snapshot/restore by using helper functions

---

docs/windows.md
tests/integration.rs
vmm/src/memory_manager.rs

The patch makes sure care taken of a possible overflow and fixes the subtraction part, while adding a test and a documentation part.
Fixes #1800.

memory_manager: Fix address range calculation in MemorySlot

---

vmm/src/seccomp_filters.rs

This is used when running on a new libc like Fedora34.

vmm: seccomp: Add missing SYS_newfstatat

---

arch/src/aarch64/layout.rs

For now, memory layout on arm64 is sparse and is conflict with uefi.
Here, we do some rearrangement to let it compact and compatible with
uefi support.
@michael2012z @MrXinWang  @sboeuf

Update memory layout to accommodate uefi on arm64.

---

README.md
docs/device_model.md
release-notes.md

This way, the links can be navigated locally, not just on GitHub.

Use relative links between cloud-hypervisor docs

---

vmm/src/config.rs

Prohibit use of stdin, stdout and stderr.

Reject reserved fd from NetworkConfig

---

Cargo.lock
vmm/Cargo.toml

The master branch of 'micro_http' crate was renamed to 'main'.
Now the old branch name is making build errors.
Signed-off-by: Michael Zhao <michael.zhao@arm.com>

vmm: Update 'micro_http' crate branch to 'main'

---

resources/Dockerfile

In order to avoid possible issues with Bionic Beaver (18.04) as it's
getting old, we move the CI container to Focal Fossa (20.04).

resources: Update Dockerfile to Ubuntu Focal Fossa

---

pci/src/configuration.rs
pci/src/vfio.rs
virtio-devices/src/transport/pci_device.rs
vmm/src/device_manager.rs

This PR fixes a bug in the PCI BAR reprogramming detection logic, which fixes proper support for 64 bit BARs in Windows guests.
This fixes both network hotplug along with the weird MSIX issues we were seeing.
Fixes #1797 
Fixes #1798

pci: Fix BAR reprogramming detection logic

---

tests/integration.rs
virtio-devices/src/net.rs

Currently the VMM fails to reboot as the tap interface  fd has been closed. Duplicate it so that the original version is not closed and so can be reused in the new boot.

Support tap from fd (e.g. macvtap) usage over reboot

---

tests/integration.rs

It appears that mshv is not yet there to succeed with these tests. It is
suggested to ignore them and enable later one by one as the
functionality gets fixed.
/cc @russell-islam

tests: Disable test_windows_* for mshv

---

net_util/src/open_tap.rs
net_util/src/tap.rs
vhost_user_net/src/lib.rs
virtio-devices/src/net.rs
virtio-devices/src/net_util.rs

Whilst investigating #2528 I identified issues with the handling of virtio-net offload features. In particular the features should be only set on the tap if they are negotiated by the guest.

Start fixing network offload issues

---

src/main.rs
vmm/src/api/http.rs
vmm/src/api/mod.rs
vmm/src/lib.rs

To avoid race issues where the api-socket may not be created by the
time a cloud-hypervisor caller is ready to look for it, enable the
caller to pass the api-socket fd directly.
Avoid breaking current callers by allowing the --api-socket path to be
passed as it is now in addition to through the path argument.
Signed-off-by: William Douglas <william.r.douglas@gmail.com>

main: Enable the api-socket to be passed as an fd

---

scripts/run_integration_tests_x86_64.sh
tests/integration.rs

Use the PVH vmlinux for all tests (with the exception of the specific
bzImage test.)
See: #2231

tests: Don't build separate pvh/non-pvh vmlinux binary

---

docs/iommu.md
docs/vfio.md

With recent kernels, it is now expected to use "bind" control from the
sysfs in order to bind a specific device to the vfio-pci driver.
The use of "new_id" is still required but it is only needed once per
device type. Let's say you want to bind two virtio-net devices, you will
need to add the device_id:vendor_id pair through "new_id", while you
will be required to use "bind" for each device.
Fixes #2545

docs: Update VFIO binding instructions

---

README.md

Version 0.3.1 supports booting with stock groovy and hirsut.

README.md: Update rust-hypervisor-firmware version

---

vmm/src/api/http.rs
vmm/src/lib.rs
vmm/src/seccomp_filters.rs

Update the creation of the http server to always create the socket fd inside the vmm thread. This fixes #2534.

Change http thread seccomp

---

tests/integration.rs

test_reboot became flaky after the refactoring of the VM reboot code.
This is because we removed the ability to specify a custom timeout.
This patch fixes the issue by allowing a custom timeout of 120s to be
set.

tests: Fix reboot by allowing specifying the custom timeout

---

Cargo.lock
Cargo.toml
release-notes.md

The Rust manifiest requires a three part version number however we
continue with out plan to use two digits so the last part will not be
used.

build: Release v15.0

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_x86_64.sh
tests/integration.rs

The CI is failing due the git server that the submodules required for
this fork of QEMU need to build from is unavailable.

tests: Don't test virtiofsd

---

scripts/run_integration_tests_vfio.sh
tests/integration.rs

Moving to latest Ubuntu version as the guest image is needed to move to more recent guest kernel (5.11). With more recent kernels, we are able to add PCI hotplug as well as memory hotplug (both ACPI and virtio-mem) tests to the VFIO baremetal CI.
Fixes #2404

tests: Extend VFIO baremetal integration tests relying on Ubuntu 21.04

---

vmm/src/vm.rs

This helps with debugging VM behaviour when the VM is created via an
API.

vmm: Output config used for booting VM at info!() level

---

docs/vhost-user-blk-testing.md

Updated the obsoleted path of `vhost` the in spdk folder and fixed some
formatting issues.

docs: Update documentation `vhost-user-blk-testing.md`

---

virtio-devices/src/net.rs

In some situations (booting with OVMF) fewer queues will be enabled
therefore we should iterate over the number of enabled queues (as passed
into VirtioDevice::activate()) rather than the number of create tap
devices.
Fixes: #2578

virtio-devices: net: Loop over enabled queue pairs when activating

---

tests/integration.rs
vhost_user_backend/src/lib.rs
vhost_user_block/src/lib.rs
vhost_user_net/src/lib.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/net.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs

This PR adds global support for `vhost-user-net` backends using the `client` mode. This means the backend is running as the client instead of running as the server by default. This is useful for OVS-DPDK, as it is deprecated to run in `server` mode.
Fixes #1745

vhost-user-net: Add support for client mode

---

docs/vhost-user-net-testing.md

Updated the obsoleted instructions and scripts, based on Open vSwitch
v2.15(.90), DPDK stable v20.11(.1), and Cloud Hypervisor v15.0 (on
Ubuntu 20.04.1).

docs: Update documentation `vhost-user-net-testing.md`

---

tests/integration.rs

This PR first refactors the global integration test code by removing the need for lifetime on both `DiskConfig` and `Guest`. This simplifies the code and allows a guest structure to be easily embedded into a higher level one.
Relying on this change, the Windows specific code is refactored by introducing `WindowsGuest` wrapping structure, making the integration tests easier to read and maintain.
This is preparatory work for adding multiple IP support to our Windows testing.

tests: Refactoring in preparation for adding multi IP support to Windows CI

---

Jenkinsfile
scripts/run_integration_tests_windows.sh
tests/integration.rs

Relying on dnsmasq running on the host, the Windows guest are now
getting allocated with the expected IP addresses. This allows for
multiple VMs, therefore multiple tests to run in parallel.
The end goal is to reduce the time spent running Windows integration
tests.
Fixes #1891

tests: Dynamically assign IPs for Windows integration tests

---

tests/integration.rs

Create as many queues as there are boot CPUs for block and twice as many
for net.

tests: use MQ for both block and net in Windows tests

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_x86_64.sh
tests/integration.rs

Re-enable virtiofsd testing now that issues with capstone repository
have been resolved.
This reverts commit 2aec0a92a59b5c349a56ab21537c579f8efe7db9.

tests: Re-enable virtiofsd tests

---

Jenkinsfile

Since SGX and VFIO tests don't need to be run on pull requests, we
should not have to wait for the corresponding node (bionic-sgx or
bionic-vfio) to become available in order to skip them.
Fixes #2607

Jenkinsfile: Don't wait for a node that is not being used

---

tests/integration.rs

Bump the sleep time before checking the guest RAM size from 10 to 30
seconds. This will help the VFIO baremetal CI passing more consistently.
Fixes #2606

tests: vfio: Increase time for memory hotplug

---

.github/workflows/quality-aarch64.yaml
arch/Cargo.toml
arch/src/aarch64/fdt.rs
arch/src/aarch64/mod.rs
arch/src/lib.rs
resources/Dockerfile

This PR move the libfdt methods to rust native helpers from rust-vmm `vm-fdt` crate when creating the FDT. Also this PR removes the redundant libfdt in github action and docker images.

AArch64: Use rust native FDT methods and remove libfdt

---

virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/handler.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs

Some refactoring is performed in order to always expect the irqfd to be
provided by VirtioInterrupt trait. In case no irqfd is available, we
simply fail initializing the vhost-user device. This allows for further
simplification since we can assume the interrupt will always be
triggered directly by the vhost-user backend without proxying through
the VMM. This allows for complete removal of the dedicated thread for
both block and net.
vhost-user-fs is a bit more complex as it requires the slave request
protocol feature in order to support DAX. That's why we still need the
VMM to interfere and therefore run a dedicated thread for it.

virtio-devices: vhost-user: Don't run threads for net and block

---

resources/Dockerfile

This will make `mkfs.ntfs` available in the next image update, so then
it can be used in the tests.

docker: Add ntfs-3g to the package list

---

README.md
docs/hotplug.md
docs/macvtap-bridge.md
docs/profiling.md
docs/vfio.md
virtio-devices/src/vsock/packet.rs
vm-virtio/src/queue.rs
vmm/src/lib.rs

Fix some typos or misspellings without functional change.
Signed-off-by: Dayu Liu <liu.dayu@zte.com.cn>

docs: Fix some typos in docs and comments

---

arch/src/aarch64/fdt.rs
arch/src/aarch64/layout.rs
arch/src/aarch64/mod.rs
arch/src/aarch64/regs.rs
scripts/run_integration_tests_aarch64.sh
vmm/src/acpi.rs

Partially fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/2178.
This PR is part of implementing AArch64 ACPI support.
Changes:
- Update memory layout
- Verify ACPI build

Prepare memory layout and test infrastructure for AArch64 ACPI

---

vmm/src/acpi.rs

Partially fixes #2178.
This is a preparing change for adding ACPI tables on AArch64.
To make it easier to extend for multi-architecture, the code of create_acpi_tables() was split into multiple functions.

acpi: Refactor create_acpi_tables()

---

docs/windows.md
tests/integration.rs

This patch adds the necessary tooling, a test and a documentation note for the disk hotplug functionality.
The disk image is created on the fly. Yet FAT is used as the tooling to create NTFS is not present.
The tooling is to be made more flexible to support further tests for multiple disk device hotplug. Prior to that, `mkfs.ntfs` will need to be added to the docker image.
Closes #2539.

Windows disk hotplug test

---

hypervisor/src/hypervisor.rs
hypervisor/src/kvm/mod.rs
vmm/src/cpu.rs
vmm/src/vm.rs

Slowly working towards #2542 by removing the requirement for the vmm crate to know hypervisor specific details.

Reduce hypervisor specific leaks into vmm crate

---

tests/integration.rs

Yet another small refactoring step for WindowsGuest
after f56471566b313207c9cdd32ac58b98b711fa6ab6.
For this particular case - there's currently neither overloading nor
default argument support in Rust (except a macro or other tricky stuff),
so keep the timeout and other options default for now.

tests: Pull common code into a separate method

---

net_util/src/ctrl_queue.rs
net_util/src/lib.rs
vhost_user_backend/src/lib.rs
vhost_user_net/src/lib.rs
virtio-devices/src/seccomp_filters.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs
vmm/src/device_manager.rs

Having the control queue running as a VMM thread while the worker queues were running in the backend was an incorrect design. This PR fixes this issue by moving the control queue handling to the vhost-user-net backend, allowing for further simplification of the vhost-user-net device in the VMM codebase.
Fixes #2562

vhost-user-net: Move the control queue to the backend

---

scripts/sha1sums-aarch64

The sha1sum of bionic-server-cloudimg-arm64.qcow2 was obsolete.
The failing signature was first found in local test. After refreshing the file on CI server, the fault was seen in CI.

scripts: Fix an obselete sha1sum

---

vmm/src/lib.rs
vmm/src/vm.rs

In migration, vm object is created by new_from_migration with
NULL kvm clock. so vm.set_clock will not be called during vm resume.
If the guest using kvm-clock, the ticks will be stopped after migration.
As clock was already saved to snapshot, add a method to restore it before
vm resume in migration. after that, guest's kvm-clock works well.
Signed-off-by: Ren Lei <ren.lei4@zte.com.cn>

vmm: support restore KVM clock in migration

---

virtio-devices/src/vhost_user/vu_common_ctrl.rs

The VIRTIO features should not be set before they are acked from the
guest. This code was only present to overcome a vhost crate limitation
that was expecting the VIRTIO features to be set before we could fetch
and set the protocol features.
The vhost crate has been recently fixed by removing the limitation,
therefore there's no need for this workaround in the Cloud Hypervisor
codebase anymore.

virtio-devices: vhost_user: Don't set features before ACK from guest

---

acpi_tables/src/sdt.rs
arch/src/aarch64/fdt.rs
arch/src/aarch64/gic/mod.rs
arch/src/aarch64/layout.rs
arch/src/lib.rs
devices/Cargo.toml
devices/src/gic.rs
vm-allocator/src/system.rs
vmm/src/acpi.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/interrupt.rs
vmm/src/vm.rs

Partially fixes #2178.
This PR implements all the ACPI tables needed on AArch64:
1. MADT
2. DSDT
3. MCFG
4. GTDT
5. SPCR
6. IORT
The new code has not been covered by integration test case. The test requires integrating EDK2. It will be added in a separate PR latter.
For the correctness of the code here, please refer to the original PR https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2241.

AArch64 ACPI tables

---

Cargo.lock
virtio-devices/src/lib.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/net.rs

A lot of the VIRTIO reserved features should be supported or not by the
vhost-user backend. That means on the VMM side, these features should be
available, so that they don't get lost during the negotiation.

virtio-devices: vhost_user: Enable most virtio reserved features

---

net_util/src/lib.rs
vhost_user_net/src/lib.rs
virtio-devices/src/seccomp_filters.rs
virtio-devices/src/vhost_user/net.rs
vmm/src/device_manager.rs

We thought moving the control queue to the backend would be a good idea, as it simplified the VMM code and was moving all queue handling to the backend. Unfortunately, that's not how the existing backends are designed (such as OVS-DPDK), which means we have to roll some of our changes back.
Fixes #2671

vhost-user-net: Move control queue handling back to the VMM

---

resources/Dockerfile

The Dockerfile is extended with some new instructions to install the
OVS-DPDK packages. This will be useful for writing new integration tests
and make sure OVS-DPDK is working properly.
This also updates the Rust toolchain from 1.51.0 to 1.52.1.

resources: Add ovs-dpdk install to Dockerfile

---

Cargo.lock
arch/src/aarch64/fdt.rs

Replaces https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2684.
Interface of vm-fdt changed.
Updated aarch64 code to adapt.

arch: Bump vm-fdt from 13ab882 to 956b5a5

---

Jenkinsfile
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_x86_64.sh
tests/integration.rs

In order to avoid regression regarding OVS-DPDK support, a new
integration test is added. This test consists of running two VMs, both
attached to a distinct OVS port, where both ports are connected to an
OVS bridge. Once the VM are running, the test validates the connection
between the two VMs works correctly.

ci: Add OVS-DPDK integration test

---

tests/integration.rs

This test is flaking out regularly, particularly on the musl build.

tests: Temporarily disable test_ovs_dpdk

---

arch/src/aarch64/gic/gicv3.rs
arch/src/aarch64/gic/gicv3_its.rs
arch/src/aarch64/gic/mod.rs
arch/src/aarch64/gic/redist_regs.rs
arch/src/aarch64/mod.rs
devices/src/gic.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

This PR refactored the GIC (Generic Interrupt Controller) related code in `vmm/` (mainly `DeviceManager`)  and `arch/` for better design.
Issues to resolve:
- An AArch64 GIC device instance was held in DeviceManager, it's better to move it somewhere architecture specific;
- A function for calculating `gicr-typer` was also added in DeviceManager, but in fact it is totally arch specific and it has nothing with DeviceManager.

Refactor GIC (AArch64) related source code

---

hypervisor/src/kvm/mod.rs

For now enable the TDX attribute for TDX debug.

hypervisor: tdx: Unconditionally enable TDX debug

---

vmm/src/cpu.rs
vmm/src/vm.rs

This matches with the features that QEMU clears as they are not
supported with TDX.

vmm: tdx: Clear unsupported KVM PV features

---

virtio-devices/src/seccomp_filters.rs

The control queue was missing rt_sigprocmask syscall, which was causing
a crash when the VM was shutdown.

virtio-devices: Update seccomp filters for vhost-user-net control queue

---

virtio-devices/src/vhost_user/vu_common_ctrl.rs

The logic was reversed, causing the retry to fail consistently.

virtio-devices: vhost_user: Fix connection retry logic

---

virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/console.rs
virtio-devices/src/device.rs
virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/watchdog.rs

Add a helper to VirtioCommon which returns duplicates of the EventFds
for kill and pause event.

virtio-devices: Add helper to VirtioCommon for EventFd duplication

---

Cargo.lock
hypervisor/src/mshv/mod.rs

MSHV set_xsave got changed to fix the Snapshot and restore issue.
This patch fixes the API call.

hypervisor: Fix MSHV set_xsave API call

---

tests/integration.rs

Enable `test_ovs_dpdk` now that it's been fixed by assigning the VMs to NUMA node 0.
Also improves the test by using OVS in client mode since server mode is deprecated, along with using `netcat` to simplify the validation about connectivity being functional.

tests: Re-enable test_ovs_dpdk

---

virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs

Based on the vhost-user-net reconnection implementation  #2694, this PR enables the socket reconnection support for vhost-user-blk backends. 
I tested it with both QEMU vhost-user-blk daemon and cloud-hypervisor vhost-user-blk daemon. If there is no inflight I/O requests in the virtqueue when crashing, the daemons work properly after reconnection.

Vhost-user-blk socket reconnection

---

test_infra/src/lib.rs
tests/integration.rs

This PR simplifies a bit the integration tests code by replacing `ssh_command_ok()` with `ssh_command()` now that it returns an actual error if the exit code is not 0.
Also, it factorizes some code executing commands on the host, by introducing two new wrapper functions in `test_infra`.

ci: Cleanup and factorize a few functions in the integration tests

---

acpi_tables/Cargo.toml
arch/src/aarch64/fdt.rs
arch/src/aarch64/layout.rs
arch/src/aarch64/mod.rs
arch/src/aarch64/uefi.rs
arch/src/lib.rs
resources/Dockerfile
scripts/run_integration_tests_aarch64.sh
tests/integration.rs
vmm/Cargo.toml
vmm/src/device_manager.rs
vmm/src/vm.rs

Partially fixes #2178.
This PR enabled ACPI on AArch64 and integrated with EDK2.
What's included:
- Updating some AML and FDT code
- Introducing EDK2 in CI
- Adding a basic test case
The PR is not totally ready. There are some issues to fix and discuss. Please see my comments.

Enable ACPI on AArch64

---

docs/custom-image.md
scripts/run_integration_tests_x86_64.sh
scripts/sha1sums-x86_64
test_data/cloud-init/ubuntu/user-data
tests/integration.rs

Some new integration tests will require the "stress" binary to be
present in the guest in order to run correctly.

ci: Update guest cloud image by installing "stress" utility

---

Cargo.lock

`Cargo.lock` should have been updated when the PR #2680 introduced the dependency onto the `uuid` crate. This PR is here to fix this.

deps: Update Cargo.lock to include uuid crate

---

arch/src/aarch64/mod.rs
hypervisor/src/hypervisor.rs
hypervisor/src/kvm/mod.rs

https://github.com/rust-vmm/kvm-ioctls/pull/94 has provided us with the ability to get `Host_IPA_Limit` for AArch64, and hence the current hardcoded host IPA size for AArch64 can be removed.

AArch64: Remove hardcoded host IPA size

---

tests/integration.rs
vmm/src/seccomp_filters.rs

The PR contains:
- Allowing syscall `SYS_readlinkat` to unblock pty console
- Enabling pty test case

Enable pty console on AArch64

---

tests/integration.rs

We somehow both missed this one last time.... @michael2012z

tests: Enable AArch64 API pause/resume test case

---

tests/integration.rs

Some vhost-user test cases used to be unstable in the early stage of AArch64 enabling.
But a recent test revealed good result. No failure was seen in 20 reruns.

Unblock some vhost-user tests on AArch64

---

Cargo.lock
fuzz/Cargo.lock
vhost_user_backend/src/lib.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs

The first commit supports inflight shmfd transferring, and the second commit enables this support for vhost-user-blk.

Support vhost-user inflight I/O tracking shmfd transferring

---

virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/net.rs

Since the reconnection thread took on the responsibility to handle
backend initiated requests as well, the variable naming should reflect
this by avoiding the "reconnect" prefix.

virtio-devices: vhost_user: Fix wrong naming regarding reconnection

---

Cargo.lock
virtio-devices/src/vhost_user/vu_common_ctrl.rs

Now that vhost crate allows the caller to set the header flags, we can
set NEED_REPLY whenever the REPLY_ACK protocol feature is supported from
both ends.

virtio-devices: vhost_user: Set NEED_REPLY when REPLY_ACK is supported

---

tests/integration.rs

Additionally, he disk creation routine is extended to support NTFS and
variable image size.
This solves the first bullet point from #1916.

tests: Add test for Windows guest multiple disk hotplug

---

arch/Cargo.toml
arch/src/aarch64/fdt.rs
arch/src/aarch64/mod.rs

To debug the FDT (Flattened Device Tree), we usually need to modify source code to save the generted DTB data to disk, and use `dtc` command to decode the binary file into a text file to analyze.
It would be ideal if the FDT content can be seen in log.
This commit makes it real by:
- Introducing `fdt` crate for parsing FDT.
- Printing the content of the FDT in tree view.
The parsing and printing only happen when Debug level logging enabled. With these log, debugging issues like https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2762 would be convenient.

Add log for FDT debugging on AArch64

---

Jenkinsfile

Groovy is EOLed on 2021-07-22.
Fixes: #2769

Jenkins: Migrate workers to Hirsute Hippo

---

vmm/src/cpu.rs

Filter out the KVM_FEATURE_STEAL_TIME_BIT when running with TDX.

vmm: tdx: Add KVM_FEATURE_STEAL_TIME_BIT to filtered bits

---

Jenkinsfile

Since we ran into issues while using the Azure credentials plugin for
Jenkins, let's rely directly on the Azure CLI to download the Windows
guest image along with the modified OVMF firmware.

Jenkinsfile: Update the way to download private images

---

tests/integration.rs

The virtio_balloon test is a bit flaky since we can't really know how
much the balloon is gonna be deflated when the guest is under memory
pressure. That's why it's safer to simply check that the balloon is not
the initial size anymore.
One small detail, but we don't need to check for the balloon size to be
higher than 0 since the returned value is a u64.

tests: Fix virtio_balloon integration test

---

vmm/src/device_manager.rs

The Linux kernel expects that any PCI devices that advertise I/O bars
have use an address that is within the range advertised by the bus
itself. Unfortunately we were not advertising any I/O ports associated
with the PCI bus in the ACPI tables.

vmm: Add I/O port range to PCI bus resources

---

hypervisor/src/mshv/x86_64/mod.rs

Co-Developed-by: Nuno Das Neves <nudasnev@microsoft.com>
Signed-off-by: Nuno Das Neves <nudasnev@microsoft.com>

hypervisor: Set MTRRdefType in MSHV guest initialization to enable cpu caching

---

Cargo.lock
fuzz/Cargo.lock
vhost_user_backend/src/lib.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs

This dependency bump needed some manual handling since the API changed
quite a lot regarding some RawFd being changed into either File or
AsRawFd traits.

deps: Update vhost crate from 1a03a2a to 9982541

---

.github/workflows/quality-aarch64.yaml
arch/src/aarch64/layout.rs
arch/src/aarch64/mod.rs
docs/arm64.md
scripts/run_integration_tests_aarch64.sh
tests/integration.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs

This PR optimize ACPI on AArch64 in following aspects:
- Reduced the UEFI space from 64M to 4M.
- Simplified build instructions. After enabling ACPI, we can build with default features on AArch64.
- Simplified integration test steps.
- Simplified document.

Optimize ACPI on AArch64

---

vmm/src/api/mod.rs
vmm/src/lib.rs
vmm/src/vm.rs

Couple of refactoring to ensure all handlers for `ApiRequest` in `control_loop` are
consistent and minimum. Hope it makes the code simpler and read better.
No functional changes.

vmm: Refactor slightly 'vm_create', 'vm_boot', and 'control_loop'

---

.github/workflows/quality-aarch64.yaml
devices/src/legacy/gpio_pl061.rs
devices/src/legacy/rtc_pl031.rs
vmm/src/cpu.rs
vmm/src/interrupt.rs
vmm/src/vm.rs

Enabled `--all` option in clippy test and fixed all errors.

Enhance AArch64 clippy

---

tests/integration.rs
vmm/src/acpi.rs

This PR enables the arm64 NUMA support (Using ACPI). The device tree support will be submitted in the future :)

AArch64: Enable arm64 NUMA support using ACPI

---

test_infra/src/lib.rs

warning: use of `expect` followed by a function call
--> test_infra/src/lib.rs:598:10
|
598 |         .expect(&format!("Expected '{}' to run", command))
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|_| panic!("Expected '{}' to run", command))`
|
= note: `#[warn(clippy::expect_fun_call)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call
warning: use of `expect` followed by a function call
--> test_infra/src/lib.rs:605:10
|
605 |         .expect(&format!("Expected '{}' to run", command))
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|_| panic!("Expected '{}' to run", command))`
|
= help: for further information visit …

test_infra: Fix clippy warning (expect_fun_call)

---

tests/integration.rs

The output from getty ("login:") does not always appear. This can be
observed interactively when booting the VM. (Mashing return will bring
it up.) Instead of checking for that string to ensure the VM has booted
instead check for a message from systemd to say it has started the SSH
daemon.
Fixes: #2799

tests: Change string checking for console success

---

net_util/src/queue_pair.rs
vhost_user_net/src/lib.rs
virtio-devices/src/net.rs

If writing to the TAP returns EAGAIN then listen for the TAP to be
writable. When the TAP becomes writable attempt to process the TX queue
again.
Fixes: #2807

virtio-devices, net_util, vhost_user_net: Retry writing to TAP

---

Cargo.lock
hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
pci/src/vfio.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

Previously the same function was used to both create and remove regions.
This worked on KVM because it uses size 0 to indicate removal.
MSHV has two calls -- one for creation and one for removal. It also
requires having the size field available because it is not slot based.
Split set_user_memory_region to {create/remove}_user_memory_region. For
KVM they still use set_user_memory_region underneath, but for MSHV they
map to different functions.
This fixes user memory region removal on MSHV.

Fix user space region removal on MSHV

---

pci/src/vfio.rs

The BAR calculation code was incorrect for calculating I/O BARs but also
has misleading comments (mixing bits and bytes, first and least
significant, etc).
This change adjusts the algorithm to more closely match the version
described in the PCI specification and takes advantage of Rust's binary
literals for ease of reading. Although this is slightly longer by
calculating the 64-bit and 32-bit paths separately I think this is
easier to read.

pci: vfio: Fix and clarify BAR calculation code

---

arch/src/aarch64/gic/gicv3.rs
arch/src/aarch64/gic/gicv3_its.rs
arch/src/aarch64/gic/mod.rs
arch/src/aarch64/gic/redist_regs.rs
tests/integration.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

Finally we have something works...
As the `virtio-mmio` snapshot/restore code has been merged before, this PR is mainly focusing on the missing `virtio-pci` and GICv3ITS support.
Thanks @jongwu for debugging and testing the prototype :))

AArch64: Enable snapshot/restore

---

arch/src/x86_64/tdx/mod.rs
vmm/src/vm.rs

This patch fixes a few things to support TDVF correctly.
The HOB memory resources must contain EFI_RESOURCE_ATTRIBUTE_ENCRYPTED
attribute.
Any section with a base address within the already allocated guest RAM
must not be allocated.
The list of TD_HOB memory resources should contain both TempMem and
TdHob sections as well.

arch, vmm: Fix TDVF section handling

---

Cargo.lock
arch/src/aarch64/fdt.rs

Upstream commit `02d1b8f` changed the definition of `FdtWriter::new()`, and therefore we need a manual bump to avoid clippy issue (see https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2831).
Bumps [vm-fdt](https://github.com/rust-vmm/vm-fdt) from `bbfd1e7` to `02d1b8f`.
- [Release notes](https://github.com/rust-vmm/vm-fdt/releases)
- [Commits](https://github.com/rust-vmm/vm-fdt/compare/bbfd1e7719eef34e42f7853b37a871abbd96cafe...02d1b8fde288f42b4e2c0a0ec036f70ab797141c)
---
updated-dependencies:
- dependency-name: vm-fdt
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>

build: bump vm-fdt from `bbfd1e7` to `02d1b8f`

---

hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

The SGX provisioning feature was exposed to the guest but it was not correctly backed from a host perspective. This PR enables the feature by opening the provisioning device on the host and by enabling the feature through KVM.
Fixes #2756

Add support for SGX provisioning

---

resources/linux-config-x86_64

Enabling CONFIG_HYPERV in the Linux Kernel allows
guest to use hyperv clock source. This changes
improves guest performance. Without this changes
we saw slowness in the guest on MSHV.
Signed-off-by: Vineeth Pillai <viremana@linux.microsoft.com>

resources: Enable CONFIG_HYPERV in the kernel config

---

arch/src/x86_64/mod.rs
docs/intel_sgx.md
docs/memory.md
tests/integration.rs
vmm/src/acpi.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/cpu.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

This PR gives the user the ability to choose the NUMA node related to each SGX EPC section.
Fixes #2757

SGX: Allow EPC sections to be attached to specific NUMA nodes

---

docs/arm64.md
scripts/run_integration_tests_aarch64.sh

The edk2 upstream has already suppoorted AArch64 Cloud Hypervisor (see https://github.com/tianocore/edk2/commit/0e3b6bd0ee753d77c957480657060ae1ea5172b0),
and hence we can use upstream edk2 in CI and doc.

docs, scripts: Use upstream edk2 for AArch64

---

arch/src/x86_64/tdx/mod.rs

The handoff table was missing the boot_mode field.
Suggested-by: Jiaqi Gao <jiaqi.gao@intel.com>

arch: x86_64: tdx: Fix HobHandoffInfoTable

---

fuzz/Cargo.lock
fuzz/Cargo.toml

Just like how it is done in the top-level Cargo.toml.
This fixes a warning [0] when building the fuzzer binaries.
[0] https://github.com/rust-lang/rust/issues/82523

fuzz: patch versionize_derive in Cargo.toml

---

Cargo.lock
fuzz/Cargo.lock
vm-device/Cargo.toml
vmm/Cargo.toml

PR rust-vmm/vfio-ioctls#14 has been merged.
Make use of the new feature gate in Cloud Hypervisor.

Make use of the new KVM feature gate in vfio-ioctls

---

Cargo.lock
arch/Cargo.toml
arch/src/lib.rs
arch/src/x86_64/mod.rs
vmm/src/cpu.rs

This refactoring ensures all CPUID related operations are centralized in
`arch::x86_64` module, and exposes only two related public functions to
the vmm crate, e.g. `generate_common_cpuid` and `configure_vcpu`.

arch, vmm: Move "generate_common_cpuid" from "CpuManager" to "arch"

---

vmm/src/device_manager.rs
vmm/src/vm.rs

When running a TDX guest, we need the virtio drivers to use the DMA API
to share specific memory pages with the VMM on the host. The point is to
let the VMM get access to the pages related to the buffers pointed by
the virtqueues.
The way to force the virtio drivers to use the DMA API is by exposing
the virtio devices with the feature VIRTIO_F_IOMMU_PLATFORM. This is a
feature indicating the device will require some address translation, as
it will not deal directly with physical addresses.
Cloud Hypervisor takes care of this requirement by adding a generic
parameter called "force_iommu". This parameter value is decided based on
the "tdx" feature gate, and then passed to the DeviceManager. It's up to
the DeviceManager to use this parameter on every virtio device creation,
which will imply …

vmm: Force VIRTIO_F_IOMMU_PLATFORM when running TDX

---

vmm/src/cpu.rs
vmm/src/vm.rs

When running TDX guest, the Guest Physical Address space is limited by
a shared bit that is located on bit 47 for 4 level paging, and on bit 51
for 5 level paging (when GPAW bit is 1). In order to keep things simple,
and since a 47 bits address space is 128TiB large, we ensure to limit
the physical addressable space to 47 bits when runnning TDX.

vmm: Limit physical address space for TDX

---

Cargo.lock
api_client/Cargo.toml
api_client/src/lib.rs
src/bin/ch-remote.rs
tests/integration.rs
vmm/src/seccomp_filters.rs

By adding the support for sending file descriptor along with the `add-net` command through the `ch-remote` tool, we are now able to provide a dedicated integration test validating that a `macvtap` interface can be hotplugged after the VMM has been started.

Add macvtap hotplug support and validation

---

Cargo.lock
Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
virtio-devices/Cargo.toml
vmm/Cargo.toml

Updating both the global `Cargo.lock` and the one in `fuzz` crate to bump `seccomp` from v0.24.4 to v0.24.5.

build: bump seccomp from v0.24.4 to v0.24.5

---

hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

This patch extends slightly the current live-migration code path with
the ability to dynamically start and stop logging dirty-pages, which
relies on two new methods added to the `hypervisor::vm::Vm` Trait. This
patch also contains a complete implementation of the two new methods
based on `kvm` and placeholders for `mshv` in the `hypervisor` crate.
Fixes: #2858

hypervisor, vmm: Add dynamic control of logging dirty pages for live-migration

---

arch/src/lib.rs
arch/src/x86_64/mod.rs
vmm/src/lib.rs
vmm/src/vm.rs

This patch adds CPUID check to the 'Config' step of live migration
We now send not only the 'VmConfig' at the 'Command::Config' step of
live migration, but also send the 'common CPUID'. In this way, we can
check the compatibility of CPUID features between the source and
destination VMs, and abort live migration early if needed.
This patch also added the same CPUID check for snapshot/restore.

arch, vmm: Add CPUID check to live migration and snapshot/restore

---

hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

Following KVM interfaces, the `hypervisor` crate now provides interfaces
to start/stop the dirty pages logging on a per region basis, and asks
its users (e.g. the `vmm` crate) to iterate over the regions that needs
dirty pages log. MSHV only has a global control to start/stop dirty
pages log on all regions at once.
This patch refactors related APIs from the `hypervisor` crate to provide
a global control to start/stop dirty pages log (following MSHV's
behaviors), and keeps tracking the regions need dirty pages log for
KVM. It avoids leaking hypervisor-specific behaviors out of the
`hypervisor` crate.
This use the above changes, we also need to explicitly tell the hypervisor (KVM)
whether a region needs dirty-pages-log when it is created. This is done through
reverting commit  f063346. …

hypervisor, vmm: Abstract the interfaces to start/stop dirty log to support both KVM and MSHV

---

devices/src/acpi.rs
devices/src/gic.rs
devices/src/ioapic.rs
devices/src/legacy/gpio_pl061.rs
devices/src/legacy/rtc_pl031.rs
devices/src/legacy/serial.rs
devices/src/legacy/uart_pl011.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
pci/src/msi.rs
pci/src/msix.rs
pci/src/vfio.rs
virtio-devices/src/transport/pci_device.rs
vm-device/src/interrupt/mod.rs
vmm/src/cpu.rs
vmm/src/interrupt.rs
vmm/src/vm.rs

With the new beta version, clippy complains about redundant allocation
when using `Arc<Box<dyn T>>`, and suggests replacing it simply with
`Arc<dyn T>`.

clippy: Fix redundant allocations

---

tests/integration.rs
vhost_user_net/src/lib.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs
vmm/src/device_manager.rs

Add the support for snapshot/restore to all vhost-user devices from the VMM device model. Only partial support is provided for virtio-fs since it will require some extra support from the `virtiofsd` daemon.

vhost-user: Add support for snapshot/restore

---

hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
vmm/src/memory_manager.rs
vmm/src/seccomp_filters.rs

This PR adds the APIs needed for live migrations on MSHV. Modifies existing get_dirty_log function to accept extra parameters needed for MSHV. Implement start/stop_dirty_log for MSHV. For this PR I have tested Live migrations and measures some numbers. The numbers are very close to KVM.  Steps used to test this on MSHV:
Source VM:
sudo ./cloud-hypervisor/target/release/cloud-hypervisor --kernel ./linux-cloud-hypervisor/arch/x86/boot/compressed/vmlinux.bin --disk path=focal-server-cloudimg-amd64.raw --cpus boot=4 --memory size=1G --cmdline "root=/dev/vda1 console=ttyS0" --serial tty --console off --api-socket=/tmp/api1 
Destination VM: 
sudo ./cloud-hypervisor/target/release/cloud-hypervisor --api-socket=/tmp/api2
#Receiving migration for the destination
sudo …

Add live migration support on MSHV

---

virtio-devices/src/seccomp_filters.rs
vmm/src/seccomp_filters.rs

This patch adds all the seccomp rules missing for MSHV.
With this patch MSFT internal CI runs with seccomp enabled.

vmm, virtio-devices: Add missing seccomp rules for MSHV

---

Cargo.lock
hypervisor/Cargo.toml

Moving the MSHV crate form Cloud Hypervisor to rust-vmm
is done. This patch update the MSHV referent to rust-vmm

hypervisor: Use MSHV crates from rust-vmm

---

vhost_user_block/src/main.rs
vhost_user_net/src/main.rs

I don't think the `min_values(1)` was doing anything, since `takes_value(true)` was already set, and after this change I still get an error if I try to supply the argument with no value.
But the unwrap below would fail if the argument wasn't supplied at all.  By setting `required(true)` we get a nice message from clap instead.

vhost_user_*: mark --*-backend as required

---

Cargo.lock
vhost_user_block/Cargo.toml
vhost_user_block/src/main.rs
vhost_user_net/Cargo.toml
vhost_user_net/src/main.rs

These crates are written to produce log messages using the error!
macro, but their logs didn't actually go anywhere, which made it very
difficult to debug when they're not working.
I've used env_logger here because it's the same log implementation
that the hypervisor crate uses.

vhost_user_*: set up logging

---

docs/fuzzing.md
docs/windows.md

Replacing QCOW mentions with other viable options. There is still
docs/custom-image.md which talks about creating QCOW, however it
might be more convenient to be touched when the actual changes
are indeed there.
Related to #1985.

doc: Stop advertizing QCOW usage at some places in doc

---

Cargo.lock
fuzz/Cargo.lock
virtio-devices/Cargo.toml
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs
vm-migration/src/lib.rs
vm-migration/src/protocol.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

This PR provides the migration support to all vhost-user devices through the extension of the `Migratable` trait.
Fixes #2813

vhost-user: Migration support

---

arch/src/aarch64/fdt.rs
arch/src/aarch64/mod.rs
tests/integration.rs
vmm/src/acpi.rs
vmm/src/cpu.rs
vmm/src/vm.rs

This PR adds the device tree and ACPI support for AArch64 CPU topology. Related ACPI integration test cases are also added.

AArch64: Support CPU topology (ACPI and Device Tree)

---

virtio-devices/src/seccomp_filters.rs
vmm/src/seccomp_filters.rs

Allow vsocks to connect to Unix sockets on the host running
cloud-hypervisor with enabled seccomp.
Reported-by: Philippe Schaaf <philippe.schaaf@secunet.com>
Tested-by: Franz Girlich <franz.girlich@tu-ilmenau.de>
Signed-off-by: Markus Theil <markus.theil@tu-ilmenau.de>

virtio-devices: seccomp: allow unix socket connect in vsock thread

---

Cargo.lock
Cargo.toml
arch/Cargo.toml
block_util/Cargo.toml
devices/Cargo.toml
event_monitor/Cargo.toml
hypervisor/Cargo.toml
net_util/Cargo.toml
pci/Cargo.toml
qcow/Cargo.toml
rate_limiter/Cargo.toml
vhost_user_backend/Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml
virtio-devices/Cargo.toml
vm-allocator/Cargo.toml
vmm/Cargo.toml

This has the side effect of also removing the vm-memory 0.5.0
dependency.

build: Bump dependencies

---

fuzz/fuzz_targets/block.rs

Instead of running the generic block fuzzer with QCOW, it's better to
use a RAW file since it's less complex and it will focus on virtqueues.

fuzz: block: Test a RAW file instead QCOW

---

block_util/src/qcow_sync.rs
vmm/src/device_manager.rs

Instead of panicking with an expect() function, the QcowDiskSync::new
function now propagates the error properly. This ensures the VMM will
not panic, which might be the source of weird errors if only one thread
exits while the VMM continues to run.

block_util, vmm: Propagate error on QcowDiskSync creation

---

virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/net.rs

Introducing a new structure VhostUserCommon allowing to factorize a lot
of the code shared between the vhost-user devices (block, fs and net).

virtio-devices: vhost_user: Refactor through VhostUserCommon

---

docs/vfio-user.md

Change the block size to the standard 512 byte sector size to that
disk images can be used (since their partition tables will be specified
in terms of 512 byte sectors.)
Also remove the hugepages=on option from the command line as it is not
necessary.

docs: Improve vfio-user documentation

---

vfio_user/src/lib.rs

The current code was expecting a reply with only the header, which
wasn't reading the rest of payload that was provided. This was causing
the following replies to be completely wrong as they were shifted by the
previous payload that wasn't read.
The simple way to fix this issue is by reading the header and the
expected payload when getting a reply from a DmaUnmap request.

vfio_user: DmaUnmap expects a reply with payload

---

.github/workflows/release-aarch64.yaml

This commit adds a github action to release statically-linked arm64 binaries - `ch-remote` and `cloud-hypervisor` using cross-build.
An example is shown here: https://github.com/MrXinWang/cloud-hypervisor/pull/3/checks?check_run_id=3359117981.
Since I checked the github action VM does not contain default cross-build toolchain, the cross-build is achieved by using https://github.com/rust-embedded/cross and https://github.com/actions-rs/cargo docker containers, but it seems that it is hard to strip the binaries. The un-stripped binary sizes are shown below:
```
ch-remote-static-aarch64                2.5 MB
cloud-hypervisor-static-aarch64        6.15 MB
```

github-actions: Enable release static arm64 binary

---

Jenkinsfile

The Jenkins master is now known as the controller and the agent it provides is
called "built-in".

Jenkinsfile: Update to new Jenkins terminology

---

devices/src/legacy/cmos.rs

The type is to change from 32-bit to 64-bit. See
https://github.com/rust-lang/libc/issues/1848.
The change is announced via a deprecation warning. Cloud Hypervisor's
code does not need changing. Simply suppress these warnings.

devices: cmos: suppress deprecation warnings on time_t on musl

---

vmm/src/device_manager.rs
vmm/src/vm.rs

Check the config to find out which device is attached to the tty and
then send the input from the user into that device (serial or
virtio-console.)
Fixes: #3005

vmm: Send tty input to correct destination

---

docs/vfio-user.md

The test image file needs to be created before creating the filesystem
on it.

docs: Fix the command order in the vfio-user docs

---

pci/src/vfio_user.rs

This resolves an issue with hotplug -> removal -> hotplug of a vfio-user
device as the allocator was not updated with the now unused entries.

pci: vfio_user: Free BARs associated with vfio-user device

---

hypervisor/src/kvm/mod.rs

Definition of kvm_tdx_init_vm used by INIT_VM has been updated in latest
kernel, needing an update on the Cloud Hypervisor side as well.
Update structure TdxInitVm to fit this change and avoid -EINVAL to be
returned by the kernel.
Signed-off-by: Jiaqi Gao <jiaqi.gao@intel.com>

hypervisor: kvm: Update TDX command INIT_VM

---

hypervisor/src/kvm/mod.rs

This PR removes some redundant checks and sorts in current code base when saving Arm system registers.

hypervisor: Remove useless check when saving Arm SystemRegs

---

Cargo.lock
arch/Cargo.toml
hypervisor/Cargo.toml
pci/Cargo.toml
vm-device/Cargo.toml
vmm/Cargo.toml

The rust-vmm crates we're pulling from git have renamed their main branches.  We need to update the branch names we're giving to Cargo, or people who don't have these dependencies cached will get errors like this when trying to build:
error: failed to get `vm-fdt` as a dependency of package `arch v0.1.0 (/home/src/cloud-hypervisor/arch)`
Caused by:
failed to load source for dependency `vm-fdt`
Caused by:
Unable to update https://github.com/rust-vmm/vm-fdt?branch=master#031572a6
Caused by:
object not found - no match for id (031572a6edc2f566a7278f1e17088fc5308d27ab); class=Odb (9); code=NotFound (-3)

build: update Cargo for rust-vmm branch renames

---

vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/serial_buffer.rs

When booting with the serial port attached to a PTY then the boot will be blocked until the PTY is connected to. This PR introduces a buffer for that output.
However since the serial buffer is only flushed upon attempted writes by the guest it will not be flushed immediately upon the connection of the PTY to an output. This should be possible by utilising an epoll loop and checking for writable however that requires further refactoring. So in order to address the bug in #3004 the focus is on not blocking the boot so far.
Fixes: #3004

Don't block boot due to serial output blocking

---

Jenkinsfile
scripts/dev_cli.sh
scripts/run_integration_tests_live_migration.sh
tests/integration.rs

This test exercises the local live-migration between two Cloud
Hypervisor VMs on the same host. It ensures the following behaviors:
1. The source VM is up and functional (including various virtio-devices
are working properly);
2. The 'send-migration' and 'receive-migration' command finished
successfully;
3. The source VM terminated gracefully after live migration;
4. The destination VM is functional (including various virtio-devices
are working properly) after live migration.
Note: This test does not use vsock as we can't create two identical
vsock on the same host.
Fixes: #2965

tests: Add the integration test for live migration

---

arch/src/aarch64/gic/gicv3.rs
arch/src/aarch64/gic/gicv3_its.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

On AArch64 platform, before starting live-migration, we need to flush the GICv3ITS tables to the guest RAM, otherwise the PCI/MSI
interrupts will not be functional after migration.

vmm: Fix live-migration on AArch64 platform

---

virtio-devices/src/console.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs

Move the processing of the input from stdin, PTY or file from the VMM
thread to the existing virtio-console thread. The handling of the resize
of a virtio-console has not changed but the name of the struct used to
support that has been renamed to reflect its usage.
Fixes: #3060

vmm, virtio-console: Move input reading into virtio-console thread

---

src/main.rs
vmm/src/seccomp_filters.rs
vmm/src/vm.rs

Despite setting up a dedicated thread for signal handling, we weren't making sure that the signals we were listening for there were actually dispatched to the right thread.  While the signal-hook provides an iterator API, so we can know that we're only processing the signals coming out of the iterator on our signal handling thread, the actual signal handling code from signal-hook, which pushes the signals onto the iterator, can run on any thread.  This can lead to seccomp violations when the signal-hook signal handler does something that isn't allowed on that thread by our seccomp policy.
To reproduce, resize a terminal running cloud-hypervisor continuously for a few minutes.  Eventually, the kernel will deliver a SIGWINCH to a thread with a restrictive seccomp policy, and a seccomp …

vmm: ensure signal handlers run on the right thread

---

docs/api.md
tests/integration.rs
vmm/src/device_manager.rs

Current AArch64 power button is only for device tree using a PL061 GPIO controller device. Since AArch64 now supports ACPI, this
commit extend the power button on AArch64 to:
- Using GED for ACPI+UEFI boot.
- Using PL061 for device tree boot.
Also an integration test case is added to cover.
A question for @sboeuf and @rbradford: I didn't see any documentation about the `power-button` API in the API doc here (https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/api.md), shall I add another commit to do this, or the missing of `power-button` is expected?

Enable power button for ACPI on AArch64

---

scripts/run_integration_tests_aarch64.sh
tests/integration.rs

Currently we need to test both device tree and ACPI on AArch64. As the number of ACPI test cases is gradually increasing and expected to increase in the future - For example the test cases related to `virtio-iommu` and `memory-hotplug`, it is better to extract all ACPI test cases on AArch64 to a single module.
Also, the missing `test_memory_mergeable_on` case in mod `sequential` is added on AArch64 in this PR.

AArch64: tests: Restructure test cases and scripts

---

tests/integration.rs

We current support virtio-mem on Arm and therefore user defined memory regions test can be enabled.
Also some virtio-pmem test cases can be enabled.

Enable some more test cases (pmem, user defined memory regions) on Arm

---

vmm/src/memory_manager.rs

error: all if blocks contain the same code at the end
--> vmm/src/memory_manager.rs:884:9
|
884 | /             Ok(mm)
885 | |         }
| |_________^

vmm: Fix clippy issue

---

Jenkinsfile
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_x86_64.sh
tests/integration.rs

This patch adds the integration test for live migration with ovs-dpdk. 
It also adds a separate function to launch two guest VMs and ensure
they are connected through ovs-dpdk, so that we can reuse this function
in multiple tests.

Add integration test for live migration with ovs-dpdk

---

virtio-devices/src/seccomp_filters.rs

As well as reducing the amount of code this also improves the binary
size slightly:
cargo bloat --release -n 2000 --bin cloud-hypervisor | grep virtio_devices::seccomp_filters::get_seccomp_rules
Before:
0.1%   0.2%   7.8KiB       virtio_devices virtio_devices::seccomp_filters::get_seccomp_rules
After:
0.0%   0.1%   3.0KiB       virtio_devices virtio_devices::seccomp_filters::get_seccomp_rules

virtio-devices: seccomp: Split out common seccomp rules

---

virtio-devices/src/console.rs
virtio-devices/src/seccomp_filters.rs
vmm/src/clone3.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/seccomp_filters.rs
vmm/src/sigwinch_listener.rs
vmm/src/vm.rs

Previously, terminal resize with virtio-console worked great when the console was connected to the terminal running cloud-hypervisor, but it didn't work at all when the console was using a different pty.  Here, I make it work by fixing two different but related problems: setting the console size to the size of the connected terminal rather than always using stdin, and listening for resize notifications from the console's pty.  The details of each fix are explained in the respective commit messages, which provide important background.  In particular, it might seem surprising that listening for pty resize notifications requires a subprocess, but I'm confident after having researched it (and reading the appropriate kernel source code) that due to how ttys work in Linux, there's no other way. …

Fix resizing virtio-console pty

---

Cargo.lock
Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
hypervisor/Cargo.toml
hypervisor/src/kvm/mod.rs

Update the kvm-bindings dependency so that Cloud Hypervisor now depends
on the version 0.5.0, which is based on Linux kernel v5.13.0. We still
have to rely on a forked version to be able to serialize all the KVM
structures we need.

deps: Bump kvm-bindings to v0.5.0

---

src/main.rs

This allows Cloud Hypervisor to be run under `perf` as some of the
signals will already be blocked in the child process.

main: Don't panic() if blocking signals fails

---

Cargo.lock
hypervisor/Cargo.toml

Updating kvm-ioctls from 0.9.0 to 0.10.0 now that Cloud Hypervisor
relies on kvm-bindings 0.5.0.

deps: Update kvm-ioctls to 0.10.0

---

Cargo.lock
net_util/Cargo.toml
net_util/src/mac.rs

libc::getrandom need to be called inside unsafe and it is not
cross-platform friendly.
Change it to getrandom::getrandom that is safe and cross-platform
friendly.

net_util: Change libc::getrandom to getrandom::getrandom

---

vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/serial_manager.rs
vmm/src/vm.rs

Likely needs major changes beyond the revamp of the Serial struct but
initial layout of the change is here.
This fails due to the queue_input_bytes function being a method
implemented for Serial which can't be passed to the spawn as its
lifetime isn't static.
One option is to move most of the Serial struct implementation and
data to the SerialEpollHandler to allow for the queue_input_bytes
method to be run in SerialEpollHandler's handle_event.
I'm open to other suggestions of course and wider suggestions for
improvements as this is a lot of copying from various parts of the
virtio-devices portion of the code base that could likely be done
better.

Move serial input handling to its own thread

---

arch/src/aarch64/fdt.rs
arch/src/aarch64/gic/gicv3.rs
arch/src/aarch64/gic/gicv3_its.rs
arch/src/aarch64/layout.rs
arch/src/aarch64/mod.rs
docs/iommu.md
tests/integration.rs
virtio-devices/src/iommu.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

The PR enables virtio-iommu and its test case on AArch64.
Now virtio-iommu only works when FDT is used. The work on ACPI is on-going.
The PR includes:
- Adding IOMMU node in FDT
- Refactoring virtio-iommu and GIC code to receive architecture specific MSI-IOVA address
- Adapting the test case
- Documentation

Enable virtio-iommu on AArch64 (FDT only)

---

pci/src/bus.rs
pci/src/lib.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

Looking up devices on the port I/O bus is time consuming during the
boot at there is an O(lg n) tree lookup and the overhead from taking a
lock on the bus contents.
Avoid this by adding a fast path uses the hardcoded port address and
size and directs PCI config requests directly to the device.
Command line:
`target/release/cloud-hypervisor --kernel ~/src/linux/vmlinux --cmdline "root=/dev/vda1 console=ttyS0" --serial tty --console off --disk path=~/workloads/focal-server-cloudimg-amd64-custom-20210609-0.raw --api-socket /tmp/api`
PIO exit: 17913
PCI fast path: 17871
Percentage on fast path: 99.8%
perf before:
`marvin:~/src/cloud-hypervisor (main *)$ perf report -g | grep resolve
6.20%     6.20%  vcpu0            cloud-hypervisor    [.] vm_device::bus::Bus::resolve`
perf after: …

vmm: Add fast path for PCI config IO port

---

resources/Dockerfile

Given the 'virtiofsd' and 'virtiofsd-rs' executable are used in multiple
CI workers, installing them directly to the docker image is more
efficient and can save CI time.

Dockerfile: Build and install virtiofsd to the docker image

---

hypervisor/src/mshv/mod.rs

The binding already provides a default() method which does the same
thing.

hypervisor: mshv: drop one unsafe in code

---

resources/Dockerfile

This is a preparing PR for enabling `virtio-iommu` and its test cases on AArch64. See https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3151.
On AArch64 we need to install `libguestfs-tools` to replace kernel file in cloud image, when ACPI is used.

resource: Install libguestfs-tools in Docker image on AArch64

---

scripts/run_integration_tests_aarch64.sh
tests/integration.rs
vmm/src/device_manager.rs

Enabled virtio-iommu on AArch64 when ACPI is used:
- Added Cache Coherence (_CCA) field in DSDT
- Updated Focal cloud image kernel to 5.14
- Enabled test cases
This PR depends on https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3150. After the Dockerfile change is merged and new container images pushed to Dockerhub, the integration test should be able to run.

Enable virtio-iommu on AArch64

---

.github/workflows/fuzz-build.yaml

This resolves issues between released version of cargo fuzz and nightly.
See rust-fuzz/cargo-fuzz#276

build: Temporarily use git version of cargo-fuzz in GH action

---

vmm/src/vm.rs

Both read_exact_from() and write_all_to() functions from the GuestMemory
trait implementation in vm-memory are buggy. They should retry until
they wrote or read the amount of data that was expected, but instead
they simply return an error when this happens. This causes the migration
to fail when trying to send important amount of data through the
migration socket, due to large memory regions.
This should be eventually fixed in vm-memory, and here is the link to
follow up on the issue: rust-vmm/vm-memory#174

vmm: Fix migration when writing/reading big chunks of data

---

resources/Dockerfile

These packages will be used to compile `stress` from source, and the `stress` will be used by the virtio-balloon integration test.

resources: Add autotools and texinfo for AArch64

---

vmm/src/acpi.rs
vmm/src/device_manager.rs

Since we only support a single PCI bus right now advertise only a single
bus in the ACPI tables. This reduces the number of VM exits from probing
substantially.
Number of PCI config I/O port exits: 17871 -> 1551 (91% reduction) with
direct kernel boot.

vmm: Only advertise a single PCI bus

---

tests/integration.rs
virtio-devices/src/mem.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs
vm-migration/src/protocol.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

This PR adds the missing bits for supporting snapshot/restore along with migration for virtio-mem devices.
Fixes #1595 #1312

virtio-mem: Implement snapshot/restore and migration

---

src/main.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

The argument `prefault` is provided in MemoryManager, but it can only be used by SGX and restore.
With prefault (`MAP_POPULATE`) set, subsequent page faults will decrease during running, although it will make boot slower.
This commit adds `prefault` in `MemoryConfig` and `MemoryZoneConfig`.
To resolve conflict between memory and restore, argument `prefault` has been changed from `bool` to `Option<bool>`, when its value is `None`, config from memory will be used, otherwise the value in `Option` will be used.
Ref: #3186

vmm: add prefault option in memory and memory-zone

---

Cargo.toml

This has the side effect of turning "fwdebug" on but that is
advantageous.

build: Use "common" feature in default features

---

docs/hotplug.md
tests/integration.rs

The AArch64 ACPI will help us to use the PCI device hotplug feature, hence:
- The test cases can be enabled.
- Documentation about notes related to PCI device hotplug on AArch64 should be added.
Also this PR adds a commit to mute build warnings of the tests.

tests, doc: Enable PCI device hotplug test cases for AArch64

---

src/main.rs
vmm/src/config.rs
vmm/src/cpu.rs
vmm/src/lib.rs
vmm/src/vm.rs

When using PVH for booting (which we use for all firmwares and direct
kernel boot) the Linux kernel does not configure LA57 correctly. As such
we need to limit the address space to the maximum 4-level paging address
space.
If the user knows that their guest image can take advantage of the
5-level addressing and they need it for their workload then they can
increase the physical address space appropriately.
This PR removes the TDX specific handling as the new address space limit
is below the one that that code specified.

vmm: Set a default maximum physical address size

---

Cargo.lock
Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
virtio-devices/Cargo.toml
vmm/Cargo.toml

The `Seccompiler` crate has been published on crates.io: https://crates.io/crates/seccompiler
Reference: https://github.com/rust-vmm/seccompiler/issues/24

Build: Seccompiler: Move to use the released version from crate.io

---

pci/src/bus.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/pci_segment.rs

Move the PCI related state from the DeviceManager struct to a PciSegment
struct inside the DeviceManager. This is in prepration for multiple
segment support. Currently this state is just the bus itself, the MMIO
and PIO config devices and hotplug related state.
The main change that this this necessitated is using the
Arc<Mutex<PciBus>> in the device addition logic in order to ensure that
the bust could be created earlier.

vmm: Extract PCI related state from DeviceManager

---

scripts/check-image-compatability.sh

This script checks if an image is compatible with Cloud Hypervisor.
At first, it detects the image type(raw or qcow2),
partition type whether it is DOS or GPT.
Then it mounts the image and checks if VIRTIO Configs
are enabled in the kernel config. In the end, it provides
a message about the compatibility of the image.

scripts: Add a script to check if VM image is compatible with Cloud Hypervisor

---

devices/src/acpi.rs
pci/src/bus.rs
pci/src/device.rs
pci/src/lib.rs
pci/src/vfio.rs
pci/src/vfio_user.rs
src/main.rs
tests/integration.rs
virtio-devices/src/transport/pci_device.rs
vm-allocator/src/address.rs
vm-allocator/src/system.rs
vmm/src/acpi.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/device_tree.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/pci_segment.rs
vmm/src/vm.rs

Enable support for multiple PCI segments. This PR adds a new global option `--platform num_pci_segments=<n>` which can be combined with `pci_segment` options added to the majority of device types (console, rng & watchdog are the exceptions) which can then be used to choose which segment to add the chosen device to.
Fixes: #1400

Enable multiple PCI segments

---

virtio-devices/src/net.rs

By merging receive buffers through the VIRTIO_NET_F_MRG_RXBUF feature,
as well as enabling the use of indirect descriptors through
VIRTIO_RING_F_INDIRECT_DESC feature, we achieve better throughput for
the virtio-net device without hurting its latency.

virtio-devices: net: Improve throughput with virtio features

---

Cargo.lock
fuzz/Cargo.lock
pci/src/vfio.rs

Now that vfio-ioctls correctly exposes the list of capabilities related
to each region, Cloud Hypervisor can decide to mmap a region based on
the presence or absence of MSIX_MAPPABLE. Instead of blindly mmap'ing
the region, we check if the MSI-X table or PBA is present on the BAR,
and if that's the case, we look for MSIX_MAPPABLE.
If MSIX_MAPPABLE is present, we can go ahead and mmap the entire region.
If MSIX_MAPPABLE is not present, we simply ignore the mmap'ing of this
region as it wouldn't be supported.

pci: vfio: Mmap region based on capabilities

---

acpi_tables/src/aml.rs
devices/src/acpi.rs
vmm/src/acpi.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs
vmm/src/pci_segment.rs

Rather than merging lots of small vectors together instead append onto an existing vector.
With the very simple ACPI DSDT table using:
`target/debug/cloud-hypervisor --kernel ~/src/linux/arch/x86/boot/compressed/vmlinux.bin --cmdline "root=/dev/vda1 console=hvc0" --disk path=~/workloads/focal-server-cloudimg-amd64-custom-20210609-0.raw --api-socket /tmp/api -v`
Before: 
Release: cloud-hypervisor: 38.050611ms: <vmm> INFO:vmm/src/acpi.rs:654 -- Generated ACPI tables: took 351µs
Debug: cloud-hypervisor: 47.688808ms: <vmm> INFO:vmm/src/acpi.rs:654 -- Generated ACPI tables: took 3709µs
After:
Release: cloud-hypervisor: 36.574091ms: <vmm> INFO:vmm/src/acpi.rs:657 -- Generated ACPI tables: took 193µs
Debug: cloud-hypervisor: 42.434992ms: <vmm> INFO:vmm/src/acpi.rs:657 -- Generated ACPI tables: …

Avoid excessive vector allocations in ACPI DSDT generation code

---

rpm/cloud-hypervisor.spec

This PR documents the basic assumptions on the environment that users will use to build the Cloud Hypervisor RPM, and together with this adds two definitions to the spec file: `using_rustup` and `using_musl_libc`.
With those two definitions we can easily ensure the RPM will be built on Copr using the (basic) distro dependencies.
Copr repo: https://copr.fedorainfracloud.org/coprs/fidencio/cloud-hypervisor/
Note that this is the very first part of a work that will, at the very first, allow us to figure out which are possible / obvious problems we could and will face when installing and running this on Fedora and, possibly, on Fedora CoreOS.
I am super fine on having this PR as a draft for now if that's the preference of the maintainers.  The same way I'm fine about dropping small fixes here …

rpm: Document and extend the spec file so it can be built on Copr

---

docs/memory.md
option_parser/src/lib.rs
tests/integration.rs
vmm/src/config.rs

Extend the parser by allowing lists to be defined with commas as the delimiter. This can only work when lists are demarcated with `[` and `]` in order to identify them.
This PR allows for something like this to work:
```
--param option1=v1,option2=[v2,v3,v4],option3=v5
```

option_parser: Allow commas for lists

---

net_util/src/mac.rs
vm-migration/src/protocol.rs
vmm/src/lib.rs

Always properly initialize vectors so that we don't run in undefined behaviors when the vector gets dropped.
Fixes #3311

clippy: Make sure to initialize data

---

arch/src/x86_64/tdx/mod.rs

Implement Default trait for TdvfDescriptor and drop one unsafe in code.

arch: x86_64: tdx: drop one unsafe call in code

---

rpm/cloud-hypervisor.spec

OSTree based systems (such as Fedora CoreOS) behave differently than yum
based systems (such as Fedora) with regarding to the RPM installations.
While the latter will install the RPM on the running system, modifying
it; the former will be layered (installed in a "chroot") and only will
be present on the system after the user boots this layer up.
While in theory there shouldn't be much differences on the installation
itself, when installing cloud-hypervisor on RHCOS, the following issue
would be seen:
```
$ sudo sudo rpm-ostree install cloud-hypervisor
Checking out tree 9c1cdf9... done
Enabled rpm-md repositories: copr:copr.fedorainfracloud.org:fidencio:cloud-hypervisor
Updating metadata for 'copr:copr.fedorainfracloud.org:fidencio:cloud-hypervisor'... done
rpm-md repo …
```

rpm: Make the RPM installable on OSTree based systems

---

.github/workflows/docker-image.yaml
docs/cpu.md
docs/custom-image.md
docs/intel_sgx.md
docs/memory.md
docs/snapshot_restore.md
release-notes.md
src/main.rs
vmm/src/config.rs

This new document describes the available options for the parameter `--cpus`, how to use them and what is their usage.
Fixes #3317

docs: Add documentation for CPU parameter

---

hypervisor/src/kvm/aarch64/mod.rs

I found this undefined behaviour while going through unsafe blocks.

Fix an undefined behaviour in offset__of

---

arch/src/x86_64/interrupts.rs

This test generates an array of random numbers and then applies the same
trivial algorithm twice -- once in set_apic_delivery_mode and another
time in an anonymous function.
Its usefulness is limited. Drop it to remove one unsafe in code.

arch: x86_64: drop test_apic_delivery_mode

---

vmm/src/sigwinch_listener.rs

When running with `--serial pty --console pty --seccomp=false` the
SIGWICH listener thread would panic as the seccomp filter was empty.
Adopt the mechanism used in the rest of the code and check for non-empty
filter before trying to apply it.

vmm: Fix panic in SIGWINCH listener thread when no seccomp filter set

---

vmm/src/seccomp_filters.rs

Fix seccomp violation when trying to add the out FD to the epoll loop
when the serial buffer needs to be flushed.
```
0x00007ffff7dc093e in epoll_ctl () at ../sysdeps/unix/syscall-template.S:120
0x0000555555db9b6d in epoll::ctl (epfd=56, op=epoll::ControlOptions::EPOLL_CTL_MOD, fd=55, event=...)
at /home/rob/.cargo/registry/src/github.com-1ecc6299db9ec823/epoll-4.3.1/src/lib.rs:155
0x00005555556f5127 in vmm::serial_buffer::SerialBuffer::add_out_poll (self=0x7fffe800b5d0) at vmm/src/serial_buffer.rs:101
0x00005555556f583d in vmm::serial_buffer::{impl#1}::write (self=0x7fffe800b5d0, buf=...) at vmm/src/serial_buffer.rs:139
0x0000555555a30b10 in std::io::Write::write_all<vmm::serial_buffer::SerialBuffer> (self=0x7fffe800b5d0, buf=...)
at …
```

vmm: Add epoll_ctl() syscall to vCPU seccomp filter

---

docs/intel_tdx.md

Creating some brief documentation for TDX, summarizing the links on
where to find more information about TDX, as well as how to run Cloud
Hypervisor on it.
Fixes #3318

docs: Add documentation for TDX

---

docs/hotplug.md

This simple patch just fixes the typo in hotplug.md

docs: Fix the typo in hotplug.md

---

acpi_tables/src/rsdp.rs
arch/src/x86_64/mod.rs
arch/src/x86_64/mptable.rs
arch/src/x86_64/smbios.rs
arch/src/x86_64/tdx/mod.rs
block_util/src/lib.rs
net_util/src/ctrl_queue.rs
net_util/src/lib.rs
pci/src/configuration.rs
pci/src/msix.rs
vfio_user/src/lib.rs
virtio-devices/src/balloon.rs
virtio-devices/src/console.rs
virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs
virtio-devices/src/pmem.rs
virtio-devices/src/transport/pci_device.rs
virtio-queue/src/lib.rs
vm-migration/src/protocol.rs
vm-virtio/src/queue.rs

This is a group of low hanging fruits -- it is trivial to verify the safety requirements are met.

Add or adjust safety comments for `impl ByteValued`

---

vmm/src/device_manager.rs

I encountered some trouble trying to use a virtio-console hooked up to
a PTY.  Reading from the PTY would produce stuff like this
"\n\nsh-5.1# \n\nsh-5.1# " (where I'm just pressing enter at a shell
prompt), and a terminal would render that like this:
```
sh-5.1#
sh-5.1#
```
This was because we weren't disabling the ICRNL termios iflag, which
turns carriage returns (\r) into line feeds (\n).  Other raw mode
implementations (like QEMU's) set this flag, and don't have this
problem.
Instead of fixing our raw mode implementation to just disable ICRNL,
or copy the flags from QEMU's, though, here I've changed it to use the
raw mode implementation in libc.  It seems to work correctly in my
testing, and means we don't have to worry about what exactly raw mode
looks like under the hood any more. …

vmm: use the tty raw mode implementation from libc

---

virtio-devices/src/net.rs
vmm/src/device_manager.rs
vmm/src/lib.rs

Some only require adding a comment.
There is one real issue in which -1 may be wrapped into File. Although panicking is safe in Rust, it is still better to have clear error messages.

Unsafe comments and fixes

---

hypervisor/src/arch/x86/emulator/mod.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs

It only has a few `unsafe`. No issues found so only a few comments are added.

Add safety comments in hypervisor crate

---

pci/src/vfio_user.rs
vmm/src/device_manager.rs

I found it is easier to read when having a single `impl VfioUserPciDevice` block. Also, it fixed a trivial comment typo.

pci: vfio_user: Merge duplicate 'impl VfioUserPciDevice' block

---

vmm/src/device_manager.rs

Change  "Failed xxing" to "Failed to xx"

vmm: Make the comments consistent in 'DeviceManager'

---

docs/vfio-user.md

Add more info on how to set up SPDK NVMe-oF tgt for vfio-user usage
in NVMe device example part.

docs/vfio-user: Add more description on NVMe Device part

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_x86_64.sh

Now an error can be seen if we try to rebuild the `virtiofsd-rs` binary.

scripts: Fix an error in virtiofsd build commands

---

devices/src/legacy/cmos.rs

The register D has only one bit that is not reserved, and its purpose is
to report if the RTC/CMOS device is powered or not.
The OVMF firmware was failing to boot as it was getting the information
that the device was powered off from the register D.
The simple way to fix this issue is by always returning the bit 7 from
register D as 1, indicating the device is always powered.

devices: legacy: cmos: Fix register D emulation

---

tests/integration.rs
vmm/src/acpi.rs
vmm/src/interrupt.rs

Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3296
The PR enabled multiple PCI segments support on ACPI only. 
The enabling on FDT depends on some modifications in this PR, will come soon.

Enable multiple PCI segments on AArch64

---

tests/integration.rs

This test is flaky (#3400) while we are experiencing a bug of using the latest
SPDK/NVMe backend as VFIO user device (#3401). Let's disable this test
before we fix the above two issues.

tests: Temporarily disable test_vfio_user

---

README.md
docs/arm64.md

Current `Getting Started` section only contains steps for the x86_64 platform, as we have a documentation doing the same thing for AArch64, we can point users to the correct documentation.
Also, this commit modifies the `docs/arm64.md` to fit the documentation style within the project.

README: AArch64: Improve getting started section

---

arch/src/x86_64/layout.rs

Reduce the size of the reserved 32-bit address space to the range used
by both the PCI MMIO config data and the 32-bit PCI device space.
This avoids issues when using firmware that is loaded into the very top
of the 32-bit address space as the RAM conflicts with the reserved
memory.

arch: x86_64: Only reserve used 32-bit address space

---

arch/src/x86_64/layout.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
vmm/src/vm.rs

Place the 3 page TSS at an explicit location in the 32-bit address space
to avoid conflicting with the loaded raw firmware.

arch, hypervisor, vmm: Explicitly place the TSS in the 32-bit space

---

src/main.rs
vmm/src/vm.rs

The error was:
borrow the array with `&` or call `.iter()` on it to iterate
over it
Fixes #3348
Signed-off-by: Barret Rhoden <brho@google.com>

vmm: fix HANDLED_SIGNALS build error

---

tests/integration.rs

Commit ac2517217634ca8b89e441f5769ab6b916868ee1 bumps the rust version of virtiofsd named `virtiofsd-rs`, which causes a warning:
```
warning: use of deprecated parameter '--socket':
Please use the '--socket-path' option instead.
```
This commit updates the cmdline parameter accordingly.

tests: Update the virtiofsd-rs cmdline

---

Cargo.lock
Cargo.toml
arch/src/x86_64/layout.rs
fuzz/Cargo.lock
fuzz/Cargo.toml
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
vmm/src/seccomp_filters.rs
vmm/src/vm.rs

In order to avoid any conflict with the firmware loaded at the last 4MiB of the 4GiB space, we explicitly set the identity map address so that the corresponding one-page region is placed right after the TSS region.

vmm: Set KVM identity map

---

Jenkinsfile
docs/uefi.md
scripts/run_integration_tests_windows.sh
test_infra/src/lib.rs
tests/integration.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

Bumping the OVMF binary version to reflect the latest set of patches on
top of tianocore/edk2 'master' branch, which can be found on the Cloud
Hypervisor fork on 'ch' branch.

ci: Update the OVMF version the tests rely on

---

arch/src/aarch64/fdt.rs
arch/src/aarch64/layout.rs
arch/src/aarch64/mod.rs
arch/src/lib.rs
arch/src/x86_64/layout.rs
docs/device_model.md
tests/integration.rs
vmm/src/device_manager.rs
vmm/src/pci_segment.rs
vmm/src/vm.rs

This PR enables the FDT support of PCI multiple segments, and should be dependent on https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3356/commits/731ad9b8db7cccc4ab20b6c66585c39a60c6d436 of https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3356.
- Adds the FDT support of PCI multiple segments
- Adds some more documentation to describe how to assign device to PCI segment
- Enhances the PCI multiple segment test cases

AArch64: Enable the FDT support of PCI multiple segments

---

vmm/src/lib.rs
vmm/src/vm.rs

Saving the KVM clock and restoring it is key for correct behaviour of
the VM when doing snapshot/restore or live migration. The clock is
restored to the KVM state as part of the Vm::resume() method prior to
that it must be extracted from the state object and stored for later use
by this method. This change simplifies the extraction and storage part
so that it is done in the same way for both snapshot/restore and live
migration.

vmm: Move KVM clock saving to common Vm::restore() method

---

block_util/src/lib.rs
block_util/src/qcow_sync.rs
block_util/src/vhdx_sync.rs

The observation is that the code in question was used to bridge
synchronized and asynchronized code.
We can group the functions for that purpose under an adaptor trait. To
limit the scope of locking, the users of the trait are required to
implement a method to return a MutexGuard for the underlying file.
This then allows us to use concrete types (QcowFile and Vhdx) in code,
which is easier to read than a bunch of traits.
No functional change intended.

block_util: provide and use AsyncAdaptor trait

---

vmm/src/device_manager.rs

When restoring replace the internal value of the device tree rather than
replacing the Arc<Mutex<DeviceTree>> itself. This is fixes an issue
where the AddressManager has a copy of the the original
Arc<Mutex<DeviceTree>> from when the DeviceManager was created. The
original restore path only replaced the DeviceManager's version of the
Arc<Mutex<DeviceTree>>. Instead replace the contents of the
Arc<Mutex<DeviceTree>> so all users see the updated version.

vmm: Replace device tree value when restoring DeviceManager

---

.github/workflows/release.yaml

build: Include static ch-remote binary in release

---

tests/integration.rs
vmm/src/device_manager.rs

This time we use the Rust Hypervisor Firmware for test_vfio_user() in
order to fix the systemd issues we've seen so far.

tests: Re-enable vfio_user integration test

---

virtio-devices/src/net.rs

This reverts commit 58d25b3cccff967aa10a56f8f87692ca946aad7d.
This change introduced a regression when running iperf with the guest
running as the server:
```
marvin:~/src/cloud-hypervisor ((58d25b3c...))$ iperf  -c 192.168.249.2
------------------------------------------------------------
Client connecting to 192.168.249.2, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  1] local 192.168.249.1 port 47078 connected with 192.168.249.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  1] 0.00-10.40 sec  14.0 MBytes  11.3 Mbits/sec
marvin:~/src/cloud-hypervisor ((58d25b3c...))$ iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size:  128 KByte (default) …
```

Revert "virtio-devices: net: Improve throughput with virtio features"

---

resources/Dockerfile

This patch upgrades to the latest spdk upstream that utilizes latest libvfio-user 
submodule and several updates to nvmf.
This patch also removes the workaround of building SPDK with meson
0.59.2 as the bug has been fixed [1].
[1] https://review.spdk.io/gerrit/c/spdk/dpdk/+/10044

Dockerfile: Update version of SPDK in container

---

vmm/src/device_manager.rs

Setting up the SIGWINCH handler requires at least Linux 5.7. However
this functionality is not required for basic PTY operation.
Fixes: #3456

vmm: Only warn on error when setting up SIGWINCH handler

---

vmm/src/seccomp_filters.rs

These were use for the self spawning vhost-user device feature that has
been removed.

vmm: seccomp: Remove fork & evecve syscalls

---

vmm/src/vm.rs

It's important to maintain the ability to run in a non-TDX environment
a Cloud Hypervisor binary with the 'tdx' feature enabled.

vmm: tdx: Make sure a TDX enabled binary can be used for non-TDX

---

Cargo.toml
block_util/Cargo.toml
block_util/src/lib.rs
virtio-devices/Cargo.toml
vmm/Cargo.toml

This has been part of the default features for a long time and is widely
tested.

build: Remove io_uring feature flag

---

Cargo.lock
Cargo.toml
acpi_tables/Cargo.toml
arch/Cargo.toml
block_util/Cargo.toml
devices/Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
hypervisor/Cargo.toml
net_util/Cargo.toml
pci/Cargo.toml
vfio_user/Cargo.toml
vhost_user_backend/Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml
virtio-devices/Cargo.toml
virtio-queue/Cargo.toml
vm-allocator/Cargo.toml
vm-device/Cargo.toml
vm-migration/Cargo.toml
vm-virtio/Cargo.toml
vmm/Cargo.toml

Updating Cloud Hypervisor to rely on vm-memory version 0.7.0.

deps: Bump vm-memory to 0.7.0

---

docs/arm64.md

There is a corner case of using the Cloud Hypervisor on AArch64:
If the VM is started on a device where RAM is limited, and if the user allocates nearly as much memory for the guest as is still free on the host, we need to enable the swap memory.
Also, this commit corrects the hardware requirement of the GIC interrupt controller for running the Cloud Hypervisor on AArch64, according to [1].
Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3419
[1] https://www.kernel.org/doc/html/latest/virt/kvm/devices/arm-vgic-its.html

docs/arm64: Document the hardware constraints

---

tests/integration.rs

Two tests in our CI are flaky, let's disable them until we find the right way to fix them.

tests: Temporarily disable flaky tests

---

vmm/src/device_manager.rs

If the underlying kernel is old PTY resize is disabled and this is
represented by the use of None in the provided Option<File> type. In the
virtio-console PTY path don't blindly unwrap() the value.
Fixes: #3496

vmm: Don't assume that resize_pipe is initialised

---

virtio-devices/src/vsock/unix/muxer.rs

When forwarding an epoll event from the unix muxer to the
targeted connection event handler, the eventset the connection
registered is forwarded instead of the actual epoll
operation (IN/OUT).
For example, if the connection was registered for EPOLLIN,
and receives an EPOLLOUT, the connection will actually handle
an EPOLLOUT.
This is the root cause of previous bug, which caused the
introduction of some workarounds (i.e: handling ewouldblock
when reading after receiving EPOLLIN, which should never happen).
When matching the connection, we retrieve and use the evset of
the connection instead of the one passed as a parameter.
The compiler does not complain for an unused variable because
it was first logged in a debug! statement.
This is an unfortunate naming mistake that caused a lot of …

virtio-devices: Forward correct evset in vsock muxer

---

scripts/create-cloud-init.sh

Ignore removing a non-existing file instead of bailing out.
Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

scripts: create-cloud-init: use `rm -f` instead of `rm`

---

Cargo.lock
Cargo.toml
src/main.rs
vmm/Cargo.toml
vmm/src/device_tree.rs
vmm/src/lib.rs

This crate was used in the integration tests to allow the tests to
continue and clean up after a failure. This isn't necessary in the unit
tests and adds a large build dependency chain including an unmaintained
crate.

vmm, build: Remove use of "credibility" from unit tests

---

.gitignore

This allows developers to have their local Cargo configurations for
Cloud Hypervisor.

gitignore: ignore .cargo directory

---

Cargo.lock
block_util/src/lib.rs
fuzz/fuzz_targets/block.rs
virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs
virtio-devices/src/pmem.rs
virtio-devices/src/transport/pci_device.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs
virtio-devices/src/vsock/packet.rs
virtio-queue/Cargo.toml
virtio-queue/src/chain.rs
virtio-queue/src/defs.rs
virtio-queue/src/descriptor.rs
virtio-queue/src/iterator.rs
virtio-queue/src/lib.rs
virtio-queue/src/mock.rs
virtio-queue/src/queue.rs
virtio-queue/src/queue_guard.rs
virtio-queue/src/state.rs
virtio-queue/src/state_sync.rs
vm-virtio/src/queue.rs

This crate contains up to date definition of the Queue, AvailIter,
DescriptorChain and Descriptor structures forked from the upstream
crate rust-vmm/vm-virtio 27b18af01ee2d9564626e084a758a2b496d2c618.
The following patches have been applied on top of this base in order to
make it work correctly with Cloud Hypervisor requirements:
- Add MSI vector field to the Queue
In order to help with MSI/MSI-X support, it is convenient to store the
value of the interrupt vector inside the Queue directly.
- Handle address translations
For devices with access to data in memory being translated, we add to
the Queue the ability to translate the address stored in the
descriptor.
It is very helpful as it performs the translation right after the
untranslated address is read from memory, avoiding any errors …

virtio-queue: Update crate based on latest rust-vmm/vm-virtio

---

vmm/src/seccomp_filters.rs

The origins of the requirement for this syscall in the seccomp filter
list are unknown.

vmm: seccomp: Remove arch_prctl syscall from seccomp filter

---

vmm/src/seccomp_filters.rs

The origins of the requirement for this syscall in the seccomp filter
list are unknown.

vmm: seccomp: Remove set_tid_address syscall from seccomp filter

---

README.md

Current command to run cloud-hypervisor binary has
wrong --rng argument in the README file.
This commit fixes all the references of --rng argument
by removing the --rng option to use default.

README: Remove --rng option from command to launch a guest

---

net_util/src/queue_pair.rs

Do not silently ignore descriptors that are not of the expected form for
the RX and TX queues.

net_util: Error out if the virtio-net descriptor chain is malformed

---

vmm/src/api/openapi/cloud-hypervisor.yaml

`tap` has its default value set to `None`, but in the openapi yaml file
we've been setting it to `""`.
When using this code on the Kata Containers side we'd be hit by a non
expected behaviour of cloud-hypervisor, as even when using a different
method to initialise the `tuntap` device the code would be treated as if
using `--net tap` (which is a valid use-case).
Related: #3554

vmm: openapi: Fix default value for tap

---

src/main.rs

Passing no boot related parameters (e.g. no --kernel) is used for e.g.
receiving a live migration or an API based boot.
```
marvin:~/src/cloud-hypervisor (2022-01-11-live-migration-with-fds *)$ target/debug/cloud-hypervisor --api-socket /tmp/api2
thread 'main' panicked at '`tdx` is not a name of an argument or a group.
Make sure you're using the name of the argument itself and not the name of short or long flags.', /home/rob/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.6/src/parse/matches/arg_matches.rs:598:14
stack backtrace:
0: rust_begin_unwind
at /rustc/7d6f948173ccb18822bab13d548c65632db5f0aa/library/std/src/panicking.rs:498:5
1: core::panicking::panic_fmt
at /rustc/7d6f948173ccb18822bab13d548c65632db5f0aa/library/core/src/panicking.rs:107:14
2: …
```

vmm: Don't check for presence of tdx parameter when not built with tdx

---

arch/src/aarch64/mod.rs
arch/src/aarch64/regs.rs
vmm/src/cpu.rs

Drop the unused parameter throughout the code base.
Also take the chance to drop a needless clone.
No functional change intended.

arch: aarch64: vm_memory is not required when configuring vcpu

---

docs/hotplug.md

Currently cloud-hypervisor supports hotplug of CPUs, passthrough devices, virtio devices and memory resizing, 
but in hotplug.md it still mentiones: "Currently Cloud Hypervisor only supports hot plugging of CPU devices."
We need to remove the incorrect information from hotplug.md to reflect the true situation.
Fixes: #3504
Signed-off-by: Liang Zhou <zhoul110@chinatelecom.cn>

docs: update hotplug.md

---

docs/live_migration.md
src/bin/ch-remote.rs
tests/integration.rs
vm-migration/src/protocol.rs
vmm/src/api/mod.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

Pass the FDs for the guest memory across the socket allowing very fast live migration (and for live upgrade.)
Fixes: #3566

Support fast local live migration

---

scripts/run_integration_tests_windows.sh
scripts/run_integration_tests_x86_64.sh

By pinning the OVMF version, we will be able to update the EDK2 fork
with a new version without potentially breaking our Cloud Hypervisor CI.
Once the new version is ready on the EDK2 fork, we'll be able to update
Cloud Hypervisor codebase, replacing the fixed version with the latest,
as well as replacing OVMF.fd with CLOUDHV.fd. This is because we'll
start building from the new target CloudHvX64.

scripts: Pin OVMF EDK2 version

---

docs/uefi.md
docs/windows.md
scripts/run_integration_tests_windows.sh
scripts/run_integration_tests_x86_64.sh
tests/integration.rs

Update documentation and CI to rely on the new CLOUDHV.fd firmware built
from the newly introduced target CloudHvX64.

edk2: Rely on latest OVMF based on CloudHvX64 target

---

vmm/src/cpu.rs

These are the leftovers from the commit 8155be2:
arch: aarch64: vm_memory is not required when configuring vcpu

vmm: cpu: Remove unused import in unit tests

---

block_util/src/lib.rs

The code can be written in a better form and the clippy warning
suppression can be dropped.

block_util: rewrite code and drop allow(clippy::ptr_arg)

---

vmm/src/vm.rs

Ensure all pending virtio activations (as triggered by MMIO write on the
vCPU threads leading to a barrier wait) are completed before pausing the
vCPUs as otherwise there will a deadlock with the VMM waiting for the
vCPU to acknowledge it's pause and the vCPU waiting for the VMM to
activate the device and release the barrier.
Fixes: #3585

vmm: Avoid deadlock between virtio device activation and vcpu pausing

---

vmm/src/acpi.rs
vmm/src/device_manager.rs

This table is listed as required in the ARM Base Boot Requirements
document. The particular need arises to make the serial debugging of
Windows guest functional.=
/cc @jongwu  

acpi: aarch64: Implement DBG2 table

---

tests/integration.rs

tests: ignore the result from test_vfio_user

---

arch/src/x86_64/tdx/mod.rs
vmm/src/acpi.rs
vmm/src/vm.rs

This PR updates the way to expose the ACPI tables to the TDVF firmware, which is used in TDShim as well. Each table content is individually passed through the HOB so that it can be parsed, analyzed and measured from the firmware before being passed to the TD guest OS.
After removing the previous method, this PR implements the new way of passing the tables.
It's been tested with the TDVF counterpart: https://github.com/tianocore/edk2-staging/pull/269

tdx: Update method to expose ACPI tables to TDVF

---

tests/integration.rs

As it might take more time for the VM to boot (especially under high
load) when using the firmware, let's increase the timeout waiting for
the VM to be reachable.

tests: Increase timeout when booting with firmware

---

virtio-devices/src/seccomp_filters.rs

When freeing memory sometimes glibc will attempt to read
"/proc/sys/vm/overcommit_memory" to find out how it should release the
blocks. This happens sporadically with Cloud Hypervisor but has been
seen in use. It is not necessary to add the read() syscall to the list
as it is already included in the virtio devices common set. Similarly
the vCPU and vmm threads already have both these in the allowed list.
Fixes: #3609

virtio-devices: Add openat() syscall to seccomp filter

---

block_util/src/lib.rs
net_util/src/ctrl_queue.rs
net_util/src/queue_pair.rs
vhost_user_block/src/lib.rs
vhost_user_net/src/lib.rs
virtio-devices/src/block.rs
virtio-devices/src/console.rs
virtio-devices/src/device.rs
virtio-devices/src/iommu.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/transport/pci_common_config.rs
virtio-devices/src/transport/pci_device.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vsock/csm/connection.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/vsock/mod.rs
virtio-devices/src/vsock/packet.rs
virtio-devices/src/vsock/unix/muxer.rs
virtio-queue/src/chain.rs
virtio-queue/src/iterator.rs
virtio-queue/src/lib.rs
virtio-queue/src/queue.rs
virtio-queue/src/state.rs
vm-virtio/src/lib.rs
vmm/src/device_manager.rs

Instead of relying on the virtio-queue crate to perform the address translation when a virtio device is placed behind a vIOMMU, this PR moves the code to the Cloud Hypervisor codebase. This is the last step before we can move Cloud Hypervisor to the upstream version of `virtio-queue` (given that https://github.com/rust-vmm/vm-virtio/pull/132 will get merged).

Handle virtio queues addresses translation from Cloud Hypervisor

---

Cargo.lock
tests/integration.rs
vmm/src/api/http.rs
vmm/src/api/http_endpoint.rs

Based on the latest code from the micro-http crate, this PR adds the support for multiple file descriptors to be sent along with the add-net request. This means we can now hotplug multiqueue network interface to the VM.
The macvtap integration test has been updated so that both coldplug and hotplug codepath now use multiqueue network device.

vmm: api: Support multiple fds with add-net

---

vmm/src/api/openapi/cloud-hypervisor.yaml

While cloud-hypervisor does support receiving the file descriptors of a
tuntap device, advertising the fds structure via the openAPI can lead to
misinterpretations of what can and what should be done.
An unadvertised consumer will think that they could rather just set the
file descriptors there directly, or even pass them as a byte array.
However, the proper way to go in those cases would be actually sending
those via send_msg(), together with the request.
As hacking the openAPI auto-generated code to properly do this is not
*that* trivial, and as doing so during a `create VM` request is not
supported, we better not advertising those.
Please, for more details, also check:
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3607#issuecomment-1020935523
Signed-off-by: Fabiano Fidêncio …

vmm: openapi: Remove mention to net fds

---

Cargo.lock
Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_block/src/lib.rs

Instead of relying on the local version of vhost-user-backend, this
patch allows the block backend implementation to rely on the upstream
version of the crate from rust-vmm.

vhost_user_block: Rely on upstream vhost-user-backend crate

---

Cargo.lock
pci/Cargo.toml
vm-device/Cargo.toml
vmm/Cargo.toml

Make sure Cloud Hypervisor relies on upstream and actively maintained
vfio-ioctls crate from the rust-vmm/vfio repository instead of the
deprecated version coming from rust-vmm/vfio-ioctls repository.
Fixes #3673

vfio-ioctls: Move away from archived crate rust-vmm/vfio-ioctls

---

arch/src/x86_64/tdx/mod.rs
vmm/src/config.rs
vmm/src/vm.rs

Relying on newly defined TDVF sections from the metadata, Cloud Hypervisor can provide its users a way to boot a TD VM with direct kernel boot.

tdx: Add direct kernel boot support for TD firmwares

---

Cargo.toml

The patch mechanism in Cargo.toml doesn't support features to be
specified, and was leading to the following warning:
warning: patch for `kvm-bindings` uses the features mechanism.
default-features and features will not take effect because the patch
dependency does not support this mechanism
Removing the "features" parameter from the patch fixes this warning
without breaking the build.

build: Fix cargo patch warning

---

hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
vmm/src/cpu.rs

As per this kernel documentation:
For KVM_EXIT_IO, KVM_EXIT_MMIO, KVM_EXIT_OSI, KVM_EXIT_PAPR, KVM_EXIT_XEN,
KVM_EXIT_EPR, KVM_EXIT_X86_RDMSR and KVM_EXIT_X86_WRMSR the corresponding
operations are complete (and guest state is consistent) only after userspace
has re-entered the kernel with KVM_RUN.  The kernel side will first finish
incomplete operations and then check for pending signals.
The pending state of the operation is not preserved in state which is
visible to userspace, thus userspace should ensure that the operation is
completed before performing a live migration.  Userspace can re-enter the
guest with an unmasked signal pending or with the immediate_exit field set
to complete pending operations without allowing any further instructions
to be executed.
Since we capture the …

vmm: Ensure that PIO and MMIO exits complete before pausing

---

docs/snapshot_restore.md
vmm/src/lib.rs
vmm/src/migration.rs
vmm/src/vm.rs

In order to allow for human readable output for the VM configuration, we
pull it out of the snapshot, which becomes effectively the list of
states from the VM. The configuration is stored through a dedicated file
in JSON format (not including any binary output).
Having the ability to read and modify the VM configuration manually
between the snapshot and restore phases makes debugging easier, as well
as empowers users for extending the use cases relying on the
snapshot/restore feature.

vmm: Split VM config and VM state for snapshot/restore

---

virtio-devices/src/transport/pci_device.rs

This should not occur as ioeventfd is used for notification. Such an
error message would have made the discovery of the underlying cause of

virtio-devices: Print error on notification BAR read/write

---

docs/intel_tdx.md

Adding a bit of documentation and links about the TDShim and how to run
it with Cloud Hypervisor.

docs: Add TDShim to the Intel TDX documentation

---

Jenkinsfile

No need to run the Jenkins CI on pull request for which exclusively markdown files have been modified.

Jenkinsfile: Filter out pull requests containing only documentation

---

tests/integration.rs
virtio-devices/src/balloon.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs

Adding a new parameter free_page_reporting=on|off to the balloon device
so that we can enable the corresponding feature from virtio-balloon.
Running a VM with a balloon device where this feature is enabled allows
the guest to report pages that are free from guest's perspective. This
information is used by the VMM to release the corresponding pages on the
host.

Enable guest to report free pages through virtio-balloon

---

src/main.rs
tests/integration.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs

This allows the hotplugging of devices behind the IOMMU provided they are assigned to a segment that is in the list.

Support forcing all devices on a segment behind the IOMMU

---

vmm/src/api/openapi/cloud-hypervisor.yaml

TDx support is already present on the project for quite some time, but
the TDx configuration was not yet exposed to the ones using CH via the
OpenAPI auto generated code.

openapi: Expose TDx configuration

---

Cargo.lock
pci/Cargo.toml
pci/src/lib.rs
vmm/src/device_manager.rs
vmm/src/device_tree.rs

By having the DeviceNode storing a PciBdf, we simplify the internal code
as well as allow for custom Serialize/Deserialize implementation for the
PciBdf structure. These custom implementations let us display the PCI
s/b/d/f in a human readable format.
Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3711

pci, vmm: Update DeviceNode to store PciBdf instead of u32

---

pci/src/configuration.rs

The PCI spec specifies that only the following bits are writable:
16: MSI Enable
20,21,22: Multiple Message Enable
26: Extended Message Data Enable

pci: Only allow writes to RW bits in MSI-X register

---

pci/src/configuration.rs

The PCI spec does not specify that the access has to be of a specific
size.
Fixes: #3714

pci: Support DWORD/4-byte writes to the MSI-X control register

---

.github/workflows/build.yaml
Cargo.lock
Cargo.toml
performance-metrics/Cargo.toml
performance-metrics/build.rs
performance-metrics/src/main.rs
performance-metrics/src/performance_tests.rs
resources/Dockerfile
scripts/dev_cli.sh
scripts/run_metrics.sh
test_infra/Cargo.toml
test_infra/src/lib.rs

This patch adds a new binary target `performance-metrics` for generating performance metrics data, including boot time, network throughput & latency, and block I/O. 
The new target can be compiled from: 
`$ cargo build --all --bin performance-metrics`
Also, we provide a quick way to generate the performance metrics via our dev container:
`$ ./scripts/dev_cli.sh tests --metrics`
The output is in both human-readable and JSON format:
```
root@7439288450fd:/cloud-hypervisor# ./target/debug/performance-metrics  --test-filter pmem
Test 'performance_boot_time_pmem' running .. (test_time = 2s, test_iterations = 10)
Test 'performance_boot_time_pmem' .. ok: mean = 0.0791802, std_dev = 0.007185693728513626
{
"git_human_readable": "v21.0-135-g8c9d5b01-dirty",
"git_revision": …
```

Add a new binary target for generating performance metrics

---

pci/src/msix.rs

This helps debugging MSI-X issues.

pci: add debug output for enabling and disabling MSI-X

---

resources/Dockerfile

Simplify the dev container to both reduce the build time (from over 1hr50) but also to reduce the binary size.

Streamline dev container

---

resources/Dockerfile

This reverts commit d27316dab63c0e6e3d1e8ed2e5a7c11489fe283b.
Jenkins testing showed up issues that didn't appear during manual
testing even after using "dev_cli.sh build-container" before running
integration tests.

Revert "Dockerfile: Streamline installed packages"

---

resources/Dockerfile

This reverts commit 98bbfa97385b21526bf17c0a5bee2fa1af71b85a.
Some tests are continuing to fail even after reverting
d27316dab63c0e6e3d1e8ed2e5a7c11489fe283b. This is the only other
relevant change.

Revert "Dockerfile: Move to impish as base for packaged virtiofsd"

---

.github/workflows/docker-image.yaml
resources/Dockerfile

This will allow easier transitioning between versions of the container.
A later PR will update the CI to use this new tag.

github: Use tag derived from date for docker image

---

scripts/dev_cli.sh

This allows more predictable use of the container.

scripts: Use date tagged docker container in dev_cli.sh

---

arch/src/aarch64/fdt.rs
vmm/src/config.rs
vmm/src/cpu.rs

Fixes #3733.
Update VCPU topology handling code:
- ACPI: When VCPU topology is not specified, a bland ACPI PPTT table was built. Now we fill the PPTT with default topology setting.
- FDT: Simplify the source code.

Update VCPU topology handling code on AArch64

---

vmm/src/api/openapi/cloud-hypervisor.yaml

42b5d4a2f7820469bd538ddd19d7f33eea6f68a8 has changed how the PciBdf
field of a DeviceNode is represented (from an int32 to its own struct).
To avoid marshelling / demarshelling issues for the projects relying on
the openapi auto generated code, let's propagate the change, updating
the yaml file accordingly.

openapi: Update the PciBdf type

---

pci/src/configuration.rs

I incorrectly used the MSI message control register values for the mask
not the the MSI-X control registers.
The correct writable fields for MSI-X are only bits 14 and 15 of 2nd
16-bit word.
Those are:
* Function Mask: 14
* MSI-X Enable: 15
See "Table 7-47 Message Control Register for MSI-X" from
"NCB-PCI_Express_Base_5.0r1.0-2019-05-22.pdf"

pci: configuration: Correctly mask MSI-X control register

---

virtio-devices/src/transport/pci_common_config.rs
virtio-devices/src/transport/pci_device.rs

The Rust beta channel has been updated, and some recent CIs fail as the new version of Clippy reports warnings. This PR fixes the issues as Clippy suggested.

Fix Clippy Reported Issues

---

.github/workflows/build.yaml
Cargo.toml

Starting from Rust 1.56 Cargo supports specifying the minimum supported
rust version (MSRV) via "rust-version". If the compiler version is not
satisfied, Cargo prints an error and exits early.
MSRV is useful information to packagers. Using this field also saves us
from adding another file to the tree.
The version is currently set to 1.54, which is tested to build Cloud
Hypervisor successfully. Although anyone who uses 1.54 will see a
warning because "rust-version" is only introduced in 1.56. The warning
can be safely ignored.

build: introduce rust-version in Cargo.toml

---

vmm/src/api/openapi/cloud-hypervisor.yaml

Make sure the OpenAPI definition matches the code.

vmm: api: Make 'local' optional in SendMigrationData

---

vmm/src/api/openapi/cloud-hypervisor.yaml

openapi: Mark ReceiveMigrationData.receiver_url as required

---

Cargo.lock
performance-metrics/Cargo.toml
performance-metrics/src/main.rs
scripts/dev_cli.sh
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_sgx.sh
scripts/run_integration_tests_vfio.sh
scripts/run_integration_tests_windows.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh
scripts/test-util.sh

Performance-metrics: Store test list with a `const` array and pass custom arguments to the test binary from "dev_cli.sh"

---

scripts/dev_cli.sh

This series addresses a regression in the `dev_cli.sh` script, which was noticed when bumping the Cloud Hypervisor version used by Kata containers.
scripts: dev_cli: Don't quote $features_build
2805e7b1dc203ff4468e3743afe2fe77f444a0a8 quoted enclose variables to
prevent globbing or incorrect splitting.  However, by doing with with
$features_build it broke the capability to call the script as:
```
$ ./scripts/dev_cli.sh build --release --libc musl -- --features tdx
```
Before 2805e7b1dc203ff4468e3743afe2fe77f444a0a8 it simply worked, after,
the result is:
```
docker run --user 1000:1000 --workdir /cloud-hypervisor --rm --volume /dev/kvm --volume /home/ffidenci/go/src/github.com/cloud-hypervisor/cloud-hypervisor:/cloud-hypervisor --env RUSTFLAGS= cloudhypervisor/dev:20220223-0 cargo build …
```

scripts: dev_cli: Add the ability to pass `--features foo` to the dev_cli.sh script

---

scripts/dev_cli.sh

Adding the missing TARGET_CC environment variable to get the build to
complete correctly.
Fixes #3776

scripts: Fix musl build on aarch64

---

performance-metrics/src/main.rs

The unit from ethr is microseconds.

performance-metrics: Rename virtio_net_latency_ns->virtio_net_latency_us

---

Jenkinsfile
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_unit_tests.sh

Follow up https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3777. 
Same errors can also be reproduced in AArch64 integration tests with command: `./scripts/dev_cli.sh tests --libc musl --integration`

scripts: Fix musl build error in integration tests on AArch64

---

net_util/src/lib.rs
net_util/src/tap.rs

Most uses of create_socket() don't need an AF_INET, and some host
kernels are IPv6-only.  The tun ioctls such as SIOCGIFHWADDR work with
an AF_UNIX socket, which most everyone should have.
Signed-off-by: Barret Rhoden <brho@google.com>

net_util: fallback to AF_UNIX if AF_INET sockets are not supported

---

.github/workflows/release.yaml

Needed since:
commit 0ab4097606000181d0763a376cdc05011243ecc2
Author: Bo Chen <chen.bo@intel.com>
Date:   Thu Feb 10 18:29:53 2022 -0800
test_infra: Enable cross-build for "musl" and "aarch64" targets
With enabling the `vendered-openssl` feature, we can now cross-build the
`test_infra` crate for  "musl" and "aarch64" targets. In this way, we
can remove the `test_infra` crate from the "exclude" list, so that this
crate can be checked and processed by "cargo clippy" and "cargo fmt".
More details can be found: https://docs.rs/openssl/latest/openssl/#vendored
As 'musl-gcc' is required, this commit also installs the `musl-tools`
package for our "build" github action on the musl target [1].
[1] https://github.com/actions-rs/toolchain/issues/102 …

github: Install missing musl tools

---

Cargo.lock
vhost_user_block/Cargo.toml

Using multiple different versions breaks vendoring.

build: Use single version of vhost-user-backend

---

arch/src/lib.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

Add a field for its length and fix up users.
Things work just because all hardcoded values agree with each other.
This is prone to breakage.

arch: do not hardcode MMIO region length in MmioDeviceInfo

---

scripts/run_metrics.sh

To be consistently with the integration scripts, we now pass through the
`--test-filter` option of the test scripts to the `performance-metrics`
binary. Now the following two commands achieve the same results:
`$./scripts/dev_cli.sh tests --metrics -- --test-filter boot_time_ -- --test-filter latency`
`$./scripts/dev_cli.sh tests --metrics -- -- --test-filter boot_time_ --test-filter latency`
Note that, the test scripts support only single occurrence of the
`--test-filter` option while the `performance-metrics` binary allows
multiple occurrences for filtering based on different keywords.
Fixes: #3787

scripts: Pass-through '--test-filter' option to `performance-metrics`

---

scripts/run_metrics.sh

Reverts cloud-hypervisor/cloud-hypervisor#3803

Revert "scripts: Pass-through '--test-filter' option to `performance-metrics`"

---

Cargo.lock
Cargo.toml
block_util/Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
net_util/Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml
virtio-devices/Cargo.toml
vm-virtio/Cargo.toml
vmm/Cargo.toml

Move to release version v0.2.0 for both vm-virtio and vhost-user-backend
crates rather than relying on their main branch, as they might be
subject to breaking changes.
Fixes #3800

deps: Move to latest vm-virtio and vhost-user-backend releases

---

scripts/run_metrics.sh
scripts/test-util.sh

Populate iff the the parameter is passed.
Following combinations tested:
scripts/dev_cli.sh tests --metrics -- --test-filter boot_time
scripts/dev_cli.sh tests --metrics -- --test-filter boot_time -- --report-file /root/workloads/metrics.json
scripts/dev_cli.sh tests --metrics
scripts/dev_cli.sh tests --metrics --  -- --report-file /root/workloads/metrics.json
Fixes: #3787

scripts: Propagate "--test-filter" metrics test

---

.github/dependabot.yml

Reduce the number of open pull requests dependabot will create to avoid
excessive rebase and rebuilds of PRs. This avoids a situation with a 2nd
PR being rebased after a 1st is merged resulting in a wasteful rebuild.

.github: Avoid excessive rebase & rebuilds from dependabot

---

arch/src/x86_64/layout.rs
arch/src/x86_64/mod.rs

This allows ACPICA to find the EBDA and load the ACPI tables when
scanning for them.

arch: x86_64: Write EBDA address to BIOS data area

---

virtio-devices/src/transport/pci_device.rs
vmm/src/device_manager.rs

In order to anticipate the introduction of the vDPA feature, this is a preliminary PR to handle generic DMA mapping and unmapping for virtio devices.

vmm: device_manager: Allow DMA map/unmap for virtio devices

---

vmm/src/api/http_endpoint.rs

vmm.ping/vm.info will hang for PUT method, vm.create/vmm.shutdonw hang for GET method.
Because these four APIs do not write the response body when the HTTP method does not match.
Signed-off-by: LiHui <andrewli@kubesphere.io>

API: fix http hang for vmm.ping/vm.create/vm.info/vmm.shutdown

---

net_util/src/ctrl_queue.rs
net_util/src/queue_pair.rs
virtio-devices/src/net.rs
virtio-devices/src/vhost_user/net.rs

* Use `Queue::enable_notifications()` as advised in documentation
* Generate control queue interrupt if necessary
* Use virtio-net implementation of `NetCtrlEpollHandler` inside vhost-user-net

virtio-devices: net: Tweaks and improvements

---

vmm/src/cpu.rs

Generate an error if the `CpuManager` does not support hotplug/unplug and streamline the generated DSDT table to remove the unused content when it cannot be resized.

Limit CPU hotplug/unplug on TDX

---

docs/fs.md

Update the content of the documentation to clarify how the cache option
from virtiofsd has an impact on the host page cache, while the dax
option for the filesystem in the guest has an impact on the guest page
cache.
The document is also updated to not have lines exceeding 80 characters.
Fixes #3826

docs: Update virtio-fs documentation

---

pci/src/vfio_user.rs
vfio_user/src/lib.rs

Whenever a vfio-user device is dropped, the communication between the
VMM and the backend should be shutdown.

vfio_user: Shutdown the communication with the backend

---

hypervisor/src/mshv/mod.rs

It should have said MSHV in the comment.

hypervisor: mshv: fix a comment

---

vmm/src/acpi.rs

This can already be calculated by the summing the tables reported by the
Linux kernel but this is more convenient.

vmm: acpi: Print total size of ACPI tables

---

docs/iommu.md
tests/integration.rs
vmm/src/config.rs
vmm/src/device_manager.rs

* Return an error if trying to hotplug a device behind an IOMMU when not using an IOMMU segment
* Validate configuration for devices on IOMMU segments to ensure they are fully behind the IOMMU
* Actually setup mappings for virtio devices that are actually behind the IOMMU when hotplugged.

Improve virtio-iommu & dedicated IOMMU segment handling

---

devices/src/legacy/uart_pl011.rs
performance-metrics/src/main.rs
performance-metrics/src/performance_tests.rs
scripts/run_integration_tests_aarch64.sh
scripts/run_metrics.sh
scripts/test-util.sh

Enable current performance-metrics tests on arm64.
boot up time test: trap from guest to vmm base on pl011 reserved mmio region. this need support from guest kernel, so using a temporary linux branch which will be removed on merge.
fio test: build fio from source code as the default one doesn't work well with iouring on arm64.
network latency test: build ethr from source code as there is no such binary for arm64 and do some twists to let the test work as ethr is not stable on arm64.

Enable performance-metrics tests on AArch64

---

virtio-devices/src/vhost_user/fs.rs

The file descriptor provided to fs_slave_map() and fs_slave_io() is
passed as a AsRawFd trait, meaning the caller owns it. For that reason,
there's no need for these functions to close the file descriptor as it
will be closed later on anyway.

virtio-devices: vhost-user: fs: Don't close file descriptor

---

vmm/src/device_manager.rs
vmm/src/memory_manager.rs

When running non-dynamic or with virtio-mem for hotplug the ACPI
functionality should not be included on the DSDT nor does the
MemoryManager need to be placed on the MMIO bus.
Fixes: #3883

vmm: Don't expose MemoryManager ACPI functionality unless required

---

virtio-devices/src/vdpa.rs

Now that we rely on vhost v0.4.0, which contains the fix for
get_iova_range(), we don't need the workaround anymore, and we can
actually call into the dedicated function.
Fixes #3861

virtio-devices: vdpa: Remove get_iova_range() workaround

---

virtio-devices/src/seccomp_filters.rs

virtio-devices: Add missing syscalls to virtio common list

---

.github/workflows/build.yaml
.github/workflows/quality.yaml
Cargo.toml
docs/cpu.md
option_parser/src/lib.rs
src/main.rs
vmm/Cargo.toml
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/cpu.rs
vmm/src/lib.rs

Adds support for an x86_64 only --amx option that will attempt to
enable AMX usage for guests (needs a 5.16+ kernel) or exit with
failure.
Might be worthwhile moving this to the vmm thread and checking for the
option in migrations but letting this be as simple as possible for the
first pass.
Signed-off-by: William Douglas <william.douglas@intel.com>

Add support for enabling AMX in vm guests

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh
scripts/test-util.sh

This commit unifies the custom linux kernel build in x86, Arm, and
performance metrics to the same function. Therefore, when bumping
the kernel version, we can make sure we only need to make the change
in one place.

scripts: Use the same linux kernel build function everywhere

---

Cargo.toml
devices/src/legacy/cmos.rs
devices/src/legacy/mod.rs
tests/integration.rs
vmm/src/device_manager.rs

If EFI reset fails on the Linux kernel then it will fallthrough to CMOS
reset. Implement this as one of our reset solutions.
Fixes: #3912

devices: cmos: Implement CMOS based reset

---

virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/net.rs
vmm/src/device_manager.rs

By enabling the VIRTIO feature VIRTIO_F_IOMMU_PLATFORM for all
vhost-user devices when needed, we force the guest to use the DMA API,
making these devices compatible with TDX. By using DMA API, the guest
triggers the TDX codepath to share some of the guest memory, in
particular the virtqueues and associated buffers so that the VMM and
vhost-user backends/processes can access this memory.

virtio-devices: vhost-user: Add support for TDX

---

arch/src/x86_64/mod.rs
hypervisor/src/hypervisor.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/lib.rs

Extends the `Hypervisor` API to retrieve the TDX capabilities from KVM, and patch the CPUID to expose a correct list of XFAM features.

Retrieve TDX capabilities to patch CPUID

---

vmm/src/cpu.rs
vmm/src/memory_manager.rs

vmm,cpu: Deny resizing only if the vcpu amount has changed
188078467db42f50f5b7e7a7969738ebf8aec95c made clear that resize should
only happen when dealing with a "dynamic" CpuManager.  Although this is
very much correct, it causes a regression on Kata Containers (and on any
other consumer of Cloud Hypervisor) in cases where a resize would be
triggered but the vCPUs values wouldn't be changed.
There's no doubt Kata Containers could do better and do not call a
resize in such situations, and that's something that should **also** be
solved there.  However, we should also work this around on Cloud
Hypervisor side as it introduces a regression with the current Kata
Containers code.
--- 
vmm,memory_manager: Deny resizing only if the ram amount has changed
Similarly to the previous commit …

Only deny cpu and memory resizing if the request amount has changed.

---

vmm/src/cpu.rs
vmm/src/memory_manager.rs

The introduction of errror if live resizing is not possible is a
regression compared to the original behaviour where the new size would
be stored in the config and reflected in the next boot. This behaviour
was also inconsistent with the effect of resizing with no VM booted.
Instead of generating an error allow the code to go ahead and update the
config so that the new size will be available upon the reboot.

vmm: Don't error if live resizing is not possible

---

arch/src/x86_64/tdx/mod.rs
docs/intel_tdx.md
vmm/src/vm.rs

Based on QEMU patches from branch `tdx-qemu-2022.03.29-v7.0.0-rc1` and based on latest guest kernel/image, let's update the Cloud Hypervisor support for TDX with this PR.

Update TDX according to latest version

---

block_util/src/lib.rs
net_util/src/ctrl_queue.rs
net_util/src/queue_pair.rs
tests/integration.rs
virtio-devices/src/console.rs
virtio-devices/src/device.rs
virtio-devices/src/iommu.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/transport/pci_common_config.rs
virtio-devices/src/vdpa.rs
virtio-devices/src/vsock/packet.rs
vm-virtio/src/lib.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs

Adding the support for placing a vDPA device behind a virtual IOMMU, making the guest seeing the device as being attached to an IOMMU.
Partially fixes #3809

Add vIOMMU support to vDPA devices

---

arch/src/aarch64/fdt.rs
arch/src/aarch64/layout.rs
arch/src/aarch64/mod.rs
tests/integration.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3890
Reserve the hole for some devices that have to be placed close to 4 GiB. Now this is only for TPM device (which requires 20KB between 0xfed40000-0xfed44fff). 
To make it generic for similar requirements, totally 64MiB is reserved.

Reserve a memory hole in32-bit address space on AArch64

---

tests/integration.rs
virtio-devices/src/iommu.rs

It doesn't matter if we're trying to translate a GVA or a GPA address,
but in both cases we must error out if the address couldn't be
translated.

virtio-devices: iommu: Error out if couldn't translate address

---

arch/src/aarch64/fdt.rs
arch/src/aarch64/gic/gicv3.rs
arch/src/aarch64/layout.rs
arch/src/aarch64/mod.rs
arch/src/aarch64/regs.rs
arch/src/lib.rs
vmm/src/acpi.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

Some code optimization work:
-  Align the type of `*_START` constants to `GuestAddress`
- Remove some functions that only return a layout constant

Refactoring layout related code on AArch64

---

.github/workflows/build.yaml
.rustfmt.toml
Cargo.toml
acpi_tables/Cargo.toml
api_client/Cargo.toml
arch/Cargo.toml
block_util/Cargo.toml
devices/Cargo.toml
event_monitor/Cargo.toml
fuzz/Cargo.toml
hypervisor/Cargo.toml
net_gen/Cargo.toml
net_util/Cargo.toml
option_parser/Cargo.toml
pci/Cargo.toml
performance-metrics/Cargo.toml
qcow/Cargo.toml
rate_limiter/Cargo.toml
test_infra/Cargo.toml
vfio_user/Cargo.toml
vhdx/Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml
virtio-devices/Cargo.toml
vm-allocator/Cargo.toml
vm-device/Cargo.toml
vm-migration/Cargo.toml
vm-virtio/Cargo.toml
vmm/Cargo.toml

Rust 2021 edition has a few improvements over the 2018 edition. Migrate
the project to 2021 edition by following recommended migration steps.
Luckily, the code itself doesn't require fixing.
Bump MSRV to 1.56 as it is required by the 2021 edition. Also fix the
clap build dependency to make Cloud Hypervisor build again.

build: migrate to Rust 2021 edition

---

.github/workflows/release.yaml

Unfortunately Rust 1.59 produces binaries that segfault when compiled
with musl-gcc wrappers. Which is exactly how we produce out aarch64 and
musl binaries for the release.
See: https://github.com/rust-lang/rust/issues/95926

.github: Fix Rust version for release to 1.58

---

devices/src/gic.rs
devices/src/ioapic.rs
devices/src/legacy/gpio_pl061.rs
devices/src/legacy/rtc_pl031.rs
devices/src/legacy/serial.rs
devices/src/legacy/uart_pl011.rs
pci/src/msi.rs
pci/src/msix.rs
vm-device/src/interrupt/mod.rs
vmm/src/interrupt.rs

The calls to these functions are always preceded by a call to
InterruptSourceGroup::update(). By adding a masked boolean to that
function call it possible to remove 50% of the calls to the
KVM_SET_GSI_ROUTING ioctl as the the update will correctly handle the
masked or unmasked case.
This causes the ioctl to disappear from the perf report for a boot of
the VM.

vm-device, pci, devices: Remove InterruptSourceGroup::{un}mask

---

vmm/src/config.rs
vmm/src/device_manager.rs

KSM would never merge the file backed pages so this option has no
effect.
See: #3968

vmm: Deprecate mergeable option from virtio-pmem

---

.github/workflows/release.yaml

.github: Use correct toolchain version for release builds

---

pci/src/bus.rs
pci/src/device.rs
pci/src/vfio.rs
pci/src/vfio_user.rs
virtio-devices/src/transport/pci_device.rs
vmm/src/device_manager.rs

By relying on the `Resource` structure defined in the `vm-device` crate, we're able to factorize and reuse the same code from VIRTIO, VFIO and vfio-user, so that we can store the BARs addresses of every device. This is preparatory work to make sure all PCI devices can be eventually snapshot/restored/migrated.

pci: Store BARs addresses through a list of PCI resources

---

.github/workflows/build.yaml
.github/workflows/quality.yaml

Cargo comes with a `--locked` option that makes sure Cargo.lock is not
changed.
Drop the `git status` check which is supposed to achieve the same thing
in the CI.

github: use --locked in cargo invocations

---

docs/io_throttling.md

The I/O operations knobs are prefixed `ops_` rather than `bw_`, as `bw_`
refers to the "bandwidth" knobs.

docs: Fix the name of the I/O operations knobs

---

scripts/dev_cli.sh

For example:
```shell
./scripts/dev_cli.sh build --release --libc musl --runtime "sudo nerdctl"
```
works. And presumably podman as well.
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

scripts: dev_cli.sh: add option to specify container runtime

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
test_infra/src/lib.rs
tests/integration.rs

By augmenting existing set of tests, this patch added a set of tests for live-upgrade that covers use cases with NUMA, vhost-user (OVS-DPDK), and local-migration.
Fixes: #3949

Add live upgrade tests

---

vmm/src/seccomp_filters.rs

glibc 2.35 as shipped by Fedora 36 now uses the rseq syscall.

vmm: seccomp: Allow SYS_rseq as required by newer glibc

---

arch/src/x86_64/mod.rs
arch/src/x86_64/smbios.rs
option_parser/src/lib.rs
src/main.rs
tests/integration.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/vm.rs

- option_parser: Support having "=" inside option values
- vmm: config: Add "serial_number" option to "--platform"
- arch, vmm: Expose platform serial_number via SMBIOS
- vmm: openapi: Add serial_number to PlatformConfig
Fixes: #4002

Expose platform serial number to guest (for cloud-init)

---

vmm/src/config.rs
vmm/src/memory_manager.rs

If using the ACPI based hotplug only memory can be added so if the
hotplug RAM size is the same as the boot RAM size then do not include
the memory manager DSDT entries.
Also: this change simplifies the code marginally by making the
HotplugMethod enum Copyable.
This was identified from the following perf output:
1.78%     0.00%  vmm              cloud-hypervisor      [.] <vmm::memory_manager::MemorySlots as acpi_tables::aml::Aml>::append_aml_bytes
|
---<vmm::memory_manager::MemorySlots as acpi_tables::aml::Aml>::append_aml_bytes
<vmm::memory_manager::MemorySlot as acpi_tables::aml::Aml>::append_aml_bytes
acpi_tables::aml::Name::new
<acpi_tables::aml::Path as acpi_tables::aml::Aml>::append_aml_bytes
__libc_malloc

vmm: Only create ACPI memory manager DSDT when resizable

---

tests/integration.rs
virtio-devices/src/iommu.rs

Implement the bypass mode for virtio devices sitting behind a virtual IOMMU. This mode allows such devices to be accessed by a firmware that wouldn't know anything about `virtio-iommu` without breaking the boot.
Fixes #3941 
Partially fixes #3987

virtio-devices: iommu: Implement bypass mode for virtio devices

---

vmm/src/api/openapi/cloud-hypervisor.yaml

The Token Bucket fields are, on the Cloud Hypervisor side, u64.
However, we expose those for Kata Containers as int64.
Let's take the same approach as Firecracker and expose those as uint64.

vmm, openapi: Token Bucket fields should be uint64

---

test_infra/src/lib.rs
tests/integration.rs

We don't have the coverage for the following virtio devices from our live migration/upgrade tests:
What's already being covered:
- Console
- Mem
- Net
- Rng
- Block

Cover all virtio devices for live migration and upgrade tests

---

vmm/src/api/openapi/cloud-hypervisor.yaml

This reverts commit 87eed369cd091db76ed8542750803659e729b239.
The reason we're reverting this is that OpenAPI doesn't know how to deal
with unsigned types. :-/
Right now the best to do is keep it as it's, as an int64, and try to fix
OpenAPI, or even switch to swagger, as the latter knows how to properly
deal with those.  However, switching to swagger is far from being an 1:1
transition and will require time to experiment, thus reverting this for
now seems the best approach.

Revert "vmm, openapi: Token Bucket fields should be uint64"

---

tests/integration.rs
vmm/src/api/http.rs

The socket will safely deleted on shutdown and so it is not necessary to
delete the API socket when starting the HTTP server.
Fixes: #4026
Signed-off-by: LiHui <andrewli@kubesphere.io>

vmm: api: Do not delete the API socket on API server creation

---

vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

We must verify that identifiers provided through cold boot as well as hotplug mechanism are unique.
Fixes #4024

vmm: Ensure identifiers are unique

---

vmm/src/cpu.rs
vmm/src/gdb.rs

We don't use the VmmOps trait directly for manipulating memory in the
core of the VMM as it's really designed for the MSHV crate to handle
instruction decoding. As I plan to make this trait MSHV specific to
allow reduced locking for MMIO and PIO handling when running on KVM this
use should be removed.

gdb: Do not use VmmOps for memory manipulation

---

devices/src/legacy/debug_port.rs
devices/src/legacy/mod.rs
devices/src/legacy/uart_pl011.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

This is a cleaner approach to handling the I/O port write to 0x80.
Whilst doing this also use generate the timestamp at the start of the VM
creation. For consistency use the same timestamp for the ARM equivalent.

vmm, devices: Move logging of 0x80 timestamp to its own device

---

vmm/src/seccomp_filters.rs

This is required when hot-removing a vfio-user device. Details code path
below:
```
Thread 6 "vcpu0" received signal SIGSYS, Bad system call.
[Switching to Thread 0x7f8196889700 (LWP 2358305)]
0x00007f8196dae7ab in shutdown () at ../sysdeps/unix/syscall-template.S:78
78	T_PSEUDO (SYSCALL_SYMBOL, SYSCALL_NAME, SYSCALL_NARGS)
(gdb) bt
0x00007f8196dae7ab in shutdown () at ../sysdeps/unix/syscall-template.S:78
0x000056189240737d in std::sys::unix::net::Socket::shutdown ()
at library/std/src/sys/unix/net.rs:383
std::os::unix::net::stream::UnixStream::shutdown () at library/std/src/os/unix/net/stream.rs:479
0x000056189210e23d in vfio_user::Client::shutdown (self=0x7f8190014300)
at vfio_user/src/lib.rs:787
0x00005618920b9d02 in <pci::vfio_user::VfioUserPciDevice as core::ops::drop::Drop>::drop ( …
```

vmm: Add 'shutdown()' to vCPU seccomp filter

---

pci/src/vfio.rs
pci/src/vfio_user.rs

We can return prematurely from 'map_mmio_regions()' (e.g. when a mmap call
failed for vfio or 'create_user_memory_region()' failed for vfio-user)
without updating the 'MmioRegion::user_memory_regions' with the
information of previous successful mmaps, which in turn would cause mmap
leaks particularly for the case of hotplug where the 'vmm' thread will
keep running. To fix the issue, let's keep 'MmioRegion::user_memory_regions'
updated right after successful mmap calls.
Fixes: #4068

pci: vfio: Fix potential mmap leaks from the mmio regions

---

vmm/src/vm.rs

Whenever going through the codepath of loading a RAW firmware, we always
add an extra RAM region to the guest memory through the memory manager.
But we must be careful to use the updated guest memory rather than a
previous reference that wasn't containing the new region, as this can
lead to the following error:
VmBoot(FirmwareLoad(InvalidGuestAddress(GuestAddress(4290772992))))
This is fixed by the current patch, getting the latest reference onto
the guest memory from the memory manager right after the new region has
been added.

vmm: Fix loading RAW firmware

---

hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
vmm/src/cpu.rs
vmm/src/vm.rs

The trait and functionality is about operations on the VM rather than
the VMM so should be named appropriately. This clashed with with
existing struct for the concrete implementation that was renamed
appropriately.

vmm, hypervisor: Clean up nomenclature around offloading VM operations

---

performance-metrics/src/main.rs
performance-metrics/src/performance_tests.rs

performance-metrics: Add boot time metrics using multiple vCPUs

---

Cargo.lock
hypervisor/Cargo.toml
hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
vm-device/Cargo.toml
vm-device/src/interrupt/mod.rs
vmm/src/device_manager.rs
vmm/src/interrupt.rs

My goal is to reduce the amount of conditional hypervisor code present in the vmm crate:
- hypervisor: Move creation of irq routing struct to hypervisor crate
- vmm: Simplify MsiInterruptManager generics

Refactor interrupt handling

---

arch/src/aarch64/mod.rs
arch/src/x86_64/mod.rs
arch/src/x86_64/regs.rs
hypervisor/src/arch/x86/emulator/mod.rs
hypervisor/src/cpu.rs
hypervisor/src/hypervisor.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/lib.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/mshv/x86_64/mod.rs
hypervisor/src/vm.rs
vm-device/src/interrupt/mod.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs

The goal is to make it more obvious what the types are that are exported from the hypervisor crate in order to facilitate building with both mshv and kvm in the same binary:
- hypervisor: Make vm module private
- hypervisor: Make hypervisor module private
- hypervisor: mshv: Move CpuIdEntry alias into x86_64 module
- vmm, arch: CpuId is x86_64 specific so import from the x86_64 module
- hypervisor: Explicitly `pub use` at the hypervisor crate top-level
- arch: Use more descriptive name for hypervisor::Vcpu than fd
- vmm: cpu: tdx: Don't use fd suffix for something not an FD

Be more explicit with hypervisor crate interface

---

Cargo.lock
Cargo.toml
acpi_tables/Cargo.toml
arch/Cargo.toml
block_util/Cargo.toml
devices/Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
hypervisor/Cargo.toml
net_util/Cargo.toml
pci/Cargo.toml
vfio_user/Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml
virtio-devices/Cargo.toml
virtio-devices/src/transport/pci_device.rs
virtio-devices/src/vhost_user/mod.rs
vm-allocator/Cargo.toml
vm-device/Cargo.toml
vm-migration/Cargo.toml
vm-virtio/Cargo.toml
vm-virtio/src/lib.rs
vmm/Cargo.toml

The main goal of this PR is to move to `virtio-queue` 0.3.0. To do so, it needs to update the dependency on `vhost-user-backend` to the latest revision from the main branch. It also need to patch the Cloud Hypervisor code to keep cloning the `Queue` now that the `QueueState` doesn't implement `Clone` anymore.
Just a note that from a Rust perspective, it'd be cleaner to use the `QueueStateSync` approach, placing the `QueueState` behind an `Arc<Mutex<>>`, and allowing for cloning the reference. But this would involve many locks to be taken on the hotpath of handling the virtio queues, affecting directly the performance.
After some analysis, we confirmed that the current design present in Cloud Hypervisor isn't introducing any issue, even when relying on copies of the Queue. That's because …

deps: Bump to virtio queue 0.3.0

---

event_monitor/src/lib.rs
tests/integration.rs

In this way, we can cover a broad range of events from the event monitor
while avoiding code duplication.
Fixes: #4054

tests: Extend existing tests with checks on event monitor

---

Cargo.lock
arch/Cargo.toml
arch/src/lib.rs
event_monitor/Cargo.toml
event_monitor/src/lib.rs
hypervisor/Cargo.toml
hypervisor/src/kvm/aarch64/mod.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/mshv/x86_64/mod.rs
pci/Cargo.toml
performance-metrics/Cargo.toml
performance-metrics/src/main.rs
virtio-devices/Cargo.toml
virtio-devices/src/lib.rs
vm-device/Cargo.toml
vm-device/src/lib.rs
vm-migration/Cargo.toml
vm-migration/src/lib.rs
vm-migration/src/protocol.rs
vmm/Cargo.toml
vmm/src/api/mod.rs
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/device_tree.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

There is no need to include `serde_derive` separately,
as it can be specified as serde feature instead.
Also this PRs removes relevant `extern crate` imports as these are
[deprecated](https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html) in 2015 edition.
Signed-off-by: Maksym Pavlenko <pavlenko.maksym@gmail.com>

Clean up serde dependencies

---

README.md

The qemu-img tool is used as part of the tutorial but is not installed
by default on a fresh ubuntu 22.04 server.

docs: Add dependency qemu-img

---

tests/integration.rs
virtio-devices/src/seccomp_filters.rs
vmm/src/seccomp_filters.rs

Latest cargo beta version raises warnings about unused macro rules.
Simply remove them to fix the beta build.

virtio-devices, vmm: Remove unused macro rules

---

virtio-devices/src/transport/mod.rs
virtio-devices/src/transport/pci_device.rs
vmm/src/device_manager.rs

In order to ensure that the virtio device thread is spawned from the vmm
thread we use an asynchronous activation mechanism for the virtio
devices. This change optimises that code so that we do not need to
iterate through all virtio devices on the platform in order to find the
one that requires activation. We solve this by creating a separate short
lived VirtioPciDeviceActivator that holds the required state for the
activation (e.g. the clones of the queues) this can then be stored onto
the device manager ready for asynchronous activation.

virtio-devices, vmm: Optimised async virtio device activation

---

virtio-devices/src/transport/mod.rs
virtio-devices/src/transport/pci_device.rs
vmm/src/device_manager.rs

This reverts commit f160572f9deed7735bb249c6a734c915e9bce432.
There has been increased flakiness around the live migration tests since
this was merged. Speculatively reverting to see if there is increased
stability.

Revert "virtio-devices, vmm: Optimised async virtio device activation"

---

.github/workflows/release.yaml

This reverts commit 6a099257e8e9222c53e19fa3858e9211ae943f95.
It is now clear that pinning the toolchain for cross compilation is not
necessary since we only use it for building to aarch64:
https://github.com/rust-lang/rust/issues/95926#issue-1199547707
"This problem doesn't currently show up when cross-compiling from x86_64
to aarch64, since aarch64 doesn't use static-pie by default, but
enabling PIE with -C relocation-model=pie triggers the same bug and
makes the resulting binaries segfault."
Fixes: #3962

Revert ".github: Fix Rust version for release to 1.58"

---

.gitignore
rpm/cloud-hypervisor.spec
rpm/update_src

Refactoring and features in this patch:
- Add support for aarch64 build
- Add offline build configuration using vendored crates
- Add script to generate vendored sources
- Fix openssl-sys dependency

rpm: Extend spec to support aarch64 and more

---

tests/integration.rs

From the logs it appears that booting the VM to the point at which it
can signal to the host can sometimes take longer than then 30 seconds
specified.
Fixes: #4136

tests: Use default timeout for booting in live migration tests

---

.github/workflows/release.yaml

.github: Use 1.60 toolchain consistently in release process

---

vmm/src/vm.rs

The vCPU is created and set after all the devices on a VM's boot.
There's no reason to follow a different order on the restore codepath as
this could cause some unexpected behaviors.

vmm: Ensure restore matches boot sequence

---

Jenkinsfile

In order to conserve resources it is better to not run CI, whenever there
are changes only in fuzz/Cargo.toml or fuzz/Cargo.lock.
Fixes #4148

Jenkinsfile: Bypass running CI for fuzzer Cargo file changes

---

Jenkinsfile

This reverts commit 86d243938e878abe134bf174f32a7816bb5ccef0.
Build error:
Obtained Jenkinsfile from 86d243938e878abe134bf174f32a7816bb5ccef0
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 311: unexpected char: '\' @ line 311, column 88.
_TARGET}... | grep -v -E 'fuzz\/Cargo.(t

Revert "Jenkinsfile: Bypass running CI for fuzzer Cargo file changes"

---

Jenkinsfile

This reverts commit 0d0013c46e86c18d383f3e180fa8959091bba8b9.
Grovvy shell script execution engine does not like backslash as the
escape character. So we need to put another backslash to escape the
backslash character. This would most likely fix the issue that we saw
with the CI.

Reapply "Jenkinsfile: Bypass running CI for fuzzer Cargo file changes"

---

vmm/Cargo.toml

vmm: Pull in gdb dependencies only when building with feature

---

pci/src/msi.rs
pci/src/msix.rs
pci/src/vfio.rs
pci/src/vfio_user.rs
vmm/src/device_manager.rs

This PR doesn't provide full support for VFIO migration since it still requires the implementation of the VFIO migration API to be implemented. This will be responsible for storing the device's internal state.
It provides the first bits to let the VMM accept to snapshot and restore a VFIO device, by storing VMM internal states related to this device.

pci, vmm: Allow VFIO and vfio-user devices to be migrated

---

hypervisor/src/hypervisor.rs
hypervisor/src/mshv/mod.rs

By default Microsoft Hypervisor send a GP to the guest if it tries
read/write an unimplemented MSR from the hypervisor prospective. Instead
change this behavior to ignore read/write operations for unimplemented
MSRs

hypervisor: mshv: Override hypervisor R/W behavior for unknown MSR

---

performance-metrics/src/main.rs
scripts/run_metrics.sh

- performance-metrics: Produce some error messages if git commands fail
- scripts: Mark git repository as safe

performance-metrics: Fix metrics generation

---

test_infra/src/lib.rs
tests/integration.rs

Use direct kernel boot for all the tests that create the VM via API.

tests: Unify API based boot across architectures

---

docs/device_model.md

In the [Summary table of the device model documentation](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/device_model.md#summary), the Negative Squared Cross Mark emoji (❎) indicates that a device does not support build/runtime configuration, or is not enabled by default. Unfortunately, [many platforms render the Negative Squared Cross Mark emoji as a white X with a green background](https://emojipedia.org/cross-mark-button/), which is a bit confusing to me - in my experience, green/white indicate "yes" or "OK", and red/black indicate "no" or "not OK".
This PR updates the table to use the Cross Mark emoji (❌), which [appears as a red or black X against a transparent background for all platforms](https://emojipedia.org/cross-mark/).
Fixes #4240 
Signed-off-by: Dylan …

Docs: Change :negative_squared_cross_mark: to :x: emoji in device_model.md.

---

vmm/src/cpu.rs

The snapshots are stored in a BTree which is ordered however as the ids
are strings lexical ordering places "11" ahead of "2". So encode the
vCPU id as string with padding so that the ordering is preserved.
This fixes issues with CPU restore on aarch64.
See: #4239

vmm: cpu: Store the vCPU snapshots in ascending order

---

src/main.rs
vmm/src/vm.rs

Tested:
1. SIGTERM based
2. VM shutdown/poweroff
3. Injected VM boot failure after calling Vm::setup_tty()
Fixes: #4248

vmm: Always reset the console mode on VMM exit

---

src/bin/ch-remote.rs
tests/integration.rs

- ch-remote: Simplify ch-remote create from config file
- tests: tests_api_create_boot: Use ch-remote for creating and booting vm
- tests: Report stderr on ch-remote command failure

ch-remote "create" improvement and testing

---

net_util/src/tap.rs

Enabling the TAP interface is only about the IFF_UP flag, meaning we
shouldn't be testing the presence of IFF_RUNNING, and therefore we
shouldn't set it when not present.

net_util: Don't expect the interface to be IFF_RUNNING

---

virtio-devices/src/vhost_user/vu_common_ctrl.rs

Two issues in the vhost-user common code have been fixed in order to be able to boot a VM with either Rust Hypervisor Firmware or EDK2 OVMF when the booting disk is backed by a vhost-user-block device. Testing has been performed with SPDK.
Fixes #4285

virtio-devices: vhost-user: Allow booting with firmware from vhost-user-block

---

Cargo.lock
block_util/Cargo.toml
fuzz/Cargo.toml
net_util/Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml
virtio-devices/Cargo.toml
vm-virtio/Cargo.toml
vmm/Cargo.toml

And along with virtio-queue, we must also bump vhost-user-backend from
0.3.0 to 0.5.0 (since it relies on virtio-queue 0.4.0).

deps: bump virtio-queue from 0.3.0 to 0.4.0

---

vhdx/src/vhdx_header.rs

In the original code:
If the first header was invalid and the second header had the same
sequence number (zero) then the invalid first header would be returned.
The new code is more Rust idiomatic and avoids this situation.
See: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48858

vhdx: Avoid unwrap() of invalid header

---

src/main.rs
vmm/src/lib.rs
vmm/src/vm.rs

The VM specific signal (currently only SIGWINCH) should only be handled
when the VM is running.
The generic VMM signals (SIGINT and SIGTERM) need handling at all times.
Split the signal handling into two separate threads which have differing
lifetimes.
Tested by:
1.) Boot full VM and check resize handling (SIGWINCH) works & sending
SIGTERM leads to cleanup (tested that API socket is removed.)
2.) Start without a VM and send SIGTERM/SIGINT and observe cleanup (API
socket removed)
3.) Boot full VM, delete VM and observe 2.) holds.
4.) Boot full VM, delete VM, recreate VM and observe 1.) holds.
Fixes: #4269

vmm: Split signal handling for VM and VMM signals

---

arch/src/x86_64/regs.rs
hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/mshv/x86_64/mod.rs
vmm/src/cpu.rs

This allows dispatching to either KVM or MSHV automatically.

hypervisor: turn boot_msr_entries into a trait method

---

hypervisor/src/kvm/mod.rs
hypervisor/src/lib.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs

This avoids leaking hypervisor specific types into the wider VMM code.
Based on Dev's patches.

Introduce and use generic UserMemoryRegion

---

docs/custom-image.md

For installing packages for the custom Ubuntu image, we
need to setup DNS inside the chroot.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

docs: Add step to resolve DNS for installing packages

---

hypervisor/src/device.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
vmm/src/device_manager.rs

When going through Dev's code, I noticed vfio-ioctls is also leaking KVM / MSHV types.
I've thought of a way to fix it there too. It is probably going to break the existing APIs in vfio-ioctls, but I do want to make it more type-safe when I do that.
On the Cloud Hypervisor side, I want to access the underlying DeviceFd type from either KVM or MSHV. That means I need to use `Any`. Although its full potential can only be fulfilled when vfio-ioctls is fixed, we can use it immediately to catch type mismatch issues.

Provide downcasting ability to DeviceFd trait

---

hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/vm.rs
vmm/src/cpu.rs

Part of the PR prepares for https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3980
Refactor VCPU registers related code in `hypervisor` crate:
- Rename `(set_)core_registers` to `get/set_regs`, aligning to the equivalent functions on X86. Now we have following registers related functions:
- `get/set_regs` (X86_64 & AArch64): Access general purposed registers
- `get/set_sregs` (X86_64 only): Access special registers
- `get/set_sys_regs` (AArch64 only): Access some system registers. (Now this group of function can not be aligned to `get/set_sregs` on X86_64, they are quite different.)
- Improve the name and parameter setting of `(set_)system_registers`.
- Replace `#[cfg(any(target_arch = "arm", target_arch = "aarch64"))]` with `#[cfg(target_arch = "aarch64")]`. Because we do not …

Refactor AArch64 VCPU registers related code in `hypervisor`

---

hypervisor/src/lib.rs
hypervisor/src/mshv/x86_64/mod.rs

It is not used anywhere outside of the hypervisor crate.

hypervisor: do not export VcpuExit

---

vmm/src/lib.rs

[Whitespace-insensitive diff](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4309/files?w=1)
Previously, we were assuming that every time an eventfd notified us,
there was only a single event waiting for us.  This meant that if,
while one API request was being processed, two more arrived, the
second one would not be processed (until the next one arrived, when it
would be processed instead of that event, and so on).  To fix this,
make sure we're processing the number of API and debug requests we've
been told have arrived, rather than just one.  This is easy to
demonstrate by sending lots of API events and adding some sleeps to
make sure multiple events can arrive while each is being processed.
For other uses of eventfd, like the exit event, this doesn't matter —
even if we've …

vmm: fix missed API or debug events

---

tests/integration.rs

tests: Disable test_windows_guest_snapshot_restore for now

---

Cargo.lock
arch/src/x86_64/interrupts.rs
hypervisor/Cargo.toml
hypervisor/src/arch/x86/mod.rs
hypervisor/src/cpu.rs
hypervisor/src/hypervisor.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/mshv/x86_64/mod.rs
vmm/src/cpu.rs

In this PR I attempted to reduce the amount of generic structures needed by dropping some of the trait methods.
If there are needs in the future for those structures outside of the hypervisor crate we can always introduce them back to the trait.

Unified binary -- part 4

---

tests/integration.rs

It might sometimes take a few seconds for the guest to trigger the OOM
and report it back to the host. That's why this patch adds some sleep
time between the command in the guest supposedly triggering the OOM and
the check of the balloon size from the host.
Fixes #4336

tests: Fix test_virtio_balloon_deflate_on_oom()

---

fuzz/fuzz_targets/block.rs
virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/console.rs
virtio-devices/src/device.rs
virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/transport/pci_common_config.rs
virtio-devices/src/transport/pci_device.rs
virtio-devices/src/vdpa.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vhost_user/vu_common_ctrl.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/watchdog.rs

There were some assumptions in the code preventing some virtio queues from not being activated. This was mainly related to the fact that in such case the queue index would be determined in the wrong way and lead to unexpected behaviors.
This PR is also taking care of fixing the vhost-user common code so that virtio-fs can handle not having the `hiprio` queue activated and also be able to support a virtio reset. All these fixes allows to boot a Cloud Hypervisor VM with a virtio-fs backend attached along with using the EDK2 firmware. (Some patches from vhost-user-backend will be needed to fix `virtiofsd` as well).

virtio-devices: Ensure queue indexes are correct

---

api_client/src/lib.rs

Breaks the receive loop of the API client when the VMM shuts down the
socket connection. A shutdown is indicated by the return value 0 of the
`recv()` system call.[^1][^2] This case was not handled before, so the
API client tried infinitely to receive more bytes and did not return.
[^1]: https://linux.die.net/man/2/recv
[^2]: https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read

api-client: Break the receive loop if the VMM shuts down the socket

---

acpi_tables/src/sdt.rs
vmm/src/acpi.rs
vmm/src/device_manager.rs

Make it easier to change the bus addresses by storing them in one canonical place.
- vmm: device_manager: Store ACPI platform addresses for later use
- vmm: acpi: Use ACPI platform device addresses from DeviceManager

Improve ACPI platform device address handling

---

vmm/src/cpu.rs
vmm/src/vm.rs

When starting the VM such that it is already on a breakpoint (via
stop_on_boot) when attached to gdb then start the vCPUs in a paused
state rather than starting the vCPUs later (upon resume).
Further, make the resumption/break of the VM more resilient by only
attempting to resume the vCPUs if were are already in a break point and
only attempting to pause/break if we were already running.
Fixes: #4354

vmm: Make gdb break/resuming more resilient

---

tests/integration.rs

Rely on /proc/sysrq-trigger to forcibly trigger an OOM in the guest.

tests: Reliably trigger a guest OOM

---

api_client/src/lib.rs

Introduce a match expression for `body_offset` to handle the `None`
case instead of calling `unwrap()` which leads to a panic.

api-client: Handle body_offset is None

---

docs/intel_tdx.md

Adding a new limitation related to the TDX guest kernel as it doesn't
allow for most ACPI devices, meaning the PCI hotplug through ACPI isn't
supported unless we use 'tdx_disable_filter' boot parameter.

docs: Extend the list of TDX guest limitations

---

hypervisor/src/arch/x86/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
hypervisor/src/mshv/x86_64/mod.rs

Both KVM and MSHV share the same layout. We can drop one level of
indirection.
See #4377

hypervisor: simplify LapicState

---

arch/src/aarch64/mod.rs
arch/src/aarch64/regs.rs
hypervisor/src/cpu.rs
hypervisor/src/kvm/aarch64/gic/redist_regs.rs
hypervisor/src/kvm/aarch64/mod.rs
hypervisor/src/kvm/mod.rs
vmm/src/cpu.rs

This PR contains some cleanup work of system registers related functions in `hypervisor`:
- Removing redundant functions `Vcpu::get/set_sys_regs()`, they were only used internally in `hypervisor` crate
- Removing redundant functions `Vcpu::get/set_reg()`, they were also only used internally in `hypervisor` crate
And a refactoring proposal for improving the way to get the system register:
- The problem to resolve: ARM64 defines a big collection of system registers for various purposes. So far we have only used `MPIDR`, we accessed it via the `hypervisor::Vcpu::read_mpidr()` function. But now there is increasing requirements to access more system registers, see https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4355/commits/badb93351dba1d3b3269295d4de873e854ff63f0. In implementing …

Refactor system-registers related code on AArch64

---

docs/fs.md

The `-d` option is deprecated.

docs: update fs.md virtiofs command

---

vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs

The parameter "poll_queue" was useful at the time Cloud Hypervisor was
responsible for spawning vhost-user backends, as it was carrying the
information the vhost-user-block backend should have this option enabled
or not.
It's been quite some time that we walked away from this design, as we
now expect a management layer to be responsible for running vhost-user
backends.
That's the reason why we can remove "poll_queue" from the DiskConfig
structure.

vmm: Remove unused "poll_queue" from DiskConfig
