fuzz/Cargo.lock
fuzz/Cargo.toml
fuzz/fuzz_targets/http_api.rs
vmm/src/api/http.rs
vmm/src/lib.rs

Fuzz the HTTP API handling code with a minimum HTTP API
receiver (e.g. mocking the behavior of our "vmm" thread).

Add fuzzer for HTTP API

---

Jenkinsfile
tests/integration.rs

Move the live migration tests to a 'jammy' worker rather than
'jammy-small'. This type of worker has more CPUs (64 vs 16) and more RAM
(256G vs 64G), which should improve the time it takes to run each test.
With this improvement, the test shouldn't fail anymore due to timeout
being reached.
A second improvement is to reduce the amount of vCPUs created for each
VM. The point is simply to check we can migrate a VM with multiple
vCPUs, therefore using 2 instead of 6 should be enough when possible.
When testing NUMA, we can't lower the amount of vCPUs since there's a
quite complex topology that is expected there.
Also, the total amount of vCPUs is reduced from 12 to 4 (again when not
testing with NUMA).

tests: Improve live migration tests reliability

---

performance-metrics/src/performance_tests.rs

The test virtio_net_latency_us recently failed because of the ethr tool
couldn't complete the latency measurement with the following error
message:
Error dialing the latency connection: dial tcp4
:0-\u003e172.19.0.2:8888: connect: connection refused
The "connection refused" error comes from the Golang Dial function which
couldn't complete as expected because there was no server listening on
the specified port at the specified destination.
In other words, the ethr server wasn't ready when the ethr client tried
to connect to it.
The easy way to avoid this problem is simply by increasing the sleep
time between the command spawning the ethr server in the guest and the
command running the ethr client from the host.

performance-metrics: Improve reliability of virtio_net_latency_us

---

virtio-devices/Cargo.toml
vmm/Cargo.toml

There is no code that needs it.

virtio-devices: drop mshv feature

---

tests/integration.rs

It's been observed on the Bionic image that udev and snapd services can
cause some delay in the VM's shutdown. Disabling them before shutting
down the VM improves the reliability of the test.
Also increasing slightly the sleep time to ensure we give the VM enough
time to shutdown before checking the list of events provided by the
event monitor.

tests: Improve reliability of test_bionic_ovmf

---

pci/src/configuration.rs
pci/src/vfio.rs

- Set prefetchable bit with VFIO devices
- pci: vfio: Preserve prefetchable state of BAR across
- HACK: Run VFIO worker on this PR

pci: vfio: Preserve prefetchable flag on BAR

---

option_parser/src/lib.rs
vmm/src/config.rs

- option_parser: Move test_option_parser to option_parser crate
- option_parser: Enhance test_option_parser
- option_parser: Simplify code for splitting on commas
- option_parser: Rename split_commas_outside_brackets to split_commas
- option_parser: Support quoting to avoid splitting

option_parser: Parsing improvements

---

pci/src/configuration.rs
pci/src/lib.rs
pci/src/vfio.rs
pci/src/vfio_user.rs

There are PCI extended capabilities that can't be passed through the VM
as they would be unusable from a guest perspective. That's why we
introduce a way to patch what is returned to the guest when the PCI
configuration space is accessed. The list of patches is created from the
parsing of the extended capabilities in that case, and particularly
based on the presence of the SRIOV and Resizable BAR capabilities.

pci: vfio: Filter out some PCI extended capabilities

---

virtio-devices/src/device.rs

Looks like we no longer need the `queue_evts` for `reset()`.

virtio-devices: Drop unused 'queue_evts' from VirtioCommon

---

test_infra/src/lib.rs

test_infra: Avoid file descriptor leak with epoll

---

src/main.rs
vmm/src/config.rs
vmm/src/lib.rs
vmm/src/vm.rs

Introduce a new top level member of VmConfig called PayloadConfig that
(currently) encompasses the kernel, commandline and initramfs for the
guest to use.
In future this can be extended for firmware use. The existing
"--kernel", "--cmdline" and "initramfs" CLI parameters now fill the
PayloadConfig.
Any config supplied which uses the now deprecated config members have
those members mapped to the new version with a warning.
See: #4445

vmm: Encompass guest payload configuration in PayloadConfig

---

fuzz/fuzz_targets/block.rs

There are several issues being fixed for the virtio-block fuzzer:
1. Ensure a queue event is properly processed;
2. Ensure the virtio-block thread is killed and joined;
3. Remove meaningless setup to the virt-queue.

fuzz: Fix the virtio block fuzzer

---

.github/workflows/build.yaml
.github/workflows/quality-aarch64.yaml
.github/workflows/quality.yaml

This removes the requirement for the tests (dev-dependencies) to build
with all supported toolchains including the MSRV.
See: #4318

.github: Move per-commit check (using --tests) to quality checks

---

CONTRIBUTING.md

If contributors add this pre-commit hook we should have fewer issues
with build churn on our CI as the most basic checks will pass.

CONTRIBUTING.md: Add sample pre-commit hook

---

Cargo.lock
block_util/src/lib.rs
net_util/Cargo.toml
net_util/src/lib.rs
net_util/src/open_tap.rs
net_util/src/queue_pair.rs
net_util/src/tap.rs
tests/integration.rs
virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/console.rs
virtio-devices/src/epoll_helper.rs
virtio-devices/src/iommu.rs
virtio-devices/src/lib.rs
virtio-devices/src/mem.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/thread_helper.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/mod.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/vsock/mod.rs
virtio-devices/src/watchdog.rs

This PR ensures VMM shutdown upon errors from virtio-device worker threads, through the following steps:
* Derive `this::error` for related Error enums from `virtio-device` and dependent crates
* Refactor `EpollHelperHandler::handler_event()` and all its implementations from various virtio devices to propagate errors properly
* Refactor `spawn_virtio_thread()` to shutdown VMM upon receiving errors from virtio-device worker threads
This PR also exposes a flaw from the integration test `test_live_migration_ovs` which is now being fixed.
Fixes: #4462

Shutdown VMM upon errors from virtio-device workers

---

README.md

The documentation states to install qemu-img. This is located in the
package qemu-utils. The documentation imples the binary is wihtin the
qemu-img package, which doesn't exist.
Signed-off-by: Steven Dake <sdake@lambdal.com>

docs: readme: Fix evaluation error

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_x86_64.sh
tests/integration.rs

Only the ovs-dpdk live-migration tests need to run in sequential as they
use the same ovs-dpdk setup.

tests: live_migration: Run most tests in parallel

---

src/main.rs
vmm/src/config.rs
vmm/src/vm.rs

This prepares the ground work for chained booting as required on aarch64 by
adding explicit firmware controls and using them on x86_64. This is just a
start as I think it would be nice if this could be split into a new struct as
vmm::payload::Payload which might help simplify the vmm::Vm code.
- vmm: x86_64: Split legacy firmware loading into own function
- vmm: x86_64: Use more general name for payload handling
- vmm: x86_64: Make kernel loading use PayloadConfig
- vmm: x86_64: Split payload loading into it's own function
- main, vmm: Add option to pass firmware parameter in payload
- vmm: x86_64: Add support for firmware loading
- vmm: x86_64: Rename load_firmware() to reflect its purpose
See: #4445

Prepare for chained booting (firmware -> kernel)

---

scripts/run_integration_tests_live_migration.sh
tests/integration.rs

Following our recent v26.0 release we can re-enable our live upgrade
tests to try and make it possible for us to move to making LTS releases.
Fixes: #3949

tests: Enable live upgrade tests

---

virtio-devices/src/rng.rs

When configuring Cloud Hypervisor with an RNG device that is not backed by a character device, but by an ordinary text file, reads from that file may only be partial.
When that happens, the device needs to signal to the driver that only parts of the buffer have been overwritten, but right now it marks the whole buffer as used.
Even after this change, the device is still not fully compliant with the [virtio specification](https://web.archive.org/web/20220719215721/https://docs.oasis-open.org/virtio/virtio/v1.2/cs01/virtio-v1.2-cs01.pdf) for Entropy Devices (Section 5.4), which states:
> When the driver requires random bytes, it places the descriptor of one or more buffers in the queue. It will be completely filled by random data by the device. 
> [...]
> The device MUST place one or more …

virtio-devices: rng: correctly indicate number of bytes written

---

vmm/src/vm.rs

Curently all the firmware blobs we support can use PVH loading.
See: #4511

vmm: Deprecate non-PVH firmware loading

---

vmm/src/device_manager.rs
vmm/src/serial_buffer.rs
vmm/src/serial_manager.rs

The goal of this patch is to provide a reliable way to detect when the
other end of the PTY is connected, and therefore be able to identify
when we can write to the PTY device. This is needed because writing to
the PTY device when the other end isn't connected causes the loss of
the written bytes.
The way to detect the connection on the other end of the PTY is by
knowing the other end is disconnected at first with the presence of the
EPOLLHUP event. Later on, when the connection happens, EPOLLHUP is not
triggered anymore, and that's when we can assume it's okay to write to
the PTY main device.
It's important to note we had to ensure the file descriptor for the
other end was closed, otherwise we would have never seen the EPOLLHUP
event. And we did so by removing the "sub" field from the …

vmm: serial: Wait for PTY to be available before writing to it

---

arch/src/aarch64/layout.rs
vmm/src/cpu.rs

There's no need to recompute GIC_V3_DIST_START etc in this function.
Remove `pub` from MAPPED_IO_START too since it's not needed outside layout.rs
Signed-off-by: Nuno Das Neves <nudasnev@microsoft.com>

vmm: aarch64: Use GIC_V3_* consts instead of magic numbers in create_madt()

---

Cargo.lock
arch/src/aarch64/regs.rs
hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs
vmm/src/cpu.rs
vmm/src/gdb.rs
vmm/src/seccomp_filters.rs
vmm/src/vm.rs

Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3980
This PR enables the support of GDB to debug guest kernel.
Following GDB commands were tested:
- `info registers` command: Checking general purposed registers
- `hb`: Setting HW breakpoints
- `ctrl+c`: Interrupting
- `bt`: Checking backtrack
- `nexti(n)`: Next line
- `stepi(s)`: Next line (into function)
Following functionalities are known not ready:
- `info registers`: More registers (mainly system registers) are to be added
- `w`: HW watchpoints
On AArch64, API `KVM_CAP_GUEST_DEBUG_HW_BPS` should be checked for the max number of HW breakpoints. A PR https://github.com/rust-vmm/kvm-ioctls/pull/202 was created to `kvm-ioctls` for the support. Before that improvement, the hardcoded limit `4` should be practical enough.

Enable GDB support on AArch64

---

vmm/src/cpu.rs

Using anyhow::Error should cover both architectures.

vmm: unify TranslateVirtualAddress error for both x86_64 and aarch64

---

Cargo.lock
hypervisor/src/hypervisor.rs
hypervisor/src/kvm/mod.rs
vmm/src/gdb.rs
vmm/src/lib.rs

On AArch64 (KVM) the maximum number of GDB HW breakpoints should be determined by querying the return value of CAP KVM_CAP_GUEST_DEBUG_HW_BPS.

Restrict the number of GDB HW breakpoints on AArch64

---

tests/integration.rs

Enabled 3 more tests on AARCH64. Excluded CPU/RAM hotplug and other unsupported or currently unstable cases.
The runtime for the specific test run climbs from ~33 seconds to ~3 minutes. The total test time doesn't seem to be impacted, though. There are stages still demanding more resources than the AARCH64 one.

tests: Enable more Windows guest tests for aarch64

---

Cargo.lock
Cargo.toml
serial_buffer/Cargo.toml
serial_buffer/src/lib.rs
virtio-devices/Cargo.toml
virtio-devices/src/console.rs
virtio-devices/src/epoll_helper.rs
vmm/Cargo.toml
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/serial_manager.rs
vmm/src/sigwinch_listener.rs

Through multiple changes, this PR aims at providing a reliable solution for detecting the state of the PTY's connection. Being able to find out when the other end of the PTY is connected is essential to prevent the loss of data being output through the PTY. When the PTY isn't connected, the output is buffered through the SerialBuffer, the same solution that was created for the serial port initially.
Fixes #4521

virtio-console: Fix lost output when connected to a PTY

---

vmm/src/device_manager.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

A new payload struct, including "kernel", "firmware" ..., is introduced and used in kernel load on x86 while aarch64 stays in the old way.
This PR try to eliminate the divergency by unifying the payload chain on aarch64 with x86. The big change for payload loading on aarch64 is that uses async way, like x86 does, to load payload instead of sync.

Unify payload load chain on AArch64 with x86

---

devices/src/gic.rs
hypervisor/src/arch/aarch64/gic.rs
hypervisor/src/kvm/aarch64/gic/mod.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/vm.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

This series introduces a structure and a couple of helpers which are used to initialize the Vgic.
- Instead of computing GIC redist/msi regs everywhere, only compute it in devices::gic::create_vgic_config()
- For tests, use the config created by hypervisor::arch::aarch64::gic::create_test_vgic_config()
- Passing the config from a higher level (configure_system()) makes the code more flexible - GIC can be placed anywhere and the code only has to be modified in one place

Introduce VgicConfig structure for initializing Vgic

---

tests/integration.rs

As 'handle_child_output()' may terminate the test on panic, we need to
cleanup ovs-dpdk setup in advance.
see: #4555
Also, we need to wait for VM termination to cleanup the ovs-dpdk.

Cleanup ovs-dpdk setup correctly

---

vmm/src/pci_segment.rs

The PCI buses should not declare the address space related to the MMIO
config space given it's already declared in the MCFG table and through
the motherboard device PNP0C02 in the DSDT table.
The PCI MMIO config region for the segment was being wrongly exposed as
part of the _CRS for the ACPI bus device (using Memory32Fixed). Exposing
it via this object was ineffectual as the equivalent entry in the
PNP0C02 (_SB_.MBRD) marked those ranges as not usable via the kernel.
Either way, with both devices used by the kernel, the kernel will not
try and use those memory ranges for the device BARs. However under
td-shim on TDX the PNP0C02 device is not on the permitted list of
devices so the the memory ranges were not marked as unusable resulting
in the kernel attempting to allocate BARs that …

 vmm: acpi: Don't declare MMIO config space through PCI buses

---

docs/intel_tdx.md
src/main.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/lib.rs
vmm/src/vm.rs

Removing the option --tdx to specify that we want to run a TD VM. Rely
on --platform option by adding the "tdx" boolean parameter. This is the
new way for enabling TDX with Cloud Hypervisor.
Along with this change, the way to retrieve the firmware path has been
updated to rely on the recently introduced PayloadConfig structure.
Fixes #4556

vmm: config: Move TDX to rely on PayloadConfig

---

tests/integration.rs

Until the issue #4583 is resolved, we must disable this test given it's
failing quite often on the aarch64 worker.

tests: Disable test_windows_guest_disk_hotplug for aarch64

---

Jenkinsfile

The baremetal CI for x86-64 was disabled while the machines were out for maintenance. Now that the machines are back up, let's re-enable the full CI.
This reverts commit 476e30f5cb563f38002610005aeb8fc459a70101.

Jenkinsfile: Re-enable x86-64 bare metal testing

---

tests/integration.rs

This PR simplifies the huge `_test_live_migration()` function (over 450 LOC) by splitting tests of balloon, numa and watchdog into their own functions. This improves readability for easier debugging.

Refactor live-migration integration tests for readability

---

virtio-devices/src/pmem.rs

To have a more robust error handling, this patch ensures errors are properly
reported and propagated from the virtio-pmem worker thread, which avoids 
to panic when processing virt queues.

virtio-devices: pmem: Avoid panic and propagate errors properly 

---

Cargo.lock
Cargo.toml
acpi_tables/Cargo.toml
arch/Cargo.toml
block_util/Cargo.toml
devices/Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
hypervisor/Cargo.toml
net_util/Cargo.toml
pci/Cargo.toml
vfio_user/Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml
virtio-devices/Cargo.toml
vm-allocator/Cargo.toml
vm-device/Cargo.toml
vm-migration/Cargo.toml
vm-virtio/Cargo.toml
vmm/Cargo.toml

Multiple rust-vmm crates must be updated at once given the vm-memory one has been updated and they all rely on vm-memory.
- vm-memory from 0.8.0 to 0.9.0
- vhost from 0.4.0 to 0.5.0
- virtio-queue from 0.5.0 to 0.6.0
- vhost-user-backend from 0.6.0 to 0.7.0

build: Bulk dependencies update

---

Cargo.lock
Jenkinsfile
performance-metrics/src/main.rs
performance-metrics/src/performance_tests.rs
scripts/dev_cli.sh
scripts/run_integration_tests_rate_limiter.sh
test_infra/Cargo.toml
test_infra/src/lib.rs
tests/integration.rs

It covers rate limiter on both `block` (single-queue, throughput and IOPS) and `net` (single-queue, rx/tx throughput), which reproduces the results reported from #2333 and #2401.

Add integration tests for rate limiter

---

fuzz/Cargo.toml
fuzz/fuzz_targets/block.rs
fuzz/fuzz_targets/pmem.rs

The fuzzer is focusing on the virtio-pmem code that processes guest
inputs (e.g. virt queues). Given 'flush' is the only virtio-pmem
request, the fuzzer is essentially testing the code for parsing and
error handling.
To make the fuzzers more focused and more efficient, we now provide
default addresses for the descriptor table, available ring, and used
ring, which ensures the virt-queue has a valid memory layout (e.g. no
overlapping between descriptor tables, available ring, and used ring).

Add fuzzer for virtio-pmem

---

README.md

The `#use-prebuilt-binaries` entry shifted to the left due to wrong markup.

README: Fix contents entry indent

---

Cargo.lock
hypervisor/src/kvm/mod.rs

The latest kvm-ioctls contains a breaking change to its API. Now Arm's get/set_one_reg use u128 instead of u64.

build: update to the latest kvm-ioctls

---

Cargo.toml

This reduces the binary size from 7.3M to 6.5M.
Also the build time for a clean build shrinks from 1m28s to 1m14s on my
development machine (an eight-core VM on Azure). This goes against the
conventional wisdom but it is what it is.

build: enable size optimization for release profile

---

devices/src/legacy/uart_pl011.rs

This makes it consistent with x86_64 and allows the performance metrics
tooling to continue to work on aarch64.

devices: legacy: pl011: Move boot timestamping to warn!()

---

.github/workflows/build.yaml
.github/workflows/quality.yaml
Cargo.toml
vmm/Cargo.toml
vmm/src/config.rs
vmm/src/cpu.rs

Given the AMX x86 feature has been made available since kernel v5.17, and given we don't have any test validating this feature, there's no need to keep it behing a Rust feature gate.
Fixes #3996

vmm: Remove "amx" feature gate

---

virtio-devices/src/balloon.rs
virtio-devices/src/device.rs

There's no need to delegate the resize operation to the virtio-balloon
thread. This can come directly from the vmm thread which will use the
Balloon object to update the VIRTIO configuration and trigger the
interrupt for the guest to be notified.

virtio-devices: balloon: Simplify the resize operation

---

qcow/src/raw_file.rs
vhdx/src/vhdx_io.rs

Found these issues while code review. Counter examples provided 
in the commit message to explain why they were wrong.

Fix wrong alignment calculation for qcow and vhdx

---

Cargo.toml
devices/Cargo.toml
vmm/Cargo.toml

This only affects the build system; the feature was already always
compiled in with ca68b9e7a90c9e25e8d9399dea059c9b63cd0419

build: Remove the exposed "cmos" feature

---

Jenkinsfile

This was unfortunately missing from
430bfd38bed635cd26ffeddd501345b0661a511f which disabled the other builds
that rely on the bare metal systems.

build: Disable SGX build

---

.github/workflows/quality.yaml
Cargo.lock
Cargo.toml
docs/tracing.md
scripts/ch-trace-visualiser.py
tracer/Cargo.toml
tracer/src/lib.rs
tracer/src/tracer.rs
tracer/src/tracer_noop.rs
vmm/Cargo.toml
vmm/src/acpi.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

Add basic support for tracing the boot. The tracing only has overhead if
compiled in with the "tracing" feature.
- tracing: Add initial basic tracing support
- vmm: Add some tracing
- scripts: Add tracing visualisation script
- docs: Add documentation of tracing infrastructure
- .github: Add clippy check of tracing feature

Add initial tracing support

---

fuzz/fuzz_targets/balloon.rs
fuzz/fuzz_targets/block.rs
fuzz/fuzz_targets/pmem.rs
fuzz/fuzz_targets/rng.rs
fuzz/fuzz_targets/watchdog.rs
virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/device.rs
virtio-devices/src/mem.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/watchdog.rs

This function is for really for the transport layer to trigger a device
reset. Instead name it appropriately for the fuzzing specific use case.

fuzz: Don't overload meaning of reset()

---

fuzz/fuzz_targets/balloon.rs

As the virt queues are initialized with random bytes from the fuzzing engine, a descriptor buffer for the available ring can have a very large length (e.g. up to 4GB). This means there can be up to 1 billion entries (e.g. page frame number) for virtio-balloon to process a signal available descriptor (given each entry is 4 bytes). This is the reason why oss-fuzz reported a hanging issue for this fuzzer, where the generated descriptor buffer length is 4,278,321,152.
We can avoid this kind of long execution by reducing the size of guest memory. For example, with 1MB of guest memory, the number of descriptor entries for processing is limited ~256K.

fuzz: Reduce the guest memory size for balloon fuzzer

---

.github/workflows/build.yaml
.github/workflows/quality.yaml
Cargo.toml
devices/Cargo.toml
devices/src/legacy/mod.rs
vmm/Cargo.toml
vmm/src/device_manager.rs

This simplifes the buld and checks with very little overhead and the
fwdebug device is I/O port device on 0x402 that can be used by edk2 as a
very simple character device.
See: #4679

build: Remove "fwdebug" and "common" feature flags

---

hypervisor/src/cpu.rs
hypervisor/src/hypervisor.rs
hypervisor/src/vm.rs

TDX functionality is not currently available on MSHV but we should not
preclude building a binary that can run on both.
Fixes: #4677

hypervisor: Support compiling "tdx" and "mshv" feature together

---

.github/workflows/build.yaml
.github/workflows/quality.yaml
Cargo.toml
docs/gdb.md
src/main.rs
vmm/Cargo.toml
vmm/src/config.rs
vmm/src/cpu.rs
vmm/src/lib.rs
vmm/src/vm.rs

This simplifies the CI process but also logical with the existing
functionality under "guest_debug" (dumping guest memory).
Fixes: #4679

build: Consolidate "gdb" build feature into "guest_debug"

---

scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_rate_limiter.sh
scripts/run_integration_tests_windows_x86_64.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh
scripts/run_unit_tests.sh

These changes are to remove references of common features from script files. Some of the scripts are still using that parameter specifically test related to mshv hypervisor. Thus fix those scripts by removing common feature flag.
Common feature was already removed as part of below commit : 
https://github.com/cloud-hypervisor/cloud-hypervisor/commit/b2d1dd65f399d0e3a2c4025a245062ee4fbcece7#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542

removal of common feature reference from script files

---

fuzz/Cargo.lock

fuzz: Cargo.lock: Bump virtio-queue to 0.6.1

---

vmm/src/api/openapi/cloud-hypervisor.yaml

This option is needed for the openapi consumer (e.g. Kata Containers) to load firmware (e.g. td-shim) for booting.

openapi: Add 'firmware' to 'PayloadConfig'

---

vmm/src/device_manager.rs

These addresses have been superseded and replaced with other I/O ports.
Fixes: #4483

vmm: Remove legacy I/O ports for ACPI

---

fuzz/fuzz_targets/balloon.rs

With the guest memory size of 1MB, a valid descriptor size can be close to the guest memory size (e.g. 1MB) and can contain close to 256k valid pfn entries (each entry is 4 bytes). Multiplying the queue size (e.g. 256), there can be close to 64 millions pfn entries to process in a single request. This is why the oss-fuzz reported a timeout (with a limit of 60s).
By reducing the guest memory size and the queue size, the worst-case now is 8 million pfn entries for fuzzing, which can be finished in around 20 seconds according to my local experiment.

fuzz: Balloon: Reduce the guest memory size and queue size

---

virtio-devices/src/rng.rs

The RNG device never reads from the guest memory it reads from a file
and writes to the guest memory.

virtio-devices: rng: Fix error message

---

src/main.rs
vmm/src/config.rs
vmm/src/lib.rs
vmm/src/vm_config.rs

Simplify and clean-up config.rs by splitting it up to ease readability. Whilst
doing this I found some other items that needed fixing including removing
deprecated funtionality.
- vmm: Split structs from logic that make up VmConfig
- vmm: Move `impl Default for ...` to vm_config.rs
- vmm: Rename queue size / number of queues constants
- vmm: Remove deprecated VmConfig::{kernel, initramfs, cmdline} members

Simplify config.rs

---

tests/integration.rs

This test has been identified as flaky and is creating CI churn.
See: #4749

tests: Temporarily disable test_live_{migration,upgrade}_watchdog{_local}

---

fuzz/Cargo.toml
fuzz/fuzz_targets/mem.rs
vmm/src/memory_manager.rs

This patch also make `MemoryManager::create_ram_region()` public,
so that it can be used externally, such as for fuzzing.
Signed-off-by: Bo Chen [chen.bo@intel.com](mailto:chen.bo@intel.com)

Add fuzzer for virtio-mem

---

test_data/cloud-init/ubuntu/user-data

This means that the guest image does not need to have netcat installed
making it easiert to use unmodified images.

test_data: Use bash TCP support instead of netcat for boot check

---

Cargo.lock
Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
pci/src/device.rs
virtio-devices/src/transport/pci_device.rs
virtio-devices/src/vdpa.rs
vm-migration/src/lib.rs
vmm/src/device_manager.rs
vmm/src/seccomp_filters.rs

Vdpa now implements the Migratable trait, which allows the device to be
added to the DeviceTree and therefore allows live migrating any vDPA
device that supports being suspended.
Given a vDPA device can't be resumed from a suspended state without
having to reset everything, we don't support pause/resume for a vDPA
device, as well as snapshot/restore (which requires resume to be
supported).

virtio-devices: Implement live migration support for Vdpa

---

qcow/src/qcow.rs

In function create_for_size()，it calculates l1_clusters by dividing by cluster_size, whereas it should be divided by cluster_size/size_of(u64).
This fixes: #4762

qcow: Fix the calculation of the number of clusters for L1 table

---

virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs

virtio-devices: mem: Report error instead of panic
virtio-devices: iommu: Switch to use 'thiserror' 
virtio-devices: iommu: Propagate errors of processing request queue

Improve error handling for virtio-mem and virtio-iommu

---

README.md
docs/building.md

Refresh our README in a consistent style and update it to reflect:
* A recommendation to use binaries
* Clarify our relationship with other Rust based VMMs/Rust-VMM project
* Ensure instructions result in a usable image (cloud-init)
* Simplify script instructions
* Move compilation details elsewhere
* Add Fedora 36 image details
* Point to CLOUDHV as well as Rust Hypervisor Firmware

docs: Modernise README

---

test_infra/src/lib.rs
tests/integration.rs

The systemd journal has a known issue of generating large size logs[1],
which makes it unreliable as a source for retrieving system
information, such as for counting reboot times. This is particularly
problematic on disk-constrained systems, like the VMs we launched for
our integration tests, where the disk size is normally 2GB. By default,
the systemd journal has a size limit of 10% of the size of the
underlying file system (e.g. around 200MB for the VMs of our integration
tests), which would remove archived journal files on demand.
A better alternative to count reboot times is based on information from
`wtmp` (e.g. the login records) which is much more concise and can be
accessed via the `last` command.
[1] https://github.com/systemd/systemd/issues/5285
Fixes: #4749
Signed-off-by: Bo …

tests: Rely on wtmp (the login records) to count reboot times

---

vmm/src/vm.rs

The restore path of MemoryManager is handled specially without implementing a `Snapshottable:restore()`. Removing the explicit call to it along the migration code path to avoid confusions.
See: #4783

vmm: Remove the explicit call to 'Snapshottable:restore()'

---

vmm/src/vm.rs

These look alarming if you are booting with the a distro kernel which is
now a recommended approach.
See: #4786

vmm: Reduce logging severity for unknown MMIO/PIO device accesses

---

fuzz/fuzz_targets/mem.rs

The kernel will trigger a SIGBUS upon hugetlb page faults when there is no huge pages available. We neither have a way to ensure enough huge pages available on the host system, nor have a way to gracefully report the lack of huge pages in advance from Cloud Hypervisor. For these reasons, we have to avoid using huge pages from the virtio-mem fuzzer to avoid SIGBUS errors.

fuzz: mem: Avoid using hugepages

---

vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

This is preliminary work to ensure a migrated VM is created right before it is restored. This will be useful when moving to a design where the VM is both created and restored simultaneously from the Snapshot.
In details, that means the MemoryManager is the object that must be created upon receiving the config from the source VM, so that memory content can be later received and filled into the GuestMemory. Only after these steps happened, the snapshot is received from the source VM, and the actual Vm object can be created from both the snapshot and the MemoryManager previously created.

vmm: migration: Create destination VM right before to restore it

---

virtio-devices/src/iommu.rs

In this way, the virtio-iommu code can properly report an error when
a wrong number of queues is provided, instead of triggering an
out-of-bound error.

virtio-devices: iommu: Specify minimum number of queues to avoid OOB

---

vmm/src/api/openapi/cloud-hypervisor.yaml

The add_device() function, from the device manager code, takes a DeviceConfig as a parameter, instead of a VmAddDevice.

api: Fix vm.add-device argument type

---

fuzz/fuzz_targets/balloon.rs
fuzz/fuzz_targets/block.rs
fuzz/fuzz_targets/iommu.rs
fuzz/fuzz_targets/mem.rs
fuzz/fuzz_targets/pmem.rs
fuzz/fuzz_targets/rng.rs
fuzz/fuzz_targets/watchdog.rs
virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/console.rs
virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/vdpa.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/vsock/mod.rs
virtio-devices/src/watchdog.rs
vm-migration/src/lib.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs

Following the new design proposal to improve the restore codepath when
migrating a VM, all virtio devices are supplied with an optional state
they can use to restore from. The restore() implementation every device
was providing has been removed in order to prevent from going through
the restoration twice.
Here is the list of devices now following the new restore design:
- Block (virtio-block)
- Net (virtio-net)
- Rng (virtio-rng)
- Fs (vhost-user-fs)
- Blk (vhost-user-block)
- Net (vhost-user-net)
- Pmem (virtio-pmem)
- Vsock (virtio-vsock)
- Mem (virtio-mem)
- Balloon (virtio-balloon)
- Watchdog (virtio-watchdog)
- Vdpa (vDPA)
- Console (virtio-console)
- Iommu (virtio-iommu)
See #4783

vmm: virtio-devices: Restore every VirtioDevice upon creation

---

vmm/src/memory_manager.rs

Until there is a need for sharing the memory fd with a child process, we should err on the safe side to close it on exec.

memory_manager: use MFD_CLOEXEC flag when creating memory fd

---

vmm/src/device_manager.rs

After several tests, `io_uring_is_supported()` causes about 38ms of overhead when creating virtio-blk. By modifying the position of `io_uring_is_supported()`, the overhead of creating virtio-blk is reduced to less than 1ms when close io_uring.
Added debug information to vmm/src/device_manager.rs. Disabling io_uring and mounting virtio-blk with "--disk", the log shows the following message.
```
cloud-hypervisor: 6.728455ms: <vmm> DEBUG:vmm/src/device_manager.rs:2118 -- point 1
cloud-hypervisor: 45.277803ms: <vmm> DEBUG:vmm/src/device_manager.rs:2125 -- point 2
```
After the fix, the log shows the following message when disabling io_uring and mounting virtio-blk with "--disk".
```
cloud-hypervisor: 6.693065ms: <vmm> DEBUG:vmm/src/device_manager.rs:2118 -- point 1
cloud-hypervisor: …
```

virtio-devices: Fix high overhead of creating virtio-blk caused by io_uring

---

block_util/src/lib.rs

The probing logic wasn't updated to reflect the actual opcodes in use
for io_uring which are vectored read/writes not the unvectored versions.

block_util: Probe for used io_uring opcodes

---

docs/memory.md
vmm/src/config.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs

- vmm: Refactor creation of the FileOffset for GuestRegionMmap::new()
- vmm: memory_manager: Split filesystem backed and anonymous RAM creation
- vmm: memory_manager: Only file back memory when required
- vmm: memory_manager: Avoid MAP_PRIVATE CoW with VFIO for hugepages too
Fixes: #4805

Improve RAM memory allocation

---

virtio-devices/src/mem.rs

An integer overflow from our virtio-mem device can be triggered
from (misbehaved) guest driver with malicious requests. This patch
handles this integer overflow explicitly and treats it as an invalid
request.
Note: this bug was detected by our virtio-mem fuzzer through 'oss-fuzz'.

virtio-devices: mem: Handle integer overflow properly

---

tests/integration.rs

The current snapshot_restore test case has many things to test specifically balloon/hotplug.
We should have a basic snapshot/restore test case for better separation to verify if
basic test works. For example MSHV does not support hot plugging virtio-mem yet
but there is not way to run a test case to see if basic snapshot/restore works for MSHV.
This PR separates out these two scenario for better debugging/development.

Split Snapsot/restore test case for better separation

---

docs/memory.md
fuzz/fuzz_targets/mem.rs
src/main.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/vm_config.rs

If the memory is not backed by a file then it is possible to enable
Transparent Huge Pages on the memory and take advantage of the benefits
of huge pages without requiring the specific allocation of an appropriate
number of huge pages.
TEST=Boot and see that in /proc/`pidof cloud-hypervisor`/smaps that the
region is now THPeligible (and that also pages are being used.)

vmm: Enable THP when using anonymous memory

---

virtio-devices/src/seccomp_filters.rs

It's perfectly reasonable to expect if that some virtio threads trigger
libc behaviour that needs mprotect() that all virtio threads would do
the same.
Fixes: #4874

virtio-devices: seccomp: Move mprotect() to virtio common rules

---

Jenkinsfile

Temporarily turn off AArch64 integration test in Jenkins for server maintenance.
The server will be absent for about 1 week.

Temporarily turn off AArch64 CI

---

hypervisor/src/mshv/mod.rs

Setting that MSR causes the reference TSC page to be disabled.
That's giving a huge perf hit to the guest.

hypervisor: do not get and set MSR_IA32_TSC for MSHV

---

Cargo.lock
Cargo.toml
arch/src/aarch64/layout.rs
arch/src/x86_64/layout.rs
devices/Cargo.toml
devices/src/lib.rs
devices/src/tpm.rs
docs/tpm.md
src/main.rs
tpm/Cargo.toml
tpm/src/emulator.rs
tpm/src/lib.rs
tpm/src/socket.rs
vmm/src/acpi.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs
vmm/src/vm_config.rs

This patchset enables vTPM device that supports CRB Interface with version TPM 2.0.
Sending this version out for review. There are some TODOs in tpm.rs that still need to be addressed. I will address the TODOs while waiting for feedback.
V5:
* drop  dependency on `nix` crate
V4:  
* Add TPM ACPI tables only if tpm parameter is passed at cmdline
V3:
* modified the input argument to --tpm following the suggestions below
* Addressed github and CI failures
V2:
* Ran basic checks: cargo fmt, cargo clippy
* Add missing copyright header

vTPM Support in Cloud-Hypervisor

---

Jenkinsfile

Reverts cloud-hypervisor/cloud-hypervisor#4885
The AArch64 server maintenance is done. Now we can enable the CI again.

Turn on AArch64 CI

---

.github/workflows/release.yaml

Fixes: #4678
Currently release build is done on kvm feature only, that makes live upgrade test on MSHV failing since
it does not find /dev/kvm. As Cloud-Hypervisor supports both kvm and mshv in a single binary we should
make the release build with both KVM/MSHV feature enabled.  That way live upgrade test does not fail on MSHV.

.github: do release build with both KVM and MSHV enabled

---

.github/workflows/release.yaml
Cargo.toml

From Rust 1.59, the cargo command is now able to strip a binary [1]. This can be enabled in Cargo.toml by adding a `strip = "true"` to the `[profile.release]` section.
Adding such binary stripping support in Cargo.toml of the project, also change the stripping process in the release workflow to the one using toolchain, so that the AArch64 release binaries can also be stripped.
Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4916
[1] https://doc.rust-lang.org/beta/cargo/reference/profiles.html#strip

github,Cargo.toml: Strip release binaries using toolchain

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_rate_limiter.sh
scripts/run_integration_tests_sgx.sh
scripts/run_integration_tests_vfio.sh
scripts/run_integration_tests_windows_aarch64.sh
scripts/run_integration_tests_windows_x86_64.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh

The binary stripping is now done by the toolchain for release builds.

scripts: Remove stripping from testing scripts

---

net_util/src/queue_pair.rs

This panic was triggered with fuzzing on the virtio-net device. This commits handles the error explicitly to avoid the panic, which also makes the fuzzer happy (as panic is treated as bugs).

net_util: queue_pair: Avoid panic and handle error properly

---

vmm/src/device_manager.rs
vmm/src/vm.rs

This optimisation provided some peformance improvement when measured by
perf however when considered in terms of boot time peformance this
optimisation doesn't have any impact measurable using our
peformance-metrics tooling.
Removing this optimisation helps simplify the VMM internals as it allows
the reordering of the VM creation process permitting refactoring of the
restore code path.

vmm: Remove PCI PIO optimisation

---

devices/src/gic.rs
devices/src/interrupt_controller.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

This PR moves lots of code around to be able to create both the CpuManager and associated Vcpus before the DeviceManager's creation. The reason is to unify the boot sequence for both x86_64 and aarch64 architectures. And given aarch64 requires the vCPU to be created in order to create the vGIC (equivalent of the vLAPIC in case of x86_64), we decided to defer the creation of the DeviceManager as much as possible.
It includes a patch from @michael2012z (specifically for aarch64) that is required to move the vGIC creation out of the Gic object, and make sure the vGIC is created before the DeviceManager. At the time the DeviceManager gets created, all vCPUs and associated vGIC are ready so that registering irqfds and setting up GSI routes can succeed.

vmm: Create vCPUs before the DeviceManager

---

tests/integration.rs

This allows the unification of the same testing methodology with aarch64
and removes a user of the Bionic image.

tests: Use Ubuntu Jammy for test_multi_cpu

---

pci/src/bus.rs
pci/src/configuration.rs
pci/src/lib.rs
pci/src/msix.rs
pci/src/vfio.rs
pci/src/vfio_user.rs
tests/integration.rs
virtio-devices/src/transport/mod.rs
virtio-devices/src/transport/pci_common_config.rs
virtio-devices/src/transport/pci_device.rs
vmm/src/device_manager.rs

Now that vCPUs are created prior to the DeviceManager, we're able to restore interrupts from `DeviceManager::create_devices()`.
The code for restoring a VirtioPciDevice has been updated, including the dependencies VirtioPciCommonConfig, MsixConfig and PciConfiguration.
It's important to note that both PciConfiguration and MsixConfig still have restore() implementations because Vfio and VfioUser devices still rely on the old way for restore.

pci, virtio-devices: Move VirtioPciDevice to the new restore design

---

Jenkinsfile
scripts/run_integration_tests_vfio.sh
test_infra/src/lib.rs
tests/integration.rs

Re-enable the VFIO integration now the machine is back online.
The image has been updated to rely on Ubuntu 22.04 (Jammy) and it's smaller given only the NVIDIA drivers along with the nvidia-smi tool are installed.
The test to verify the GPU is functional has been simplified given it only relies on nvidia-smi to validate it has been able to find the Tesla T4 card, meaning the associated driver was loaded correctly.

tests: Enable VFIO integration tests

---

docs/custom-image.md

Extend the existing `custom-image.md` document with a new section on how to create a custom image that contains NVIDIA drivers that are required for our VFIO baremetal CI.

docs: Provide documentation for creating custom image for VFIO CI

---

devices/src/ioapic.rs
vmm/src/device_manager.rs

Moving the Ioapic object to the new restore design, meaning the Ioapic is created directly with the right state, and it shares the same codepath as when it's created from scratch.

devices, vmm: Move Ioapic to new restore design

---

devices/src/legacy/gpio_pl061.rs
devices/src/legacy/serial.rs
devices/src/legacy/uart_pl011.rs
fuzz/fuzz_targets/serial.rs
vmm/src/device_manager.rs

Moving legacy devices objects to the new restore design, meaning they are created directly with the right state, and they share the same codepath as when they are created from scratch.

devices: Move legacy devices to new restore design

---

docs/tpm.md

I found a typo on the doc for TPM during I was trying the command shown.
This PR would fix the typo.

docs: Fix a typo on the doc for tpm

---

net_util/src/queue_pair.rs

This integer overflow was triggered with fuzzing on the virtio-net
device. The integer overflow is from the wrong assumption that the
packets read from or written to the tap device is always larger than the
size of a virtio-net header.

net_util: queue_pair: Avoid integer overflow

---

pci/src/configuration.rs
pci/src/msi.rs
pci/src/msix.rs
pci/src/vfio.rs
pci/src/vfio_user.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

This PR moves both `VfioPciDevice` and `VfioUserPciDevice` to the new restore design. Given it completes all PCI devices (`VirtioPciDevice` was moved earlier), the old way of restoring `MsiConfig`, `MsixConfig` and `PciConfiguration` can be removed as well.

pci: Move VfioPciDevice and VfioUserPciDevice to new restore design

---

fuzz/Cargo.lock
fuzz/Cargo.toml
fuzz/fuzz_targets/net.rs
net_util/src/tap.rs
virtio-devices/src/net.rs
vmm/src/lib.rs

To synthesize the interactions between the virtio-net device and the tap
interface, the fuzzer utilizes a pair of unix domain sockets: one socket
(e.g. the dummy tap frontend) is used to construct the 'net_util::Tap'
instance for creating a virtio-net device; the other socket (e.g. the
dummy tap backend) is used in a epoll loop for handling the tx and rx
requests from the virtio-net device.

Add fuzzer for virtio-net

---

virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/console.rs
virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/vdpa.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/watchdog.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

Every Vcpu is now created with the right state if there's an available snapshot associated with it. This simplifies the restore logic.

vmm: Move CpuManager and Vcpu to the new restore design

---

devices/src/gic.rs
devices/src/interrupt_controller.rs
tests/integration.rs
vmm/src/device_manager.rs
vmm/src/vm.rs

The PR:
- Moves the snapshotting and restoring of Gic (AArch64) from `Vm` to `DeviceManager`
- Moves the occasion of Gic restoration earlier from after `DeviceManager::restore()` to `DeviceManager::add_interrupt_controller()` which is in the very beginning of `DeviceManager::restore()`

Move Gic to the new restore path

---

vm-migration/src/lib.rs
vmm/src/lib.rs
vmm/src/vm.rs

Now the entire codebase has been moved to the new restore design, we can complete the work by creating a dedicated restore() function for the Vm object and get rid of the method restore() from the Snapshottable trait.

vmm: Move Vm to the new restore design

---

arch/src/aarch64/mod.rs
arch/src/x86_64/mod.rs
devices/src/gic.rs
vmm/src/cpu.rs
vmm/src/gdb.rs
vmm/src/lib.rs
vmm/src/vm.rs

- vmm: cpu: Rename "vm_memory" parameter/member to "guest_memory"
- aarch, vmm: Reduce requirement for guest memory to vCPU boot only
- vmm: Don't store GuestMemoryMmap for "guest_debug" functionality
- vmm: Seperate the CPUID setup from the CpuManager::new()
- vmm: Propagate vCPU configure error correctly

Decouple CpuManager/MemoryManager creation

---

src/bin/ch-remote.rs

Add vmm-ping subcommand to ch-remote.

ch-remote: Add support for vmm.ping

---

.github/workflows/quality.yaml
vmm/src/api/http.rs
vmm/src/api/http_endpoint.rs
vmm/src/api/mod.rs
vmm/src/cpu.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/migration.rs
vmm/src/vm.rs

- vmm: guest_debug: Mark coredump functionality x86_64 only
- .github: Enable "guest_debug" clippy on aarch64

Gate "coredump" functionality behind x86_64 architecture

---

src/bin/ch-remote.rs

Add shutdown-vmm subcommand to ch-remote.

ch-remote: Add support for vmm.shutdown

---

docs/memory.md
src/main.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs

Remove from the documentation and API definition but continue support
using the field (with a deprecation warning.)
See: #4837

vmm: Deprecate MemoryZoneConfig::file

---

docs/uefi.md

after testing the build briefly, it seems upstream tianocore EDK2 works fine, no need for the separate cloud-hypervisor edk2 repo.

docs: update UEFI.md to reference upstream tianocore EDK2 repository

---

acpi_tables/src/sdt.rs
block_util/src/async_io.rs
devices/src/legacy/rtc_pl031.rs
devices/src/lib.rs
hypervisor/src/lib.rs
vmm/src/seccomp_filters.rs

Not a complete set of clippy oriented improvements but a small start
- acpi_tables: sdt: Implement Std::is_empty()
- block_util: Use anonymous case to handle ioctl signature difference
- devices: Remove unnecessary clippy directives
- vmm: seccomp: Remove unreachable patterns
See #4986

Reduce clippy/compiler overrides

---

Cargo.lock
hypervisor/src/mshv/mod.rs

With this bump there was a change in one of the externally exposed variable. Thus, the use of that variable in CLH must be adjusted accordingly.

build: Bump mshv-ioctls from `10d0c52` to `ef01a5a`

---

README.md
scripts/run_integration_tests_x86_64.sh
scripts/sha1sums-x86_64
tests/integration.rs

This OS is EOL this year and is well tested by the Rust Hypervisor
Firmware CI so there is no need to duplicate this effort.

tests: Remove support for Ubuntu Bionic

---

performance-metrics/src/main.rs
performance-metrics/src/performance_tests.rs
test_infra/src/lib.rs
tests/integration.rs

Pump as many packets as possible through the link. Account for only the packets that are not lost.
Output looks like this:
```
Test 'virtio_net_throughput_single_queue_tx_pps' running .. (control: test_timeout = 10s, test_iterations = 5, num_queues = 2, queue_size = 256, rx = false, bandwidth = false, overrides: )
Test 'virtio_net_throughput_single_queue_tx_pps' .. ok: mean = 495612.1093586601, std_dev = 34035.03688487209
Test 'virtio_net_throughput_single_queue_rx_pps' running .. (control: test_timeout = 10s, test_iterations = 5, num_queues = 2, queue_size = 256, rx = true, bandwidth = false, overrides: )
Test 'virtio_net_throughput_single_queue_rx_pps' .. ok: mean = 237217.9915156765, std_dev = 2578.1319394996667
Test 'virtio_net_throughput_multi_queue_tx_pps' running .. (control: …
```

Measure UDP PPS in performance metrics

---

src/main.rs

With this change, all log messages will have the same width for the timestamp. The amount of ms is rounded to 6 decimal places.
**Before (not aligned in every case):**
**After:**

log: align log message timestamp

---

tests/integration.rs

Since SGX testing doesn't rely on a custom guest image anymore, there's no need to keep the custom filename around as it's already not in use.

tests: Remove unnecessary filename

---

docs/memory.md
src/main.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs

This reverts commit 9fb0274479afe2bcebdf53245b542b1261ad0985.
A user was identified of this functionality.
See: #4837

Revert "vmm: Deprecate MemoryZoneConfig::file"

---

vmm/src/memory_manager.rs

This functionality has been obsoleted by our native support for
hugepages and shared memory.
See: #5082

vmm: memory_manager: Deprecate directory backing for memory

---

Cargo.lock
block_util/Cargo.toml
block_util/src/async_io.rs
block_util/src/fixed_vhd_async.rs
block_util/src/fixed_vhd_sync.rs
block_util/src/lib.rs
block_util/src/qcow_sync.rs
block_util/src/raw_async.rs
block_util/src/raw_sync.rs
block_util/src/vhdx_sync.rs
virtio-devices/src/block.rs

- block_util: Pass a reference to the slice of iovecs
- block_util: Use SmallVec for I/O requests
- block_util: Avoid intermediate completion queue allocation
- block_util: Preserve ordering of sync file backend completions
The total DHAT change is:
dhat: Total:     1,166,412 bytes in 40,383 blocks
to
dhat: Total:     380,444 bytes in 3,469 blocks

Further optimise heap allocations for block I/O

---

hypervisor/src/lib.rs
vmm/src/cpu.rs

Looks like this code guarded by kvm feature flag does not work properly. When we build with both kvm and mshv restore hangs indefinitely.

vmm: Ensure PIO/MMIO exits complete before pausing only for KVM

---

block_util/src/lib.rs
virtio-devices/src/block.rs

Once IO jitter occurs inside VM, we need some metric to show the virtio-block process latency to do help investigate.
This PR adds latency counters for virtio-block base request, so that we could get virtio-block process latency by counters, the feature is disabled by default, you have to add these configs to disks `"latency":{"low":30,"mid":60,"hig":100}`, this mean enables latency accounting, now support three thresholds, this mean there will be four latency range.
The latency counters could be got via counter API, the result will be something like this.
`{"_disk0":{"read_latency_huge":0,"write_ops":0,"read_bytes":4096,"write_bytes":0,"read_latency_low":1,"write_latency_mid":0,"write_latency_huge":0,"read_latency_high":0,"write_latency_low":0,"write_latency_high":0,"read_ops":1,"read_lat …

Proposal: add virtio-block process latency accounting

---

virtio-devices/src/balloon.rs
virtio-devices/src/block.rs
virtio-devices/src/console.rs
virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs
virtio-devices/src/net.rs
virtio-devices/src/pmem.rs
virtio-devices/src/rng.rs
virtio-devices/src/vhost_user/blk.rs
virtio-devices/src/vhost_user/fs.rs
virtio-devices/src/vhost_user/net.rs
virtio-devices/src/vsock/device.rs
virtio-devices/src/watchdog.rs

My team and I think that the Cloud Hypervisor doesn't properly join threads of virtio devices. This PR fixes this.
What are your thoughts?
Some device models are special, such as `Fs` or `Blk`.
`self.common.wait_for_epoll_threads();` seems to be useless there but
```rust
if let Some(handle) = self.epoll_thread.take() {
handle.join().unwrap();
}
```
does the trick.
ping @blitz @snue
PS: In case you're fine with merging this, is there any chance of this ending up in the `v29` release?

virtio-devices: properly join all threads on Drop

---

.github/workflows/release.yaml
Cargo.toml
build.rs
performance-metrics/Cargo.toml
performance-metrics/build.rs
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml

This reverts commit 998fb48ff276821f3b3ced6d07d492130eef7fec.
This is breaking the release build process (cross build for aarch64
musl) so temporarily reverting until we can identify the cause to allow
the release proceeed.

Revert "build: drop clap from dev-dependencies"

---

.github/workflows/release.yaml
Cargo.toml
build.rs
performance-metrics/Cargo.toml
performance-metrics/build.rs
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml

Some crates don't need it at all.
Some crates are using it for a simple functionality which can be
replaced easily.
This was causing issues with the release build process but we now have a
fix to clean residual build assets.

Reland: build: drop clap from dev-dependencies

---

.github/workflows/release.yaml

Since we run "cargo clean" before running the aarch64 build we need to
create the release and upload the x86-64 assets before the clean.

.github: Re-order release steps to ensure binaries are available

---

tests/integration.rs

KSM doesn't work with MSHV stack since guest memory is pinned (`pin_user_pages`) and pinned pages cannot be merged.
So, don't run the test for mshv.
Signed-off-by: Anirudh Rayabharam <anrayabh@linux.microsoft.com>

tests: disable test_memory_mergeable_on for mshv

---

.github/workflows/release.yaml

Dependabot will create a branch on the repo for it's updates this
triggers the release action (because it's the same event as a tag) which
will then fail leading to dependabot PRs not being automerged. Instead
only run the release check test on PRs or tag creation.

.github: Don't try and create releases for created branches

---

hypervisor/src/kvm/mod.rs
vmm/src/vm.rs

In order to comply with latest TDX version, we rely onto the branch `kvm-upstream-2022.08.07-v5.19-rc8` from `https://github.com/intel/tdx` repository. Updates are based on changes that happened in `arch/x86/include/uapi/asm/kvm.h` headers file.

tdx: Update support based on kvm-upstream v5.19

---

docs/intel_tdx.md

docs: Use the TDVF firmware from the edk2 repository

---

virtio-devices/src/mem.rs
virtio-devices/src/vsock/packet.rs

Fixed few typos in `virtio-device`. I found them using <https://github.com/crate-ci/typos>
One typo fix is probably a breaking change.

virtio-devices: typo fixes

---

Cargo.lock
devices/Cargo.toml
devices/src/tpm.rs

See https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4873
This drops the number of dependencies from 129 to 120.
No change in build time.

Drop PHF from TPM dependency

---

devices/src/tpm.rs
tpm/src/emulator.rs

Drop unused things. Simplify code. Make code more idiomatic. Avoid unnecessary allocations.

Simplify TPM code

---

scripts/dev_cli.sh

Right now integration test fails during the test run if /dev/mshv or /dev/kvm does not exist. We should not progress and exit early if not present.

scripts: check if /dev/{mshv,kvm} exists before test run

---

.github/workflows/build.yaml
Cargo.toml

Needed for #[derive(Default)] on enums which is now clippy checked in
1.68.
Fixes: #5140

build: Bump MSRV to 1.62

---

docs/building.md

As a first time user of cloud-hypervisor and Rust environment you get build errors for this instruction.
$ cargo build --release --target=x86_64-unknown-linux-musl --all
...
running: "musl-gcc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "src/zlib" "-fvisibility=hidden" "-DSTDC" "-D_LARGEFILE64_SOURCE" "-D_POSIX_SOURCE" "-o" "/home/rveerama/src/github/CH/cloud-hypervisor/cloud-hypervisor/target/x86_64-unknown-linux-musl/release/build/libz-sys-96e9774dc769c364/out/lib/src/zlib/adler32.o" "-c" "src/zlib/adler32.c"
--- stderr
error occurred: Failed to find tool. Is `musl-gcc` installed?
warning: build failed, waiting for other jobs to finish...

doc: Add musl-tools to instructions for build

---

Jenkinsfile

This patch adds a global execution timeout to the Jenkinsfile to avoid infinite pending Jenkins pipelines, such as when certain worker nodes are not available. The global execution timeout is now set to 4 hours which is derived from total timeout of our longest stage (e.g. the `Worker build`).
Fixes: #5148

Jenkinsfile: Enforce global execution timeout

---

hypervisor/src/kvm/mod.rs

This is required for booting Linux:
From: https://lore.kernel.org/all/20221028141220.29217-3-kirill.shutemov@linux.intel.com/
"""
Virtualization Exceptions (#VE) are delivered to TDX guests due to
specific guest actions such as using specific instructions or accessing
a specific MSR.
Notable reason for #VE is access to specific guest physical addresses.
It requires special security considerations as it is not fully in
control of the guest kernel. VMM can remove a page from EPT page table
and trigger #VE on access.
The primary use-case for #VE on a memory access is MMIO: VMM removes
page from EPT to trigger exception in the guest which allows guest to
emulate MMIO with hypercalls.
MMIO only happens on shared memory. All conventional kernel memory is
private. This includes everything from …

tdx: Set the SEPT_VE_DISABLE attribute

---

docs/intel_tdx.md

Updates include:
- Add references to 'TDX Tools'
- Expand instructions on buidling and using TDShim
- Add version information of guest/host kernel, TDVF, TDShim being tested

docs: Update the intel_tdx documentation

---

arch/src/x86_64/mod.rs
hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
vmm/src/seccomp_filters.rs

This hypervisor leaf includes details of the TSC frequency if that is
available from KVM. This can be used to efficiently calculate time
passed when there is an invariant TSC.
Fixes: #5178

arch, hypervisor: Populate CPUID leaf 0x4000_0010 (TSC frequency)

---

vmm/src/memory_manager.rs
vmm/src/vm.rs

The main motivation behind refactoring is driven from the SEV-SNP prospective as explained in  #4761

Refactor create userspace mapping for guest memory

---

Jenkinsfile
scripts/run_integration_tests_windows_x86_64.sh
tests/integration.rs

The updated image is configured in a same way as the prev used 2019, it has same
- Credentials
- Services configured, like SAC, SSH, RDP
- Size
All the Windows updates are applied so the state is current to the date. Also, the latest stable version 0.1.229 of the VirtIO Windows drivers is installed.
Fixes: #5126

ci: Switch to Windows Server 2022

---

Cargo.lock
tpm/Cargo.toml
tpm/src/emulator.rs
vmm/src/seccomp_filters.rs

While running tpm commands, if swtpm becomes unresponsive, guest gets blocked at "recvmsg" on tpm's data FD. This change adds a timeout to the data fd socket. If swtpm becomes unresponsive guest waits for "timeout" (secs) and continues to run after returning an I/O error to tpm commands.
Signed-off-by: Praveen K Paladugu <prapal@linux.microsoft.com>

tpm: Add recv timeout while running recvmsg

---

vmm/src/config.rs
vmm/src/vm_config.rs

These are owned by the config (and are duplicated before being used to
create the `Tap` for the virtio-net device.)
Fixes: #5197

vmm: config: Close FDs for TAP devices that are provided to VM

---

vmm/src/config.rs

This PR fixed the following two issues that were introduced from #5199:
- Avoid closing reserved FDs from 'NetCOnfig::drop()'
- Avoid closing invalid FDs from 'test_net_parsing()'
Fixes: #5203

Avoid closing reserved FDs and fix unit tests caused by closing invalid FDs

---

scripts/run_integration_tests_vfio.sh

This test (which relies on nesting) is failing on the VFIO worker. The tests that use the
dedicated hardware pass fine.
See: #5190

tests: Disable test_vfio test

---

vmm/src/config.rs

vmm: config: Replace use of memfd_create with fd pointing to /dev/null

---

vmm/src/cpu.rs

Once error occur, vcpu thread may exit, this should be critical event for the whole VM, we should fire exit event and set vcpu state.
If we don't set vcpu state, the shutdown process
will hang at signal_thread, which is waiting the
vcpu state to change.

vmm: properly set vcpu state when thread exited

---

scripts/ch-trace-visualiser.py

Unused import 'xml' is redefined at:
> xml = ET.ElementTree(element=svg)
Hence, remove unused xml import.

scripts: ch-trace-visualiser.py: remove unused import 'xml'

---

scripts/dev_cli.sh

To improve user friendliness, print help text when an unknown command or no command is given.

scripts: dev_cli.sh: print help for unknown command

---

vmm/src/config.rs

The PR #2333 added I/O rate limiter on block device, with some options in `DiskConfig`.  And the PR #2401 added rate limiter on virtio-net device with same options, but it still throws `Error::ParseDisk`.
This commit fixes it with correct values.
Fixes: #2401

vmm: config: fix incorrect values of error

---

arch/src/x86_64/mod.rs
hypervisor/src/hypervisor.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs

To better reflect its nature and avoid confusion with get_cpuid2.

hypervisor: rename get_cpuid to get_supported_cpuid

---

virtio-devices/src/vhost_user/fs.rs

We should reset the offset to 0, when asked to remove the whole dax mapping.

virtio-devices: vhost-user: fs: reset offset when to remove the whole mapping

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_vfio.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh

On aarch64 server,cat /proc/meminfo
Hugepagesize:     524288 kB
Hugetlb:          524288 kB
On x86 server,cat /proc/meminfo
Hugepagesize:       2048 kB
Hugetlb:            2048 kB
2048kB x 6144 = 524288kB x 24.
We should dynamically configure nr_hugepages。

Use hugepagesize of the current device to calculate nr_hugepages

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
tests/integration.rs

Due to refactoring on snapshot/restore support #4960 #4970 and CLI changes #5086, the live-upgrade tests were disabled since release v28.0. Now we are ready to re-enable them based on release v30.0

tests: Enable live-upgrade tests based on v30.0

---

performance-metrics/src/main.rs
test_infra/src/lib.rs

This commit will add timeout parameter to performance metrics testcases as runtime argument. Testcases are facing the timeout issue sometimes when we run it with MSHV hypervisor. This change will provide mechanism to pass the timeout as per the need while running the testcases. If nothing is passed, default timeout or timeout set as per the testcase will be followed.

tests: performance-metrics: Add timeout parameter as runtime argument.

---

.github/workflows/docker-image.yaml
resources/Dockerfile
scripts/dev_cli.sh

It is necessary to transition away from DockerHub as the small
organisation plan in being EOLed.

build: Migrate from DockerHub to ghcr

---

scripts/dev_cli.sh

Unfortunately the build had a transient error and so needed to be
restarted which generated a build with a different date tag.

scripts: dev_cli: Bump container version

---

scripts/dev_cli.sh

Adds a section to the help string for "Available Flags" and documents the `--local` flag.

scripts: dev_cli: mention the `--local` flag in the help string

---

src/bin/ch-remote.rs

Fixes `ShutdownVmm` and `Shutdown` commands to call the correct API endpoints.

ch-remote: fixed `ShutdownVmm` and `Shutdown` commands

---

docs/api.md

I noticed that `/vm.receive-migration` and `/vm.send-migration` endpoints are not documented in the API docs. I did go through the source code for the `VmReceiveMigration` call and there doesn't seem to be any prerequisite, happy to correct the commit if there's any.

docs: api: document `receive-migration` and `send-migration`

---

tests/integration.rs

balloon_free_page_reporting test case should not work as expected. The reason is that MSHV pins  all the pages during the memory map for the guest. Those pages can not be altered without unpinning the pages. MSHV does not support modifying the pages during the guest life cycle. This test case can be enabled once we add VA backed VM support.

tests: disable virtio_balloon_free_page_reporting on mshv

---

hypervisor/Cargo.toml

It was not possible to build just hypervisor with Cargo's -p flag, because it was not properly specifying the features it requires from vfio-ioctls.

hypervisor: make buildable independently

---

arch/src/aarch64/regs.rs
virtio-devices/src/vsock/csm/connection.rs
virtio-devices/src/vsock/csm/mod.rs
virtio-devices/src/vsock/packet.rs
virtio-devices/src/vsock/unix/mod.rs
virtio-devices/src/vsock/unix/muxer.rs
virtio-devices/src/vsock/unix/muxer_killq.rs
virtio-devices/src/vsock/unix/muxer_rxq.rs

This fixes documentation that showed up in rustdoc but shouldn't have, documentation that didn't show up in rustdoc but should have, documentation that was applied to the wrong items, and documentation that was formatted improperly.
More information about each specific change is in the commit message.

Doc comment fixes

---

hypervisor/src/kvm/mod.rs
hypervisor/src/lib.rs
hypervisor/src/mshv/mod.rs
scripts/run_unit_tests.sh

It seems like these examples were always intended to be doctests, since there are lines marked with "#" so that they are excluded from the generated documentation, but they were not recognised as doc tests because they were not formatted correctly.
The code needed some adjustments so that it would actually compile and run as doctests.

hypervisor: use proper doc tests for examples

---

arch/src/aarch64/mod.rs
arch/src/lib.rs
arch/src/x86_64/mod.rs
vmm/src/device_manager.rs
vmm/src/seccomp_filters.rs
vmm/src/sigwinch_listener.rs
vmm/src/vm.rs

For tty, SIGWINCH was handled in the main cloud-hypervisor process, but that wasn't workable for pty, so they were handled in the separate SIGWINCH listener process.  This meant that there were two completely different code paths used to handle console resizing, depending on whether the console was connected to tty or pty, which made understanding the console handling code unnecessarily complicated.
Here, I've unified the implementations, so both tty and pty use the SIGWINCH handler process.  Since this means the SIGWINCH handler will be more widely used, I've made it compatible with older kernels (tested on Ubuntu 20.04), so this will also fix PTY resizing for those old kernels.  The code size comes out roughly the same as it was before, but that's mostly due to the added fallbacks for …

Unify console SIGWINCH handling code

---

Cargo.lock
Cargo.toml
release-notes.md
vm-migration/src/lib.rs

Please review but do not merge before April 6. There may be update.
Please also take a look whether the scope of `https://github.com/orgs/cloud-hypervisor/projects/6/views/4` is proper. I applied a filter `is:pr is:closed merged:>2023-02-23 -label:dependencies` to search the PR's (not for dependency) that have been merged since our last release, and picked items from the search result.

build: Release v31.0

---

Cargo.lock
hypervisor/src/mshv/mod.rs

Recently generated mshv-bindings has most of the registers
renamed. This patch renames some of the MSHV registers.

hypervisor: Fix few register names on MSHV

---

vmm/src/api/http_endpoint.rs

Valid FDs can only be sent from another process via `SCM_RIGHTS`.

vmm: Ignore and warn TAP FDs sent via the HTTP request body

---

virtio-devices/src/seccomp_filters.rs

Cloud Hypervisor's vhost-user implementation will reconnect if it gets disconnected from the backend.  That means connections happen inside the vhost-user seccomp sandbox, so all syscalls used in reconnecting have to be allowed in that sandbox.
clock_nanosleep is used by Glibc, and nanosleep is used by musl.

virtio-devices: seccomp: add vhost-user syscalls

---

Cargo.lock
Cargo.toml
hypervisor/src/kvm/mod.rs
vmm/src/cpu.rs

Having PMU in guests isn't critical, and not all hardware supports it (e.g. Apple Silicon).
CpuManager::init_pmu already has a fallback for if PMU is not supported by the VCPU, but we weren't getting that far, because we would always try to initialise the VCPU with KVM_ARM_VCPU_PMU_V3, and then bail when it returned with EINVAL.

vmm: only use KVM_ARM_VCPU_PMU_V3 if available

---

virtio-devices/src/lib.rs
virtio-devices/src/vhost_user/mod.rs

This code is shared between all vhost-user devices, not just vhost-user-blk.

virtio-devices: remove incorrect "blk" references

---

build.rs
performance-metrics/src/main.rs
src/bin/ch-remote.rs
src/main.rs
vhost_user_block/src/main.rs
vhost_user_net/src/main.rs
vmm/src/api/mod.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/lib.rs

This PR introduces several additional fields to the `VmmPingResponse` struct beyond the `version` information. The updated response now includes the `build_version` and `pid` fields as shown below:
```json
{
"build_version": "v31.0-4-g48084c33-dirty",
"version": "31.0.0",
"pid": 60639
}
```

Additional fields for `VmmPingResponse`

---

src/main.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs

When neither serial nor console are connected to the tty, cloud-hypervisor shouldn't touch the tty at all.  One way in which this is annoying is that if I am running cloud-hypervisor without it using my terminal, I expect to be able to suspend it with ^Z like any other process, but that doesn't work if it's put the terminal into raw mode.
Instead of putting the tty into raw mode when a VM is created or restored, do it when a serial or console device is created.  Since we now know it can't be put into raw mode until the Vm object is created, we can move setting it back to canon mode into the drop handler for that object, which should always be run in normal operation.  We still also put the tty into canon mode in the SIGTERM / SIGINT handler, but check whether the tty was actually used, …

vmm: only touch the tty flags if it's being used

---

src/main.rs
tests/integration.rs
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm_config.rs

Preserved FDs are the ones that share the same life-time as its holding
VmConfig instance, such as FDs for creating TAP devices.
Preserved FDs will stay open as long as the holding VmConfig instance is
valid, and will be closed when the holding VmConfig instance is destroyed.

Extend 'VmConfig' with 'preserved_fds'

---

arch/src/x86_64/mod.rs
hypervisor/src/arch/x86/mod.rs
hypervisor/src/kvm/aarch64/gic/mod.rs
virtio-devices/src/vsock/packet.rs
vmm/src/api/mod.rs
vmm/src/gdb.rs
vmm/src/lib.rs

As the code has evolved these clippy overrides are no longer needed.
See #4986

misc: Remove unnecessary clippy directives

---

test_infra/src/lib.rs
tests/integration.rs

This fixes the following tests that have been consistently failing on
the CI:
[2023-04-22T07:00:53.760Z] failures:
[2023-04-22T07:00:53.760Z]     common_parallel::test_focal_hypervisor_fw
[2023-04-22T07:00:53.760Z]     common_parallel::test_focal_ovmf
I'm not sure of the origin of this check but it obviously dependent on
the underlying platform as the guest OS has not changed. Since it
depends on the host environment it doesn't make sense to assert for it.

tests: Remove "initial apicid" check from test_simple_launch

---

Jenkinsfile

Windows guests tests are failing consistently.
See: #5400

build: Temporarily disable Windows guest tests

---

hypervisor/src/hypervisor.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
vmm/src/cpu.rs

On KVM this is provided by an ioctl, on MSHV this is constant. Although
there is a HV_MAXIMUM_PROCESSORS constant the MSHV ioctl API is limited
to u8.

hypervisor, vmm: Limit max number of vCPUs to hypervisor maximum

---

vmm/src/seccomp_filters.rs

This is used on older kernels where close_range() is not available.
So far I've only checked glibc x86_64.  It's possible we'll need to allow additional syscalls for aarch64/musl.
Fixes #5389.

vmm: allow getdents64 in seccomp filter

---

src/main.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs

I discovered a couple of cases where https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5343 was not doing quite the right thing:
- The OPOST flag was being set but not unset.
- If an error happened in `start_vmm` after starting the vmm thread, the tty was not reset.
More details are in the commit messages.
Getting TTY handling right is really hard, but I think we're gradually converging towards getting it right in all circumstances.

TTY reset fixes

---

hypervisor/src/mshv/mod.rs
tests/integration.rs
vmm/src/cpu.rs
vmm/src/seccomp_filters.rs

This set of patches implements the `set_cpuid2` for MSHV based on the `HvCallRegisterInterceptResult` hypercall. 
Summary of the implementation and accompanying fixes:
- Implement `set_cpuid2` for MSHV
- [moved to mshv crate] Handle topology leafs `0xb` and `0x1f` for Intel processors
- Topology related integration tests can be enabled on MSHV
- Seccomp filter is extended for `HvCallRegisterInterceptResult` hypercall
This enablement of this functionality will mean, that all the entries passed through `CpuidPatch` and other CPUID modifications will be registered for the interception through MSHV and then delivered directly to the guest. Depending on a concrete CPUID entries, some additional handling might need to be implemented (like in this case for the topology leafs).
Please note also, …

mshv: Implement set_cpuid2 call and ensure topology

---

vmm/src/device_tree.rs

The current implementation of breadth first traversal for device tree uses a temporary vector, therefore causes unnecessary memory copy. Remove it and do it within vector nodes.

vmm: reduce memory copy when BFT device tree

---

arch/src/aarch64/mod.rs
arch/src/x86_64/mod.rs
hypervisor/src/cpu.rs
hypervisor/src/hypervisor.rs
hypervisor/src/lib.rs
vmm/src/cpu.rs
vmm/src/lib.rs
vmm/src/vm.rs

CPU vendor identification is required to correctly determine available host features and do necessary fine tuning at runtime. For x86, the current code in most case assumes an `Intel` based host. This patch initially adds support for detecting `Intel` and `AMD`, while other processors can be of course added. Later on, there might be a least some interest determining features for two other processors - `Hygon` and `Zhaoxin`. For Hygon, there's already #5305 reported, which can require some specific handling. This functionality can be also extended to support `ARM` processors, if makes sense.
In general, with the functionality to determine the host CPU vendor, the potential is also to improve the portability and extend the range of compatible hosts where CH can be used. Currently there …

hypervisor: Add infrastructure to detect host CPU vendor

---

scripts/sha1sums-x86_64

Remove empty line to fix warning:
"sha1sum: WARNING: 1 line is improperly formatted"

tests: fix sha1sum check warning

---

src/main.rs

Rust documentation comments follows 80 char per line. But some of these help options doesn't have space in between. Longlines of text is starting from beginning of the next line instead of proper format.
```
Before fix:
Options:
--cpus            boot=<boot_vcpus>,max=<max_vcpus>,topology=<threads_per_core>:<cores_per_die>:<dies_per_package>:<packages>,kvm_hyperv=on|off,max_phys_bits=<maximum_number_of_physical_bits>,affinity=<list_of_vcpus_with_their_associated_cpuset>,features=<list_of_features_to_enable>
After fix:
Options:
--cpus            boot=<boot_vcpus>, max=<max_vcpus>,
topology=<threads_per_core>:<cores_per_die>:<dies_per_package>:<packages>,
kvm_hyperv=on|off,
max_phys_bits=<maximum_number_of_physical_bits>,
affinity=<list_of_vcpus_with_their_associated_cpuset>, …
```

vmm: Improve "cloud-hypervisor --help" view format

---

docs/custom-image.md

We get a "404 - page not found" when clicking on this link on github.

docs: Fix broken link to macvtap doc in custom-image.md

---

Cargo.lock
Cargo.toml
arch/Cargo.toml
block_util/Cargo.toml
devices/Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
hypervisor/Cargo.toml
net_util/Cargo.toml
pci/Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml
virtio-devices/Cargo.toml
vm-allocator/Cargo.toml
vm-device/Cargo.toml
vm-migration/Cargo.toml
vm-virtio/Cargo.toml
vmm/Cargo.toml

Bump to the latest rust-vmm crates, including vm-memory, vfio,
vfio-bindings, vfio-user, virtio-bindings, virtio-queue, linux-loader,
vhost, and vhost-user-backend,
Signed-off-by: Bo Chen [chen.bo@intel.com](mailto:chen.bo@intel.com)

build: Bulk update rust-vmm dependencies

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_x86_64.sh
tests/integration.rs

In this way, our integration tests exercise the same set of build features (e.g. "kvm,mshv") being used for releases.

tests: Enable "dbus_api" feature build only for dbus_api tests

---

virtio-devices/src/seccomp_filters.rs
vmm/src/seccomp_filters.rs

SerialBuffer uses VecDeque::extend, which calls realloc, which a maximum buffer size of 1 MiB.  Starting at allocation sizes of 128 KiB, musl's mallocng allocator will use mremap for the allocation. Since this was not permitted by the seccomp rules, heavy write load could crash cloud-hypervisor with a seccomp failure.  (Encountered using virtio-console, but I don't see any reason it wouldn't happen for the legacy serial device too.)

vmm, virtio-devices: allow mremap for consoles

---

arch/src/x86_64/mod.rs

When start clh from edk2 with vcpu number larger than 2, edk2 will crash at Ap initialization. The root cause is that when get ApicId from cpuid, it returns a wrong value that ApicId is the same for each Ap. Further more, stack selection depends on ApicId, that leads to all Aps share the same stack space.
Explicitly set ApicId in cpuid for each vcpu can solve this issue.
Fixes: #5475

x86: set ApicId in cpuid for each vcpu

---

scripts/run_integration_tests_vfio.sh

Download firmware and focal image to fix issue of running vfio tests with empty worlkoads directory:
$ scripts/dev_cli.sh tests --integration-vfio
cp /root/workloads/focal-server-cloudimg-amd64-custom-20210609-0.raw /root/workloads/vfio cp: cannot stat '/root/workloads/focal-server-cloudimg-amd64-custom-20210609-0.raw': No such file or directory
cp /root/workloads/hypervisor-fw /root/workloads/vfio cp: cannot stat '/root/workloads/hypervisor-fw': No such file or directory

tests: fix issue running vfio tests with empty worlkoads directory

---

virtio-devices/src/transport/pci_device.rs

Remove enum_variant_names clippy. Enumeration variant names should specify their variant, not repeat the enumeration name.
https://rust-lang.github.io/rust-clippy/master/index.html#/enum_variant_names
See https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4986

Remove repeated suffix from enum names

---

Jenkinsfile

This reverts commit 83d57d3cce31b6f0750cb5f1fac8d3d311b03db2.
Fixes: #5400
The actual fix has landed in #5512

ci: Re-enable Windows guest integration tests

---

pci/src/msix.rs
pci/src/vfio.rs
vm-allocator/src/lib.rs
vm-allocator/src/page_size.rs
vm-allocator/src/system.rs

vfio: fix vfio device fail to initialize issue for 64k page size
Currently, vfio device fails to initialize as the msix-cap region in BAR is mapped as RW region.
To resolve the initialization issue, this commit avoids mapping the msix-cap region in the BAR.
However, this solution introduces another problem where aligning the msix table offset in the
BAR to the page size may cause overlap with the MMIO RW region, leading to reduced performance.
By enlarging the entire region in the BAR and relocating the msix table to achieve page size
alignment, this problem can be overcomed effectively.
Fixes: #5292

vfio: fix vfio device fail to initialize issue for 64k page size

---

vmm/src/seccomp_filters.rs

This can be triggered by debugging cloud-hypervisor using gdb, or probably if the process is suspended and restarted.
Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5489.

vmm: allow restart_syscall() in PTY process

---

arch/src/aarch64/fdt.rs

CLH and QEMU pass device information to the guest kernel through the device tree instead of the ACPI Table on the ARM64 architecture. However, CLH did not realize the CPU Cache topology structure in the process of building the device tree. Therefore, the lscpu command can not output cache-related information after the virtual machine is started, and there is no cache for this folder /sys/devices/sys/cpu/cpu0/. This is unfriendly for some applications, because some applications need to obtain hardware cache information  to optimize.
We modified CLH /arch/src/aarch64/fdt.rs to directly read the cache information (/sys/devices/sys/cpu/cpu0/) from the Host side, and write the appropriate cache node into the device tree.
Of course, due to the limitations of the device tree itself, we can only …

aarch64/fdt: support CPU cache passthrough through device-tree

---

scripts/run_integration_tests_vfio.sh
tests/integration.rs

Test was failing due to regression caused by commit
https://github.com/cloud-hypervisor/cloud-hypervisor/commit/d5558aea2a4205564b00ee8796a8ab47879df337
Failing command:
sudo /mnt/ch-remote --api-socket /tmp/ch_api.sock resize --memory=1073741824"

Fix vfio test

---

pci/src/configuration.rs

According the std docs implementing From<..> is preferred since it gives you Into<..> for free where the reverse isn’t true.
https://rust-lang.github.io/rust-clippy/master/index.html#/from_over_into
See: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4986

Remove "from_over_into" clippy

---

tests/integration.rs

Between musl and glibc there is a difference in the signature of the ioctl libc function. Use an anonymous cast to force the type coversion.
Solution adopted from https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5002/commits/56c878e6df6c06d68970196e48617e31427fd46d
See: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4986

Remove "useless_conversion" clippy

---

net_gen/src/if_tun.rs
net_gen/src/iff.rs
net_gen/src/lib.rs

Remove clippy:all and update it with correct clippy audit, so that it gives proper information. This PR doesn't completely remove clippy but gives some clarity on it.
See: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4986

Replace "clippy::all" with correct ones

---

hypervisor/Cargo.toml
hypervisor/src/arch/x86/mod.rs

On x86-64, when the underlying hypervisor platform is KVM, no instruction emulator is necessary. KVM handles instruction boundaries internally.
This change allows to skip the iced-x86 dependency on KVM, improving build times, prunes the dependency graph and reduces network traffic during the initial build.
For Hyper-V, the emulator is still necessary on x86-64, so nothing changes there.
This PR is my second attempt addressing the changes requested in the (now closed) #5554.

hypervisor: x86: Emulator is only needed on `mshv`, not `kvm`

---

Cargo.lock

build: Bump proc-macro2 crate to fix nightly builds

---

fuzz/Cargo.lock
fuzz/Cargo.toml

This reverts commit efb579b2247ffa523db5677c463ea809d65108db.
This PR was mistakenly merged due to the confusion around nightly
builds. The vm-memory update needs to be done in both the root workspace
and fuzz workspace together.

Revert "build: Bump vm-memory from 0.11.0 to 0.12.0 in /fuzz"

---

tests/integration.rs

test_cpu_affinity needs the number of host CPUs. Since it is possible
for the host to have more than 255 CPUs; increase the size of the
datatype used for parsing the string to accomodate this.

tests: Correctly parse number of host cpus > 255

---

vmm/src/vm_config.rs

This fixes the valid VM config unit tests, which would otherwise fail to deserialize their expected JSON config due to the missing "gdb" field.

vmm: default GDB to false when deserializing

---

vmm/src/seccomp_filters.rs

Add MSHV_CREATE_DEVICE, MSHV_SET_DEVICE_ATTR ioctls to filters. These ioctls are required to passthrough PCI devices on mshv.

vmm: Extend mshv ioctls in seccomp filters

---

Cargo.lock

* zbus v3.13.1 -> v3.14.1
* zbus_macros v3.13.1 -> v3.14.1
* zbus_names v2.5.1 -> v2.6.0
* zvariant v3.14.0 -> v3.15.0
* zvariant_derive v3.14.0 -> v3.15.0
(previous PR by dependabot: #5630)

build: bump zbus related dependencies

---

README.md
arch/src/x86_64/mod.rs

The commit b92fe648e925 (vmm: cpu: Disable KVM_FEATURE_ASYNC_PF_INT in CPUID) disabled APF (Asynchronous Page Fault) mechanism to address problem that makes vcpu thread spin 100%. As the actual issue is in KVM, which has been merged in commit 2f15d027c05f (KVM: x86: Properly handle APF vs disabled LAPIC situation) since 2021, so it's okay to re-enable APF now.

arch: x86_64: re-enable KVM_FEATURE_ASYNC_PF_INT in CPUID

---

tests/integration.rs
vmm/src/coredump.rs
vmm/src/vm.rs

It makes sense pause/resume in coredump() method, so api caller doesn't  need to pause vm firstly.
Also, add integration test of this modification.

vmm: allow coredump no need pause firstly

---

scripts/run_integration_tests_x86_64.sh

The VFIO tests based on the NVMe emulation framework require cause a high number of file descriptors to be opened on the system. On systems with a low limit on opened files, tests like test_vfio_user can possibly fail with "too many open files" exeption. This issue is fixed by raising the corresponding limit.
A tricky detail here is, that the limit has to be changed in the test container and not on the host. As the the container is executed in the privileged mode, the setting in it will override the host value.
Related: #5426

tests: Ensure sufficient nofile limit for VFIO tests

---

hypervisor/src/arch/x86/emulator/instructions/mov.rs
hypervisor/src/arch/x86/emulator/mod.rs
hypervisor/src/lib.rs

Hi! While playing with some toy kernels as boot payload, I noticed that the emulator is not capable of emulating the following instructions:
- Mov_moffs16_AX
- Mov_AX_moffs16
- Mov_moffs32_EAX
- Mov_EAX_moffs32
- Mov_moffs64_RAX
- Mov_RAX_moffs64
This PR also adds unit tests.

x86 emulator: add `Mov_moffs_AX` & `Mov_AX_moffs` (16,32,64)

---

devices/src/gic.rs
devices/src/ioapic.rs
devices/src/legacy/gpio_pl061.rs
devices/src/legacy/rtc_pl031.rs
devices/src/legacy/serial.rs
devices/src/legacy/uart_pl011.rs
fuzz/fuzz_targets/serial.rs
pci/src/msi.rs
pci/src/msix.rs
vm-device/src/interrupt/mod.rs
vmm/src/interrupt.rs

Split interrupt source group restore into two steps, first restore the irqfd for each interrupt source entry, and second restore the GSI routing of the entire interrupt source group.
This patch will reduce restore latency of the interrupt source group, and in a 200-concurrent restore test, the patch reduced the average IOAPIC restore time from 15ms to 1ms.

vm-device: support batch update interrupt source group GSI

---

scripts/dev_cli.sh

Currently if container registry is inaccessible the image will be built locally and that takes time. This patch adds support to use mirror registry. To use a different registry CTR_IMAGE environment variable must be set. For example:
CTR_IMAGE="registry/cloud-hypervisor" scripts/dev_cli.sh
or
export CTR_IMAGE="registry/cloud-hypervisor"
scripts/dev_cli.sh

scripts: dev_cli: add possibly to use different container registry

---

.github/workflows/release.yaml

In this way, we are releasing binaries with all default features plus feature "mshv".

build: Enable default features for release workflow

---

scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_rate_limiter.sh
scripts/run_integration_tests_sgx.sh
scripts/run_integration_tests_vfio.sh
scripts/run_integration_tests_windows_x86_64.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh
scripts/run_unit_tests.sh

Now feature "mshv" can be built together with "kvm". There is no need to use "--no-default-features" any more.
Fixes: #5647

scripts: Stop using "--no-default-features" for cargo build

---

resources/Dockerfile
scripts/dev_cli.sh

As the container image can be used on both Intel and AMD, ensure the SPDK binaries are compatible. This implies -march=skylake passed to the underlaying toolchain.
Ref: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5627#issuecomment-1665095193

Dockerfile: Build SPDK for skylake

---

Jenkinsfile

Add jobs to run some tests on AMD. Jet it is a minimal run for Linux only glibc/musl.
Test failures:
<strike>common_parallel::test_cpu_hotplug
common_parallel::test_macvtap
common_parallel::test_macvtap_hotplug
common_parallel::test_memory_hotplug
common_parallel::test_tap_from_fd
common_parallel::test_virtio_mem
live_migration::live_migration_parallel::test_live_upgrade_watchdog
live_migration::live_migration_parallel::test_live_upgrade_watchdog_local</strike>
Failed duo to CMOS reset at reboot, fixed by #5645
<strike>common_parallel::test_vfio_user</strike>
Failing due to the SPDK build, fixed by updating the builds in the Docker container, see #5654.
live_migration::live_migration_parallel::test_live_migration_watchdog
live_migration::live_migration_parallel::test_live_migration_watchdo …

ci: Add AMD pass

---

Jenkinsfile
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh

These had to be previously disabled because a released binary has to be used in course of the test scenario. The necessary functionality is now supported with the release 34.0, thus these tests should now pass.
Fixes: #5660

tests: Re-enable live migration tests for AMD

---

vmm/src/cpu.rs

Add pending removed vcpu check according to VcpuState.removing, which can avoid cloud hypervisor hangup during continual vcpu resize.
Fix #5419

vmm: cpu: Add pending removed vcpu check to avoid resize vcpu hang

---

virtio-devices/src/balloon.rs

Currently, virtio-balloon can't work well with pagesize other than 4k. Maybe, this is a issue for balloon spec that fails to consider pagesize other 4k.
That's say this is not the case for cloud hypervisor but also other VMM. So, we can refer to the existed solution. Luckily, qemu gives us one [1].
Though it's forbidden to free page smaller than pagesize which is larger than 4k, we can wait for the whole pagesize needs to be freed. What has been done here is that account and wait then handle it. For balloon deflation, we can just align the address and length to page size.
Fixes: #5369
[1] https://patchwork.kernel.org/project/qemu-devel/cover/20190214043916.22128-1-david@gibson.dropbear.id.au/

balloon: let balloon work on pagesize other than 4k

---

hypervisor/src/mshv/mod.rs

It is discovered in our testing that MSHV didn't handle this message.
In general I don't think Cloud Hypervisor handles level-triggered interrupts well. KVM code is missing resamplefd code. That's something to be fixed later.

Handle APIC EOI message for MSHV

---

block/src/async_io.rs
block/src/raw_async.rs
block/src/raw_sync.rs
block/src/vhdx/vhdx_metadata.rs
hypervisor/src/arch/x86/emulator/instructions/mod.rs
net_util/src/queue_pair.rs
src/bin/ch-remote.rs
virtio-devices/src/transport/pci_common_config.rs
virtio-devices/src/transport/pci_device.rs
virtio-devices/src/vsock/csm/txbuf.rs
vm-device/src/bus.rs
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/sigwinch_listener.rs

- block: vhdx: Fix block size check
- block: async_io: Remove unnecessary mut from reference
- net_util: queue_pair: Remove unnecessary mut from reference
- hypervisor: x86: emulator: Remove unncessary mut from reference
- vm-device: bus: Fix incorrect partial_cmp implementation
- virtio-devices: transport: Remove unnecessary mut from reference
- virtio-devices: vsock: Fix slow vector initialization
- vmm: cpu: Fix slow vector initialization
- ch-remote: dbus: Remove unnecessary mut from reference
- vmm: device_manager: Remove unnecessary mut from reference
- vmm: sigwinch_listener: Remove unncessary mut from reference

Fix beta clippy issues

---

devices/src/pvpanic.rs

There is no need for this struct to be public and since it is used in
this module the #[allow(dead_code)] invocation can be removed.

devices: pvpanic: Clean up struct visibility

---

Cargo.lock
docs/api.md
event_monitor/src/lib.rs
src/main.rs
vmm/Cargo.toml
vmm/src/api/dbus/mod.rs
vmm/src/lib.rs

~This PR enables the `event-monitor` crate to broadcast events to other subsystems of the project. It accomplishes this by making use of an unbounded MPMC channel ([`flume`](https://crates.io/crates/flume)).~
~The broadcasted events are then emitted on the D-Bus API using a signal called `Event`, which users can subscribe to.~
~We chose to use an MPMC channel instead of an MPSC channel because publishing events from `event-monitor` to a single consumer didn't seem like a good API design choice. This decision also future-proofs the feature, allowing other subsystems to subscribe to those events. `flume` being lightweight and widely adopted also contributed to this decision.~
Implementation is substantially changed, see comment: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5517# …

D-Bus API and `event-monitor` integration

---

tests/integration.rs

In the documentation of function check_latest_events_exact use same events argument name as in the implementation

tests: fix typo expected_events to latest_events

---

hypervisor/src/arch/x86/emulator/instructions/mod.rs

This is a bugfix for the emulator that we discovered when executing our test suite in debug mode.
Example instruction:
`c7 40 a0 00 10 00 00    movl   $0x1000,-0x60(%rax)`
rax is 0xfee003e0 and the displacement is negative 0x60. The effective address is then 0xfee00380. This is perfectly valid.

emulator: bugfix wrapping add

---

Jenkinsfile

The worker is running focal not bionic - this fixes build issues on that
worker machine due to the bionic version not being installable.

build: Use focal version of azure-cli client on aarch64

---

rate_limiter/src/lib.rs

This PR updates the RateLimiter type to allow it to be easily shared between threads. This will allow a follow-up PR to implement [rate limiting groups](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5726).
Following this change, the intended implementation of rate limiting groups is that a single RateLimiter struct will be shared by multiple virt-queue threads via an `Arc<RateLimiter>` type. This is preferable to sharing a RateLimiter with an `Arc<Mutex<RateLimiter>>` because it minimizes mutex contention. A main thread is responsible for handling RateLimiter timerfd events, and each individual virt-queue thread is responsible for consuming bandwidth and IO tokens.
```
// Main Thread
rate_limiter.event_handler()
// block1_queue0
rate_limiter.is_blocked() …
```

rate-limiter: Allow RateLimiter to be shared between threads

---

.github/workflows/build.yaml
.github/workflows/quality.yaml
Cargo.lock
Cargo.toml
arch/Cargo.toml
docs/amd_sev_snp.md
hypervisor/Cargo.toml
hypervisor/src/hypervisor.rs
hypervisor/src/mshv/mod.rs
src/main.rs
vmm/Cargo.toml
vmm/src/config.rs
vmm/src/lib.rs
vmm/src/vm.rs
vmm/src/vm_config.rs

In this patch set, I am introducing a new feature flag called "snp" to barricade all SNP related features under it. Also refactored the VM creation workflow to make way for SEV-SNP guest creation. Along with it added support for setting the initial SNP guest policy required from MSHV prospective.
This fixes in task 1 for #4761 
CC: @liuw @russell-islam

Initial patches to add support for MSHV based SEV-SNP guest.

---

Cargo.lock
devices/src/acpi.rs
fuzz/Cargo.lock
vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs
vmm/src/pci_segment.rs

Fix newly added deprecation for mispelling of cacheable.

build: Bump acpi_tables version

---

virtio-devices/src/block.rs

There is a "LATENCY_SCALE" being used for calculating cumulative average latency, so it should also be used for the latency of the first op.
See: #5712

virtio-devices: block: Correct the latency for the first op

---

tests/integration.rs

This test is consistently failing after the on demand worker kernel
upgrade.
See: #5756

tests: Temporarily disable test_vdpa_net

---

arch/src/x86_64/mod.rs
vmm/src/vm.rs

`EntryPoint` had an optional `entry_addr`, but there is no usage of this struct that makes it necessary that the address is optional.
Remove the `Option` to avoid being able to express things that are not useful.

vmm: simplify EntryPoint

---

tests/integration.rs

tests: test_memory_overhead: use guest.vm_wait_boot

---

block/src/lib.rs
fuzz/fuzz_targets/block.rs
vhost_user_block/src/lib.rs
virtio-devices/src/block.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/vm_config.rs

This PR adds support for explicitly specifying the serial number of a virtio-blk device. To enable easy automation, hyperscale cloud providers [such as GCP](https://medium.com/@DazWilkin/compute-engine-identifying-your-devices-aeae6c01a4d7) offer a convenient way to identify disks within a virtual machine. Qemu allows the ID_SERIAL property of virtio-blk devices to be specified with a `serial` argument.
A disk can be specified with serial number `abcdefghijklmnopqrst` in cloud hypervisor using the following arguments.
```
--disk path=focal-server-cloudimg-amd64.raw,serial=abcdefghijklmnopqrst
```
Within a virtual machine, the disk is available as `virtio-abcdefghijklmnopqrst`
```
ls /dev/disk/by-id/virtio-abcdefghijklmnopqrst
/dev/disk/by-id/virtio-abcdefghijklmnopqrst
```
The exact …

block: Add support for user specified ID_SERIAL

---

virtio-devices/src/block.rs

The cumulative average formula [1] requires to use signed integers for proper calculations, while calculated result (e.g. cumulative average) is always positive. This patch reflects the above requirements in our code.
[1] https://en.wikipedia.org/wiki/Moving_average#Cumulative_average
Fixes: #5745

virtio-devices: block: Fix latency counter for average read/write

---

virtio-devices/src/block.rs

This patch fixes the  max read/write latency for block device which now is always reported as `u64::MAX`.
See: #5712

virtio-devices: block: Fix the latency counter for max read/write

---

Cargo.lock
event_monitor/Cargo.toml
event_monitor/src/lib.rs

See discussion in https://github.com/rust-lang/rust/issues/53639. This came up during an internal review.

event_monitor: Replace unsound `static mut MONITOR`

---

Cargo.lock
fuzz/Cargo.lock
vmm/Cargo.toml

The 'derive' feature of `zerocopy` crate now is optional and requires to be enabled explicitly [1]. Also, a version bump on `acpi_tables` is needed to reply on a single version of `zerocopy` to avoid compilation errors.
[1] https://github.com/google/zerocopy/pull/176

build: Bump versions of acpi_tables and zerocopy

---

tests/integration.rs

This test is now supported on MSHV so we can re-enable the support for it.

tests: Enable testing for multi PCI segment for mshv

---

Cargo.toml
src/main.rs
vmm/src/api/mod.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/lib.rs

vmm: Report enabled features from the '/vmm.ping' endpoint
main: Report enabled features from CLI with "--version -v"
Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5817

Report enabled features via api endpoint and CLI

---

devices/src/legacy/serial.rs
devices/src/legacy/uart_pl011.rs
src/main.rs
tests/integration.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/serial_manager.rs
vmm/src/vm_config.rs

Cloud-Hypervisor takes a path for Unix Socket, where it will listen
on. Users can connect to the other end of the socket and access serial
port on the guest.
"--serial unix=/path/to/socket" is the cmdline option to pass to
cloud-hypervisor.
Users can use socat like below to access guest's serial port once the
guest starts to boot:
socat -,crnl UNIX-CONNECT:/path/to/socket

Unix Socket backend for Serial Port

---

resources/Dockerfile
scripts/dev_cli.sh
scripts/run_integration_tests_aarch64.sh

When performing integration testing on the Ampere One server, an error occurred when compiling spdk and not recognizing the CPU ID. 
The latest spdk already contains fixes.

tests: Update spdk commit id to support Ampere's new CPU

---

hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
vmm/src/vm.rs

As part of this initialization for a SEV-SNP VM on MSHV, it is required that we transition the guest state to secure state using partition hypercall. This implies all the created VPs will transition to secure state and could access the guest encrypted memory.

vmm, hypervisor: Initialize SEV-SNP VM

---

vmm/src/lib.rs

The lock to `vm_config` is held for accessing `cpus.kvm_hyperv` passing as a reference to `arch::generate_common_cpuid()`, so acquiring the same lock again while calling to the same function is a deadlock.
Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/commit/3793ffe888dbc9c4aaf929d1b4846e50f1122d6c
Reported-by: Yi Wang <foxywang@tencent.com>

vmm: tdx: Fix a deadlock while accessing `vm_config`

---

hypervisor/src/mshv/mod.rs

For a SEV-SNP enabled partition on MSHV, some of the VMGEXITS are offloaded for Hypervisor to handle while the rest are handled by VMM. By setting this additional partition property hypervisor is informed about the VMGEXITs it needs to take care off, rest all would be handled by the CloudHypervisor.

hypervisor: Enable VMGEXIT offload for SEV-SNP partition

---

arch/src/lib.rs
arch/src/x86_64/mod.rs
vmm/src/cpu.rs
vmm/src/lib.rs
vmm/src/vm.rs

This PR fixes #5833 with a refactoring for easier generation of common CPUIDs based on guest VM configurations.

Only advertise AMX feature bits to guest when the AMX cpu feature is enabled

---

arch/src/lib.rs
docs/memory.md
tests/integration.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/pci_segment.rs
vmm/src/vm.rs
vmm/src/vm_config.rs

Although multiple PCI segments are supported, all PCI segments have an affinity to NUMA node 0. This PR supports assigning non-default PCI segments to non-zero NUMA nodes.
For example, the following command will start cloud-hypervisor with two NUMA nodes and two PCI segments (one for each NUMA node).  The addition of the `pci_segments` argument to `NumaConfig` allows the user to specify the relationship between PCI Segments and NUMA nodes.
- An error is returned if the default PCI Segment (0) is not assigned to NUMA node zero.
- All PCI Segments default to NUMA node 0 if unspecified.
```
./cloud-hypervisor \
--platform num_pci_segments=2 \
--kernel /var/lib/cloud-hypervisor/CLOUDHV.fd \
--cpus boot=20,topology=2:5:1:2,affinity=[0@[2],2@[3],4@[4],6@[5],8@[6],10@[7],12@[8],14@[9],16@[10],18@ …
```

vmm: Allow assignment of PCI segments to NUMA node

---

.github/workflows/build.yaml
Cargo.toml
virtio-devices/src/block.rs
vm-allocator/src/system.rs

Sev-Snp on MSHV uses igvm crate to parse the igvm file. igvm crate needs minimum rust version 1.65 to build.

Update MSRV to 1.65

---

docs/vsock.md

In Connecting from Host to Guest section, the host/guest are misused, this patch fix that.
FYI, this is part of #5594 which has been closed, and the doc issue may should be fixed, so I open this PR :)

docs: fix the description of host/guest in vsock

---

docs/coverage.md
scripts/common-aarch64.sh
scripts/dev_cli.sh
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_rate_limiter.sh
scripts/run_integration_tests_sgx.sh
scripts/run_integration_tests_vfio.sh
scripts/run_integration_tests_windows_aarch64.sh
scripts/run_integration_tests_windows_x86_64.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh
scripts/run_unit_tests.sh

This requires changing the test scripts a bit.
Add some notes on how to do that in coverage.md.

Allow collecting coverage data from in-tree tests

---

tests/integration.rs

This PR enables the `test_pci_multiple_segments_numa_node` test and adds a `distance` field to `aarch64` to allow the test to pass.
See https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5864 https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5869

tests: Enable "test_pci_multiple_segments_numa_node"

---

vmm/src/vm.rs

This patch fixes following warnings:
error: boolean to int conversion using if
--> vmm/src/vm.rs:866:42
|
|                       .create_vm_with_type(if sev_snp_enabled.into() {
|  __________________________________________^
| |                         1 // SEV_SNP_ENABLED
| |                     } else {
| |                         0 // SEV_SNP_DISABLED
| |                     })
| |_____________________^ help: replace with from: `u64::from(sev_snp_enabled.into())`
|
= note: `-D clippy::bool-to-int-with-if` implied by `-D warnings`
= note: `sev_snp_enabled.into() as u64` or `sev_snp_enabled.into().into()` can also be valid options
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_to_int_with_if
error: useless conversion to the same …

vmm: Fix clippy warnings

---

Cargo.lock
hypervisor/Cargo.toml
hypervisor/src/mshv/mod.rs
hypervisor/src/mshv/snp_constants.rs
hypervisor/src/vm.rs

These two APIs are needed for vmm to import and complete isolated pages after loading the IGVM to the guest memory,
Microsoft hypervisor adds these pages for PSP measurement.

Hypervisor: Add APIs to import and complete isolated pages

---

Cargo.lock
hypervisor/src/cpu.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/mshv/snp_constants.rs

This PR implements the part 6 of #4761. There are still two things which are pending as part of GHCB handling:
- Adding support for secondary AP creation.
- Adding support for SNP guest request.
I will add support for these two things in the subsequent PRs as they require bit more restructuring around the existing codebase.

Add support for GHCB handling for SEV-SNP guest on MSHV

---

scripts/run_integration_tests_aarch64.sh

virtiofsd must be built with the default gnu toolchain so clear the
environment variables that may poisoned by the alternative C library
support.

scripts: Clear the toolchain environment variables for virtiofsd

---

.github/workflows/build.yaml
Cargo.lock
Cargo.toml

MSRV 1.66 is required for the following dependency:
toml_edit v0.19.15
└── proc-macro-crate v1.3.1
├── zbus_macros v3.14.1 (proc-macro)
└── zbus v3.14.1
├── cloud-hypervisor v35.0.0 (/home/chenb/project/cloud-hypervisor/cloud-hypervisor)
└── vmm v0.1.0 (/home/chenb/project/cloud-hypervisor/cloud-hypervisor/vmm)
└── cloud-hypervisor v35.0.0 (/home/chenb/project/cloud-hypervisor/cloud-hypervisor)

build: Bump MSRV to 1.66 and bump toml_edit from 0.19.8 to 0.19.15 

---

arch/src/aarch64/fdt.rs

Once vcpu_topology is None, values, like cores_per_package, will be set to zero.
Correct it by setting them to 1s when vcpu_topology is none.
Also add check in case one or more of these values are zero.
Fixes: #5892

aarch64:fdt: correct vcpu topology related value

---

scripts/test-util.sh

Launching test suite locally is broken by the recent change to use authenticated download URL.

Fix the check for GitHub authentication token

---

block/src/raw_async_aio.rs

If writeback cache is disabled, cloud-hypervisor performs a `flush` after each write. The newly added `aio` backend does not handle this case properly. Under these conditions, `io_uring` backend performs a synchronous flush. This PR updates the `aio` backend to have the same behavior. A modern guest will support writeback cache mode for performance (which is likely why this wasn't caught by manual testing or integration tests).

block: fix aio backend behavior when writeback cache disabled

---

tests/integration.rs

tests: Temporarily disable vhost_user_blk tests on aarch64

---

virtio-devices/src/vhost_user/vu_common_ctrl.rs

error: use of a fallible conversion when an infallible one could be used
Error:    --> virtio-devices/src/vhost_user/vu_common_ctrl.rs:206:51
|
206 |             let actual_size: usize = queue.size().try_into().unwrap();
|                                                   ^^^^^^^^^^^^^^^^^^^ help: use: `into()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_fallible_conversions
= note: `-D clippy::unnecessary-fallible-conversions` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::unnecessary_fallible_conversions)]`
error: could not compile `virtio-devices` (lib) due to previous error
Error: warning: build failed, waiting for other jobs to finish...
error: could not compile `virtio-devices` (lib …

virtio-devices: Fix beta clippy issue

---

tests/integration.rs

Since the 'write()' to the event file was moved to its own thread (see #5633), we have no reliable way to read the latest contents of the event file from our integration tests, since we can't ensure the 'read()' from our test always happen after 'write()' is completed from Cloud Hypervisor. This is also why we started to see random failures on snapshot_restore tests (particularly when the system workload is high).
This patch adds a 1s sleep before reading the event file to mitigate the random failures.

tests: Stabilize snapshot_restore tests

---

devices/src/pvpanic.rs

The PvPanicDevice has a 2-byte BAR size, which is smaller than the 16-byte minimum legacy PCI-Express BAR size and the 128-byte minimum modern PCI-Express BAR size. The base address register masks off the lower four bits, so all BARs must be at least 16-byte aligned (although the PCI specification requires that devices are aligned to their size). Despite being smaller than the minimum BAR size, the PvPanic device appears to work as long as it's BAR is 16-byte aligned.

devices: fix pv_panic alignment

---

vmm/src/migration.rs

We found that it's slow to load JSON when reading snap files. As described in [1], using from_slice instead of from_reader can fix this.
1. https://github.com/serde-rs/json/issues/160

vmm: speed up JSON load when reading snap files

---

hypervisor/src/mshv/mod.rs

There are two additional VmOps(i.e., create AP thread and issue SNP guest reuqest) which are required as part of SEV-SNP guest VMGEXITs handling.

Extend MshvVcpu with VmFd to implement SEV-SNP operations

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
tests/integration.rs

These live-upgrade tests were disabled due to CLI changes (#5791).

tests: Enable live-upgrade tests based on release v36.0

---

.github/workflows/openapi.yaml

Fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5960
Create an action to run the OpenAPI validation.

ci: Enable OpenAPI validate action

---

scripts/gitlint/rules.py

Valid title format:
component1[, component2, componentN]: submodule: summary
Title should have at least one component
Components are separated by comma+space: ", "
Components are validated to be in valid_components
Components list is ended by a colon
Submodules are not validated
See: #5846

 gitlint: validate title components

---

devices/src/pvpanic.rs
pci/src/device.rs
pci/src/vfio.rs
pci/src/vfio_user.rs
virtio-devices/src/transport/pci_device.rs
vm-allocator/src/system.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs
vmm/src/pci_segment.rs
vmm/src/vm.rs

This PR is a fix for https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5952. I have followed the pattern established for 64-bit memory regions to creating a separate 32-bit memory area allocator for each PCI segment (as opposed to assigning the entire 32-bit memory area to PCI segment 0). This allows passthrough of VFIO devices w/ 32-bit memory BARs to non-zero PCI segments.

vmm: assign each pci segment 32-bit mmio allocator

---

vmm/src/api/openapi/cloud-hypervisor.yaml

The change is missed when add "add-user-device" support in 53b2e19934abfe2920258e586e627498653b2371, use this commit to fix it.
Change-Id: Ifcfa4e94ce2342cc6c0723f65326f04b88bf2664

vmm:api: add add-user-device support in cloud-hypervisor.yaml

---

tests/integration.rs

Running on host where vdpa_sim_blk module is not correctly loaded test_vdpa_block passes.
"test common_parallel::test_vdpa_block ... ok"
This commit fixes the vdpa_sim_blk test to fail in that case.

tests: test_vdpa_block: fix false positive

---

scripts/run_integration_tests_aarch64.sh

The wget has been causing frequent CI failure for the past few days, while it can't be reproduced manually. Let's show the wget details in our CI pipeline to understand better future errors.

scripts: Show wget details for aarch64 worker

---

net_util/src/open_tap.rs
vmm/src/device_manager.rs

Hi,
this PR fixes an issue with named tap devices. In the current implementation, tap devices with an explicit name cannot be assigned an IP/netmask. The creation of the VM works and the TAP interface is silently created without any ip configuration. This fix will assign the IP address given by the user in the `NetConfig` struct.
Caveat: This might have an impact on existing use-cases as `"tap=customTap,mac=,ip=,mask="` will now set the default IP on that interface as it would on an "unnamed" interface.
Creating a TAP device without an IP configuration seems to therefore become impossible (?) with this change.
I have not found any documentation that this behavior was intentional. I'd find it preferable to make creation of TAP interfaces without an IP explicitly possible (e.g. by not …

vmm: Allow IP configuration on named TAP interfaces

---

.github/workflows/audit.yaml
.github/workflows/build.yaml
.github/workflows/dco.yaml
.github/workflows/docker-image.yaml
.github/workflows/fuzz-build.yaml
.github/workflows/hadolint.yaml
.github/workflows/openapi.yaml
.github/workflows/quality.yaml
.github/workflows/release.yaml
hypervisor/Cargo.toml
vmm/Cargo.toml

Currently Github CI complains about two things:
- There are few inconsistencies in Cargo.toml which is causing warnings while parsing it.
- actions/checkout@v2 is using a deprecated version of nodejs so we should update it.

Fix warning emitted by Github CI

---

vmm/src/igvm/igvm_loader.rs

There is no requirement to call copy_from_slice, since all the member variables are identical and we can directly assign them value.

vmm: igvm: Remove redundant copy_from_slice

---

docs/windows.md

There is missing backslash in the qemu command to launch windows guest.

docs: Add a missing backslash

---

hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs

This patch adds missing new lines after functions, fixes few typos in the comments, adds few missing
comments to SNP related functions.

hypervisor: fix few typos and cosmetic issues

---

arch/src/lib.rs
arch/src/x86_64/mod.rs

This patch defines a new function 'generate_ram_ranges', to generate usable physical memory ranges for the guest based on the existing guest memory managed by VMM. This function is also made public, so that it can be reused, say by the IGVM loader in the future [1].
See: #6020

arch: x86_64: Refactor the way to generate e820 RAM maps

---

test_infra/src/lib.rs
tests/integration.rs

The 'test_vfio_user' is prone to fail when the system is under high workloads with errors:
```
Error while connecting to /var/tmp/spdk.sock
Is SPDK application running?
Error details: Invalid or non-existing address: '/var/tmp/spdk.sock'
```
This is because SPDK is not fully functional before we request to create a nvme device using the vfio_user protocol. This patch stabilize this test with allowing retires to execute host commands.

tests: Stabilize 'test_vfio_user' with retries to run host commands

---

docs/api.md
scripts/check-image-compatibility.sh
scripts/common-aarch64.sh
scripts/create-cloud-init.sh
scripts/dev_cli.sh
scripts/prepare_vdpa.sh
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_rate_limiter.sh
scripts/run_integration_tests_sgx.sh
scripts/run_integration_tests_vfio.sh
scripts/run_integration_tests_windows_aarch64.sh
scripts/run_integration_tests_windows_x86_64.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh
scripts/run_openapi_tests.sh
scripts/run_unit_tests.sh
scripts/test-util.sh

`#!/bin/bash` is not available on all systems, such as [NixOS](https://nixos.org/). Using `#!/usr/bin/env bash` is the most compatible way on all UNIX-like systems.

scripts: more compatible shebangs

---

src/main.rs
vmm/src/igvm/igvm_loader.rs
vmm/src/vm.rs

For SEV-SNP guests we need to provide the extended memory. It follows a very simple layout and very similar to other x86 guests.
First segment: [HIGH_RAM_START - MEM_32BIT_RESERVED_START]
PCI hole: [MEM_32BIT_RESERVED_START - RAM_64BIT_START]
Second segment: [RAM_64BIT_START - RAM_END]
Fixes #5993

vmm: igvm: Generate memory map for SEV-SNP guests

---

resources/Dockerfile
scripts/dev_cli.sh
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_x86_64.sh
tests/integration.rs

Migration attempt has been done few times already in following PRs. https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5072, https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5449, https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5456, https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5487 and dropped due to various reasons. One main reason was failure of the test named `live_migration::live_migration_sequential::test_live_migration_ovs_dpdk` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5532.
After analyzing those PRs I would like to approach this issue step by step.
1. Migrate to Ubuntu 22.04 with minimal changes where all the tests will be passed and CI will be happy.
2. Upgrade SPDK to latest or stable version.
3. Upgrade virtiofsd to …

Migrate docker container from ubuntu 20.04 to 22.04

---

arch/src/x86_64/mod.rs
arch/src/x86_64/mptable.rs
tests/integration.rs
vmm/src/acpi.rs
vmm/src/cpu.rs
vmm/src/vm.rs

This PR addresses a bug in which the cpu topology reported by a guest with non power-of-two number of cores is incorrect. For example, in some contexts, a virtual machine with 2-sockets and 12-cores will report believe that 16 cores are on socket 1 and 8 cores are on socket 2. In other cases, common topology enumeration software such as `hwloc` will crash.
The root of the problem is the way that cloud-hypervisor generates apic_id. On x86_64, the (x2) apic_id embeds information about cpu topology. The `cpuid` instruction is primarily used to discover the number of sockets, dies, cores, threads, etc. Using this information, the (x2) apic_id is masked to determine which {core, die, socket} the cpu belongs to on. When the cpu topology is not a power of two (e.g. a 12-core machine), this …

arch: x86_64: handle npot CPU topology

---

Cargo.lock
docs/io_throttling.md
rate_limiter/Cargo.toml
rate_limiter/src/group.rs
rate_limiter/src/lib.rs
src/main.rs
tests/integration.rs
virtio-devices/src/block.rs
vmm/Cargo.toml
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm_config.rs

this PR adds a 'group rate-limiter' to cloud-hypervisor. This allows cloud-hypervisor to be configured to limit the aggregate bandwidth / ops of all (or a subset) of virtio-blk disks attached to a virtual machine.  This is similar to [qemu throttle groups](https://github.com/qemu/qemu/blob/master/docs/throttle.txt).
It is possible to use cgroups to throttle individual block devices... but there is no good way (outside of native hypervisor support) to throttle groups of block devices. This feature is primarily targeted at network attached storage where bandwidth / iops is a shared resource between disks.
This feature request was discussed a few months ago in [this issue](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5726).
```
--disk path=<path1>,rate_limit_group=group0 \ …
```

rate_limiter: add group rate-limiter

---

docs/intel_tdx.md

Current instructions are incorrect and there is now a new profile called dev-opt to build the debug version of TD-SHIM.

docs: Update instructions to build debug TD-SHIM

---

vmm/src/config.rs
vmm/src/lib.rs

I accidentally ran a VM with CID 2 (VMADDR_CID_HOST), and very strange and difficult to debug behavior ensued.  I don't think a virtio-vsock device should be allowed to have any of the special CIDs (VMADDR_CID_ANY, VMADDR_CID_HYPERVISOR, VMADDR_CID_LOCAL, VMADDR_CID_HOST).

vmm: forbid using special VSOCK CIDs for guests

---

virtio-devices/src/vsock/device.rs
virtio-devices/src/vsock/mod.rs
virtio-devices/src/vsock/unix/muxer.rs
vmm/src/config.rs
vmm/src/vm_config.rs

The [VIRTIO specification][1] says:
> The upper 32 bits of the CID are reserved and zeroed.
We should therefore not allow the user to supply a VSOCK CID with those bits set.  To accomplish this, limit the public API of the virtio-vsock device to only accept 32-bit CIDs, while still using 64-bit CIDs internally since that's how virtio-vsock works.
[1]: https://docs.oasis-open.org/virtio/virtio/v1.2/csd01/virtio-v1.2-csd01.html#x1-4400004

vmm: limit VSOCK CIDs to 32 bits

---

arch/src/aarch64/layout.rs

warning: this URL is not a hyperlink
--> arch/src/aarch64/layout.rs:114:58
|
114 | ...in https://www.kernel.org/doc/Documentation/arm64/booting.txt.
|       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://www.kernel.org/doc/Documentation/arm64/booting.txt.>`
|
= note: bare URLs are not automatically turned into clickable links
= note: `#[warn(rustdoc::bare_urls)]` on by default
I also noticed that it looks like this comment was supposed to be applied to FDT_MAX_SIZE, not FDT_START, so I moved it.

arch: fix rustdoc warning

---

docs/iommu.md

Since 5.3, 5.14 merged x86 support.
By the way, I haven't, like, tried this out or anything, but I noticed the information appears out of date.

Update Kernel pre-requisite information for iommu

---

docs/vhost-user-net-testing.md

Testing instructions are very old and type=dpdkvhostuser is deprecated from DPDK.
logs from /var/log/openvswitch/ovs-vswitchd.log
|netdev_dpdk|WARN|dpdkvhostuser ports are considered deprecated; please migrate to dpdkvhostuserclient ports

Update vhost-user-net-testing instructions

---

.gitignore

This is the default output directory for `cargo vendor`.

gitignore: ignore vendor directory

---

scripts/run_integration_tests_windows_x86_64.sh
scripts/run_integration_tests_x86_64.sh
scripts/test-util.sh

Move the duplicated logic to download OVMF into a helper function. Explicitly specify the OVMF_FW_TAG instead of downloading the latest so that new OVMF versions can be easily tested.

scripts: create download_ovmf helper function

---

option_parser/src/lib.rs
vmm/src/config.rs
vmm/src/cpu.rs
vmm/src/vm_config.rs

On hosts with >256 cpus, setting the vcpu affinity to a host cpu index >255 will return an error.
This commit changes the host_cpu type to a u16 to support setting the vcpu affinity to a host cpu with an index >255.
For example, on a host with 384 cpus, setting the vcpu affinity to host cpu 256 results in the following error:
```
400 : SerdeJsonDeserialize(Error(\"invalid value: integer `256`, expected u8\", line: 1, column: 3397))
```

vmm: support setting cpu affinity with host cpu indices >255

---

fuzz/fuzz_targets/http_api.rs
src/main.rs
vmm/src/config.rs
vmm/src/lib.rs
vmm/src/vm_config.rs

These Default implementations either don't produce valid configs, are no longer used outside of tests, or both.
For the tests, we can define our own local "default" values that make the most sense for the tests, without worrying about what's a (somewhat) sensible "global" default value.

vmm: remove Default impls for config

---

hypervisor/src/cpu.rs
hypervisor/src/mshv/mod.rs
vmm/src/cpu.rs
vmm/src/vm.rs

Set the SEV control register so we know where to start running.  This register configures the SEV feature control state on a virtual processor.

set SEV control register for SEV-Enabled guest

---

devices/src/debug_console.rs
devices/src/lib.rs
docs/debug-port.md
fuzz/fuzz_targets/http_api.rs
src/main.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs
vmm/src/vm_config.rs

This commit adds the debugcon device to CHV. The debugcon device is a very simple device on I/O port 0xe9 supported by QEMU and BOCHS. It is meant for printing information as easy as possible, without any configuration from the guest at all.
The device is configured on the cmdline like this: `--debugcon file=<path>`
It is primarily interesting to OS/kernel developers as they can produce output as soon as the guest starts without any configuration of a serial device or so. Furthermore, a kernel hacker might use this device for information of type B whereas information of type A are printed to the serial device.
This device is not used by default by Linux, Windows, or any other "real" OS. It is for developers.
-- 
More info:
- https://phip1611.de/blog/how-to-use-qemus-debugcon-feature-and-wr …

devices: add debug-console device

---

scripts/dev_cli.sh

Variable cargo is unused, hence remove it.

scripts: dev_cli: remove unused cargo variable

---

hypervisor/src/mshv/mod.rs

Unaccepted GPA is usually thrown by Microsoft hypervisor in case of mismatch between GPA and GVA mappings. Thus, handle that scenario as part of vCPU run loop.

hypervisor: Add support for handling unaccepted GPA

---

scripts/gitlint/rules.py
src/main.rs

Currently kernel and firmware are checked as a payload. IGVM should be checked as well. Otherwise, it hangs indefinitely.

main: Support igvm as a payload

---

block/src/vhdx/vhdx_header.rs

This also fixes the following clippy warning on nightly build from cargo fuzz:
warning: struct `RegionEntry` is never constructed
--> /home/chenb/project/cloud-hypervisor/cloud-hypervisor/block/src/vhdx/vhdx_header.rs:357:8
|
357 | struct RegionEntry {
|        ^^^^^^^^^^^
|
= note: `RegionEntry` has derived impls for the traits `Debug` and `Clone`, but these are intentionally ignored during dead code analysis
= note: `#[warn(dead_code)]` on by default

block: vhdx: Remove unused 'struct RegionEntry'

---

vmm/src/cpu.rs

Traditional way to configure vcpu don't work for sev-snp guests. All the vCPU configuration for SEV-SNP guest is provided via VMSA.

vmm: Don't configure vcpu in case of SEV-SNP

---

fuzz/fuzz_targets/block.rs
tests/integration.rs
virtio-devices/src/block.rs
virtio-devices/src/seccomp_filters.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/vm_config.rs

This PR adds Rest + CLI options to pin virtqueue threads for block devices to specific host cpus. The relevant struct to store this information is included below:
```
pub struct VirtQueueAffinity {
pub queue_index: u16,
pub host_cpus: Vec<usize>,
}
```
The CLI has been updated to include a queue_affinity option to the --desk flag:
```
./cloud-hypervisor \
--kernel ./hypervisor-fw \
--disk path={image_path},num_queues=4,queue_affinity=[0@[1],1@[2],2@[3],3@[4] \
--cpus boot=4 \
--memory size=1024M \
--net "tap=,mac=,ip=,mask="
```
Related issue: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5728

block: Block Device Virtqueue Thread Pinning

---

.github/workflows/shlint.yaml
scripts/check-image-compatibility.sh
scripts/common-aarch64.sh
scripts/create-cloud-init.sh
scripts/dev_cli.sh
scripts/prepare_vdpa.sh
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_rate_limiter.sh
scripts/run_integration_tests_sgx.sh
scripts/run_integration_tests_vfio.sh
scripts/run_integration_tests_windows_aarch64.sh
scripts/run_integration_tests_windows_x86_64.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh
scripts/run_openapi_tests.sh
scripts/run_unit_tests.sh
scripts/test-util.sh

Implement workflow to to run static analysis and linting of all shell scripts by using shfmt and shellcheck.
Also, fix shell scripts according to shfmt and shellcheck errors.
Fixes: #5396

build: add shell script linter workflow

---

hypervisor/src/mshv/mod.rs

IO events are delivered using GHCB protocol so traditional ioeventfs are not required in case of sev-snp VMs.

mshv: Do not register ioevents in case of SEV-SNP enabled guest

---

arch/src/x86_64/mod.rs
vmm/src/igvm/igvm_loader.rs

The 'generate_ram_ranges' function currently hardcodes the assumption that there are only 2 E820 RAM entries. This is not flexible enough to handle vendor specific (AMD) memory holes. Returning a Vec is also more convenient for users of this function.
Refactor this method to return a Vec instead of a 2-tuple to relax this assumption.

arch: x86_64: allow more than 2 E820_RAM ranges.

---

pci/src/vfio.rs

According to PCIe specification, a 64-bit MMIO BAR should be naturally aligned. In addition to being more compliant with the specification, natural aligned BARs are mapped with the largest possible page size by the host iommu driver, which should speed up boot time and reduce IOTLB thrashing for PCIe P2P traffic on virtual machines with VFIO devices.
Props to @acarp-crusoe for finding this.

pci: vfio: naturally align bar

---

vmm/src/vm.rs

In case of SEV-SNP guest devices use sw-iotlb to gain access guest memory for DMA. For that F_IOMMU/F_ACCESS_PLATFORM must be exposed in the feature set of virtio devices.

vmm: Force enable IOMMU incase of SEV-SNP guest

---

virtio-devices/src/transport/pci_device.rs

For SevSnp guest IO events are handled by GHCB protocol. While we get the notification we have to notify via eventfd.

virtio-devices: handle IO event for SevSnp properly

---

README.md
arch/src/lib.rs
arch/src/x86_64/mod.rs
arch/src/x86_64/regs.rs
scripts/test-util.sh
tests/integration.rs
vmm/src/cpu.rs
vmm/src/vm.rs

Fixes: #5766 
This feature was [previously removed](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2569) in favor of just supporting uncompressed PVH ELF binaries for simplicity. However, direct bzImage support has a couple benefits that would be nice.
* No need to keep uncompressed images around
* Ability to use the distro provided kernel from `/boot` directly
By using the [regular 32 bit entry point](https://docs.kernel.org/arch/x86/boot.html#bit-boot-protocol), the necessary code changes are rather small. Most of the machine setup can be shared with the PVH setup. We just need to provide the zero page and point to it in the initial register state. The boot variant is auto-detected with no further switches needed. I opted to just use the availability of the `setup_header` as …

Bring back bzImage direct kernel boot support for x86_64

---

src/main.rs
vmm/src/sigwinch_listener.rs

When a guest running on a terminal reboots, the `sigwinch_listener` subprocess exits and a new one restarts. The parent never wait()s for children, so the old subprocess remains as a zombie. With further reboots, more and more zombies build up.
As there are no other children whose exit status we want, the easiest fix is to take advantage of the implicit reaping specified by POSIX when we set the disposition of `SIGCHLD` to `SIG_IGN`.
For this to work, we also need to set the correct default exit signal of `SIGCHLD` when using `clone3() CLONE_CLEAR_SIGHAND`. Unlike the fallback `fork()` path, `clone_args::default()` initialises the exit signal to zero, which results in a child with non-standard reaping behaviour.

vmm: Avoid zombie sigwinch_listener processes

---

hypervisor/src/mshv/mod.rs

Since we don't register ioevents in case of SEV-SNP guests. Thus, we should not unregister it as well.

hypervisor: mshv: Don't unregister ioevent in case of SEV-SNP guest

---

vmm/src/seccomp_filters.rs

There are new IOCTLs added for SevSnp guest support. This patch adds necessary seccomp ruled.

vmm: Add seccomp rules for MSHV SevSnp guest

---

src/main.rs
vmm/src/config.rs
vmm/src/igvm/igvm_loader.rs
vmm/src/lib.rs
vmm/src/vm.rs
vmm/src/vm_config.rs

The host data provided at launch. Data is passed to the hypervisor during the completion of the
isolated import. Host Data provided by the hypervisor during guest launch.
The firmware includes this value in all attestation reports for the guest.

vmm: pass host data to SevSnp guest

---

src/bin/ch-remote.rs
src/main.rs
vhost_user_block/src/main.rs
vhost_user_net/src/main.rs

ch-remote crashes when run with `--api-socket` but no subcommand:
```
$ target/release/ch-remote --api-socket /tmp/api
thread 'main' panicked at src/bin/ch-remote.rs:509:14:
internal error: entered unreachable code
```
Use `clap::Command::subcommand_required(true)` to yield a more friendly error in this case.

ch-remote: Fix crash when run with no subcommand

---

.github/workflows/audit.yaml
.github/workflows/build.yaml
.github/workflows/dco.yaml
.github/workflows/docker-image.yaml
.github/workflows/fuzz-build.yaml
.github/workflows/gitlint.yaml
.github/workflows/hadolint.yaml
.github/workflows/integration-arm64.yaml
.github/workflows/integration-sgx.yaml
.github/workflows/integration-vfio.yaml
.github/workflows/integration-windows.yaml
.github/workflows/integration-x86-64.yaml
.github/workflows/openapi.yaml
.github/workflows/quality.yaml
.github/workflows/release.yaml
.github/workflows/shlint.yaml

Move some jobs to the merge queue only: Windows guest + AMD x86-64 + musl. Unfortunately there is no way to have different status checks for PR and merge queue - so add dummy jobs to "pass" on the jobs that should be skipped because they are only  running on the merge queue.
This requires an extra sprinkling of conditions but this means that we can enforce Window Guest tests on merges as that job cannot be run from forks.

build: Use merge queue for some integration tests

---

docs/custom-image.md
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_rate_limiter.sh
scripts/run_integration_tests_sgx.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh

focal-server-cloudimg-amd64-custom-20210609-0.qcow2
jammy-server-cloudimg-amd64-custom-20230119-0.raw
focal-server-cloudimg-arm64-custom-20210929-0.qcow2
jammy-server-cloudimg-arm64-custom-20220329-0.qcow2
focal-server-cloudimg-arm64-custom-20210929-0.raw
jammy-server-cloudimg-arm64-custom-20220329-0.raw
jammy-server-cloudimg-amd64-custom-20230119-0.qcow2
These are the only images copied to new storage location which I found in the scripts. Please let me know if there are any other images which is required for publicly accessible.

Update Azure storage location to access images

---

pci/src/vfio.rs
pci/src/vfio_user.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/vm_config.rs

On platforms where PCIe P2P is supported, inject a PCI capability into NVIDIA GPU to indicate support.
A [previous PR](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6175) added support for PCIe P2P between VFIO devices. The NVIDIA driver does not utilize PCIe P2P unless it detects hardware support. The PCIe specification doesn't require platforms to support PCIe P2P traffic between root ports (although many systems do). Within a virtual machine, information about the host PCIe bridge is lost, so NVIDIA recommends the use of an injected PCI capability to signal support for PCIe P2P between GPUs.
This PR adds a new argument `x_nv_gpudirect_clique` to VFIO devices `--device path=<PCI_DEVICE_PATH>,x_nv_gpudirect_clique=<CLIQUE_ID>` that injects a PCI capability indicating the "P2P …

vmm: add NVIDIA GPUDirect P2P support.

---

scripts/dev_cli.sh

Because of double quotes the current value is passed as a single argument with a space in it to cargo. This commit changes it to an array so each element is passed as a different arguments.

scripts: Change features_build variable type to array

---

src/main.rs
vmm/src/api/http/mod.rs
vmm/src/lib.rs
vmm/src/seccomp_filters.rs

This commit ensures that the HttpApi thread flushes all the responses before the application shuts down. Without this step, in case of a VmmShutdown request the application might terminate before the thread sends a response.
Fixes: #6247

vmm: http: graceful shutdown of the http api thread

---

.github/workflows/integration-windows.yaml
.github/workflows/integration-x86-64.yaml
tests/integration.rs

The x86 intel worker on glibc build now takes around 30 mins on a 16 cores VM while it was around 21 mins when using a 64 cores VM. By reducing the size of VMs to run a single worker, we are able to run more workers in parallel with the same vCPU quota from Azure.

build: Run integration tests on smaller VMs

---

vmm/src/api/openapi/cloud-hypervisor.yaml

The DiskConfig `queue_affinity` config is incorrectly specified as `affinity` in the OpenAPI yaml.

vmm: fix openapi queue_affinity config

---

hypervisor/src/cpu.rs
hypervisor/src/mshv/mod.rs
vmm/src/seccomp_filters.rs

Currently, we only support injecting NMI for KVM guests but we can do the same for MSHV guests as well to have feature parity.
I actually tested manually for a MSVH guest and here is a sample backtrace which I obtained in the process:
```
[  OK  ] Finished Update UTMP about System Runlevel Changes.
[    4.178592] Uhhuh. NMI received for unknown reason 20 on CPU 0.
[    4.178595] Kernel panic - not syncing: NMI: Not continuing
[    4.178596] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 6.1.58.mshv1 #1
[    4.178598] Hardware name: Cloud Hypervisor cloud-hypervisor, BIOS 0
[    4.178598] Call Trace:
[    4.178610]  <NMI>
[    4.178611]  dump_stack_lvl+0x3b/0x59
[    4.178615]  panic+0xfb/0x274
[    4.178617]  ? _printk+0x53/0x6e
[    4.178619]  nmi_panic.cold+0xc/0xc
[    4.178620] …
```

vmm: hypervisor: Add support for injecting NMI for MSHV guest

---

.github/workflows/audit.yaml

actions-rs/audit-check is unmaintained, hence replace it with actions-rust-lang/audit
See: #5929

build: replace actions-rs/audit-check with actions-rust-lang/audit

---

hypervisor/src/mshv/mod.rs

Current version can't boot a SNP guest while using more than one VCPU. It turns out that there is an
issue in the Snp AP creation process. We should be writing to Software exitinfo1 instead of exitinfo2. This patch fixes the issue and now we can boot multi vcpu SNP guest.

hypervisor: Fix boot failure on SNP guest

---

vmm/src/device_manager.rs

A deadlock can happen from the destination VM of live upgrade or migration due to waiting on paused device worker threads. For example, when a serialization error happens after the `DeviceManager` struct is restored (where all virtio device worker threads are spawned but in paused/parked state), a deadlock will happen from
`DeviceManager::drop()`, as it blocks for waiting worker threads to join.
This patch ensures that we wake up all device (mostly virtio) worker threads before we block for them to join.

vmm: Avoid deadlock from waiting on paused device worker threads

---

hypervisor/src/mshv/mod.rs

MSR and CPUID are limited to x86 architecture so, reduce the visbility of these two members inside struct MshvVcpu to just x86 architecture.

hypervisor: mshv: Restrict MSR and CPUID visbility for MshvVcpu to x86

---

hypervisor/src/lib.rs
hypervisor/src/mshv/mod.rs

Currently there are bunch of VMExits which can only happen for x86 guests so guard them with x86_64 feature flag. This will help in future when we add support for aarch64 guests on MSHV.

hypervisor: mshv: Guard x86 features under x86_64 feature flag

---

virtio-devices/src/iommu.rs

According to the virtio iommu spec (section 5.13.6.6), all mappings within the entire range from virt_start to virt_end in an unmap request must be removed. This change adds this functionality, iterating through all mappings that fall within an unmap request for that domain and removing them.

virtio-devices: Removing all mappings found in an unmap request

---

virtio-devices/src/transport/pci_device.rs

When restoring a VM, the VirtioPciCfgCapInfo struct is not properly initialized. All fields are 0, including the offset where the capabibility should start. Hence, when you read a PCI configuration register in the range [0..length(VirtioPciCfgCap)] you get the value 0 instead of the actual register contents.
Linux rescans the whole PCI bus when adding a new device. It reads the values vendor_id and device_id for every device. Because these are stored at offset 0 in pci configuration space, their value is 0 for existing devices. As such, Linux considers that the devices have been unplugged and it removes them from the system.
Fixes: #6265

virtio-devices: save pci configuration capability state in snapshot

---

block/src/vhdx/vhdx_header.rs
virtio-devices/src/vsock/csm/mod.rs

- virtio-devices: vsock: csm: Use thiserror to provide error messages
- block: vhdx: "signature" field is unused

Fix cargo fuzz (nightly) compiler warnings

---

vmm/src/lib.rs
vmm/src/vm.rs

See https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6274.
There is already an event for shutdown. There is no event for reboot.
@alexellis can you please check if this meets your need?

vmm: add an event for VM reboot

---

vmm/src/vm_config.rs

The 'NetConfig' may contain FDs which can't be serialized correctly, as FDs can only be donated from another process via a Unix domain socket with `SCM_RIGHTS`. To avoid false use of the serialized FDs, this patch explicitly set 'NetConfig' FDs as invalid for (de)serialization.
See: #6286

vmm: Explicitly set NetConfig FDs as invalid for (de)serialization

---

Cargo.lock
hypervisor/src/mshv/mod.rs
vmm/src/seccomp_filters.rs

Update mshv IOCTL numbers which have changed, and add a new seccomp rule for generic hvcall IOCTL.
Update mshv commit hash in Cargo.lock so the correct new get/set VP state IOCTLs are used.

Update mshv crate commit and IOCTL numbers

---

vmm/src/memory_manager.rs

The memory region that is associated with the hotpluggable part of a virtio-mem zone isn't backed by the file specified in the MemoryZoneConfig. The file is used only for the fixed part of the zone. When you try to restore a snapshot with virtio-mem, the backing file is used for all its regions. This results in the following error:
VmRestore(MemoryManager(GuestMemoryRegion(MappingPastEof)))
This patch sets backing_file only for the fixed part of a virtio-mem zone.
Fixes: #6337

vmm: memory_manager: don't set backing_file for virtio_mem regions

---

virtio-devices/src/iommu.rs

Properly detach a device from a domain if that device is already attached to another domain on an attach request (following section 5.13.6.3.2 of the virtio-iommu spec) - resolves nested virtualization reboot

virtio-device: Detaching endpoint from old domain in virtio-iommu

---

virtio-devices/src/vhost_user/fs.rs
vmm/src/config.rs

vmm: validate virtio-fs tag length

---

vmm/src/api/openapi/cloud-hypervisor.yaml

Hello, if i'm not wrong, the pvpanic boolean is missing in the api specification on the VmConfig model.

openapi: add  missing pvpanic property to VmConfig

---

.github/workflows/release.yaml

Replace actions: actions-rs/toolchain, upload-release-asset.
actions-rs/toolchain is unmaintained, for cross-compilation replace it
with houseabsolute/actions-rust-cross
Action upload-release-asset is unmaintained and has been archived since
Mar 4, 2021. An issue with upload-release-asset is that it creates
separate release for each job of matrix strategy. Thus, to solve these
issues, replace unmaintained upload-release-asset with upload-artifact
See: #5929

build: release: replace unmaintained actions actions-rs/toolchain, upload-release-asset.

---

docs/vfio.md
fuzz/fuzz_targets/http_api.rs
src/main.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm_config.rs

When using multiple PCI segments, the 32-bit and 64-bit mmio aperture is split equally between each segment. Add an option to configure the 'weight'. For example, a PCI segment with a `mmio32_aperture_weight` of 2 will be allocated twice as much 32-bit mmio space as a normal PCI segment.
I considered adding a `mmio32_aperture_size` config instead of `mmio32_aperture_weight` config to precisely configure the size of the mmio apertures for each segment. I chose to not implement this because the logic to implement that correctly was a lot more complicated. Also, allocating mmio space between PCI segments does not actually require that level of precision.
Unfortunately, some devices actually use quite a bit of 32-bit MMIO space. For example, a NVIDIA NVSwitch device uses 32 MB of 32-bit mmio. …

vmm: add pci_segment mmio aperture configs

---

hypervisor/src/cpu.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/mshv/x86_64/mod.rs

On Microsoft Hypervisor, we need to save/restore five VP state components which are as follows:
1. Local APIC
2. Xsave
3. Synthetic Message Page
4. Synthetic Event Flags Page
5. Synthetic Timers
In the MSHV crate we created a single struct for all the components and API to get/set the states.

hypervisor: rework VP state components

---

net_util/Cargo.toml

Import derive feature since `net_util` uses macro `Serialize` and `Deserialize`.
Fixes: #6421

net_util: import derive feature for serde

---

tests/integration.rs

Improve test_snapshot_restore test to reduce transient issues.
* tests: Reduce Guest memory in _test_snapshot_restore
* tests: clean up snapshot dir after restore

tests: cleanup snapshot dir and reduce default guest memory

---

vmm/src/api/openapi/cloud-hypervisor.yaml

This is to resolve the inconsistencies from our openapi specification, as default values do not make sense for required fields.
Reported-by: James O. D. Hunt <james.o.hunt@intel.com>

vmm: openapi: Do not provide default values for required fields

---

src/bin/ch-remote.rs

remove-device can remove not only VFIO device but also pci device.

ch-remote: fix help of remove-device

---

hypervisor/src/mshv/mod.rs

Certain VMEXITs can only happen for x86 guests, thus reduce the scope to x86_64 at the compilation stage.

hypervisor: mshv: Reduce the scope of VMEXITs to x86_64

---

src/bin/ch-remote.rs
vmm/src/api/dbus/mod.rs

Fixes deprecation related warnings introduced in #6400.

vmm: ch-remote: replace deprecated zbus macros with new equivalents

---

Cargo.lock
hypervisor/Cargo.toml
vmm/Cargo.toml

And bump vfio commit in Cargo.lock to align, since it should also point to mshv v0.2.0.

mshv: Pin mshv crates to release tag v0.2.0

---

Cargo.lock
api_client/Cargo.toml
api_client/src/lib.rs
arch/src/aarch64/fdt.rs
arch/src/aarch64/mod.rs
arch/src/aarch64/uefi.rs
arch/src/x86_64/mod.rs
arch/src/x86_64/mptable.rs
arch/src/x86_64/regs.rs
arch/src/x86_64/smbios.rs
block/src/qcow/mod.rs
block/src/qcow/refcount.rs
devices/src/interrupt_controller.rs
devices/src/legacy/gpio_pl061.rs
devices/src/legacy/rtc_pl031.rs
devices/src/legacy/uart_pl011.rs
hypervisor/src/arch/aarch64/gic.rs

Apologies for the delay, but I've made the suggested changes as mentioned in a previous pull request (See #6376).
I've added just a few of the commits here to make it easier for review, let me know if you see any changes need to be made.
See #1910

Use thiserror for better error handling

---

fuzz/Cargo.lock
fuzz/Cargo.toml

The cloud-hypervisor package does not have a lib target, so it is invalid. Cargo just ignores that line.
Dropping it removes a warning.

build: drop an invalid dependency in fuzz

---

hypervisor/src/mshv/mod.rs

Populating these cpuid with default values so that CLH can patch with topology information. Otherwise it gets skipped while setting some topology information.

hypervisor: mshv: fix topology for Intel HW on MSHV

---

vmm/src/cpu.rs

Currently by default each core is allocated it's own socket. Basically
it is n socket 1 core 1 thread/core kind of a structure as witnessed
from within the guest.
```
CPU(s):                             8
On-line CPU(s) list:                0-7
Thread(s) per core:                 1
Core(s) per socket:                 1
Socket(s):                          8
NUMA node(s):                       1
```
This is not a good default topology because resources are distributed
across multiple sockets. For example, a Linux guest with multi socket
configuration will have to calibrate TSC per socket due to which it
might observe a higher amount of boot time than usual.
A better idea for default topology would be 1 socket n core 1
thread/core which ensure better resource locality.
After this change …

arch: Change the default topology for x86 guests

---

Cargo.toml

Since CloudHypervisor also supports running on top of Microsoft Hypervisor (MSHV).

misc: Update description in Cargo.toml to include MSHV

---

arch/src/x86_64/mod.rs

If the KVM version is older than v6.6, `KVM_GET_SUPPORTED_CPUID` will omit the L1 cache information reported by  CPUID function `0x8000_0005` on amd64 machines. We should fall back to the host L1 cache information if it is omitted because the KVM version is older than [this commit](https://github.com/torvalds/linux/commit/af8e2ccfa6f101f505add076c1a4d56c718e0d50).
This PR is analogous to [this merged PR](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4920) merged which added the equivalent behavior for the L2 cache information reported by CPUID function `0x8000_0006` in case it was omitted because the KVM version is older than [this commit](https://github.com/torvalds/linux/commit/43d05de2bee7561b7958628b7c27c89b779de990).

arch: x86_64: fall back to host cpuid l1 cache info if omitted by kvm

---

virtio-devices/src/vdpa.rs

Since vdpa device does not support pause/resume [1], it does not make
sense to restore on paused state.
[1] https://github.com/cloud-hypervisor/cloud-hypervisor/commit/099cdd2af88ac6a8ede490e73ff0eb58a812bde2

virtio-devices: vdpa: Not error out on resume if not paused and not restore on paused state

---

test_infra/src/lib.rs
tests/integration.rs

tests: send SIGTERM to kill GuestCommand
Killing CLH by SIGKILL will cause inaccurate code coverage information. This patch changes the signal to SIGTERM. 
Fixes: #6507

tests: send SIGTERM to kill GuestCommand

---

Cargo.toml

[cargo-cyclonedx](https://github.com/CycloneDX/cyclonedx-rust-cargo) rejects the current license key in Cargo.toml, because it doesn't comply with the SPDX standard:
```
Package cloud-hypervisor has an invalid license expression (LICENSE-APACHE & LICENSE-BSD-3-Clause), using as named license: Invalid Lax SPDX expression: unknown term
```
Fix by using the names from the SPDX list: https://spdx.github.io/license-list-data/

build: Fix license string to comply with SPDX list

---

hypervisor/src/arch/x86/emulator/mod.rs

Patches to clean things up, and remove an unwanted restriction that the input stream has to be non-empty.

Improvements to x86 instruction emulator

---

virtio-devices/src/console.rs

`TIOCGWINSZ` modifies its argument, so it needs to mutably borrow it. Unfortunately, `ioctl()`'s signature is not able to enforce this, and the write happens in the kernel, so I don't think anything like miri, valgrind, UBSan, etc. would have been able to catch this.
The UB passing an immutable reference caused resulted, for me, in `get_win_size()` returning `(0, 0)` since LLVM commit
https://github.com/llvm/llvm-project/commit/9a09c737a052dc0e2b8c15a969d16cff7ea0c133 ("[BasicAA] Make isNotCapturedBeforeOrAt() check for calls more precise ([#69931](https://github.com/llvm/llvm-project/pull/69931))").
I've had a look through the other `ioctl()` calls in Cloud Hypervisor, and I don't think any others have the same problem.

virtio-devices: fix UB getting tty size

---

hypervisor/src/arch/x86/emulator/mod.rs
hypervisor/src/mshv/mod.rs

We have a new use case coming soon. It requires Cloud Hypervisor to handle a new intercept. This new intercept exposed some shortcomings in MSHV's instruction emulation.

MSHV: handle GPA intercepts

---

hypervisor/src/arch/emulator/mod.rs
hypervisor/src/arch/x86/emulator/mod.rs
hypervisor/src/mshv/mod.rs

Our testing reveals some issues. Remove the broken assumption in code.

Allow specifying translation flags in MSHV's x86 instruction emulator

---

block/src/lib.rs
vhost_user_block/src/lib.rs
virtio-devices/src/block.rs

As per VirtIO spec 1.2 section 5.2.6, the `status` field is a byte, not u32. cloud-hypervisor writes an `u32` to guest memory, which accidentally zeros out the following 3 bytes, and may corrupt guest OS internal state.

block: fix `status` value size

---

arch/Cargo.toml
arch/src/x86_64/mod.rs
vmm/Cargo.toml

HV APIC (i.e., synthetic APIC controller exposed by Microsoft Hypervisor) does not support one-shot operation using a TSC deadline value. Due to which we see the following backtrace inside the guest when running with hypervisor-fw/OVMF:
[    0.560765] unchecked MSR access error: WRMSR to 0x832 (tried to write 0x00000000000400ec) at rIP: 0xffffffff8f473594 (native_write_msr+0x4/0x30)
[    0.560765] Call Trace:
[    0.560765]  ? native_apic_msr_write+0x2b/0x30
[    0.560765]  __setup_APIC_LVTT+0xbc/0xe0
[    0.560765]  lapic_timer_set_oneshot+0x27/0x30
[    0.560765]  clockevents_switch_state+0xaf/0xf0
[    0.560765]  tick_setup_periodic+0x47/0x90
[    0.560765]  tick_setup_device.isra.0+0x7c/0x110
[    0.560765]  tick_check_new_device+0xce/0xf0
[    0.560765] …

arch: x86_64: Don't expose TSC deadline timer for MSHV guests

---

virtio-devices/src/block.rs

Support event idx feature for virtio-blk device.
This feature could improve disk IO performance by suppressing notifications from guest to host and interrupts from host to guest, which has been already supported in virtio-net and vhost-user devices.
To achieve this, virtqueue's event-idx-related API is leveraged for avail_event field update and needs_notification check.
Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6580

virtio-devices: support event idx for virtio-blk

---

block/src/lib.rs
devices/src/legacy/serial.rs
devices/src/legacy/uart_pl011.rs
option_parser/src/lib.rs
performance-metrics/src/performance_tests.rs
virtio-devices/src/iommu.rs
vmm/src/lib.rs

`inspect_err` was recently stabilized in 1.76, but MSRV is already 1.77 for us, so it is fine to use that.

Fix issues reported by beta clippy

---

docs/performance_metrics.md
performance-metrics/src/main.rs
performance-metrics/src/performance_tests.rs

performance-metrics: add restore latency performance metric
This patch calculates the recovery latency from the start of recovery program to the end of restore.

performance-metrics: add restore latency performance metric

---

docs/landlock.md
fuzz/fuzz_targets/http_api.rs
src/main.rs
tests/integration.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/lib.rs
vmm/src/vm_config.rs

As discussed in #6617, moving landlock config to VMConfig.
Fixes #6617

Move Landlock config to VMConfig

---

virtio-devices/src/seccomp_filters.rs

This fixes the vsock::device::tests::test_virtio_device with Rust 1.80.0 or later, where this check was introduced.

virtio-devices: allow vsock to call fcntl in debug

---

hypervisor/src/mshv/mod.rs

CVM guests can configure GHCB page multiple times during it's lifetime depending on it's requirement. For example a Linux CVM guest configures a different GHCB page during compressed kernel boot and sets up a new one after decompressing the kernel. As a cleanup step, VMM should unset the previous GHCB page before registering a new one for a particular vcpu thread.

hypervisor: mshv: Disable previous GHCB page before setting new one

---

hypervisor/src/mshv/mod.rs
vmm/src/seccomp_filters.rs

Use the IOCTL numbers directly from mshv-ioctls instead of hardcoding them in the seccomp filters.
Remove seccomp rules for unused ioctls:
MSHV_GET_VERSION_INFO,
MSHV_ASSERT_INTERRUPT.

vmm: Replace hardcoded mshv IOCTL numbers in seccomp

---

pci/src/msix.rs

The index is derived from the access offset, so it is controlled by the guest. Check it before accessing internal data structures.
Since Rust enforces strict bound check even in release builds, the VMM process will crash if the guest misbehaves. There is no security issue since the guest can only DoS itself.

pci: validate index before accessing MSI-X arrays

---

Cargo.lock
arch/src/x86_64/regs.rs
hypervisor/Cargo.toml
hypervisor/src/arch/x86/emulator/mod.rs
hypervisor/src/arch/x86/mod.rs
hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
hypervisor/src/lib.rs
hypervisor/src/mshv/mod.rs
hypervisor/src/mshv/x86_64/mod.rs
vmm/src/cpu.rs
vmm/src/vm.rs

As discussed with @likebreath in #6361, this PR tries to remove redefinition of StandardRegisters in CloudHypervisor for x86 side of the world. Next step would be to do the same ARM64.

hypervisor: Remove redefinition of StandardRegisters instead directly use the definition from bindings crate

---

Cargo.lock
block/Cargo.toml
block/src/lib.rs
fuzz/Cargo.toml
net_util/Cargo.toml
net_util/src/queue_pair.rs
vhost_user_block/Cargo.toml
vhost_user_block/src/lib.rs
vhost_user_net/Cargo.toml
vhost_user_net/src/lib.rs
virtio-devices/Cargo.toml
vm-virtio/Cargo.toml
vmm/Cargo.toml

The current Cloud Hypervisor LTS version is incompatible with virtiofsd versions after 1.11.0. See #6673 for details.
The fix came with https://github.com/rust-vmm/vhost/pull/243 (🙏 @alyssais) and was consumed here with #6430. But the fix was never backported, so the LTS is still b0rken.
This PR backports https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6430 to fix the incompatibility. There were some conflicts in the Cargo.toml files, but nothing major. The integration tests pass for me (except `common_parallel::test_vdpa_block` which I can't get working yet before or after these changes).
I've manually tested this against virtiofsd 1.10.1 and 1.11.1.
@rbradford I'm not quite sure what the process is for proposing changes for the LTS branch, so please advise, if I'm doing …

[LTS v37.x] Fix Compatibility with virtiofsd >=1.11.0

---

hypervisor/src/mshv/mod.rs

swei2_rw_gpa_arg.data is an array of size 16 and value.to_le_bytes() is only 8 bytes.

snp: fix panic when rejecting extended guest report

---

hypervisor/src/mshv/mod.rs

Implement get_guest_debug_hw_bps() for mshv and simply return 0 for now. This unblocks the usage of the crashdump feature with mshv. If left unimplemented, Cloud Hypervisor built with mshv and guest_debug features crashes immediately upon start due to the unimplemented!() macro.

hypervisor: mshv: implement get_guest_debug_hw_bps

---

virtio-devices/src/seccomp_filters.rs
vmm/src/seccomp_filters.rs

This fixes a issue of running vm compiled in debug with Rust 1.80.0 or later, where this check was introduced.
Fix: #6694

vmm: allow to call fcntl in debug

---

Cargo.lock
virtio-devices/Cargo.toml
virtio-devices/src/seccomp_filters.rs

With commit 1e967697c ("vmm: pass AccessPlatform implementation for SEV-SNP guest"), we started performing one additional ioctl to gain access to the guest memory before accessing those regions inside virtio-device emulation code path. This additional ioctl is not part of the current seccomp filter, which is causing the SevSnp guest to crash in this scenario with seccomp violation.
Fixes: 1e967697c ("vmm: pass AccessPlatform implementation for SEV-SNP guest")

virtio-devices: Fix seccomp rules for SevSnp guest

---

hypervisor/src/cpu.rs
hypervisor/src/kvm/aarch64/mod.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/lib.rs
vmm/src/cpu.rs

This is along the lines of #6629, in the previous PR the major focus was on x86. This PR tries to do the same thing but for ARM64 side of the world. Basically remove the redefinition of StandaradRegisters and define a union structure which entails all possible hypervisor implementations.

hypervisor: aarch64: Remove redefinition of StandardRegisters

---

hypervisor/src/mshv/mod.rs
hypervisor/src/mshv/snp_constants.rs

Previously we didn't handle extended guest requests at all and always returned an error. This lead to issues with some guests that expected extended requests to succeed. Instead, handle extended requests like normal requests and write zeros to the extended area to signal to the guest that we don't want to supply any additional certificate data.

hypervisor: mshv: implement extended guest requests with empty certs

---

vmm/src/console_devices.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs

`DeviceManager::add_virtio_console_device` used to create the console resize pipe and assign it to `self.console_resize_pipe`, but when this was changed to use console_info, that was deleted without replacement. This meant that, even though the console resize pipe was created by `pre_create_console_devices`, the `DeviceManager` never found out about it, so console resize didn't work (at least for pty consoles).
To fix this, the console resize pipe needs to be passed to the `Vm` initializer, which is already supported, it was just previously not used for new VMs.
Since `DeviceManager` already stores the console resize pipe in an `Arc`, and `Vmm` also needs a copy of it, the sensible thing to do is change `DeviceManager::new` to take `Arc`, and then we don't need to dup the file descriptor, …

vmm: fix console resizing

---

fuzz/fuzz_targets/qcow.rs

Imports were not sorted lexicographically, thus causing rustfmt warning.

fuzz: Fix rustfmt warning

---

hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs
vmm/src/cpu.rs
vmm/src/seccomp_filters.rs

This change then adds the first --cpus features option sve that when passed will enable SVE usage for guests (needs a 5.2+ kernel) or exits with failure.
Fix: #6678

arm64: Add support for enabling SVE in vm guests

---

vmm/src/seccomp_filters.rs

... in case of guest running on Microsoft Hypervisor.

vmm: Fix seccomp violation while injecting NMI

---

arch/src/x86_64/mod.rs
hypervisor/src/kvm/aarch64/mod.rs
pci/src/configuration.rs
rate_limiter/src/group.rs
virtio-devices/src/device.rs
virtio-devices/src/lib.rs
virtio-devices/src/vsock/mod.rs
vm-device/src/dma_mapping/mod.rs
vm-migration/src/lib.rs
vmm/src/cpu.rs

An example warning output is:
error: first doc comment paragraph is too long
--> virtio-devices/src/lib.rs:158:1
|
158 | / /// Convert an absolute address into an address space (GuestMemory) 159 | | /// to a host pointer and verify that the provided size define a valid 160 | | /// range within a single memory region.
161 | | /// Return None if it is out of bounds or if addr+size overlaps a single region.
| |_
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#too_long_first_doc_paragraph
= note: `-D clippy::too-long-first-doc-paragraph` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::too_long_first_doc_paragraph)]`

misc: Fix various warnings from clippy 0.1.82

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_rate_limiter.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_metrics.sh
scripts/test-util.sh

The Linux kernel fork repository for Cloud Hypervisor now produces
prebuilt x86-64 and aarch64 binaries. Speed up the CI by using those
binaries.

build: Use binary kernel artifacts

---

Cargo.lock
fuzz/Cargo.lock
hypervisor/Cargo.toml

Particularly update kvm-bindings, kvm-ioctls, vfio-bindings, and vfio-ioctls.

build: Update rust-vmm dependencies

---

api_client/src/lib.rs

Otherwise, you just see output like "Error running command: Server responded with an error: InternalServerError", which isn't very helpful.  The response body used to be include with the message, but was removed when the Error enum was converted to thiserror.
Fixes: 5d0d56f5 ("api_client: Use thiserror for errors")

api_client: show response body in ServerResponse

---

virtio-devices/src/mem.rs
vmm/src/memory_manager.rs

Bound checks for virtio-mem and ACPI memory hotplug are off by one and two, respectively. This prevents users to fully use the reserved memory hotplug size.
For ACPI, if we specific `--memory size=2G,hotplug_size=4G` and run `ch-remote resize --memory 6G`, cloud-hypervisor will report the following error because of the incorrect bound check:
`<vmm> ERROR:vmm/src/lib.rs:1631 -- Error when resizing VM: MemoryManager(InsufficientHotplugRam)`
Similarly, for virtio-mem, cloud-hypervisor will fail the incorrect bound check and abort the resize. The VM will see the following error in dmesg:
`virtio_mem virtio3: unknown error, marking device broken: -22`
This patch has fixed both bound checks and ensure that users can hot add memory up to the reserved hotplug size.
Signed-off-by: Yuhong Zhong …

vmm: memory_manager: Fix bound checks for memory hotplug

---

tests/integration.rs

The rate-limiter worker now is running on Azure VMs whose performance are more prone to be fluctuate, particularly on block performances. This commit relaxes the limit check for group rate limiter tests to make them less flaky.

tests: Relax rate limit check for group rate limiter

---

hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs

The error message of `SetRegister` and `GetRegister` fail to describe the reason as the error variant suggests. Fixed error message accordingly.

hypervisor: cpu: Fix get/set one reg error message

---

Cargo.lock
hypervisor/Cargo.toml
hypervisor/src/lib.rs
hypervisor/src/mshv/mod.rs
virtio-devices/Cargo.toml
vmm/Cargo.toml
vmm/src/seccomp_filters.rs

Several kernel (and mshv crate) interfaces have been reworked. Update these, and bump the mshv and vfio crates to match.
~Before this PR can be merged, upstream vfio needs to point to mshv v0.3.0 as well (https://github.com/rust-vmm/vfio/pull/56), and I'll update the commit in this PR to bump vfio.~ done.
Now vfio is pointing to the right mshv version, this PR still depends on https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6659 for the KVM ioctls/bindings
This is an update of a previous closed PR: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6428

Update reworked MSHV hypervisor interfaces

---

virtio-devices/src/vhost_user/fs.rs

Complete the removal of the DAX support by removing the use of
non-standard messages. These messages have since been removed from the
vhost_user crate (rust-vmm/vhost#246) and so need to be removed from our
implementation since that would otherwise block updating to a newer
version of the crate.
The ability to enable DAX support in Cloud Hypervisor has been disabled
some time ago but this code was residual with no way to enable it.

virtio-devices: vhost_user: Remove unused backend support from virtio-fs

---

vmm/src/serial_manager.rs

I've moved this so that it's just after the enum definition, which will hopefully make it less easy to miss if events are added/removed again in future.
Fixes: 6d1077fc ("vmm: Unix socket backend for serial port")

vmm: update serial manager epoll events size

---

vmm/src/device_manager.rs

Fixes: 38a1b457 ("vmm: use the SIGWINCH listener for TTYs too")

vmm: remove unused DeviceManager::console method

---

vmm/src/device_manager.rs

The assignment of console_resize_pipe in the TTY case seems to have been accidentally deleted.  I've put it back, but since this is adding code, I used the new safe API for checking whether a file is a terminal, introduced in Rust 1.70.0.  We should probably use that everywhere, but that's out of scope of this bug fix.
Fixes: 52eebaf6 ("vmm: refactor DeviceManager to use console_info")

vmm: fix resizing TTY consoles

---

virtio-devices/src/console.rs
vmm/src/console_devices.rs
vmm/src/device_manager.rs
vmm/src/serial_manager.rs

Rebooting a VM fails with the following error when debug assertions are enabled:
fatal runtime error: IO Safety violation: owned file descriptor already closed
This happens because FromRawFd::from_raw_fd is used on RawFds stored in ConsoleInfo every time a VM begins to boot, so the second time (after a reboot, or if the first attempt to boot via the API failed), the fd will be closed.  Until this assertion is hit, the code is operating on either closed file descriptors, or new file descriptors for something completely different.  If debug assertions are disabled, it will just continue doing this with unpredictable results.
To fix this, and prevent the problem reocurring, ownership of the console file descriptors needs to be properly tracked, using Rust's type system, so this commit …

vmm: fix console IO safety

---

vmm/src/lib.rs

For a VM with virt-console enabled, when a reboot is requested, the console devices are closed during the shutdown path. As part of this the sigwinch listener process and the console resizer pipe could be closed. For the new incarnation of the VM, fresh set of console devices are setup and a new console resizer pipe is created. The new VM should be setup to use the newly created console devices including the console resizer pipe.
Reading from the older console resizer pipe results in unexpected eof error and terminates the cloud hypervisor process.
cloud-hypervisor: 182.581732s: <__console> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(Failed to get resize event: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })

Pass the newly created console resizer pipe during vm reboot

---

Cargo.toml
api_client/Cargo.toml
arch/Cargo.toml
block/Cargo.toml
devices/Cargo.toml
fuzz/fuzz_targets/console.rs
hypervisor/Cargo.toml
net_gen/Cargo.toml
net_util/Cargo.toml
pci/Cargo.toml
rate_limiter/Cargo.toml
test_infra/Cargo.toml
tpm/Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml
virtio-devices/Cargo.toml
vm-allocator/Cargo.toml
vm-device/Cargo.toml
vm-migration/Cargo.toml
vm-virtio/Cargo.toml
vmm/Cargo.toml

- Modify `Cargo.toml` in each member crate to follow the dependencies
specified in root `Cargo.toml` file.
- The construction of `FilePair` in `virtio_devices` component has changed
in 287887c, wrapping the parameters with `Arc` to fix fuzz build.

build: Centralize rust-vmm crates to workspace

---

scripts/dev_cli.sh
scripts/run_coverage.sh
scripts/run_integration_tests_x86_64.sh
scripts/run_unit_tests.sh
test_infra/src/lib.rs

scripts: export code coverage information
In this patch, we add a code coverage script to support exporting code coverage information.
Fixes: #6507

scripts: export code coverage information

---

fuzz/fuzz_targets/http_api.rs
src/main.rs
vmm/src/api/dbus/mod.rs
vmm/src/api/http/http_endpoint.rs
vmm/src/api/mod.rs
vmm/src/lib.rs

This patch removes locks in VmCreate request and VmInfo response since we needn't use a lock here and should ensure that internal implementation is transparent to the runtime.

vmm: remove unused mutex in api

---

vmm/src/console_devices.rs

Serial device doesnt support resize semantics. Setting up the console resize pipe in the Serial device setup path, overwrites the setup done as part of virtio-console.

vmm: Remove console resize for Serial

---

Cargo.toml

See the following discussion: https://github.com/rust-lang/cargo/issues/12162#issuecomment-2020763765

build: disable vfio-ioctls default features on workspace level

---

.github/workflows/build.yaml
.github/workflows/quality.yaml
arch/src/x86_64/mod.rs
arch/src/x86_64/mptable.rs
block/src/qcow/mod.rs
devices/src/legacy/serial.rs
devices/src/legacy/uart_pl011.rs
hypervisor/src/arch/x86/emulator/instructions/cmp.rs
hypervisor/src/arch/x86/emulator/instructions/mov.rs
hypervisor/src/arch/x86/emulator/instructions/movs.rs
hypervisor/src/arch/x86/emulator/instructions/or.rs
hypervisor/src/arch/x86/emulator/instructions/stos.rs
hypervisor/src/arch/x86/emulator/mod.rs
hypervisor/src/kvm/aarch64/gic/mod.rs
net_util/src/mac.rs
net_util/src/tap.rs
option_parser/src/lib.rs
rate_limiter/src/group.rs
rate_limiter/src/lib.rs
tests/integration.rs
virtio-devices/src/vsock/device.rs
vm-device/src/bus.rs
vmm/src/config.rs
vmm/src/cpu.rs
vmm/src/landlock.rs
vmm/src/lib.rs
vmm/src/vm.rs

Inspired by @roypat.
Asserting on .is_ok()/.is_err() leads to hard to debug failures (as if
the test fails, it will only say "assertion failed: false". We replace
these with `.unwrap()`, which also prints the exact error variant that
was unexpectedly encountered (we can to this these days thanks to
efforts to implement Display and Debug for our error types). If the
assert!((...).is_ok()) was followed by an .unwrap() anyway, we just drop
the assert.
Enable clippy::assertions_on_result_states lint for `build.yaml` and `quality.yaml`.

misc: Eliminate use of `assert!((...).is_ok())`

---

arch/Cargo.toml

Currently `arch` crate cannot be built, by specifying `hypervisor/kvm` to turn on the features required for its dependency - `hypervisor` crate to build. Thus enabling `arch` crate to be built with command:
```sh
cargo build -p arch --features kvm
```

arch: Enable build with `kvm` feature

---

block/src/qcow/qcow_raw_file.rs
block/src/qcow/raw_file.rs
block/src/vhdx/mod.rs
block/src/vhdx/vhdx_bat.rs
block/src/vhdx/vhdx_io.rs
fuzz/fuzz_targets/balloon.rs
fuzz/fuzz_targets/console.rs
fuzz/fuzz_targets/iommu.rs
fuzz/fuzz_targets/mem.rs
fuzz/fuzz_targets/net.rs
fuzz/fuzz_targets/rng.rs
hypervisor/src/lib.rs
net_util/src/queue_pair.rs
net_util/src/tap.rs
pci/src/configuration.rs
pci/src/lib.rs
rate_limiter/src/group.rs
rate_limiter/src/lib.rs
src/bin/ch-remote.rs
tests/integration.rs
virtio-devices/src/vsock/mod.rs
vm-virtio/src/queue.rs
vmm/src/coredump.rs
vmm/src/device_tree.rs
vmm/src/memory_manager.rs

This PR addresses some clippy warnings appeared since `1.83.0-beta.1`:
- Replace div_round_up operation with div_ceil
- Remove manual implementation of is_power_of_two
- Use c"" to construct nul-terminated string
- Elide needless lifetimes
- Remove redundant return statement
- Remove redundant pub keyword of helper functions
But leaves two problem unsolved:
1. The new clippy wants a `.wait()` in places we try to spawn a child thread, while we did manually take care of these threads but it fails to understand.
2. In `tracing` module, we are trying to create shared reference to mutable static, which is discouraged

misc: Appease clippy

---

tracer/src/tracer.rs

This PR is raised to resolve clippy warning appeared since `1.83.0-beta.1` in `tracer` module:
```
error: creating a shared reference to mutable static is discouraged
--> tracer/src/tracer.rs:111:59
|
111 |         timestamp: Instant::now().duration_since(unsafe { TRACER.get().unwrap().start }),
|                                                           ^^^^^^^^^^^^ shared reference to mutable static
|
= note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
= note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives
= note: `-D static-mut-refs` implied by `-D warnings`
= help: to override `-D …
```

tracer: Allow shared reference to mutable static

---

Cargo.toml
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml

`vhost-user-backend` is left behind in #6764, move it to root workspace.

build: Centralize vhost-user-backend to workspace

---

.github/workflows/package-consistency.yaml
scripts/package-consistency-check.py

- Add `rust-vmm-consistency-check.py` script to prevent #6809 from happening. Even though it's happening again in #6815 :(
- Enable `rust-vmm-consistency` check to prevent contributor or dependabot accidentally break `rust-vmm` consistency.

ci: Add rust-vmm consistency check

---

.github/workflows/package-consistency.yaml
Cargo.lock
Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml
hypervisor/src/kvm/aarch64/gic/dist_regs.rs
hypervisor/src/kvm/aarch64/gic/icc_regs.rs
hypervisor/src/kvm/aarch64/gic/mod.rs
hypervisor/src/kvm/aarch64/gic/redist_regs.rs

- Bump kvm-bindings from 0.9.1 to 0.10.0
- Bump kvm-ioctls from 0.18.0 to 0.19.0
- Bump vm-memory from 0.15.0 to 0.16.0
- Bump linux-loader from 0.12.0 to 0.13.0
- Bump virtio-bindings from 0.2.1 to 0.2.4
- Bump virtio-queue from 0.13.0 to 0.14.0
- Pin mshv-bindings to 0.3.1
- Pin mshv-ioctls to 0.3.1
- Pin vhost to rev "d983ae0"
- Pin vhost-user-backend to rev "d983ae0"

build: Bump rust-vmm crates

---

virtio-devices/src/block.rs

This improves sequential write performance using fio (2888MiB/s ->
3293MiB/s)
VM config: cloud-hypervisor --disk path=~/workloads/jammy.raw,direct=on path=~/workloads/big-disk.img,direct=on --cpus boot=1 --memory size=2G,shared=on --serial tty --console off --seccomp log --kernel ~/workloads/hypervisor-fw
Host: fio --filename=big-disk.img --direct=1 --rw=write --bs=256k --ioengine=libaio --iodepth=64 --runtime=120 --numjobs=1 --time_based --group_reporting --name=throughput-test-job --eta-newline=1
VM:  fio --filename=/dev/vdb --direct=1 --rw=write --bs=256k --ioengine=libaio --iodepth=64 --runtime=120 --numjobs=1 --time_based --group_reporting --name=throughput-test-job --eta-newline=1
Baseline (file on filesystem on host used as backing store for block
device):
throughput-test-job: …

virtio-devices: Enable VIRTIO_RING_F_INDIRECT_DESC

---

docs/api.md

default --api-socket removed in 78f9ddc6beea6344b3eea0c900665ebdf240935f
Not sure if the example output is relevant anymore so left it in.

docs: remove old --api-socket behavior

---

.github/workflows/preview-riscv64.yaml
hypervisor/src/arch/mod.rs
hypervisor/src/arch/riscv64/aia.rs
hypervisor/src/arch/riscv64/mod.rs
hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/riscv64/aia.rs
hypervisor/src/kvm/riscv64/mod.rs
hypervisor/src/lib.rs
hypervisor/src/vm.rs

- Introduce definitions, traits relate to RISC-V AIA (Advanced Interrupt
Architecutre) construction.
- Integrate `aia` module into `riscv64` module, and enable `riscv64`
module if target architecture is RISC-V 64-bit.
- Implement macros to calculate register ID on riscv64, definition of
RISC-V `VcpuKvmState`.
- Implement definition required to work with KVM in-kernel AIA device,
construction procedure of AIA.
- Add error variants specific to RISC-V architecture.
- Incorporates riscv64 register interaction and AIA creation to kvm
module. Complete `Vcpu` trait on RISC-V platform.
- Add RISC-V specific Vcpu trait. Disable `set_guest_debug` on RISC-V
platform.
- Introduce RISC-V specific Vm traits and error variant, disable
`create_irq_chip` on RISC-V platform.
- Introduce cpu, vm, kvm, arch …

hypervisor: Introduce RISC-V architecture

---

src/main.rs

- **main: Require a payload to boot when any VM argument provided**
- **main: Place `--tpm` in the correct argument group**

Require payload argument when parsing any other VM argument

---

.github/workflows/integration-arm64.yaml

The builds are flaking due to reaching the timeouts.

build: Increase ARM64 CI build timeouts

---

net_util/src/open_tap.rs
net_util/src/queue_pair.rs
tests/integration.rs
virtio-devices/src/block.rs
virtio-devices/src/net.rs

Replace `map_or()` on false condition with `is_some_and` to provide
better readability, as suggestted by v1.84.0-beta.1 `cargo clippy`.

misc: Replace `map_or` on false with `is_some_and`

---

docs/live_migration.md

After the existing documentation about live migration has led to some confusion internally whether remote live-migration is actually supported, I've rewritten the relevant documentation so it's hopefully clearer what can be done.
If there are more appropriate Linux binaries (bzImage/initrd) for a small interactive system, I'm happy to replace the Debian installer with a link to those. The NixOS netboot binaries are nice, but they are not available without installing Nix, which is a bit out-of-scope for this how-to guide.
Relates to #6848 (and also #6840). The documentation from #6850 is also nice, but it is pretty complex, because it also handles shared persistent storage and is pretty hard to try out without a lot of infrastructure setup.

Rewrite Live Migration Documentation

---

scripts/test-util.sh

With 0.5.0 release of `rust-hypervisor-firmware`, `aarch64` binary were added to assets, which causes the `FW_URL` to have multiple download url separated by a white space, thus our integration tests would fail.
Constrain to FW_URL to `hypervisor-fw` to resolve this.

ci: Constrain FW_URL to x86_64 one

---

.github/workflows/preview-riscv64.yaml
arch/Cargo.toml
arch/src/lib.rs
arch/src/riscv64/fdt.rs
arch/src/riscv64/layout.rs
arch/src/riscv64/mod.rs
hypervisor/src/arch/riscv64/aia.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/riscv64/aia.rs

- hypervisor: Tune Vaia trait to work with fdt setup
- hypervisor: Set pc and a1 for all vcpu
- arch: Enable fdt_parser and vm-fdt for riscv64
- arch: Introduce RISC-V 64-bit layout
- arch: Introduce fdt setup for riscv64
- arch: Introduce RISC-V architecture
- ci: Enable riscv64 CI of arch module

arch: Introduce RISC-V architecture

---

.github/workflows/preview-riscv64.yaml
vm-allocator/Cargo.toml
vm-allocator/src/gsi.rs
vm-allocator/src/system.rs

- vm-allocator: Enable arch module for riscv64
- vm-allocator: Enable build with kvm feature
- vm-allocator: Introduce RISC-V architecture
- ci: Enable riscv64 CI of vm-allocator module

vm-allocator: Introduce RISC-V architecture

---

.github/workflows/preview-riscv64.yaml
devices/Cargo.toml
devices/src/aia.rs
devices/src/interrupt_controller.rs
devices/src/lib.rs

- devices: Enable arch module for riscv64
- devices: Enable build with `kvm` feature
- devices: Introduce RISC-V AIA interrupt device
- devices: Disable tpm module for riscv64
- ci: Enable riscv64 CI of devices module

devices: Introduce RISC-V AIA interrupt controller

---

Cargo.lock
Cargo.toml
hypervisor/src/mshv/mod.rs
hypervisor/src/mshv/snp_constants.rs
hypervisor/src/vm.rs

For confidential VM on MSHV, GHCB page is the communication method between guest and host. All the CVM exits, VMM  needs to read and write to the GHCB page. MSHV provides  an option to remap the page to the root partition. This way VMM could directly read and write to the page and skip extra IOCTL and hypercall. This improvement makes
the IO 10% faster.

Map GHCB page to the root addressspace

---

Cargo.lock
hypervisor/Cargo.toml
hypervisor/src/hypervisor.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/mshv/mod.rs
vmm/src/lib.rs
vmm/src/vm.rs

For SEV-SNP VM VMM needs access to pages during IO. VMM requests for access to the page, IO threads can use same page and we don't need to request for access if the request  has already been made early and the guest did not revoke
the access. For this purpose we maintain a bit for each page. Once we have the access to the page we set the bit so that later
we can avoid such request to reduce the number of IOCTLS and hypercalls. With this caching we see performance improvement ranging around 5% or more.

Use caching during the page access request for SEV-SNP guest on MSHV

---

pci/src/bus.rs
pci/src/vfio.rs
vm-allocator/src/system.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

While non-Intel CPU architectures don't have a special concept of IO address space, support for PCI I/O regions is still needed to be able to handle PCI devices that use them.
With this change, I'm able to pass through an e1000e device from QEMU to a cloud-hypervisor VM on aarch64 and use it in the cloud-hypervisor guest. Previously, it would hit the `unimplemented!()`.
---
I'd appreciate some checking here, as while this does fix a problem, I've been learning about PCI as I've gone.  In particular:
- Is starting at address 0 in the MMIO space okay on other architectures?
- When I try to pass through a virtio-net device instead of e1000e, the guest kernel ends up stuck in rtnl_lock.  I'm not sure what's going wrong there (or if it's a Cloud Hypervisor problem, or a problem with something …

vmm: support PCI I/O regions on all architectures

---

Cargo.lock
Cargo.toml
docs/live_migration.md
tests/integration.rs
vmm/src/lib.rs

This pull request updates the vm-memory crate from version 0.16.0 to 0.16.1, incorporating the necessary implementations for TcpStream. It introduces TCP-based cross-host live migration support in Cloud Hypervisor, enhancing migration performance and simplifying the process. Additionally, the live migration documentation has been updated to provide instructions for executing cross-host live migrations over TCP connections.
- **Updated** the `vm-memory` crate dependency to version `0.16.1` to include the implementations of `ReadVolatile` and `WriteVolatile` for `TcpStream`, which are necessary for TCP-based live migration.
- **Modified** `vm_send_migration` and `vm_receive_migration` functions to support `destination_url` and `receiver_url` starting with `tcp:`, allowing live migration …

Add support for cross-host live migration over TCP

---

block/src/lib.rs

The original code relied on the default `read_vectored` or `write_vectored` implementations from the standard library.
The default implementation of those functions only uses the first non-empty buffer. That's not correct when there are more than one buffers.
Fixes: #6876
This should be backported.

block: fix short read and short write in AsyncAdaptor

---

block/src/vhdx/mod.rs
block/src/vhdx/vhdx_header.rs

There are several issues I discovered while trying to debug the SEG_MAX feature on VHDX.
1. Cloud Hypervisor cannot open a VHDX image in read-only mode.
2. Cloud Hypervisor corrupts the VHDX image after it is used once.
3. VHDX code cannot handle multiple segments.
All are fixed in this series.
I used QEMU as a reference. The image still works with QEMU after it's used by CH.

Fix bugs in VHDX code

---

fuzz/fuzz_targets/balloon.rs
fuzz/fuzz_targets/block.rs
fuzz/fuzz_targets/cmos.rs
fuzz/fuzz_targets/console.rs
fuzz/fuzz_targets/http_api.rs
fuzz/fuzz_targets/iommu.rs
fuzz/fuzz_targets/linux_loader_cmdline.rs
fuzz/fuzz_targets/mem.rs
fuzz/fuzz_targets/net.rs
fuzz/fuzz_targets/pmem.rs
fuzz/fuzz_targets/qcow.rs
fuzz/fuzz_targets/rng.rs
fuzz/fuzz_targets/watchdog.rs

When the main fuzzer function returns (), it is equivalent to returning Corpus::Keep.
In some of the return paths, we want to reject the input so that the libfuzzer won't spend more time mutating them.
The should make fuzzing more efficient. No functional change intended.

fuzz: explicitly keep or reject fuzzer corpus

---

block/src/vhdx/vhdx_io.rs

This potentially fixes #6897. I'm running tests overnight to see if I still get the occasional failures.

Properly account for bytes read and written in VHDX IO code

---

arch/src/x86_64/tdx/mod.rs
block/src/vhdx/vhdx_header.rs
block/src/vhdx/vhdx_metadata.rs
hypervisor/src/kvm/aarch64/gic/redist_regs.rs
pci/src/configuration.rs
pci/src/msix.rs
virtio-devices/src/iommu.rs
virtio-devices/src/transport/pci_device.rs
vmm/src/acpi.rs
vmm/src/cpu.rs

Beta Clippy reports issues with VHDX structures.
Fix all places where `repr` is problematic.

Use repr(C, packed) where necessary

---

vmm/src/lib.rs

When VM restore fails, the VMM state is left with some side-effects, such as a
VM being created. It would prevent the VMM from creating and booting a new VM or
restoring from a VM snapshot.
To fix this issue, this patch explicitly handles the side effects to the VMM
state when VM restore fails, e.g. clear the VmConfig and shutdown the VM being
created.
Fixes: #6869

vmm: Cleanup VM being created when VM restore fails

---

fuzz/Cargo.toml

I have a PR to add the two new fuzzers to oss-fuzz https://github.com/google/oss-fuzz/pull/12935.
The strange thing is that one of the builds fails because x86emul is not built.
My theory right now is that `--features mshv_emulator` is not honoured by oss-fuzz, hence this PR.

fuzz: build x86emul by default

---

fuzz/fuzz_targets/iommu.rs
src/main.rs
tests/integration.rs
virtio-devices/src/iommu.rs
vmm/src/api/openapi/cloud-hypervisor.yaml
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/vm_config.rs

Currently, Cloud Hypervisor does not set a VIRTIO_IOMMU_F_INPUT_RANGE feature bit for the VirtIO IOMMU device, which, [according to spec](https://docs.oasis-open.org/virtio/virtio/v1.3/csd01/virtio-v1.3-csd01.html#x1-5420006), means that the guest may use the whole 64-bit address space is for IOMMU purposes:
>If the feature is not offered, virtual mappings span over the whole 64-bit address space (start = 0, end = 0xffffffff ffffffff)
As far as I am aware, there are currently no host platforms on the market capable of addressing the whole 64-bit address space.
For example, I am currently working with a host platform that reports 39-bit address space for IOMMU purposes:
```
DMAR: Host address width 39
```
When running a VFIO pass-through guest on such a platform, NVIDIA driver in guest …

virtio-devices: iommu: allow limiting maximum address width in bits

---

pci/src/lib.rs
pci/src/vfio.rs

This PR adds the PCI device address information to the error message where the mapping and unmapping of the mmio_regions fails. The identified issues stemmed from GPUs sometime losing their PCI state occasionally. This patch helps identify the device that is failing to allow more targeted recovery for the device, as opposed to having to reboot the entire host. The pci device id has to be propagated back in an error message to allow the recovery process, and could not be just handled by the additional error logging here.
I could not find an easy way to find the pci device bdf id. This patch addresses that. If there is a better way to find this information, then please let me know.

pci: Adding the pci device address for map errors.

---

arch/src/riscv64/fdt.rs

This is a typo here, `interrupt-controller` attribute of each CPU node should not have a `#` prepended.

arch: riscv64: Fix interrupt-controller FDT property

---

build.rs

Use this to add any extra versioning information to the binary. It is useful when packaging Cloud Hypervisor.

build: Provide CH_EXTRA_VERSION

---

.github/workflows/lychee.yaml
.lychee.toml
CONTRIBUTING.md
README.md
docs/amd_sev_snp.md
docs/debug-port.md
docs/intel_sgx.md
docs/intel_tdx.md
docs/io_throttling.md
docs/logging.md
release-notes.md

- docs: Fix broken link in amd_sev_snp.md
- docs: Fix link to docs/logging.md
- docs: Fix broken link to docs/arm64.md
- docs: Fix broken link in io_throttling.md
- docs: Update outdated intel_tdx.md
- docs: Update outdated intel_sgx.md
- docs: Fix broken link to intel 0x80 debug port
- docs: Fix broken link in CONTRIBUTING.md
- docs: Fix broken to fedora 36 artifacts
- misc: Update link in release-note.md
- ci: Introduce lychee to check links

Fix broken link and introduce `lychee` to look after links

---

Cargo.lock
Cargo.toml
hypervisor/src/mshv/mod.rs

Move mshv crates from v0.3.2 to v0.3.3

build: Bump mshv crate to latest version

---

hypervisor/src/mshv/mod.rs

This fixes an compilation error when we try to compile CloudHypervisor for MSHV on aarch64.

hypervisor: Add implementation to fetch host IPA limit on MSHV

---

arch/src/x86_64/mod.rs

Reported by 1.85.0-stable (4d91de4e4 2025-02-17), fix accordingly.

misc: Fix clippy - operator precedence can trip the unwary

---

arch/src/aarch64/fdt.rs
arch/src/x86_64/tdx/mod.rs
block/src/qcow/mod.rs
pci/src/vfio.rs
virtio-devices/src/balloon.rs
virtio-devices/src/vsock/csm/connection.rs
vm-migration/src/lib.rs

Partially fix clippy warnings reported by 1.86.0-beta.1 (f0cb41030 2025-02-17):
misc: Fix clippy - doc list item overindented
misc: Fix clippy - manually reimplementing div_ceil
misc: Fix clippy - manual implementation of ok
The rest is in #6953, which requires additional fix after bumping MSRV.
Signed-off-by: Ruoqing He [heruoqing@iscas.ac.cn](mailto:heruoqing@iscas.ac.cn)

misc: Partially fix clippy warnings

---

vmm/src/seccomp_filters.rs

Similar to https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2094 the http api thread is lacking the clock_gettime system call in its seccomp filters.
As soon as we execute on a platform where gettime results in a syscall, the thread crashes.

Allow clock_gettime() on the http api thread

---

hypervisor/src/lib.rs
hypervisor/src/mshv/aarch64/mod.rs
hypervisor/src/mshv/mod.rs

Currently we are just storing the StandardRegisters in the Vcpu state which would be required for saving and restoring the ARM64 guest on MSHV.

hypervisor: Add a basic implementation of MshvVcpuState for aarch64

---

pci/src/vfio.rs
vmm/src/device_manager.rs

Comparing with BDF information on the guest, reporting the device path of the VFIO device on the host is more useful when it comes to debug DMA map/unmap errors particularly ones caused by failing hardware on the host.

pci, vmm: vfio: Report device path on host with DMA map/unmap errors

---

Cargo.lock
Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml

v0.5.0 of `seccompiler` has supported riscv64, let's bump from v0.4.0 to v0.5.0 to capture that support.

build: Manually bump seccompiler to 0.5.0

---

vmm/src/api/openapi/cloud-hypervisor.yaml

This involves the platform and VM config, that can be reused by Kata.

vmm: api: Expose SEV-SNP and igvm related options

---

.lychee.toml

Link check is likely to fail due to connectivity reasons, retry three times before it fails.

ci: Enable retry for Link Check

---

vmm/src/cpu.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/memory_manager.rs
vmm/src/pci_segment.rs
vmm/src/seccomp_filters.rs
vmm/src/serial_manager.rs
vmm/src/vm.rs

Draft, awaits rust-vmm/seccompiler#76 to be merged and released.
Capable of booting RISC-V linux with command: 
```console
./target/debug/cloud-hypervisor \
--kernel path/to/kernel \
--disk path=path/to/disk \
--cmdline "console=hvc0 root=/dev/vda rw" \
--cpus boot=1 \
--memory size=1024M \
--seccomp false
```

vmm: Introduce riscv64 architecture support

---

hypervisor/src/lib.rs
hypervisor/src/mshv/mod.rs

Use the definitions from the rust-vmm/mshv crate for various datastructures such as StandardRegisters, RegList, VcpuInit etc.

hypervisor: Fix MSHV compilation on aarch64

---

.gitlint

This is a split-out from #6974 to separate discussions.
The change helps to prevent annoying CI failures when one adds useful resources into
a commit message, such as [0].
One can test this locally using: `gitlint --commits HEAD~1..HEAD`
[0]
https://example.com/?lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum-lorem-ipsum

ci: gitlint now ignores long lines from links

---

vmm/src/vm_config.rs

when discard_writes is true, only grant read access in landlock

vmm: tighten landlock rule for PmemConfig

---

src/main.rs

The CLI has grown to a big variety of options. clap prints them in the
help message (--help) in the order they were defined. We now are at a
point where grouping things logically together doesn't work well.
Further, there is no support by clap for logical grouping and the
current code base wasn't consistent. Therefore, this commit introduces
two changes:
- a new structure do define arguments (all in an array)
- an alphabetical ordering of the arguments
No other changes have been made. No options have been altered.
This significantly improves:
- code maintainability and extensibility
- readability of the --help output
Signed-off-by: Philipp Schuster <philipp.schuster@cyberus-technology.de>
<details>
```
Launch a cloud-hypervisor VMM.
Usage: cloud-hypervisor [OPTIONS]
Options:
--cpus <cpus> …
```

vmm: Alphabetically sort CLI options in --help output

---

vmm/src/seccomp_filters.rs

Certain MSHV ioctls are only available on x86 architecture. Thus, conditionally compile seccomp filter for x86 and in general enable seccomp filters when compiling for MSHV on aarch64.

vmm: Fix compilation on aarch64 MSHV

---

hypervisor/src/kvm/mod.rs

- hypervisor: Introduce riscv64_get_one_reg_from_vcpu macro
- hypervisor: Simplify riscv64 get_regs implementation
- hypervisor: Introduce riscv64_set_one_reg_to_vcpu macro
- hypervisor: Simplify riscv64 set_regs implementation

riscv64: Simplify register handling

---

vmm/src/lib.rs

The larger the VM memory, the greater the memory pressure, and the greater the stop_dirty_log() overhead. For example, in the case of a 32c64g virtual machine with memory compression, stop_dirty_log() takes 36ms. Moving stop_dirty_log() outside the downtime period can reduce downtime.

 vm-migration: Optimize downtime by moving stop_dirty_log()

---

README.md
docs/riscv.md

RISC-V experimental support is in place, document it in our README.md.

README: Add RISC-V support status

---

Cargo.lock
devices/src/gic.rs
hypervisor/Cargo.toml
hypervisor/src/arch/aarch64/gic.rs
hypervisor/src/kvm/aarch64/gic/mod.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/lib.rs

KVM supports GICv3-ITS emulation and the current GicState is modelled around the KVM implementation. We should refactor this to accomodate other hypervisor requirements. For example, MSHV only support GICv2M emulation for guests for delivering MSI interrupts instead of GICv3-ITS.

hypervisor: Avoid leaking KVM GIC state into common GIC state

---

block/src/qcow/mod.rs
block/src/vhdx/mod.rs
hypervisor/src/mshv/mod.rs
net_util/src/mac.rs
pci/src/vfio.rs
pci/src/vfio_user.rs
test_infra/src/lib.rs
vhost_user_block/src/lib.rs
vhost_user_net/src/lib.rs
virtio-devices/src/block.rs
virtio-devices/src/iommu.rs
virtio-devices/src/mem.rs
virtio-devices/src/vdpa.rs
virtio-devices/src/vhost_user/mod.rs
vm-allocator/src/address.rs
vm-device/src/bus.rs
vmm/src/device_manager.rs
vmm/src/interrupt.rs

Rust has a new way of constructing other error and clippy complains if we are still using the older way to construct error message. Thus, migrate to the new approach suggested by the clippy.

misc: Fix clippy error from beta compiler

---

vmm/src/api/openapi/cloud-hypervisor.yaml

This aligns with our CLI syntax. The correctness of `DiskConfig` will be ensured via `VmConfig::validate()`, e.g. `path` and `socket` are mutually exclusive.
Fixes: #7016

vmm: openapi: Remove `path` as required for `DiskConfig`

---

hypervisor/src/arch/aarch64/gic.rs
hypervisor/src/kvm/aarch64/gic/mod.rs
hypervisor/src/mshv/aarch64/gic/mod.rs
hypervisor/src/mshv/aarch64/mod.rs

MSHV does not emulate a GICv3-ITS for guests to support MSI interrupts, instead it exposes a GICv2m device. Currently adding a skeleton code which would be modified later on with complete implementation.
With this we can start compiling cloud-hypervisor for MSHV on ARM64. This will make sure that we don't regress in future in terms of basic compilation test.

hypervisor: Add GICv2M support for MSHV ARM64 guest

---

Cargo.lock
Cargo.toml

- zerocopy from 0.7x to 0.8.x
- mshv crates from 0.3.3 to 0.3.5

Bump various dependencies to latest version

---

.github/workflows/quality.yaml
hypervisor/src/lib.rs
hypervisor/src/mshv/mod.rs
vmm/src/cpu.rs

With these changes we can now compile cloud-hypervisor for MSHV on ARM64. There are still some follow up changes required that would be required to launch a guest on MSHV ARM64 which would be published in the upcoming PRs.

hypervisor: Enable MSHV compilation on ARM64

---

.lychee.toml
pci/src/vfio.rs

When devices don't implement a capabilities list or just return 0xFF for the capabilities pointer sad things happen. It typically boils down to receiving 0xFF from the capabilities register. In debug builds, this will then crash the VMM, because `cap_iter + 1` overflows:
```
thread 'vmm' panicked at pci/src/vfio.rs:934:63:
attempt to add with overflow
```
Fix by:
- checking whether the device claims to have a capability list,
- terminate the checking loop if the capability points to itself.
A very broken (malicious) device might still send this code into an endless loop, but I assume this is not part of the threat model and we don't want to overcomplicate this code.
It would be nice to implement a small iterator for the capability list, so we don't have to duplicate the logic (and quirks …

pci: be more robust when parsing PCI capabilities

---

hypervisor/src/mshv/mod.rs

MSHV allows VMM to map the VP register page into root. This feature helps VMM to faster process most of the frequent used registers. This patch uses the VP register page for port handling in CPU run method.

hypervisor: mshv: use mapped register page for port handling

---

Cargo.lock
Cargo.toml
fuzz/Cargo.toml
hypervisor/src/mshv/mod.rs
release-notes.md

Latest mshv crates contains some IOCTL changes that
enhances VM creation and configures the features in correct
way. Also adds some features that improves register access.

update mshv crates to the latest release

---

README.md

Ubuntu 24.04 LTS (Noble Numbat) is tested against cloud-hypervisor v45.0 release and it is working, document status in README.md.
Signed-off-by: Bingxin Li <bl497@cam.ac.uk>

README: Update ubuntu support status

---

hypervisor/src/cpu.rs
hypervisor/src/mshv/mod.rs
vmm/src/cpu.rs
vmm/src/vm.rs

For MSHV arm64 guest, there is an in-hypervisor GICv2M emulation and for that to work, it needs to be enlightened with the base address of GIC redistributor exposed to guest via FDT.

vmm: hypervisor: Add a new interface to setup GICR for vcpus

---

hypervisor/src/mshv/aarch64/gic/mod.rs
hypervisor/src/mshv/mod.rs

On x86 MSHV guests only used to support MSI based interrupts via IOAPIC but ARM64 guests uses legacy interrupt for its functioning. Thus, extend the logic to create routing entry to support legacy interrupts for ARM64 guests on MSHV.

hypervisor: Extend interrupt handling for legacy IRQ

---

Cargo.lock
Cargo.toml
fuzz/Cargo.toml
hypervisor/src/mshv/mod.rs
hypervisor/src/vm.rs
vmm/src/vm.rs

Along with also bump the vfio-bindings crates to use the latest mshv-bindings.
There is a breaking change in the new mshv crate which requires an additional step to initialize vm after creating it.

build: Bump mshv crates from 0.4.0 to 0.5.0

---

.gitlint
scripts/gitlint/rules/BodyMaxLineLengthEx.py
scripts/gitlint/rules/TitleStartsWithComponent.py

Follow-up of 5aa1540c5dc33d61020a08dd2818c0f5fd08575f (#6989) but way more mature.
It is not perfect but better than what we have.
Allowed to exceed the 72 wide limit are now:
1. links in the following three common patterns:
https://example.com/very-long-links/very-long-links/very-long-links/very-long-links/very-long-links/very-long-links/very-long-links
[0] https://example.com/very-long-links/very-long-links/very-long-links/very-long-links/very-long-links/very-long-links/very-long-links
[0]:
https://example.com/very-long-links/very-long-links/very-long-links/very-long-links/very-long-links/very-long-links/very-long-links
2. code blocks
```
let x = "very_long_very_long_very_long_very_long_very_long_very_long_very_long_very_long_very_long_very_long_"
```
On-behalf-of: SAP …

ci: improve gitlint

---

Cargo.lock
Cargo.toml

This release has critical bug fixes IOCTL changes. No API changes.

build: Bump mshv crates from 0.5.0 to 0.5.1

---

devices/src/pvmemcontrol.rs
devices/src/pvpanic.rs
pci/src/bus.rs
pci/src/configuration.rs
pci/src/device.rs
pci/src/vfio.rs
pci/src/vfio_user.rs
virtio-devices/src/transport/pci_device.rs

A BAR reprogramming of a PCI device will only happen when the (guest)
kernel write to its PCI config space, e.g. the detection of bar
reprogramming (`detect_bar_repgraomming()`) can be embedded to the PCI
config space write (`write_config_register()`). It simplifies APIs
exposed by the `struct PciConfiguration` and `trait PciDevice`. It also
prepares for easier handling of pending bar reprogramming when the MSE
bit of the COMMAND register is not enabled at the time of changing BAR
registers.
See: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/7027#issuecomment-2853642959

pci: Keep detect_bar_reprogramming internal to PciConfiguration

---

devices/src/pvmemcontrol.rs
devices/src/pvpanic.rs
pci/src/bus.rs
pci/src/configuration.rs
pci/src/device.rs
pci/src/vfio.rs
pci/src/vfio_user.rs
virtio-devices/src/transport/pci_device.rs

Note: this PR depends on #7057.
The Memory Space Enable (MSE) bit from the COMMAND register in the
PCI configuration space controls whether a PCI device responds to memory
space accesses, e.g. read and write cycles to the device MMIO regions
defined by its BARs. The MSE bit is used by the device drivers to ensure
the correctness of BAR reprogramming. A common workflow is, the driver
first clears the MSE bit, then writes new values to the BAR registers,
and finally set the MSE bit to finish the BAR reprogramming.
This patch changes how we handle BAR reprogramming for all PCI
devices (e.g. virtio-pci, vfio, vfio-user, etc.), so that we follow the
same convention, e.g. moving PCI BARs when its MSE bit is set.
Note that some device drivers (such as edk2) only clear and set MSE once
while …

Reprogram PCI device BAR when its MSE bit is set

---

pci/src/vfio.rs
vmm/src/seccomp_filters.rs

Note: this PR depends on #7057 and #7063
To support PCIe P2P between VFIO devices, we populate IOMMU mappings for
the non-emulated MMIO regions of all VFIO devices via
`VFIO_IOMMU_MAP_DMA` (https://github.com/cloud-hypervisor/cloud-hypervisor/commit/f0c1f8d079d90d2390b2c01a88d81cd00dd08209), but the patch did not properly update
the IOMMU mappings with BAR reprogramming.
Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/7027

pci: vfio: Update IOMMU mappings of MMIO regions with BAR reprogram

---

block/src/async_io.rs
block/src/fcntl.rs
block/src/fixed_vhd_async.rs
block/src/fixed_vhd_sync.rs
block/src/lib.rs
block/src/qcow/mod.rs
block/src/qcow/qcow_raw_file.rs
block/src/qcow/raw_file.rs
block/src/qcow_sync.rs
block/src/raw_async.rs
block/src/raw_async_aio.rs
block/src/raw_sync.rs
block/src/vhdx/mod.rs
block/src/vhdx_sync.rs
devices/src/ioapic.rs
tests/integration.rs
virtio-devices/src/block.rs
vm-migration/src/lib.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs

Add advisory file locks for disk images, aligning the behavior with QEMU. Please check out the **commit messages for more details**.
</details>
Please review this **commit-by-commit**.

disks: use advisory locks for disk image files

---

pci/src/bus.rs
pci/src/configuration.rs
pci/src/device.rs
virtio-devices/src/vsock/unix/mod.rs
vm-device/src/bus.rs
vmm/src/device_manager.rs
vmm/src/memory_manager.rs

**EDIT**: This is a prerequisite for #7066. To have smaller PRs, this is a split-out.
The DeviceManagerError type is among the types missing the `Error` trait so
far. To streamline the code and to simplify usage on higher levels of this
error type, this type now implements Display and Error.
As not all variant values are Error yet, `#[source]` is not everywhere where
it could be. This is done in the next commits.
The high level goal is: Enable future work to improve the error output of
cloud hypervisor.

DeviceManagerError: Implement Error including all Variants

---

vmm/src/memory_manager.rs

For use in QEMU, I would like GuestMemoryRegion to return a BitmapSlice instead of a &Bitmap ([rust-vmm/vm-memory#324](https://github.com/rust-vmm/vm-memory/pull/324)).  This adds some flexibility that QEMU needs in order to support a single global dirty bitmap that is sliced by the various GuestMemoryRegions.
However, this removes access to the methods of AtomicBitmap, and in particular reset() and get_and_reset().  Fortunately, cloud-hypervisor always uses GuestMemoryMmap, and therefore `region` is known to be a &GuestRegionMmap.  Dereferencing it returns the MmapRegion to which the bitmap is attached, thus calling MmapRegion::bitmap(); this has the same effect as `<GuestRegionMmap as GuestRegion>::bitmap()`, and works both with or without https://github.com/rust-vmm/vm-memory/pull/324.

vmm/memory_manager: use MmapRegion::bitmap() directly

---

vmm/src/cpu.rs

No sane guest OS will allow hotplugging all cpus.
However, the REST API currently allows specifying `ch-remote resize --cpus 0`, contrary to what is [specified](https://raw.githubusercontent.com/cloud-hypervisor/cloud-hypervisor/master/vmm/src/api/openapi/cloud-hypervisor.yaml).
On Linux, we can then observe the following error in the kernel log:
`processor cpu0: Offline failed.`
Subsequent resize commands via ch-remote will then fail with `VcpuPendingRemovedVcpu` because the removal of cpu0 was never successful.
Fix this by disallowing resizing to zero vCPUs.

Don't allow resizing VM to 0 vCPUs

---

src/bin/ch-remote.rs
vmm/src/api/http/mod.rs
vmm/src/api/mod.rs

Split-out of the problematic part of #7085. The commits 
- misc: ch-remote: streamline #[source] and Error impl
- misc: vmm/api: streamline #[source] and Error impl
somehow introduce the problem.
I'm seeking help and guidance; I have no idea how to debug the failing `test_api_http_pause_resume` test efficiently. [Failing Output Example](https://github.com/cloud-hypervisor/cloud-hypervisor/actions/runs/15181465682/job/42691642237?pr=7089)
```
...
Error running ch-remote command: "target/x86_64-unknown-linux-gnu/release/ch-remote" "--api-socket=/tmp/ch4qye1L/cloud-hypervisor.sock" "resume"
stderr: Error opening HTTP socket: Connection refused (os error 111)
thread 'common_parallel::test_api_http_pause_resume' panicked at tests/integration.rs:377:9:
assertion failed: …
```

treewide: streamline #[source] and Error (follow-up (2/2))

---

vmm/src/config.rs

This commit adds the warning to deprecate the SGX support with the intention to remove the support from code base in two release cycles.
See: #6960

vmm: Deprecate SGX support

---

Cargo.toml
fuzz/Cargo.lock
hypervisor/Cargo.toml
hypervisor/src/arch/x86/emulator/instructions/cmp.rs
vmm/Cargo.toml

Since it is used by multiple components at this point, it is better to move it to workspace level dependency.

misc: Move zerocopy to workspace dependencies

---

Cargo.lock
vmm/Cargo.toml
vmm/src/config.rs

When starting a VM with a disk serial specified, for example:
```
--disk path=focal-server-cloudimg-amd64-custom.raw,serial=aabbccfjdlsdkjfkldsjlkfjdsklfjdslkjflsdk
```
The VM fails to boot and the following log is observed:
```
cloud-hypervisor: 1.041609s: <_disk0_q0> ERROR:virtio-devices/src/thread_helper.rs:53 -- Error running worker: HandleEvent(Failed to process queue (submit): RequestExecuting(BadRequest(InvalidOffset)))
```
This patch adds support for checking and truncating disk custom serial to avoid VM startup failures.

 vmm: config: Add DiskConfig check for device serial length

---

block/src/async_io.rs
block/src/lib.rs

Cargo fuzz build report an error:
error: lifetime flowing from input to output with different syntax can be confusing
--> /home/runner/work/cloud-hypervisor/cloud-hypervisor/block/src/lib.rs:747:13
|
747 |     fn file(&mut self) -> MutexGuard<F>;
|             ^^^^^^^^^     ------------- the lifetime gets resolved as `'_`
|             |
|             this lifetime flows to the output
error: lifetime flowing from input to output with different syntax can be confusing
--> /home/runner/work/cloud-hypervisor/cloud-hypervisor/block/src/async_io.rs:68:11
|
68 |     fn fd(&mut self) -> BorrowedDiskFd;
|           ^^^^^^^^^     -------------- the lifetime gets resolved as `'_`
|           |
|           this lifetime flows to the output

Fix cargo fuzz compiler errors

---

scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_live_migration.sh
scripts/run_integration_tests_x86_64.sh
scripts/test-util.sh
test_data/cloud-init/ubuntu/ci/user-data
tests/integration.rs

This bump also includes another release 'ch-release-v6.12.8-20250422' which
changed the naming convention of the released kernel binaries [1]. As a result,
few changes are made to our integration tests and test scripts.
[1] https://github.com/cloud-hypervisor/linux/releases/tag/ch-release-v6.12.8-20250422

ci: Update reference kernel to 'v6.12.8-20250613'

---

Cargo.lock
Cargo.toml
event_monitor/Cargo.toml
event_monitor/src/lib.rs
fuzz/Cargo.lock
fuzz/Cargo.toml
fuzz/fuzz_targets/http_api.rs
net_util/Cargo.toml
net_util/src/tap.rs
test_infra/Cargo.toml
test_infra/src/lib.rs
tests/integration.rs
tracer/Cargo.toml
tracer/src/tracer.rs
vmm/Cargo.toml
vmm/src/api/http/mod.rs

We now have types in the Rust standard library.
Dropping the dependency.

misc: remove once_cell; superseded by std::*

---

Cargo.lock
arch/Cargo.toml
block/Cargo.toml
vmm/Cargo.toml

Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/7071

build: Bump UUID crate to 1.17.0

---

vmm/src/memory_manager.rs

It will likely be safely rejected by the kernel, but it's still wrong.

vmm: do not treat libc::MAP_FAILED as a pointer

---

block/Cargo.toml

That feature was dropped when consolidating the UUID dependency because somehow building the whole project worked. The CI system was happy.
However, building the block crate alone is broken. The vhdx code uses Uuid::new_v4, which requires `v4` to be enabled.
Add the feature back.

block: Add back UUID crate's `v4` feature

---

vmm/src/vm_config.rs

Issue: #7083
The location of the `warn!` statements cover both `NetConfig::parse` and `NetConfig` creation via deserialization using `serde`.
Preparation for a PR like #7076 in a few releases.

vmm: warn about deprecation of default IP address + mask

---

Cargo.lock
Cargo.toml
hypervisor/Cargo.toml
src/bin/ch-remote.rs
src/lib.rs
src/main.rs
vhost_user_block/Cargo.toml
vhost_user_net/Cargo.toml
vhost_user_net/src/lib.rs

In https://github.com/cloud-hypervisor/cloud-hypervisor/pull/7179#issuecomment-3044911791 we discovered that `ch-remote` does not print any log lines generated via `log::level!`.
This PR aims to add `env_logger` to log them.
Furthermore, replace `eprintln!` with `log::error!` as they would be used alongside each other.
When using `env_logger`, messages printed "in between" with `eprintln!` lack proper formatting/colors.
This is currently only relevant in `ch-remote` + `cli_print_error_chain`.
Note that replaced messages now end up in `cloud-hypervisor`'s logfile when configured, rather than stderr.

vmm, ch-remote: add env_logger, replace eprintln! with error! for consistency

---

virtio-devices/src/iommu.rs

Cargo fuzz build report an warning:
warning: unnecessary parentheses around closure body --> /mnt/dev-store/cloud-hypervisor/russell-islam/cloud-hypervisor/virtio-devices/src/iommu.rs:578:41 |
578 |                         .retain(|&x, _| (x < req.virt_start || x > req.virt_end));
|                                         ^                                      ^
|
= note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
|
578 -                         .retain(|&x, _| (x < req.virt_start || x > req.virt_end));
578 +                         .retain(|&x, _| x < req.virt_start || x > req.virt_end);
|
warning: `virtio-devices` (lib) generated 1 warning (run `cargo fix --lib -p virtio-devices` to apply 1 suggestion)

virtio-devices: remove unnecessary parentheses

---

pci/Cargo.toml
virtio-devices/Cargo.toml
vmm/Cargo.toml

This makes it possible to run cargo test just for the virtio-devices crate (as long as either KVM or MSHV is specified).

build: add missing dependency features

---

devices/src/legacy/rtc_pl031.rs
vmm/src/device_manager.rs

The PL031 RTC provides two features: a real-time counter and an alarm interrupt. To use the alarm, the driver normally writes a time value into the match register RTCMR, and when the counter reaches that value the device triggers the interrupt.
At the moment the implementation ignores programming of the alarm, as the feature seems rarely used in VMs. However the interrupt is still triggered arbitrarily when the guest writes to registers, and the line is never cleared. This really confuses the Linux driver, which loops in the interrupt handler until Linux realizes that no one is dealing with the interrupt (200000 unanswered calls) and disables the handler.
One way to fix this would be implementing the alarm function properly, which isn't too difficult but requires adding some async timer …

devices: rtc_pl031: Disable broken interrupt

---

tpm/Cargo.toml

The other workspace members in the Cloud-hypervisor workspace currently declare libc crate version 0.2.167, but the tpm crate has an older version. This inconsistency is addressed by this PR which opens the door for declaring libc as a workspace dependency.

tpm: Use the same libc crate version as other workspace members

---

performance-metrics/src/main.rs
performance-metrics/src/performance_tests.rs

I'm exploring ideas to rework block layer traits in my copious free time. I don't want to accidentally introduce performance regression, so I wrote this series to assist me.
I don't think anyone is asking badly for this, so there is no rush to merge it. If people don't find this useful, I can keep it locally.
Example:
` ./scripts/dev_cli.sh tests --metrics -- --test-filter block_ -- --image-format qcow2`

Support more formats for block performance metrics

---

tpm/Cargo.toml

The other workspace members in the Cloud-hypervisor workspace currently declare log version 0.4.22, but the tpm crate has an older version. This inconsistency is addressed by this PR which opens the door for declaring log as a workspace dependency.

tpm: Use the same log version as other workspace members

---

.github/workflows/lychee.yaml

Fix CI: Prevent link checker rate limits
Optimize lychee workflow to check only changed files in pull requests, avoiding excessive API calls.

CI: Prevent link checker rate limits

---

arch/src/riscv64/layout.rs
arch/src/riscv64/mod.rs
arch/src/riscv64/uefi.rs
vmm/src/memory_manager.rs
vmm/src/vm.rs

- arch: riscv: Introduce UEFI related constants
- arch: riscv: Introduce UEFI module
- vmm: Enable uefi_flash field for riscv64
- vmm: Define riscv64 UEFI Error
- vmm: Enable firmware boot for riscv64

riscv64: Enable firmware booting

---

src/lib.rs

Moved discussion from https://github.com/cloud-hypervisor/cloud-hypervisor/pull/7183#issuecomment-3173923366 to this PR.
---
This partially reverts
ed8f347fe62edd33355ad771615296ff8edc8d33 from #7183 and 6277d7d5f20126945904fefdf5fb990bbcce5ae8 from #7201.
```
Error: Cloud Hypervisor exited with the following chain of errors:
0: Error booting VM
1: The VM could not boot
2: Error manipulating firmware file
3: No such file or directory (os error 2)
Debug Info: VmBoot(VmBoot(FirmwareFile(Os { code: 2, kind: NotFound, message: "No such file or directory" })))
```
```
cloud-hypervisor: 31.385730ms: <main> ERROR:/home/pschuster/dev/cloud-hypervisor/src/lib.rs:27 -- Error: Cloud Hypervisor exited with the following chain of errors:
cloud-hypervisor: 31.417961ms: <main> …
```

misc: switch error output from error! back to stderr

---

.github/workflows/build.yaml
.github/workflows/quality.yaml
Cargo.lock
Cargo.toml
arch/Cargo.toml
arch/src/aarch64/fdt.rs
arch/src/lib.rs
devices/Cargo.toml
devices/src/legacy/fw_cfg.rs
devices/src/legacy/mod.rs
docs/fw_cfg.md
fuzz/Cargo.toml
scripts/run_integration_tests_aarch64.sh
scripts/run_integration_tests_x86_64.sh
src/main.rs
tests/integration.rs
vmm/Cargo.toml
vmm/src/acpi.rs
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/lib.rs
vmm/src/vm.rs
vmm/src/vm_config.rs

We are working with the project [Oak](https://github.com/project-oak/oak) team to enable running [Oak Containers](https://github.com/project-oak/oak/tree/main/oak_containers) on cloud hypervisor. These containers are SEV-SNP enlightened and can be used alongside with the rest of the oak suite for attestation and measurement of the cvm. 
Here is the functionality we are adding to CHV.
1. Implmenting the sev-snp APIs previously defined (sev_snp_init, import_isolated_pages, complete_isolated_import). 
2. Expanded the igvm loader to support booting KVM + SEV-SNP enabled VMs. (Note that we can also use the igvm loader to boot VMs with standard cloud images with/without sev-snp enabled as seen here (https://github.com/AlexOrozco1256/chv-demo)
3. Added a fw_cfg device with DMA enabled. Oak's …

devices: Add fw_cfg device

---

arch/src/aarch64/fdt.rs
arch/src/aarch64/mod.rs
arch/src/x86_64/mod.rs
arch/src/x86_64/mptable.rs
vmm/src/acpi.rs
vmm/src/cpu.rs
vmm/src/vm.rs

This is the second patch in a series intended to let Cloud Hypervisor support more than 255 vCPUs in guest VMs; the first patch/commit is https://github.com/cloud-hypervisor/cloud-hypervisor/pull/7231
At the moment, CPU topology in Cloud Hypervisor is using u8 for components, and somewhat inconsistently:
- struct CpuTopology in vmm/src/vm_config.rs uses four components (threads_per_core, cores_per_die, dies_per_package, packages);
- when passed around as a tuple, it is a 3-tuple of u8, with some inconsistency:
- in get_x2apic_id in arch/src/x86_64/mod.rs  the three u8 are assumed to be (correctly) threads_per_core, cores_per_die, and dies_per_package, but
- in get_vcpu_topology() in vmm/src/cpu.rs the three-tuple is threads_per_core, cores_per_die, and packages (dies_per_package is …

misc: make topology a 4-tuple of u16s

---

README.md
vmm/src/config.rs
vmm/src/vm.rs
vmm/src/vm_config.rs

Currently (if I'm not missing something!), the following scenarios are supported by Cloud Hypervisor to bootstrap a VM (across all archs):
1. Provide firmware
2. Provide kernel [+ cmdline] [+ initrd] 
As the difference between `--firmware` and `--kernel` is not very clear currently, especially as both use/support a Xen PVH entry, adding this helps to identify the cause of misconfiguration. Further, I've updated the documentation.

vmm: add PayloadConfig::validate to improve error reporting + doc update

---

arch/src/lib.rs
vmm/src/vm.rs

Both functions are defined separately for the two architecture with minor differences.
* `load_firmware()`: call `arch::uefi::load_uefi` which are available on both architecture;
* `load_kernel()`: manually align to `arch::layout::KERNEL_START` 2MB for both architecture (e.g. no-op for `aarch64`);

vmm: Consolidate 'load_firmware/kernel' for aarch64 and riscv

---

hypervisor/src/kvm/mod.rs
hypervisor/src/vm.rs

Also tweak extended interrupt handlings, as needed.
Most credit should go to Neel Natu, who figured out the magic bits needed to make things work and provided detailed comments.
This patch is still NOOP, as VM config allows only up to 254 vCPUs on x86_64.
Note: changes in this and related previous patches/PRs have only been tested on Linux hosts running on Intel x86_64 hardware.
Signed-off-by: Barret Rhoden <brho@google.com>
Signed-off-by: Neel Natu <neelnatu@google.com>
Signed-off-by: Ofir Weisse <oweisse@google.com>
Signed-off-by: Peter Oskolkov <posk@google.com>

hypervisor: enable x2apic API in kvm on x86_64

---

vmm/src/seccomp_filters.rs

These are now used by Cloud Hypervisor when linked with Glibc 2.42.
These values should be correct for all currently supported Cloud Hypervisor platforms, although they are not for all Linux platforms.
Closes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/7276
---
Is there a reason for hardcoding these platform-dependent values instead of taking them from `libc`?

vmm: allow TCGETS2/TCSETS2 where TCGETS/TCSETS are

---

vmm/src/landlock.rs
vmm/src/vm_config.rs

path_beneath_rules() just needs the paths given to it to be AsRef<Path>, so there's no need to create new PathBufs for it.

vmm: drop unnecessary copies

---

vmm/src/vm_config.rs

Without write access to the directory the socket will go in, it's not possible to create the socket.
I've tested outgoing connections from the VM, and they don't seem to need read permissions on that directory to connect to a socket on the host.
Fixes: b3e5738b4 ("vmm: Introduce ApplyLandlock trait")

vmm: fix vsock with landlock

---

vmm/src/vm_config.rs

arch::aarch64::fdt::create_cpu_nodes will always look at this if it exists.  (If it doesn't exist, this is a no-op —
add_rule_with_access() won't add rules for paths that don't exist.)
Fixes: b3e5738b4 ("vmm: Introduce ApplyLandlock trait")

vmm: fix landlock on aarch64

---

arch/src/aarch64/fdt.rs

The previously linked file was converted to ReStructuredText, then later removed from the kernel, with part of the justification being "Most of what booting-without-of.rst contains is now in the DT specification", so point to that instead.

arch: aarch64: fdt: replace broken link

---

Cargo.lock
virtio-devices/src/seccomp_filters.rs
vmm/Cargo.toml
vmm/src/seccomp_filters.rs

These can differ between platforms, so it's better to use centralized definitions of them.  We can't currently do this for the KVM and VFIO ioctls, because the corresponding crates don't publicly expose the ioctl numbers.

seccomp: avoid hardcoding ioctl numbers

---

Cargo.lock
Cargo.toml
fuzz/Cargo.lock
fuzz/Cargo.toml

Bump mshv-ioctls and mshv-bindings to 0.6.0. Most notably, this version contains fixes and new bindings for arm64 guests.
Bump the vfio crates too so that they point to the latest mshv crates.

build: bump mshv and vfio crates

---

src/main.rs

This message makes it easier to confirm a successful shutdown when scanning logs during development as well as in production. If the message is missing and the last log entry is not an error, the most likely cause is a livelock (e.g. contention on a lock) introduced while developing new Cloud Hypervisor features.

vmm: add info! message on graceful shutdown

---

virtio-devices/src/vsock/unix/muxer.rs

The function `read_local_stream_port` had no proper handling for unexpected or incomplete input.
When the control socket of the VSOCK device was closed without sending the expected `CONNECT <PORT>\n` statement completely, the thread got stuck in an infinite loop as it attempted to read from a closed socket over and over again which never returned any data.
This resulted in the thread responsible for `epoll` being completely blocked. New VSOCK connections could not be established and existing ones became defunct, effectively leading to a Denial of Service of the entire VSOCK device.
The issue can be reproduced by opening a socket and immediately closing it.
```
socat - UNIX-CONNECT:/socket.vsock
<Ctrl-C>
```
Instead of applying a quick fix by handling the `EPOLLHUP` event before reading, …

virtio-devices: refactor VSOCK "connect" parsing

---

option_parser/src/lib.rs
src/main.rs
vmm/src/config.rs
vmm/src/device_manager.rs
vmm/src/vm_config.rs

This change enables easier integration with third-party tools by removing the requirement for a dummy IP address when configuring tap devices. The modification applies to both CLI and API interactions.
Previously, cloud-hypervisor would automatically set a default static IP address (192.168.249.1) if none was provided.
This could lead to:
* multiple devices without explicit IP configurations would end up with the same default IP
* unnecessary inclusion of this IP in firewall rules
* the IP address could clash with host networking and routing
Removes warnings introduced in #7179.
Closes issue #7083.
Supersedes #7076

vmm: allow net devices without ip and mask

---

vmm/src/api/http/http_endpoint.rs
vmm/src/config.rs
vmm/src/vm_config.rs

Part of #7291 to work towards live-migration with FDs for virtio-net devices.
Document and streamline the current handling of externally provided FDs for virtio-net devices.
Regarding the introduced abstraction to attach FDs to config objects.
_This version might be outdated. The most current form is in the commit message!_
The motivation of the new abstraction is to provide a verbose, solid,
and bulletproof solution for an complex domain. The interaction between
- the management layer,
- the passing of file descriptors over UNIX domain sockets via
SCM_RIGHTS,
- the attachment of configurations to those FDs,
- **and the ability to give
new developers clear insights into what happens under the hood**
is not trivial. These factors justify encapsulating the complexity
behind a convenient and …

vmm/api: document and streamline process of externally passed FDs for virtio-net devices

---

Cargo.lock
Cargo.toml
hypervisor/src/cpu.rs
hypervisor/src/kvm/mod.rs
hypervisor/src/kvm/x86_64/mod.rs
vmm/src/seccomp_filters.rs

Since the functionality of [0] was backported to `kvm-bindings@v0.12.1` and `kvm-ioctls@v0.22.1` [1, 2], we can now save nested KVM state. This way, nesting works across state save/resume and live-migration.
[0] https://github.com/rust-vmm/kvm/pull/322
[1] https://github.com/rust-vmm/kvm/pull/349
[2] https://github.com/rust-vmm/kvm/pull/350
Closes #7160 (makes it obsolete).

hypervisor: kvm/x86_64: get and set nested guest state

---

api_client/src/lib.rs

Upcoming (still nightly) versions of clippy have a new lint.

api_client: fix clippy
